src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd

ENG-7442. Remove the max value for snapshot priority. 
See matching pro pull request for making this possible in VEM.
Do not merge until pro tests pass on branch.

ENG-7442.  Remove limit in VoltDB on snapshotpriority.

---

examples/json-sessions/client/jsonsessions/JSONClient.java

This is a trivial, one-line bug, in the json-sessions example, which I noticed while writing the new, updated JSON blog(s): the special user sessions named 'voltdb' and 'voltdb2' were being created with extraneous double-quotes around the last-login value, unlike all the other, randomly generated user sessions, so I removed the .toString() call (which was used for those two user sessions, but not elsewhere), which fixes it.

Fix ENG-7466, extraneous quotes, by removing toString() call.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/sqlfeatureprocs/sqlfeatures-new-ddl.sql

When writing the example app I found a few issues that had to do with truncating a table:
* When truncating a table, the row limit trigger for a table would disappear.  It needs to be propagated to the new PersistentTable object that gets created.
* When the row limit trigger itself does a truncate table, then the insert executor's pointer to the PersistentTable being modified needs to be updated; otherwise we're just attempting to insert into the old, full table.

Fix issues with row limit trigger and truncate table

---

src/ee/executors/insertexecutor.cpp
src/frontend/org/voltdb/planner/ParsedInsertStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java

This was pretty straightforward, except that it occurred to me that we get non-deterministic behavior when doing multi-row inserts into a table with a row limit trigger. So I added checks to guard against that.

Execute row limit trigger for INSERT and UPSERT INTO ... SELECT

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.queryrender.js

In particular, we don't want to start new commands for keywords
PARTITON, EXECUTE and DELETE when they appear in a limit rows
constraint.
I tested this manually, I'll create a separate ticket for the GEB testing bit.

Add regular expressions to VMC for LIMIT PARTITION ROWS

---

src/frontend/org/voltdb/iv2/FragmentTask.java

Fix a bug introduced by not-compiling default procs until they are called.

Include a call to ensure inserts have plans for @LoadXXXTable calls in replay modes

---

examples/windowing-with-ddl/README.md
examples/windowing-with-ddl/ddl.sql
examples/windowing-with-ddl/deployment.xml
examples/windowing-with-ddl/run.sh

Per feedback from John P. and John H.  8 sites instead of 4, so needed to adjust partition row limits.

Make new DDL windowing example use default deployment

---

tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Check for the new CREATE PROCEDURE error log message with "role" instead
of "group".

ENG-7531: Fix broken TestVoltCompiler.

---

tests/geb/vmc/src/resources/sqlQueries.txt

Fixed ENG-7559, by first creating, and then dropping, all tables, views, and procedures used in Xin’s new GEB/VMC tests (in many cases, using "drop ... if exists"); also, they all now use the same table name (ddl_table).

Eng 7559 geb vmc create view procedure

---

src/ee/executors/nestloopindexexecutor.cpp
src/ee/plannodes/abstractjoinnode.cpp
src/ee/plannodes/indexscannode.cpp
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/fixedsql/fixed-sql-ddl.sql

This was causing a failed assertion when running sqlcoverage.  When searching for a value in an index that is larger than the index's component types (e.g., I have a bigint 1000 that I'm searching for in a tinyint index), then an assertion in the EE requires more than one component in the index to be specified.  Now, that I understand the code a bit better, I don't think there's any reason this needs to be the case, so I just removed the assertion.

Remove erroneous assertion from EE

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/AdHocCompilerCache.java
src/frontend/org/voltdb/compiler/AdHocPlannedStmtBatch.java
src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/planner/CorePlan.java
src/frontend/org/voltdb/sysprocs/AdHocBase.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/TestClientInterface.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestPlannerTool.java

does nothing.
- Swap out usage of CorePlan.catalogVersion to check plan matching for
usage of CorePlan.catalogHash.
-- Add convenience method wasPlannedAgainstHash to CorePlan
- Remove catalogVersion from CorePlan
- Clean up CatalogContext after making catalog bytes
non-nullity a requirement.
- Switch AdHocCompilerCache to use hash rather than version
number to track different catalogs.  Eliminate catalogVersion where
appropriate.

ENG-7573: Introduce catalog hash down into CorePlan.  Goes nowhere

---

src/frontend/org/voltdb/jni/ExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

This was causing an array out of bounds exception when the EE was
calling back into Java, and the EE was crashing.
This isn't a complete fix, as I still don't understand why m_sqlTexts did not have text for the fragment, but it least avoids taking down the EE.

Do bounds-checking when getting SQL text for long running query

---

tools/kit_tools/build_kits.py

It was checking for V4.5 or greater (and doing it wrong), but it isn't
needed at all. build_kits.py can be used to build another branch or tag,
but is not used that way by Jenkins or any other processes.

ENG-7619.  Remove version check logic used by rabbit-mq builder code.

---

examples/json-sessions/client/jsonsessions/JSONClient.java
examples/json-sessions/ddl.sql

happening (e.g. "using 'field'" or "using 'set_field'"), but especially,
emphasizing which is the old way and which is the new & improved way
(e.g. "the old way, using nested calls of 'field'" versus "using newer,
simpler dot notation”), per ENG-7599.

JSONClient: updated explanatory text only, including emphasizing what's

---

src/frontend/org/voltdb/jni/ExecutionEngine.java
tests/frontend/org/voltdb/benchmark/tpcc/procedures/FragmentUpdateTestProcedure.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

Also, add more testing and clean up the fragment progress update test.
I put an explanation of what happened with this bug in the ticket:
https://issues.voltdb.com/browse/ENG-7610

Use correct SQL text for logging long-running fragments

---

src/frontend/org/voltdb/compiler/AsyncCompilerAgent.java
tests/frontend/org/voltdb/TestAdhocWithOnlyComment.java

statements rather than returning nothing and hanging the client.

ENG-7593: Return an error to the client if @AdHoc has no actionable

---

src/frontend/org/voltdb/compiler/ClassMatcher.java
tests/frontend/org/voltdb/compiler/TestClassMatcher.java

Improved the regex generator in ClassMatcher so that '*' allows an empty string and '.' is forced to be literal in the regex.

ENG-7223 wildcard class drop

---

src/frontend/org/voltdb/utils/SQLCommand.java

Was shifting past the verb in the string twice. Fix was to delete the original shifting code.

ENG-7701 Fix explain command broken by ENG-7556

---

lib/python/voltcli/environment.py
lib/python/voltcli/runner.py
lib/python/voltcli/utility.py
lib/python/voltcli/verbs.py

Mainly had to deal with quoted arguments because exec doesn't filter them the way the shell does. We were improperly combining multiple arguments in quotes and also unnecessarily quoting paths. This solution won't handle all possible shell quoting, but is good enough for running volt.

ENG-7496 Replace python process with server

---

src/ee/common/StreamBlock.h
src/ee/storage/TupleStreamBase.cpp

Reset m_lastDRBeginTxnOffset and m_openSequenceNumber on transaction
rollback.

ENG-7796: Correctly reset DR buffers on txn rollback.

---

src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java

In case an error occurred when applying the binary log, the exception
will be propagated to the procedure and handled there.

ENG-7797: Propagate EE exception to @ApplyBinaryLog.

---

src/ee/voltdbipc.cpp

Following the pattern of not catching SerializableEEException. The IPC
process will probably exit when it hits the exception.

Fix IPC build compilation failure.

---

src/frontend/org/voltdb/planner/ParsedUnionStmt.java
tests/frontend/org/voltdb/planner/TestUnion.java

Paul,
The parameters were not propagated from the ParsedUnionStmt to its children.
Added childStmt.m_paramsById.putAll(m_paramsById) to the ParsedUnionStmt.parseTablesAndParams
Mike

Propagate parameters to the union statements

---

tests/frontend/org/voltdb/iv2/TestSpPromoteAlgo.java

Only generate uniqueId for SPs in the test or the MPs will have the
wrong uniqueIDs.

ENG-7832: Fix broken TestSpPromoteAlgo.

---

build-client.xml

ENG-7858. Change build-client.xml to have strict list of included files.  
The build now makes a copy of the required sources before compiling them.   The 2nd commit shows which files were missing from the previous <include> list.

Eng 7858 real fix build client

---

src/hsqldb19b3/org/hsqldb_voltpatches/DatabaseManager.java

There seems to be bugs in HSQL's implementation, which lead to sporadic out-of-bounds exceptions in tests that exercise schema changes.

Replace use of HSQL's HashMap with java.util.HashMap

---

src/ee/common/NValue.hpp
tests/ee/storage/persistent_table_log_test.cpp

Reset all the bits when setting an inline VARCHAR or VARBINARY, or it
may have unexpected consequences when used in an uncleared tuple during
byte comparison.

ENG-7880: Fix unsafe use of temp tuple in the EE.

---

src/frontend/org/voltdb/utils/SQLCommand.java

My recent fix to bypass the translation of LOAD/REMOVE commands 
into exec @UpdateClasses commands and rewrite them directly as 
m_client.callProcedure("@UpdateClasses" calls missed the fact that these 
particular exec calls never actually become m_client.callProcedure("@UpdateClasses"
calls at all -- they are special cased to become direct m_client.updateClasses calls.

ENG-7886 Fix regression in sqlcmd LOAD CLASSES

---

src/frontend/org/voltdb/utils/SQLCommand.java

Interactive sqlcmd was normally exiting via System.exit, bypassing the finally block that saved history between sessions.

one-line fix for sqlcmd save history

---

tests/scripts/sql_coverage_test.py

contents of any <td …> tag, not only ones that read <td align=right>;
and changed the default value of next_col_val (used when an exception is
encountered) to “0” (not “-1”).
Whereas my previous change caught the exception that was being encountered, this change should prevent it. (Though the defensive, exception-catching code remains, just in case.)

sql_coverage_test.py: fixed next_keyStats_column_value(), to parse the

---

src/ee/storage/persistenttable.cpp

The binary log mark used for rollback incorrectly included the end
transaction entry for the committed transaction because the end
transaction entry is written in the same appendTuple() as the binary log
entry that will be rolled back.

ENG-7849: Fix incorrect DR binary log rollback.

---

src/ee/storage/BinaryLogSink.cpp

It is possible to get two begin txn entries with the same sequence
number in the binary log if there was a rollback. The check should make
sure that this is allowed unless there was real binary log data in the
previous transaction.

ENG-7849: Fix a bogus check in BinaryLogSink.

---

src/frontend/org/voltdb/parser/SQLParser.java
tests/frontend/org/voltdb/parser/TestSQLParser.java

Note to reviewer: expectFromAll test helper function just got moved unchanged -- real test change was addition of recall command parser tests.
Also, I manually  tested interactive sqlcmd.

ENG-7916 fix recall parser crash from failure to expect its argument

---

src/frontend/org/voltdb/utils/SQLCommand.java
tests/sqlcmd/baselines/batching/file_inlinebatch_simple.outbaseline
tests/sqlcmd/baselines/batching/file_inlinebatch_simple_via_file.outbaseline
tests/sqlcmd/scripts/batching/file_inlinebatch_simple.in

Tested by extending a sqlcmdtest script
-- also added db schema cleanup steps to the test script.

ENG-7917 refresh sqlcmd metadata cache after a batch

---

src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h
tests/ee/storage/DRTupleStream_test.cpp

It was possible that when a transaction rolls back, it doesn't roll back
the BEGIN TXN entry, leaving it orphaned in the binary log. This causes
problems like inconsistent unique IDs for the same sequence number
downstream.
Returning the correct start USO for the undo actions to correctly
rollback all entries generated by a transaction.

ENG-7849: Rollback BEGIN TXN entry in the binary log.

---

src/ee/common/UndoQuantum.h
tests/ee/common/undolog_test.cpp

Undo actions should be released in FIFO order, which is the reverse of
what undo does. Think about the case where you insert and delete a bunch
of tuples in a table, then does a truncate. You do not want to delete
that table before all the inserts and deletes are released.

ENG-7918: Reverse the order of releasing the undo actions.

---

src/ee/storage/DRTupleStream.cpp

Wrong null array position, the header size already includes the null
array size.

ENG-7929: Fix DR tuple stream serialization error.

---

src/ee/storage/DRTupleStream.cpp

Forgot to add the current IO position to the null array location.

ENG-7929: Fix DR tuple stream serialization.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/RestoreAgent.java

In extractBuildInfo, use early return and fall-through instead of a RuntimeException throw+catch to implement normal flow control.
In "RestoreAgent.generatePlans", just fudge an error message in the unlikely (maybe impossible) event of a JSON exception during its formatting. This is preferable to leaking the exception to the caller. The caller is set up to call crashGlobalVoltDB on any exception.

Tweaks to prevent unwarranted throws/crashes.

---

src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Always include all tables in the coalesced truncation snapshot.

ENG-7952: Fix incomplete coalesced truncation snapshot during join.

---

src/frontend/org/voltdb/RealVoltDB.java

Enable the stats agent after all system components are constructed to
avoid stats request handling racing with the construction of the
sub-systems.

ENG-7874: Eliminate race caused by stats agent being initialized too early

---

tests/geb/vmc/src/tests/FullDdlSqlTest.groovy

calling ensureOnSqlQueryPage(), that we have actually arrived on the
SqlQueryPage; this won’t prevent a problem I saw running this test in
Jenkins, but it will make it clear that the problem is failing to arrive
on the correct page, rather than some kind of compile/include problem,
as it first appeared.

FullDdlSqlTest.setupSpec() & .cleanupSpec(): added a check, after

---

src/frontend/org/voltdb/RealVoltDB.java

The DR port can be passed in from the command line or set in the
deployment file. The cluster metadata should include the final decision
instead of just the command line arguments.

ENG-8053: Include correct DR interface and port in the cluster metadata.

---

src/frontend/org/voltdb/parser/SQLParser.java
tests/frontend/org/voltdb/parser/TestSQLParser.java

What's missing from here?
- No VMC support (yet)
- No sqlcmdtest tests (I tested manually)

Support hexadecimal literals in sqlcmd's EXEC syntax

---

tests/geb/vmc/src/pages/VoltDBManagementCenterPage.groovy
tests/geb/vmc/src/tests/TestBase.groovy

waitForVoltDBManagementCenterPage() & toVoltDBManagementCenterPage()
methods, to make sure that the tests don't just hang, waiting for the
browser to display the VoltDBManagementCenterPage (i.e., the VMC); and
to allow a second attempt, in the event of any problems (hang or
otherwise).
VoltDbManagementCenterPage: just changed the url to be '' (empty
string), rather than '/' (relative to the baseUrl, which is typically
'http://localhost:8080/').

TestBase: expanded ensureOnVoltDBManagementCenterPage(), and added

---

tests/ee/indexes/index_test.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/PersistentTableMemStatsTest.cpp
tests/ee/storage/constraint_test.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/ee/storage/table_test.cpp

Found by @BillWhite . Sad that we didn't pick this up earlier.

Fix nonsensical parameter passing to TableFactory::getPersistentTable() in c++ unit tests.

---

src/frontend/org/voltdb/compilereport/ReportMaker.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Some minor changes to the catalog report for row limit delete statements.  I also change how we capture the statement in HSQL so that whitespace is condensed, similar to what we do with views.

Improve display of DELETE statement for row limit triggers in VMC

---

src/hsqldb19b3/org/hsqldb_voltpatches/ErrorCode.java
src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLogical.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariableResolver.java
src/hsqldb19b3/org/hsqldb_voltpatches/TableDerived.java

These are just stylistic tweaks of Mike's work.
There were a few cases of minor whitespace-only or dead-code only changes from the original HSQL code that I backed out.
I cleaned the structured comments to more clearly mark disabled lines, new VoltDB patches, and cherry-picks from future hsql -- Mike made wise use of future code to patch current bugs, so the amount of new VoltDB code in this part of his changes turned out to be pretty minimal. We'll be glad of that soon when we upgrade. It may even help with some of the "known problems" I've already detected in the upgrade merge.
In a few places, I streamlined out some redundancy, but I don't think that I found any need to change the code's effective behavior.

HSQL Style tweaks from subquery code review.

---

tests/scripts/examples/sql_coverage/basic-select.sql

the simplest scalar subqueries. (Note: more scalar subquery patterns
will be added to a separate file, advanced-scalar-subquery.sql.)

basic-select.sql: added two basic query (sqlcoverage) patterns, to test

---

src/frontend/org/voltdb/ParameterConverter.java
src/frontend/org/voltdb/expressions/ConstantValueExpression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionArithmetic.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLogical.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionValue.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserBase.java
src/hsqldb19b3/org/hsqldb_voltpatches/types/BinaryData.java
src/hsqldb19b3/org/hsqldb_voltpatches/types/NumberType.java
tests/frontend/org/voltdb/compiler/TestVoltCompilerErrorMsgs.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestHexLiteralsSuite.java

This changeset supports using hexadecimal literals (`X'00ABCD'`) to express integers in SQL.
This required some changes to HSQL to convert VARBINARY literals into BIGINTs based on context.  This is done for arithmetic (+, -, *, /) and logical (<. >, =, etc) expressions, and the new bitwise functions.
I decided *not* to support hexadecimal literals for the other, non-bitwise functions, since it seems really unlikely that a user would ever type something like `SQRT(X'0100')`.  The way HSQL handles the non-VoltDB specific functions this would require changes for each function.  I can file a ticket to support these other functions, if we feel there's a need for it.

Support hexadecimal literals as integers

---

src/ee/execution/VoltDBEngine.cpp
src/ee/expressions/subqueryexpression.cpp
src/ee/expressions/subqueryexpression.h
src/ee/plannodes/plannodefragment.cpp
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

The first commit addresses the valgrind issue.
I added back in `std::` prefixes in VoltDBEngine.cpp.  I made this its own commit, since it makes it difficult to see the other changes.
I convinced myself that calls to `erase` that were in a couple destructors are not needed, so I removed them.
I also updated TestSubQueriesSuite now that valgrind is passing there.

Address valgrind issue and minor changes

---

src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h
src/ee/expressions/stringfunctions.h
tests/ee/expressions/function_test.cpp
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java

1. I had to move the const int POOLED_MAX_VALUE_LENGTH into the ThreadLocalPool.  It's still static, but it's now class static and not file static.
2. I wrote a small check in the existing C++ code.
3. I wrote a C++ unit test for this.  This required making the binary test function more generic.
3. I wrote a small test in the existing Java code.

Guard the argument to REPEAT(str,count) to prevent memory explosion.

---

tests/geb/vmc/src/tests/SqlQueriesTestBase.groovy

WaitTimeoutException, and give it a second chance to open the
SqlQueryPage, since this is the spot where we most often see sporadic
test failures.

SqlQueriesTestBase.ensureOnSqlQueryPage(): added a try/catch for a

---

src/frontend/org/voltdb/expressions/AbstractExpression.java

Old implementation just used toJsonString which was hard on the eyes.
The new output for `bi in (2, 3, 5)` looks like this in Eclipse:
```
InComparisonExpression[COMPARE_IN] : bigint
Left:
| TupleValueExpression[VALUE_TUPLE] : bigint
Right:
| VectorValueExpression[VALUE_VECTOR] : null
| Args:
|   | ParameterValueExpression[VALUE_PARAMETER] : integer
|   | ParameterValueExpression[VALUE_PARAMETER] : integer
|   | ParameterValueExpression[VALUE_PARAMETER] : integer
```
Still lots of possible improvements (could show values for constants and column names for TVEs), but this is a start.
Is there some reason this hasn't been done before?

Improve output from AbstractExpression.toString()

---

src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/expressions/ExpressionUtil.java
src/frontend/org/voltdb/expressions/InComparisonExpression.java
src/frontend/org/voltdb/expressions/ScalarValueExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/SubPlanAssembler.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

These changes add a post-pass over parsed expression trees to wrap scalar subqueries in an instance of ScalarValueExpression where needed.  I also pushed the check for single-column schema in to the code that creates the ScalarValueExpression node.
Another approach might be to always create the ScalarValueExpression over subqueries, and then remove the SVE node if its parent is a comparison operator or an EXISTS operator.  We still wouldn't avoid the overhead of a post-pass though: we would need to check that the subquery children of SVE nodes have only one column after parsing is complete.

Avoid wrong answers when using subqueries within other expressions

---

src/frontend/org/voltdb/expressions/AbstractSubqueryExpression.java
src/frontend/org/voltdb/expressions/ScalarValueExpression.java
src/frontend/org/voltdb/expressions/SelectSubqueryExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedInsertStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/ParsedUnionStmt.java
src/frontend/org/voltdb/planner/ParsedUpdateStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/planner/TestPlansScalarSubQueries.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

1. Added some fixes (hashCode, equals) trying to dedupe the duplicates expression. 
2. Add the guards not to support subquery inside of aggregation function.
3. Add the fix to be able to group by scalar value expression.

Squash commit the fix for group by scalar value subquery, add more tests

---

tests/scripts/examples/sql_coverage/advanced-scalar-subquery.sql

was causing mismatches (ENG-8292).

advanced-scalar-subquery.sql: commented out the 'A13' query, since it

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
src/hsqldb19b3/org/hsqldb_voltpatches/VoltXMLElement.java
tests/log4j-allconsole.xml

In this commit I do three things.
1. I make it possible to dump SQL statements, HSQLDB ASTs and VoltXML ASTs using the standard Volt logging mechanism.
1. I fix ENG-8299, which caused expressions to seem to ignore the right hand operand of binary operators.
1. I fix ENG-8262, which caused hangs when assertion failures in the PlannerTool circumvented the return of responses from the server to the client.  This needs to be merged to master sooner rather than later.

Eng 8299 no exclude join conditions

---

examples/uniquedevices/run.sh
examples/voter/run.sh

Several customers have reported problems running the voter demo.  It gets stuck on "... Waiting for VoltDB to start".  It stops printing this because it has actually succeeded, but sqlcmd is waiting for entry or somehow not exiting properly when invoked using the --query parameter and redirecting output.  When it is invoked using STDIN, it exits as expected.  This behavior is only seen on a Mac, on Linux (even old versions) it works as expected.
I filed a ticket for sqlcmd to exit properly in this scenario, but this minor change to the run.sh script fixes the demo on a Mac.  I will be making the same changes to the separate app-* demos on github.

fixes run.sh demo

---

src/frontend/org/voltdb/utils/PBDRegularSegment.java

Pooled buffers may introduce unnecessary heap usage due to the variable
buffer size.

ENG-6950: Use unpooled buffers in the PBDRegularSegment.

---

src/frontend/org/voltdb/CommandLogStats.java
src/frontend/org/voltdb/DummyCommandLog.java
tests/frontend/org/voltdb/regressionsuites/TestStatisticsSuite.java

Change column name from LOANED_SEGMENT_COUNT to IN_USE_SEGMENT_COUNT so it is more user-friendly.

Change column name describing segments in use

---

src/ee/expressions/abstractexpression.cpp
src/frontend/org/voltdb/types/VoltDecimalHelper.java
tests/frontend/org/voltcore/utils/TestCOWNavigableSet.java
tests/frontend/org/voltdb/jdbc/TestJDBCQueries.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlInsertSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/rollbackprocs/MultiPartitionParamSerializationError.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/rollbackprocs/SinglePartitionParamSerializationError.java

When we see a string which has more scale than we support, we will now round it up to the
closest supported value.  We round a value equidistant between two supported values up.
This is all done using BigDecimal's round function and the ROUND_UP rounding mode.
I had to make some inessential changes in a C++ file and a java test file.  Apparently
the C++ compiler on my macbook thinks "this" can never be null, and it is offended that 
someone would test for it.  I had to work around that.  Also, Eclipse was unhappy about
a test, so I had to cast an Object to be Comparable.  The test was testing that such a
cast would cause a ClassCastException.  This is really kind of a silly test, and tests
the Java compiler more than the VoltDB code.

Eng 8343 round decimal scale

---

src/frontend/org/voltdb/compiler/AsyncCompilerAgent.java

Catch AssertError exceptions in the planner, and return a proper
response.  Don't hang the client waiting for a response.
Note that this is not to be merged to master, but to ENG-8070-hsqldb232-upgrade.  The master version will come soon.

This seems like a very simple change which will cure some of the hanging behavior.

---

tests/scripts/examples/sql_coverage/advanced-inexists.sql

pattern ('A44'), testing column expressions on the LHS of the comparator
in an ANY/ALL query (in the outer query, not the sub-query as before).

advanced-inexists.sql: per Paul's clarified suggestion, added one more

---

src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/types/VoltDecimalHelper.java
tests/frontend/org/voltdb/jdbc/TestJDBCQueries.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestDecimalRoundingSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/rollbackprocs/MultiPartitionParamSerializationError.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/rollbackprocs/SinglePartitionParamSerializationError.java

We round up after 12 digits of scale.  Rounding happens in both the client before the wire
protocol and in the server after the wire protocol.  The server
is configured with a pair of system properties, one to enable
or disable, and one to set the rounding mode.  The client is
configured with a ClientConfig function call.  If the server
and client are configured differently, the results may be
unpredictable.
There are tests for JDBC and for the client interface.

Implemented Rounding for the DECIMAL type.

---

src/ee/storage/MaterializedViewMetadata.cpp

There is a bug in findExistingTuple that can make a materialized view crash if the source table is not empty before view creation.

ENG-8546 Fix crash bug in findExistingTuple

---

src/frontend/org/voltdb/VoltType.java
src/frontend/org/voltdb/planner/ParameterizationInfo.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestAdHocPlannerCache.java
tests/frontend/org/voltdb/regressionsuites/TestDecimalRoundingSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

AdHoc query fix:
1. Treat constants in SQL literal numbers either as integer or decimal.
2. Add tests for float E sign.
3. Fix the various of AdHoc planner caching with type issues.
4. Refactor and add more testing utils.
---
Missing stored procedure fix (Can be done separately from this ticket):
5. Stored procedure constants literal value fix either integer or decimal.
6. More tests on out of range of our decimal literal value if needed.

Various AdHoc constants value fixes

---

src/ee/common/NValue.cpp
src/ee/common/NValue.hpp
tests/ee/common/nvalue_test.cpp
tests/frontend/org/voltdb/regressionsuites/TestDecimalRoundingSuite.java

When we create a decimal number from a string in the EE,
and the resulting decimal number would have a scale which
is too large, we round the decimal number to 12 decimal digits.
If the resulting rounded number is still too large we throw
and exception.
There are java unit tests and C++ unit tests.

Decimal Rounding in the EE.

---

src/frontend/org/voltcore/messaging/HostMessenger.java

Changes the messaging when a node fails to:
WARN: Received remote hangup from foreign host 172.17.0.6
WARN: Host 1 failed. Cluster remains operational.
Other minor log cleanup. Everything is still in the on-disk log for now. Some warnings became infos to make that happen.

ENG-8576: Cleanup logging in HostMessenger.

---

src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
tests/log4j-allconsole.xml

Improve AST Printing in HSQLInterface.  When printing the HSQLDB AST we
get exceptions sometimes, mostly NPEs.  This can cause printing the
VoltXML printing to not be done, even if it would print just fine.

Improve AST Printing in HSQLInterface.

---

src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

The proposed new DR UI document requires the master node to always "listen" to network, even the "listen" attribute in the deployment file is not being set.

Eng 8526 always listen if dr tag present

---

src/hsqldb19b3/org/hsqldb_voltpatches/types/NumberType.java

In trying to identify TestFunctionsSuite issues, I discovered that the diagnostic hsql describe function would generate a lot of stack trace noise. This patch allows describe (and anything else that may try to string-format a supposedly float-typed constant) to succeed in cases where it used to throw a cast exception.

Relax hsql232 describe for supposed float-type constants

---

build.py
src/ee/common/TupleSchema.cpp
src/ee/common/TupleSchema.h
src/ee/common/TupleSchemaBuilder.h
src/ee/common/tabletuple.h
src/ee/storage/TableCatalogDelegate.cpp
tests/ee/common/tupleschema_test.cpp

Add cpptest for TupleSchema
Implmement a TupleSchemaBuilder class
A stubbed out version of hiddenColumnCount()
Reflect number of hidden columns correctly
Now passing the tuple length test
Verify details of hidden columns
Add convenience method for getting total number of columns
Add comments to TupleSchema header
Make isCompatibleForCopy work right
Also rename it it to isCompatibleForMemcpy, and other small changes.
Add more tests for schema equality involving hidden columns
Add more comments
Make TableCatalogDelegate use TupleSchemaBuilder
Refactor field inlining logic
Convert from chars to bytes in refactored logic

Add ability to create hidden columns to TupleSchema

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateBaseProc.java

Also added inserts to make sure the values retrieved from the database are non-zero.

Added generated byte array as value to partitioned/replicated tables in TxnIdSelfcheck2

---

tools/kit_tools/build_kits.py

Change to build_kit.py to try to checkout all branches and provide all errors rather than exiting on each error in sequence.
Second, if there's no RabbitMQ of the same branch name, fall through which defaults it to master.

ENG-8646 improve checkout error handling and set default to master

---

build.py
src/ee/common/TupleSchema.h
src/ee/common/tabletuple.cpp
src/ee/common/tabletuple.h
src/ee/executors/updateexecutor.cpp
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/TableCatalogDelegate.hpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/table.h
src/ee/storage/tablefactory.cpp
tests/ee/common/tabletuple_test.cpp
tests/ee/common/tupleschema_test.cpp
tests/ee/storage/persistenttable_test.cpp
tests/ee/test_utils/ScopedTupleSchema.hpp

When creating a persistent table from the catalog, add a hidden column
for the DR timestamp to the schema if active/active DR is enabled and
the table is being DR'd.
When rows are inserted or updated in such a table, update the hidden
column with the current DR timestamp.
Add unit tests for this work.

For A/A DR, tag DR'd rows with timestamp

---

tests/geb/vmc/src/tests/SqlQueriesTest.groovy
tests/geb/vmc/src/tests/TestBase.groovy
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateBaseProc.java

Code to fix ENG-8509, which is caused by Selenium trimming (removing leading & trailing whitespace) the query results. Plus some of the code for ENG-8617.

Eng 8509 geb trim failures

---

src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/planner/TestPlansCount.java

When I was writing some planner tests, I was encountering failed
assertions because a scan plan node had more than one child.  I
traced the cause to the method `connectChildrenBestPlans` which seems
to have been added as part of in/exists/scalar subquery support.
I wasn't able to recreate this issue using sqlcmd (I tried both ad hoc
and procedures), but seems like this issue might manifest in a
real-world scenario?
The added test was failing assertions in the planner before the fix.

Clear existing children when connecting subqueries to plan

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/CopyLoadPartitionedBase.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/CopyLoadPartitionedMP.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/CopyLoadPartitionedSP.java

This pull request changes the LoadTableLoader's table copying behavior to 50% of the time use a select statement followed by an insert statement, and 50% an insert into <table> select ... statement.

ENG-6685-txnid2_add_insert_into_select

---

src/ee/voltdbipc.cpp
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java

uniqueId should be after lastCommittedSpHandle, not before

ENG-8813: Fix wrong order of parameters provided for nativeLoadTable

---

tests/geb/vmc/src/pages/SqlQueryPage.groovy
tests/geb/vmc/src/resources/expectedSystemStoredProcs.txt
tests/geb/vmc/src/tests/SqlQueriesTest.groovy

This is the squashed version of VMC-223-fix-sql-queries, which includes:
SqlQueryPage.groovy: fixed getDefaultStoredProcedures & getUserStoredProcedures, and simplified those and getSystemStoredProcedures, by calling a new private method, getSpecifiedStoredProcedures, and, more importantly, correctly updating the Navigators they use (defaultStoredProcsHeader, userStoredProcsHeader & userStoredProcs), which were changed by VMC-210.
SqlQueriesTest.groovy: fixed problem where an unexpected error causes an
exception (introduced by my fix for ENG-8509).
expectedSystemStoredProcs.txt: just removed an obsolete comment.

Fixed getDefaultStoredProcedures & getUserStoredProcedures

---

tests/sqlcmd/baselines/batching/file_batch_positive.outbaseline
tests/sqlcmd/baselines/simple/exec.outbaseline
tests/sqlcmd/scripts/batching/file_batch_positive.in
tests/sqlcmd/scripts/simple/exec.in

file_batch_positive.in: added "drop table t;" and "drop table s;" to the end, to clean up the tables that are created by this test (which were sporadically causing load_remove_classes to fail).
file_batch_positive.outbaseline: added lines to the end, expecting the new "drop table t;" and "drop table s;" lines, plus two "Command succeeded." in response.
exec.in: added "drop table t2;" to (near) the beginning, just as a precaution.
exec.outbaseline: added lines to (near) the beginning, expecting the new "drop table t2;" line, plus a "Command succeeded." in response.

Fix sporadic failures of load_remove_classes, in sqlcmdtest

---

src/hsqldb19b3/org/hsqldb_voltpatches/types/NumberType.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

This issue was in code called from Expression.getSQL.  It seems like we only use this method when creating expression indexes.  We use the expression text to create a hash for the index in case we need an auto-generated name.  So the SQL text generated via this method isn't actually executed, it's just used to generate unique names.  So this is a low-risk change.
We don't use this method for other places where we capture SQL, e.g., views.  In those cases we capture text at the token level.

Fix crash when creating expression index

---

src/catgen/catalog.py

If one catalogType class has more than one catalogMaps with same type signature, catalog.py will generate wrong C++ code.

Fix catgen's bug

---

src/frontend/org/voltdb/iv2/SpDurabilityListener.java
src/frontend/org/voltdb/iv2/SpScheduler.java

The DR consumer may add itself to the durability listener after node
initialization. The DurabilityListener is not thread-safe, the accesses
to the listener list should be on the Site thread.

ENG-8889: Fix concurrent modification of the durability listener.

---

tests/scripts/SQLGenerator.py
tests/scripts/examples/sql_coverage/advanced-scalar-subquery.sql
tests/scripts/examples/sql_coverage/grammar.sql

BaseGenerator), to allow re-using the same text (for example, the same
aggregate function name) multiple times within the same query, to allow
reducing the number of queries generated by a single pattern. And, to
allow the same comparison operator to be used multiple times within the
same query (as for function names), tweaked the regular expression for a
'type'. Also, changed the default value for max_statements_per_pattern
to -1 (rather than 0), to match min_statements_per_pattern. Also, added
'import sys' near the beginning, which may help a separate issue
(ENG-8756).
advanced-scalar-subquery.sql: reduced the number of queries generated by
most patterns (and therefore the execution time), by using the new
'_symbol' feature to represent the same aggregate function (MIN, MAX,
COUNT, SUM …

SQLGenerator.py: added a new class SymbolGenerator (sub-class of

---

src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/persistenttable_test.cpp

Logic updates include:
-  Allocation of the tuple storage block to persistent table happens when creating persistent table via table factory method instead of doing so on demand - first tuple insertion.
- When freeing up tuple storage during tuple delete, caller can specify whether to release the empty tuple storage block if it's the only remaining block.
- Added unit test for truncate table case.

Eng 8872 new

---

build.py
src/ee/common/DefaultTupleSerializer.cpp
src/ee/common/FullTupleSerializer.cpp
src/ee/common/FullTupleSerializer.h
src/ee/common/RecoveryProtoMessageBuilder.h
src/ee/common/TupleSchema.cpp
src/ee/common/TupleSchema.h
src/ee/common/tabletuple.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/RecoveryContext.cpp
src/ee/storage/RecoveryContext.h
src/ee/storage/TableStreamerContext.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/table.cpp
src/frontend/org/voltdb/DefaultSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SavedTableConverter.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/ee/common/tupleschema_test.cpp
tests/ee/storage/DRBinaryLog_test.cpp

serialize/deserialize to DR has no knowledge of hidden columns, normal serialize/deserialize now has; native & stream snapshot can now save/restore hidden columns, index snapshot needs investigation
Make restore procedure DR-aware, add related tests
Consider hidden columns when loading table in EE
Move setDRTimestamp outside insertTupleCommon for snapshot restore purpose
Fix missing declaration
Refactor add hidden column logic in table converter
Add logic for EE to set uninitialized DR timestamp column during snapshot restore
Clean up unnecessary code
ENG-8723, address remaining review comments, also rebase with master branch.
Change-Id: I34d50894d866b7f1174dea5fcaab86300cf323e5
ENG-8723, if schema contains hidden DR timestamp, tempTuple creation shoule initialize the hidden column value …

Need to have name for hidden columns for snapshot restore to work

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/common/tabletuple.h
src/ee/common/types.cpp
src/ee/common/types.h
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/storage/table.cpp
src/ee/storage/table.h
src/ee/storage/tableutil.cpp
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/PartitionDRGateway.java
tests/ee/common/tupleschema_test.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/ee/storage/table_test.cpp

Add test for new function in TupleSchema
Delete global refs in destructor of JNITopend
Add NULL check for output table parameter
Count length placeholder for variable length columns
ENG-8596, rename function to make the intention more obiviously.
Change-Id: I48a68c0e22dff20baecc11a7f74eb86182695a8a
ENG-8596, eliminate reduntant code, fix ee unit test, remove unnecessary call of deleteLocalRef().
Change-Id: Id8a2774828d915aff0f10adae311ee9c92ad076d
ENG-8596, fix license check.
Change-Id: Ia2aa636cda48b42208fd5bd042e05886c180fe0a
ENG-8596, fix ee test case that only fails on all Linux platforms (but not OSX).
Change-Id: Ica8ef0f30386a1d9f76d707601540d3413c6bc32

Add EE to frontend callback interface for logging DR conflicts

---

tests/scripts/examples/sql_coverage/advanced-scalar-subquery.sql

are commented out because they do not currently work (i.e., return
errors), cleaned them up, and their associated comments, to make it
clearer why they don't work (related to which Jira tickets), and what
fixes may make them work, as a follow-up to Paul's comments, and
a brief discussion we had, about ENG-8564.

advanced-scalar-subquery.sql: for those GROUP BY and HAVING queries that

---

src/ee/common/executorcontext.cpp

This caused a hard EE crash during development.  (I had new functions
added to the planner not yet implemented in the EE.  This should have
just returned an exception to the user.)

Check that executors map is not null in temp tables emptiness check

---

tests/test_apps/s2/taxi_ddl.sql

This was my take on our conversation.  I wrote notes on the white board, but got kicked out of the room before I remembered to write my notes down, so this is from memory.
1. I renamed the point table to be taxis.  You can change it to be drivers if you want.  
1. I also added cities.  I think it's easy to add them, and I don't think it hurts anything.
1. I replicated the polygon table to be counties and states, since we wanted some nested structure.  Each has a cellid2id join table, and a couple of indices.
1. The tables ending in _map and the indices ending in _idx will together be our geospatial index, and will not be visible to the users, I think.

Created a schema for a possible application.

---

src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/persistenttable_test.cpp

This reverts commit 0e64e9b27640629315c3b4994cf5167515e8f600, reversing
changes made to ca15957839a2fea1d77bfa3e124d37e634dd891f.
Conflicts:
tests/ee/storage/persistenttable_test.cpp

Revert "Merge pull request #2771 from VoltDB/ENG-8872-New"

---

tests/frontend/org/voltdb/regressionsuites/TestComparisonOperatorsSuite.java

Update "is distinct from" TestComparisonOperatorsSuite junit tests to be order deterministic so that it produces result set in same deterministic order.
Verified after the changes "TestComparisonOperatorsSuite" junit test passes with release, debug and memcheck builds.

Update junit tests to be order deterministic so that it produces result set in same order

---

lib/python/voltcli/voltadmin.d/save.py

voltadmin was passing incorrect JSON fields to @SnapshotSave in some
cases. If user didn't specify tables to include, the JSON should not
include the 'tables' field. Including it with an empty array would
indicate no table should be included in the snapshot.
Change-Id: I8c93c5aac045bb08dad3ea4a5ef5371dae47f2bc

Fix voltadmin save.

---

src/ee/common/StringRef.cpp
src/ee/common/StringRef.h
src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h
src/ee/storage/TupleBlock.h
src/ee/storage/persistenttable.h
src/ee/storage/temptable.h
tests/ee/storage/persistent_table_log_test.cpp
third_party/cpp/boost_ext/FastAllocator.hpp

This changeset is mostly refactoring for simplified interfaces and adding comments.
The two small intended behavior changes are:
a bug fix specific to MEMCHECK builds where strings that SHOULD be leaked into the temp string pool were being explicitly deleted -- not sure why memcheck runs seemed to only sometimes complain.
an odd failure mode when freeing an invalid allocation in ThreadLocalPool that arose from too much
shared code between the allocate and free code paths. If the ThreadLocalPool could not find a pool from which to deallocate an object, based on the claimed size of the object, instead of failing, it tried to allocate a new pool for that object size (DOH!) before complaining that the pool did not contain the object (DUH!). This should never happen in production, but it has …

Simplify ThreadLocalPool memory management API

---

build.py

The python rules for choosing the C++ language setting were correctly
stated but incorrectly coded.  On Ubuntu 12.04 the system compiler is gcc 4.6.3.  We need
to compile with --std=03 there.  Also, we need to include -Wno-unused-set-variables.

Fix the language standard for gcc 4.6.3 (Ubuntu 12.04).

---

src/frontend/org/voltdb/compiler/PlannerTool.java

PlanningErrorExceptions and HSQLParseExcptions are extected behavior in
the planner.  So, we don't want stack traces for them.  Also, log to the
COMPILE logger, not the HOST logger.
I'm not 100% sure this solves the problem.  I'm not sure how to reproduce it.

Don't print too many stack traces.

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/execution/ProgressMonitorProxy.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/executors/indexscanexecutor.cpp
src/ee/executors/nestloopexecutor.cpp
src/ee/executors/nestloopindexexecutor.cpp
src/ee/executors/seqscanexecutor.cpp
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java

Here's another try at simplifying how we log long-running fragment messages.

Remove some complexity from long-running fragment progress report API

---

src/frontend/org/voltdb/compiler/ProcedureCompiler.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/expressions/AbstractSubqueryExpression.java
src/frontend/org/voltdb/expressions/AggregateExpression.java
src/frontend/org/voltdb/expressions/SelectSubqueryExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/CompiledPlan.java
src/frontend/org/voltdb/planner/ParsedDeleteStmt.java
src/frontend/org/voltdb/planner/ParsedInsertStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/ParsedUnionStmt.java
src/frontend/org/voltdb/planner/ParsedUpdateStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/parseinfo/BranchNode.java
src/frontend/org/voltdb/planner/parseinfo/JoinNode.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
tests/frontend/org/voltdb/compiler/TestVoltCompilerAnnotationsAndWarnings.java
tests/frontend/org/voltdb/compiler/procedures/InsertAggregatesOfFloat.java
tests/frontend/org/voltdb/compiler/procedures/InsertAggregatesOfFloatInHaving.java
tests/frontend/org/voltdb/compiler/procedures/InsertAggregatesOfFloatWithSetops.java
tests/frontend/org/voltdb/planner/TestDeterminism.java
tests/frontend/org/voltdb/planner/testplans-determinism-ddl.sql

If some aggregate functions are applied to floating point parameters the
result may be non-deterministic, due to floating point numeric
differences.  We need to causes errors or warnings in this case.  This
is complicated by the fact that the error messages need to propagated up
from the aggregate call expression through the containing expressions,
into the subquery statement object.  From there it may need to propagate
into a join tree or in ParsedUnionStatement objects if the expression is
in a subquery of a joined table or in a subquery of a union or
intersection expression.

Calculate non-determinism of aggregates of floating point types.

---

src/ee/execution/VoltDBEngine.cpp
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

The sqlcmd query timeout message in the EE only printed 2 decimal digits
of precision.  This did not allow for millisecond precision.  This
change increased this to 3 decimal digits.
https://issues.voltdb.com/browse/ENG-9246

Change the timeout message to allow millisecond precision.

---

src/frontend/org/voltdb/expressions/AggregateExpression.java
tests/frontend/org/voltdb/compiler/TestVoltCompilerAnnotationsAndWarnings.java

The aggregate functions min and max of floating point expressions are
deterministic.  In the previous commit, 758efd3, we incorrectly called
them non-deterministic.
https://issues.voltdb.com/browse/ENG-9358

Min and Max of float are deterministic.

---

tests/sqlcmd/baselines/querytimeout/timeout.errbaseline
tests/sqlcmd/sqlcmdtest.py

ENG-9246 added an extra digit to the query-timeout error message (now
showing milliseconds), which broke sqlcmdtest. This fixes that, by
changing the expected message from "1.00 seconds" to "1.00# seconds",
and alters the clean_output method, to ignore that final millisecond
digit, replacing it with "#", so they now match.

sqlcmdtest.py, timeout.errbaseline: fix sqlcmdtest: Bill's fix for

---

tests/frontend/org/voltdb/regressionsuites/TestUnionSuite.java

The test TestUnionSuite.testUnionStar had a query which returned order
non-deterministic results.  This sometimes caused test failures.  This
commit works around this by adding an order-by to the query.
https://issues.voltdb.com/browse/ENG-9395.

Fix a test error.

---

build.xml

project.classpath; it's simpler to just set the CLASSPATH environment
variable of the machine, when needed (including in Jenkins).

build.xml: removed my kludge of setting the PostgreSQL JDBC .jar file in

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/DummyCommandLog.java
src/frontend/org/voltdb/iv2/SpDurabilityListener.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/UniqueIdGenerator.java
src/frontend/org/voltdb/messaging/Iv2LogFaultMessage.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java

On rejoin, the durability listener won't be notified until the first SP
and MP transactions are logged. This means that if the cluster is idle,
nothing is made durable. However, we do know that anything on disk prior
to the node failing must have been made durable by other nodes.
- Notify the durability listeners even if the last txn was a sysproc
that doesn't require durability. Previously, we were just letting it
through without notifying any listener.
- Propogate the last unique ID from the master SPI to the rejoining SPI
using the Iv2LogFaultMessage, which is the very first message a
rejoining SPI will get. Then initialize the durability listener with
this unique ID.
Change-Id: Iadfa4c86d53314ee06e4c912cecbbbd20cdd4e80

ENG-9383: Fix durability notification after rejoin.

---

src/catgen/in/cppsrc/catalog.cpp
src/catgen/in/cppsrc/catalog.h
src/ee/common/NValue.hpp
tests/ee/storage/DRBinaryLog_test.cpp

Catalog::hexEncodeString() assumes that the input string is always
null-terminated, which is not true. Add a length parameter to the
function so that it doesn't rely on strlen() to find the string length.
Also added some outline strings and binary data to the DRBinaryLog tests
to exercise this path.
Change-Id: I0c12ddda9f7843d2a8305979d4520b3a0120c57a

ENG-9419: Fix invalid memory access.

---

src/ee/storage/BinaryLogSink.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

DR update was incorrectly updating the hidden DR timestamp when it
applies the binary log, which causes the row to have the wrong hidden
column value. The next update or delete on the same tuple will be a
timestamp mismatch conflict.
Now the DR update path doesn't update the DR timestamp.
I'm still working on the tests. Don't delete the branch yet.

ENG-9431: Fix DR binary log update.

---

src/ee/executors/deleteexecutor.cpp
src/ee/storage/TupleBlock.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/sqlfeatureprocs/PopulateTruncateTable.java

Changes are to optimize truncate operation where instead of performing table swap of existing table with newly created empty persistent table, logic will perform deletion of all the tuple entries in the table iteratively and retain existing objects associated to table instead of creating afresh.This helps truncate operation for table with few rows to be as fast as when performing delete all rows using predicate that is true (result in deletion of all iteratively internally does).

Optimize table truncate path for fewer numbers of rows

---

src/ee/common/executorcontext.cpp
tests/ee/storage/DRBinaryLog_test.cpp

Separate the execution engines, one for master, one for replica, so they
can have two cluster IDs and such. Check for the DR timestamp after
updates.
Change-Id: I45b57d1742ae021092528c64ae980398997e6d3b

ENG-9431: Update DR binary log unit tests.

---

build.py
src/ee/common/types.cpp

Updated build script to build code using gcc 5.* in same way as it does today for gcc versions 4.3 or higher.

Add gcc 5+ version to build script

---

src/frontend/org/voltdb/RealVoltDB.java

Change-Id: Ibabd213ddadc8bb35862993e970c7c4ecf37d0aa
There is a timing window which will trigger RejectedExecutionException. When DR active-active is set and DR consumer connection is not enabled, @UpdateApplicationCatalog path will create and initialize the DR consumer first, which will let DR consumer to enter DISABLE state and shutdown the executor service thread. But the sequencing call to update DR consumer's catalog will fail to submit a task to executor service thread if the initialization task happens first.

ENG-9396, remove redundant call to initialize().

---

lib/python/voltcli/checkconfig.py
lib/python/voltcli/verbs.py

manually test:
on thp enabled machine, voltdb  create --skip-check=thp will start voltdb with warning
voltdb check won't be affected

 ENG-8980: an override to let VoltDB start even if THP is enabled

---

tests/sqlcmd/baselines/geospatial/points.outbaseline
tests/sqlcmd/scripts/geospatial/points.in
tests/sqlcmd/scripts/geospatial/points.sql

table points at the end (to clean up); also, drop both "if exists", at
the beginning (this was already done for table points, so just added
procedure make_point).

points.in, points.sql, points.outbaseline: drop procedure make_point and

---

tests/scripts/SQLCoverageReport.py
tests/scripts/sql_coverage_test.py

NPE's from VoltDB and from the comparison database (HSqlDB or
PostgreSQL), and now fail (& red, in the HTML "SQL Coverage Test
Summary") for the former, and a strong warning (in orange) for the
latter. Also, add a command-line message giving the total number of
mismatches, when that is greater than zero (matching the ones for NPE's
- 2 separate ones, now - and for crashes).

sql_coverage_test.py, SQLCoverageReport.py: keep track separately of

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/types/VoltDecimalHelper.java
tests/frontend/org/voltdb/TestVoltTable.java
tests/frontend/org/voltdb/types/TestVoltDecimalHelper.java

caused by specifying BigDecimal values that are multiples of 10, 100, etc. using E notation in a string initializer.

ENG-9630 fix BigDecimal ArrayOutOfBounds

---

src/ee/expressions/geofunctions.cpp
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

Creating pull request again. 
Changes uses mean radius of 6371008.8 meters, when calculating great circle distance and area for the spherical earth. For comparison purpose, compared the distance and area provided by VoltDB to PostGIS. Below is summary of comparison.
- Distance between point-to-point location agree to 7 digit of precision. For shorter distance on scale of 1000 meters, the answers agree till milli-meters and for long distances like distance between Boston to San Jose, answers agree to precision level of meters. VoltDB answer: 4311575.515808559; PostGIS: 4311575.49646372.
- The difference in distances between spherical-to-spheriod (Spheriod distance calculated using PostGIS) distances is about 0.03% (https://en.wikipedia.org/wiki/Great-circle_distance#Radius_for_spherical_Ear …

Use earth's mean radius for geo computation

---

lib/python/voltcli/checkconfig.py

Change version number checking to examine x.y even if O/S provides x.y.z as in RHEL/CentOS 7 and beyond.
One question -- should we continue to "pass" Ubuntu 10.04?

ENG-9640 Accept CentOS/RHEL 7.x.y in addition to existing versions.

---

src/ee/common/GeographyValue.hpp

There is an assertion in the include file src/ee/common/GeographyValue.hpp which is too strict.  It used to demand that the depth of a loop is less than 2.  However, since these values may come from a user directly, and we don't validate polygons unless we are asked, the database could very well have a loop at different depth than 0 or 1.  The resulting polygons would be invalid, but that should not cause the EE to crash.
Note that this only affects debug builds, where assertions are enabled.  Note also that we still check that the depth is non-negative.  The depth is calculated by S2.  The java code adds a depth value, but it is not really calculated there, and is only a constant when a polygon is sent to the EE directly from Java.  The EE constructs the polygon value again using the …

Tighten an assertion.

---

src/frontend/org/voltdb/client/ProcedureInvocationType.java

Nothing Major... just found it when debugging wire protocol client

Fixed simple typo in RuntimeException message

---

build.py
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGeograpyPointValue.java

- Updated  GeographyPointValue test to take to precision of 12 decimal places when comparing two points.
- Minor changes to build script to ignore warnings for unused defines for gcc version 5. This started happening with version 5.2.1 abd results in build to fail due to unused defs flagged from s2-google apis.
Testing:
- Don't see asserts reported for points being different with changes locally that were on integration branch in memcheck environment.
- Jenkins run on the changes is under-way

Update geo-point test for decimal rounding

---

src/frontend/org/voltdb/ParameterConverter.java
src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/types/GeographyPointValue.java
src/frontend/org/voltdb/types/GeographyValue.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java
tests/frontend/org/voltdb/types/TestGeographyPointValue.java
tests/frontend/org/voltdb/types/TestGeographyValue.java

In the past we used GeographyValue.fromText and
GeographyPointValue.geographyPointValueFromText to construct geo objects
from text strings.  The text strings are always in Well Known Text
format (WKT).  This commit changes the name of both functions to fromWKT
for uniformity.
https://issues.voltdb.com/browse/ENG-9708

Use the name fromWKT to construct geo objects from text.

---

tests/test_apps/ycsb/src/com/procedures/Scan.java
tests/test_apps/ycsb/ycsb_ddl.sql

Changing keyspace to VARBINARY makes it compatible with the query inputs.
Converting Scan's rangeMin parameter to a java String makes it compatible but may hurt the benchmark numbers. If that's the case, we may want to define and use a UTF8INTERPRET sql function to do the UTF8 VARBINARY to VARCHAR "conversion" more efficiently in C++ where it is a trivial shallow copy into an NValue with a different type field setting.

Work around new runtime conversion restrictions

---

src/ee/common/NValue.cpp
src/ee/common/NValue.hpp
src/ee/expressions/geofunctions.cpp
src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/utils/VoltTableUtil.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/SaveRestoreBase.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyPointValue.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

With changes verified TestGeospatialFunction regression test passes and documentation are picked up in java docs ("ant -f mmt.xml dist.pro check"). There were no changes needed in geospatial demo apps. For sanity purpose verified, demo app runs fine with the changes.
To do: have to ping Andrew about the changes so that any documentation around it can be updated.

Update  geo function name to be consistent with geo type names

---

src/frontend/org/voltdb/VoltTableRow.java
tests/frontend/org/voltdb/TestVoltTable.java

Here's some unit tests for this class.  I found a couple of bugs: wasNull wasn't working right for polygons, and getRaw wasn't implemented for points.
I could have sworn that during a meeting we found a place where the geo types were missing from a `get` method.  I could not find it.  Maybe it was added sometime in the last few weeks?

Unit tests for geo types and VoltTable

---

tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

There was a typo for the test which caused it to always pass.  Then
error messages changed when we became more careful about ring
orientation.  We didn't see the error message changes because of the
typo.  I changed the definitions of the polygons in order to get the
error messages I want.
https://issues.voltdb.com/browse/ENG-9747

Fix the test for isInvalidReason.

---

src/ee/expressions/geofunctions.cpp
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java
third_party/cpp/google-s2-geometry/geometry/s2loop.cc

Some of the messages for isinvalidreason were not well stated.  Now each
message is a single line which does not end with a newline or a period.
https://issues.voltdb.com/browse/ENG-9748

Edit isinvalidreason messages.

---

src/ee/execution/VoltDBEngine.cpp

The Java side expects executeTask() to return something, so return 0 for
those tasks that don't have any return value to write. Otherwise, the
Java side will wait forever.

ENG-9770: Fix EE IPC interface error in exeucteTask().

---

src/ee/common/GeographyPointValue.hpp
src/ee/common/GeographyValue.hpp
tests/frontend/org/voltdb/regressionsuites/TestGeographyPointValue.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java

We previously fixed a similar problem with our Java GeographyPointValue class.  This is the corresponding change for when we do point comparison in the EE.
Also make polygon comparison use the point comparison method for vertices.  Previously we were using S2's point compare, which puts latitude first.  This resulted in having to change some unit tests.

In EE, fix point comparison at poles and antimeridian

---

src/ee/common/tabletuple.h
tests/ee/storage/DRBinaryLog_test.cpp

The optimized UPDATE/DELETE path only serializes the indexed
columns. The offset in the null array should use the relative position
of the column in the interesting column vector, not the actual table
column index.

ENG-9759: Fix serialization in optimized DR UPDATE/DELETE path.

---

tests/frontend/org/voltdb/regressionsuites/TestGeographyPointValue.java

With changes, test passes in valgrind environment on local machine. 
I have started "test-nextrelease-memcheck-pro" Jenkins job on the current branch to verify changes fixes the issue in Jenkins environment.

Minor fix to test for it's result set to be order deterministic

---

tests/frontend/org/voltdb/types/TestGeographyValue.java

In the wire protocol doc we have examples of serialized data structures.
For GeographyValue, since this is difficult to calculate, I added some
code to the TestGeographyValue test to print an HTML table of the
serialized result.  This code is disabled by default, so it does not
have any real testing performance impact.
https://issues.voltdb.com/browse/ENG-9211

Add some code to print serialized polygons for the wire protocol doc.

---

src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java

When replaySequencer receives sentinel and first fragment of MP txn,
it will remove the replay entry if there is no SP txn blocked by, and directly
sends following SP txn or remaining MP fragments to SP site's TransactionTaskQueue.
So the root cause is that during replay the sequence of txns arrive to SpScheduler are
not always same with the sequence in CL, we can't just get SpHandle from CL for
SP and advance the SpHandle for MP.
Change-Id: I6db1512ee966f22a155646dc5b76f7ffb4acaa43

ENG-9779, advance SpHandle for both SP and MP when replays CL.

---

src/ee/storage/DRTupleStream.cpp
tests/ee/storage/DRTupleStream_test.cpp

If a transaction does not fit in the current DR buffer, we create a new
one and move the whole transaction over to that buffer. If the
transaction is larger than the largest single buffer we can allocate, it
fails. At least, this is how it's supposed to work.
However, instead of looking at the space needed, it was looking at the
size of the current buffer to determine how big the next buffer should
be. If the current buffer is already a large buffer, it will refuse to
roll to a new buffer even though the currently open transaction can fit
the new buffer perfectly. This caused DR to fail prematurely.

ENG-9830: Fix DR buffer rolling.

---

build.xml
src/ee/common/tabletuple.h
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
tests/frontend/org/voltdb/planner/TestPlansJoin.java
tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexSuite.java

In HSQLDB there is some code to replace aliases in the order by list
with the expressions which the aliases name. This code had the same
diseases the regular column reference resolution code did, in that it
stopped when it found one definition. This means that ambiguous
definitions are not discovered.
This fix finds ambiguous column references in the order by list and
throws errors. Tests were added for group by, order by and having.
There were already several tests for where and joins.
There are still some problems with aliases in group by expressions.
These are to be addressed in ENG-9782.
https://issues.voltdb.com/browse/ENG-9828

Eng 9828 Make Ambiguous Column References in order by expressions be errors.

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/VoltTableRow.java

These methods are already available on the VoltTable that provides the VoltTableRow.
Making them public also on VoltTableRow makes it more convenient to define stored procedure and client helper functions that accept a VoltTableRow (but not also its VoltTable) as input.

ENG-9875 Make VoltTableRow column methods public.

---

src/ee/common/Topend.h
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/persistenttable.cpp
tests/ee/storage/DRBinaryLog_test.cpp

Move the DR stream append around in the INSERT/UPDATE/DELETE paths to
make sure it won't cause the operation half completed without proper
rollback. The INSERT/UPDATE/DELETE code paths assume that certain part
of the operation will always succeed. If it fails in the middle of those
critical sections, things won't rollback.
Change-Id: Idc28de35a73e08bf77b30f61dae63590886079e2

ENG-9830: Fix DR buffer limit error handling.

---

src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamException.h
src/ee/storage/persistenttable.cpp

Only catch constraint failure exception thrown by the index insert and
the exception thrown by tuple stream buffer overflow in
PersistentTable::insertTuple(). We can't catch all exceptions there
because the view update could also throw SQLException that doesn't
require target tuple deallocation.

ENG-9830: Fix PersistentTable::insertTuple() exception handling.

---

tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialIndexes.java

Adding test to regression suite to verify the Contains() operation on table which is indexed on geo columns produces correct answer by verify it against the result of contains on data-set using non-indexed table. 
In this review request create index on geo columns in commented out and can be enabled once the geo indexes are available.

Add regression-test to test end-to-end functionality for Contains() with geospatial index

---

src/ee/executors/abstractjoinexecutor.cpp
src/ee/executors/abstractjoinexecutor.h
src/ee/executors/aggregateexecutor.cpp
src/ee/executors/aggregateexecutor.h
src/ee/executors/executorfactory.cpp
src/ee/executors/executorfactory.h
src/ee/executors/executorutil.cpp
src/ee/executors/executorutil.h
src/ee/executors/indexscanexecutor.cpp
src/ee/executors/mergereceiveexecutor.cpp
src/ee/executors/mergereceiveexecutor.h
src/ee/executors/nestloopexecutor.cpp
src/ee/executors/nestloopindexexecutor.cpp
src/ee/executors/seqscanexecutor.cpp
src/ee/storage/tabletuplefilter.h
tests/frontend/org/voltdb/regressionsuites/TestOrderBySuite.java

Paul, 
I refactored the Aggregate and MergeReceive executors to use CountingPostfilter, plus couple of bug fixes for nestloopindex executor.
I think there was a bug in the AggregateExecutorBase::insertOutputTuple - the offset was evaluated only if limit is greater or equal to zero. If there were no limit set (-1), the offset was ignored. The new logic lives now inside the AggCountingPostfilter::eval and verifies the offset first prior to checking the limit (if tuple passes a predicate). I added a few test cases to verify the aggregated SQL with OFFSET only 
Mike

Eng 8932 full join

---

src/ee/common/types.h
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/BinaryLogSinkWrapper.cpp
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
tests/ee/storage/DRTupleStream_test.cpp

1. Changed BinaryLog producer to the new version in DRTupleStream
2. Changed BinaryLogSink and BinaryLogSinkWrapper to consume the new version
3. Changed getTestDRBuffer to produce DR BinaryLog for different scenarios (Txn Partition Key Hash)
4. Fixed the MAGIC size numbers in DRTupleStream_test for the new version

ENG-9949 DR BinaryLog Format v4

---

src/ee/storage/TableCatalogDelegate.cpp
src/frontend/org/voltdb/utils/CatalogSizing.java

Also set "countable" attribute correctly.
For stored procedure `@Statistics`, both INDEX and MEMORY make use of existing TableIndex methods getEstimatedMemory and getSize, so this was already working right.
We were setting the "countable" attribute incorrectly in the EE for hash and geospatial indexes, so I made the one-line change to fix this.  As far as I can tell, this really has no effect on behavior, since the "countable" attribute is being set correctly in the planner.
I didn't find a lot of unit tests for this stuff (maybe there are GEB tests for the sizing worksheet?).

Update catalog sizing for geo indexes

---

src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h

1. Adjusted the getTestDRBuffer() for single hash case to generate txns with different hashes so that splitter can be tested
2. Addressed remaining review comments from last pull request.

ENG-9949: DRBufferSplitter for strict SP case

---

.gitignore
tests/frontend/org/voltdb/GenerateCPPTestFiles.java
tests/scripts/generate_cpp_test_data/README
tests/scripts/generate_cpp_test_data/deployment.xml
tests/scripts/generate_cpp_test_data/generate.sql
tests/scripts/generate_cpp_test_data/run.sh

The C++ client needs some messages in binary files. This commit adds the
Java file which generates these messages to the VoltDB test source tree.
It also adds a small application in tests/scripts/generate_cpp_test_data
which allows generation of the test data through a single test script.
Typically this data goes into $CPP_CLIENT_SRC/test_src/test_data, where
$CPP_CLIENT_SRC is the path to the C++ client source folder.
This file and the tests in the C++ client source folder test_src should
be synchronized. If either changes the other should change in tandem.

Add test file generation for the C++ client.

---

bin/voltenv
examples/contentionmark/run.sh
examples/geospatial/run.sh
examples/json-sessions/deployment.xml
examples/json-sessions/run.sh
examples/voltkv/run.sh
examples/voter/run.sh
examples/windowing-with-ddl/run.sh
examples/windowing/run.sh

Add "voltenv" script to hide boilerplate for examples.
Unify run.sh across examples.
Other small cleanup.
I know many people don't care for run.sh. I don't really either? I've tried some alternatives personally, and haven't found something I like better. I encourage others with less tarnished minds to try as well.

Make run.sh more consistent, cleaner and slightly shorter across examples

---

lib/python/voltcli/checkconfig.py

9730 is closed, but this isn't merged.  Why?

ENG-9730 Update checks to 6.0 O/S and Python requirements

---

tests/geb/vmc/src/resources/sqlQueries.txt

'1970-01-01 00:00:00.000000'), now that VMC-267 bug is fixed.

sqlQueries.txt: fixed test to expect a correct NULL timestamp value (not

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java

A Geospatial Index cannot have a complex expression.  The only
expression allowed is a column reference, and only a single column
reference is allowed at that.
https://issues.voltdb.com/browse/ENG-9695

Geospatial Indexes cannot have complex expressions.

---

src/ee/common/GeographyPointValue.hpp
tests/frontend/org/voltdb/regressionsuites/TestGeographyPointValue.java
tests/frontend/org/voltdb/types/TestGeographyPointValue.java

Fix edge case in canonicalize/normalize logic to not evaluate/update point for antimeridian condition when the point is at pole.

Fix for edge case for point at poles

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/utils/SQLCommand.java
src/frontend/org/voltdb/utils/SQLCommandOutputFormatterDefault.java
tests/frontend/org/voltdb/TestVoltTable.java

Fixed issue for sqlcmd's fixed format output, to honor skip metadata flagso that column names and the  extract line break if skip meta-data flag was set. Skip meta-data flag works as expected for tabulated and csv ouput format, so no changes needed in there.

Don't include column names when skip meta data is set

---

src/frontend/org/voltdb/utils/SQLCommand.java

Additional update to avoid printing sql and extra line break in non-interactive mode if skip metadata flag is set. Tested manually the results are as expected (for interactive mode there junit tests and sqlcmd tests; for non-interactive mode have to created ticket so that we can test functionality in sql command test or similar) 
Manual test output:
- With skip metadata flag set and non-interactive mode: 
```
echo "select * from T" | sqlcmd --output-skip-metadata --output-format=tab
2
1
3
6
8
9
```
```
sqlcmd --output-skip-metadata --output-format=csv --query="select * from T;" 
"9"
"8"
"3"
"8"
"4"
```
- With show meta-data flag set:
```
sqlcmd --output-format=csv --query="select * from T;" 
select * from T;
"ID"
"9"
"8"
"3"
"8"
"4"
(Returned 5 rows in 0.00s)
```

Additional update for skip meta-data and non-interactive mode

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/ExtensibleSnapshotDigestData.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_RO_SP.java
tests/frontend/org/voltdb/TestDRConsumerDrIdTracker.java

- Use Guava RangeSet instead of implementing from scratch.
- Allow overlaps when merging two trackers.
- Move JSON serialization/deserialization to the tracker class.
- Fix some logic around last ack point and the calculation of the safe
point to use for acking. The last ack point could be way before the
start of the first entry. It's incorrect to use the end of the first
entry to ack. The range between the last ack point and the first entry
should be counted as a gap. The last ack point should not be tracked
separately. It acts the same way as a range in the range set. I added
it to the first entry of the range set, which makes tracking a lot
easier.

ENG-9547: DR consumer tracker fix.

---

src/ee/storage/DRTupleStream.cpp
src/frontend/org/voltdb/DRConsumerDrIdTracker.java
tests/frontend/org/voltdb/TestDRConsumerDrIdTracker.java

1. Handle remote promotion, local promotion WIP
2. Use DRConsumerDrIdTracker instead of DRLogSegmentId in IdempotencyFilter and BufferSplitter
3. Update the unit tests for the BufferSplitter

ENG-9547: Part 1

---

src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/executors/updateexecutor.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/temptable.cpp
src/ee/storage/temptable.h
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/ee/indexes/CoveringCellIndexTest.cpp
tests/ee/storage/persistenttable_test.cpp
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpsertSuite.java

Fixed three problems: 
The reported problem was that UPSERT statements that did not provide values for some columns were resetting the missing columns back to their default values for the UPDATE case rather than leaving them alone.
Added testing showed two other problems:
1. The planner was forcing UPSERTs (just like INSERTs) to mention all NOT NULL columns that had NO/NULL default values. For UPSERTs, this needs to be let through and conditionally caught in a runtime check.
It is a completely irrelevant condition for UPSERT's UPDATE subcase as hinted by the first fix described above. For UPSERT's INSERT subcase, we will throw a null constraint violation from the EE. That is, we won't bother to distinguish this edge case of defaulting the NOT NULL column to null from the case of …

Eng 10072 upsert with defaults

---

tests/sqlcmd/baselines/ddl/load_remove_classes.outbaseline
tests/sqlcmd/scripts/ddl/load_remove_classes.in

InsertEmployee            	varchar, varchar, varchar
since ENG-8532 has been fixed, this stored procedure is no longer listed
by SHOW PROCEDURES, *after* it has been dropped (though it is still
listed earlier); and added additional lines to match the ones added to
load_remove_classes.in.
load_remove_classes.in: added some additional:
drop table FOO if exists;
statements (where FOO is t2, addable, dropable, prefixes, or raw); now
that ENG-8532 is fixed, such lines could actually help this test past,
by removing extraneous procedures from the ones listed by SHOW
PROCEDURES (whereas before, they had no real effect).

load_remove_classes.outbaseline: removed the (last) line that reads:

---

src/frontend/org/voltdb/PostgreSQLBackend.java
tests/scripts/examples/sql_coverage/StandardNormalizer.py
tests/scripts/sql_coverage_test.py

PostgreSQL's BYTEA type, which seems to be the closest analogue (was BIN
VARYING); and added a transformation for binary constants, e.g. x'12AF'
gets transformed to E'\\x12AF', which is in PostgreSQL's preferred
format for BYTEA data.
sql_coverage_test.py: removed the kludge that ignored the known failures
(up to 1520 of them) in the index-varbinary test suite, when running
against PostgreSQL.
StandardNormalizer.py: changed the output format of VARBINARY column
data, to roughly match the same format that is used upon input (in an
INSERT statement), rather than Python's crazy default format for binary
data.

PostgreSQLBackend.java: VARBINARY column types are now transformed to

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/common/UniqueId.hpp
src/ee/common/executorcontext.hpp
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleBinaryLogSink.cpp
tests/ee/storage/DRBinaryLog_test.cpp

When a timestamp mismatch conflict occurs, the resolver receives
incorrect timestamps for comparison. The timestamp for the remote
operation is Volt-epoch-based, but the local existing tuple's timestamp
is Unix-epoch-based. This resulted in always rejecting remote changes.
Now all timestamps passed to the resolver are Unix-epoch-based.

ENG-10135: Fix XDCR timestmap mismatch conflict handling.

---

src/catgen/in/javasrc/DRCatalogDiffEngine.java
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleBinaryLogSink.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
tests/ee/storage/DRBinaryLog_test.cpp
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

- Ignore table row limit when applying DR data.
- Allow different table row limits/delete policies on master and replica clusters.

ENG-9985: Ignore table row limit when applying DR data.

---

src/ee/indexes/IndexStats.cpp
src/ee/storage/TableStats.cpp
src/frontend/org/voltdb/IndexStats.java
src/frontend/org/voltdb/MemoryStats.java
src/frontend/org/voltdb/TableStats.java
src/frontend/org/voltdb/iv2/Site.java
tests/frontend/org/voltdb/regressionsuites/TestEmptySchema.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDatabaseElementStats.java

Update column type's for table and memory components of statistics system procedure to BigInt instead of Integer so that the reported memory storage size for does not get reported in negative for values > ~2TB. The updated columns are for reporting non-inlined memory, total block storage for the table (used + free) and storage used by total tuples.

Update statistic table/tuple column's for memory size to bigint instead of integer

---

src/ee/expressions/datefunctions.h
src/ee/expressions/logicfunctions.h
src/ee/expressions/stringfunctions.h
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/failureprocs/BadParamTypesForTimestamp.java

Updated logic to generate exception if the caller supplies value of different type for timestamp function where timestamp value is expected and if conversion of value of given type to timestamp is not applied.

Handle incompatible param types to timestamp sql functions in EE

---

src/frontend/org/voltdb/expressions/TupleValueExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/plannodes/AbstractJoinPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
src/frontend/org/voltdb/plannodes/NestLoopIndexPlanNode.java
src/frontend/org/voltdb/plannodes/NodeSchema.java
src/frontend/org/voltdb/plannodes/SchemaColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java
tests/frontend/org/voltdb/planner/TestDeterminism.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java
tests/frontend/org/voltdb/plannodes/TestScanPlanNode.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java

This change set addresses incorrect behavior that can occur when doing a "select *" from a subquery that contains multiple columns with the same name.  This can happen in a couple of ways:
```SQL
SELECT * FROM (SELECT * FROM T, T) AS subq;
```
Where if persistent table T has columns (A, B) the output of the suquery wll be (subq.A, subq.B, subq.A, subq.B).  This can also happen for this case:
```SQL
SELECT * FROM (SELECT t1.a AS z, t2.a AS z FROM T AS t1, T AS t2) AS subq;
```
VoltDB's name-based column resolution pass does not deal well with these queries and was resulting in undefined behavior.
This change set only detects queries that would have caused incorrect behavior and throws an exception.  A more thorough solution should be implemented soon to make these queries execute in …

Throw an exception for internal tables with duplicate column names

---

src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
tests/frontend/org/voltdb/iv2/TestMpTransactionState.java

It is possible to receive stale fragment responses on the MPI when an MP
txn is restarted. The normal fragment path handles this by checking the
received responses with the expected dependency IDs. Stale responses
will be ignored if they don't match the expected dependency.
However, the borrow fragment path does not take this into account when
receiving response. If a stale response from a remote site comes back
when the MP is expecting the borrow fragment response, it will mistake
it as the borrow response and return it to the procedure, which resulted
in dropping the real borrow response that comes later.
Imagine the following scenario for a sysproc:
* Sends out fragments (call them batch A)
* MP is restarted
* Sends out fragments again (batch A')
* Receives stale responses for batch A …

ENG-10189: Fix MP restart stale response handling.

---

src/frontend/org/voltdb/compiler/VoltCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Partitioning of table on varbinary type is permitted though the guard message does not indicate it (verfied murmur hash in EE on varbinary type is supported). A minor change updating partition-by guard message.
.................................
5> create table t (digest varbinary(128) NOT Null, pt geography_point NOT Null);
Command succeeded.
6> partition table T on column pt;
[null]: In database, Partition column 'T.pt' is not a valid type. Partition columns must be an integer, varchar or varbinary type.
7> partition table T on column digest;
Command succeeded.
.............................

update partition guard message

---

.gitignore
src/frontend/org/voltdb/planner/SelectSubPlanAssembler.java
src/frontend/org/voltdb/planner/StatementPartitioning.java
tests/frontend/org/voltdb/AdHocQueryTester.java
tests/frontend/org/voltdb/planner/TestPlansJoin.java
tests/frontend/org/voltdb/planner/TestPlansOrderBy.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java
tests/frontend/org/voltdb/planner/TestSelfJoins.java
tests/frontend/org/voltdb/regressionsuites/TestInsertIntoSelectSuite.java

Some queries are not plannable because their joins cannot be computed
with our two fragment query model.  The error message for one such query
was misleading.  This commit fixes this.
Jira: ENG-10097.

Fix an error message for unplannable queries.

---

tests/frontend/org/voltdb/TestAdHocQueries.java

ENG-10289: temporarily disable testAdHocLengthLimit in valgrind

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/SubPlanAssembler.java
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
tests/frontend/org/voltdb/compiler/TestProcCompiler.java
tests/frontend/org/voltdb/planner/PlannerTestAideDeCamp.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java
tests/frontend/org/voltdb/planner/TestDeterminism.java
tests/frontend/org/voltdb/planner/testplans-determinism-ddl.sql
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java

Logic updates to evaluate the SQL statement determinism based on value equivalence filters in the statement and unique indexes defined on the table. If the statement has parameterized/constant equivalence filters and the equivalence filter covers the unique indexes defined on the table such that it results in at most one output row, the query result is order deterministic irrespective if it result in single or two fragment plan. 
For eg "Select * from T where a = ?;" 
where a is unique constrained defined on the table T will result in atmost one output row. 
Today though similar statement gets flagged as non-deterministic for two fragment plan. Logic updates with this pull request addresses this issue by extending determinism logic in abstract parsed statement to also check if the …

Eng 10073 - determinism updates for PK equivalence

---

tests/geb/vmc/src/resources/expectedUserStoredProcs.txt
tests/geb/vmc/src/resources/sqlQueries.txt
tests/geb/vmc/src/tests/FullDdlSqlTest.groovy

Fixed the UPSERT test in sqlQueries.txt that has been failing since ENG-10073 was fixed; and added a few similar tests to confirm which cases do and still do not work (and should not). Also fixed unrelated problems with the SqlQueriesTest.checkUserStoredProcs test failing, due to new stored procedures showing up in the list (which I've now added, see ENG-10137), and due to new stream T25N (I fixed FullDdlSqlTest.groovy to now drop any streams that are added via a CREATE STREAM statement).

Eng 10073 vmc upsert test

---

src/frontend/org/voltdb/ElasticHashinator.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LegacyHashinator.java
src/frontend/org/voltdb/NonVoltDBBackend.java
src/frontend/org/voltdb/ParameterConverter.java
src/frontend/org/voltdb/TheHashinator.java
src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/VoltType.java
src/frontend/org/voltdb/client/HashinatorLite.java
src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/expressions/FunctionExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/CorePlan.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/plannodes/IndexCountPlanNode.java
src/frontend/org/voltdb/types/GeographyValue.java
src/frontend/org/voltdb/utils/VoltTypeUtil.java
tests/frontend/org/voltdb/TestClientInterface.java
tests/frontend/org/voltdb/TestParameterSet.java
tests/frontend/org/voltdb/TestVoltTable.java
tests/frontend/org/voltdb/client/TestHashinatorLite.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestComparisonOperatorsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/regressionsuites/TestLoadingSuite.java

VoltType-related refactoring to:
migrate some static methods to more relevant classes.
use the "smart enum" feature of java 7 to special-case behavior of specific VoltTypes and reduce reliance on switch statements (should make adding new types easier) -- the new model follows a kind of 80/20 rule -- VoltType provides a simple "usual" implementation of each function which only a FEW specific VoltTypes will need to override to implement special case behavior. This is more efficient and maintainable than lots of switch statements.
better distinguish fixed and variable length types
avoid boilerplate especially in initialization
improve javadoc coverage

Refactor VoltType in advance of ENG-9873 type checking improvements.

---

src/frontend/org/voltdb/InternalConnectionHandler.java
src/frontend/org/voltdb/importclient/kafka/KafkaTopicPartitionImporter.java
tests/test_apps/kafkaimporter/client/kafkaimporter/MatchChecks.java

1. tweak to backpressure In InternalConnectionHandler to be less aggressive;
2. In kafka Importer,  wait for voltdb if observe large gap;
3. refine the KafkaImportBenchmark

ENG-10064: Kafka importer UAC system test scenario fails with short row count

---

src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/TableCatalogDelegate.hpp

This was a bug in which we saw assertion failures when instantiating an index scan executor in the EE, because the required index seemed to be missing.
This issue happened because a materialized view had a "fallback executor vector" which was being instantiated from the catalog JSON while a schema change was in progress (add or drop column).  At this time, the TableCatalogDelegate pointed to the stale, existing table which had already had its indexes removed (and recreated on the new table).
The fix was to set the table referred to by the TableCatalogDelegate to the new table before migrating the views.
The first commit has the actual behavior-changing modifications that I made, and in the second commit I just moved some methods around for the sake of consistency with other functions in …

Fix issue with materialized views and alter table

---

src/ee/common/StreamBlock.h
src/ee/common/types.h
src/ee/execution/JNITopend.cpp
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/CompatibleDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/storage/ExportTupleStream.cpp
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h
src/ee/storage/persistenttable.cpp
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/DRConsumerStatsBase.java
src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
tests/ee/storage/DRTupleStream_test.cpp

The best order to review those changes is
Producer Side:
Site.java::updateCatalog() -> generatedDRCatalogChangeEvent() -> VoltDBEngine.cpp::VoltDBEngine::executeTask()->DRTupleStream.cpp::generateDRCatalogChangeEvent()->PartitionDRGatewayImpl.java:: onBinaryDR()->DRProducerConnectionInterface.java::prepareForDispatch()
Consumer Side:
AbstractDRPartitionReceiver.java::processBuffer()->preprocessBuffer() in both syncSnapshot and normal buffer receiver -> handleInbandDREvent()
Also, this patch includes removal of an unused parameter in generate DR log path, removal the old out-of-band CATALOG_UPDATE event.

Eng 10148 pause incompatible dr stream

---

src/ee/stats/StatsAgent.cpp
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleBinaryLogSink.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStreamUndoAction.h
src/ee/storage/PersistentTableUndoDeleteAction.h
src/ee/storage/PersistentTableUndoInsertAction.h
src/ee/storage/PersistentTableUndoTruncateTableAction.h
src/ee/storage/PersistentTableUndoUpdateAction.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/table.h
src/ee/storage/temptable.cpp
src/ee/storage/temptable.h
tests/ee/storage/DRBinaryLog_test.cpp

* An optimization that uses tuple-by-tuple deletion on tables with low number of rows instead table swapping for truncation caused DR to generate a large binary log, sometimes over the 45MB limit. I'm putting a guard around that to prevent it from generating DR delete records in the binary log when it should actually be a truncation record. Regardless of the optimization, it will always generate a single truncation record in the binary log.
* Provide some context when the DR buffer size limit is reached.

ENG-10135: DR small table truncation

---

tests/ee/storage/DRBinaryLog_test.cpp

Disable the DR binary log truncate table test because it will not
trigger the interesting optimized truncation path in memcheck build. The
tuple block can only hold one tuple at a time in the memcheck build.

ENG-10315: Fix EE test in memcheck build.

---

src/frontend/org/voltdb/ParameterConverter.java
src/frontend/org/voltdb/parser/SQLParser.java
tests/frontend/org/voltdb/types/TestDateParsing.java
tests/sqlcmd/baselines/simple/parsedates.errbaseline
tests/sqlcmd/baselines/simple/parsedates.outbaseline
tests/sqlcmd/scripts/simple/parsedates.config
tests/sqlcmd/scripts/simple/parsedates.in
tests/sqlcmd/sqlcmdtest.py

The documented forms for VoltDB dates are 'yyyy-mm-dd HH:MM.sss',
'yyyy-MM-dd HH:MM' and 'yyyy-MM-dd'. The previous pattern did not
work for the latter two. This commit fixes this by trying all three
patterns. There seems to be no way to specify that a part of the
pattern is optional.
I changed the parsing strategy, and just use the one for TimestampType.
This
gives us microsecond granularity, which is what we seem to be
advertising,
and it parses all the formats we advertise.
In this commit I also added a fix to ENG-10369. It was really obvious,
and easier to fix it than to describe how to fix it in the ticket.
https://issues.voltdb.com/browse/ENG-10031

Parse dates better in sqlcmd.

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/planner/TestPlansInExistsSubQueries.java

VoltDB does not support WHERE clauses containing only constants
=====>
VoltDB does not support constant boolean values

Change the misleading error message.

---

third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/mathlimits.h
third_party/cpp/google-s2-geometry/geometry/util/math/exactfloat/exactfloat.cc

Seems like on newer platforms isinf and isnan have moved to
namespace std.

Fix build error on Ubuntu 16.04

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltcore/agreement/MeshArbiter.java
src/frontend/org/voltcore/messaging/ForeignHost.java
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java
src/frontend/org/voltdb/iv2/LeaderCache.java
tests/frontend/org/voltcore/messaging/TestHostMessenger.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java
tests/frontend/org/voltdb/regressionsuites/TestStopNode2NK1PartitionDetectionOn.java

1) Move partition detection into HostMessenger so it happens sooner.
2) Have CrashGlobal/LocalVoltDB kill the client connection ASAP.
3) Remove the partition snapshot feature.
4) Hopefully improve error messaging
I still need to add an error message if you start with partition snapshot settings set.

ENG-10453: Don't let work happen before partition detection kills nodes.

---

src/ee/storage/BinaryLogSink.cpp

Report local cluster partition id to conflict resolver, not remote cluster partition id.

ENG-10479, fix NPE when XDCR conflict occurs in mixed size cluster.

---

src/ee/storage/CopyOnWriteIterator.cpp
src/ee/storage/CopyOnWriteIterator.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/CopyOnWriteTest.cpp
tests/ee/storage/persistenttable_test.cpp
tests/frontend/org/voltdb/regressionsuites/TestJoinsSuite.java

- Updated persistent table logic to allocate tuple storage block to table on table creation. Don't release the only remaining tuple storage block back to system during truncate or delete operation. This will prevent persistent table to request fresh tuple storage block on next row insertion into empty table.
- Updated snapshot save logic so that when system is performing snapshot save, it takes into account the persistent table can contain empty tuple storage

Tuple block changes for empty persistent table

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedColInfo.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
src/frontend/org/voltdb/planner/parseinfo/StmtTableScan.java
src/frontend/org/voltdb/plannodes/AbstractJoinPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
src/frontend/org/voltdb/plannodes/NodeSchema.java
src/frontend/org/voltdb/plannodes/ProjectionPlanNode.java
src/frontend/org/voltdb/plannodes/SchemaColumn.java
src/frontend/org/voltdb/plannodes/SendPlanNode.java
tests/frontend/org/voltdb/planner/TestUnion.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java

This set of changes follows through on implementing a "differentiator" field for various data structures in the planner that represent table columns.  They're really only used as a "tie breaker" for the case when there is a `SELECT *`, and the thing we're selecting from is a subquery.  (Note that HSQL treats parenthesized joins in the FROM clause as if they were subqueries.)

ENG-10164: duplicate column bug

---

src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/ParsedUnionStmt.java
src/frontend/org/voltdb/planner/SubPlanAssembler.java

Eliminate code by standardizing on one way to search for subexpressions -- by java class rather than by ExpressionType tag.
These two search algorithms are theoretically not exactly equivalent in all cases, but they ARE equivalent in the ONE and ONLY oddball case we were using ExpressionType, namely for ExpressionType.VALUE_TUPLE. 
(this instanceof TupleValueExpression) === (m_expressionType == ExpressionType.VALUE_TUPLE)

Remove underused expression tree search code.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/SocketJoiner.java
src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltcore/messaging/TestHostMessenger.java
tests/frontend/org/voltcore/messaging/TestMessaging.java
tests/frontend/org/voltcore/zk/TestStateMachine.java
tests/frontend/org/voltcore/zk/TestZK.java
tests/frontend/org/voltcore/zk/ZKTestBase.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/TestVoltZK.java

On startup, each node sends a request to rejoin the mesh to the live node. The live node will check if the request can be accepted at the moment. For example, we only allow one node to rejoin at a time. If more than one node tries to rejoin, the first rejoning node will atomically check and set the ZK blocker. Subsequent node will fail to do so and be rejected to join the mesh. They will retry after a while until they can succeed.

ENG-10421: allow multiple hosts trying to rejoin at the same time

---

src/frontend/org/voltdb/NonVoltDBBackend.java

lastGroup variable that is never null, as opposed to the 'group' variable which sometimes is - thus avoiding the NPE we were seeing in certain cases.

NonVoltDBBackend.java: tweaked NonVoltDBBackend.transformQuery, adding a

---

src/ee/common/NValue.cpp
src/ee/expressions/datefunctions.h
tests/ee/expressions/function_test.cpp

Add EE unit tests for timestamp functions.
The functional changes here are just to avoid the boost exception produced with using the boost functions with years greater than 9999, and to avoid overflow of the int64_t storage for timestamps in the TO_TIMESTAMP method.
In particular, I didn't add code that would throw exceptions if out-of-range timestamps would be produced as output.  I wanted to avoid breaking existing apps as much as possible.  This issue can be addressed in the future ticket that will more properly guard against out-of-range timestamps.

ENG-10422 Add range checks to TRUNCATE to avoid boost exceptions

---

src/ee/storage/table.h
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
tests/frontend/org/voltdb/regressionsuites/TestIndexesSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/indexes/indexes-ddl.sql

In ENG-10478 we discovered that we sometimes could forget conjuncts in
where clauses. For example, in the select statement:
select * from SOMEVIEW where THERENT < 42 AND THERENT < 26000;
where SOMEVIEW is a view, we create an index on the view and use that to
help us evaluate the where expression. Since both conjuncts are tests
on the same column of SOMEVIEW, we can use one index to answer both
predicates. But unfortunately we lost the left hand conjunct, and only
used the right hand one.
Plus some other refactoring, spelling corrections and unit test
creation.
https://issues.voltdb.com/browse/ENG-10478

Don't forget the conjuncts.

---

src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/expressions/ExpressionUtil.java
src/frontend/org/voltdb/expressions/ScalarValueExpression.java
src/frontend/org/voltdb/expressions/SelectSubqueryExpression.java
src/frontend/org/voltdb/expressions/TupleValueExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/MaterializedViewFixInfo.java
src/frontend/org/voltdb/planner/ParsedInsertStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/SelectSubPlanAssembler.java
src/frontend/org/voltdb/planner/SubPlanAssembler.java
src/frontend/org/voltdb/planner/microoptimizations/ReplaceWithIndexCounter.java
src/frontend/org/voltdb/plannodes/AbstractJoinPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
src/frontend/org/voltdb/plannodes/AggregatePlanNode.java
src/frontend/org/voltdb/plannodes/IndexCountPlanNode.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
src/frontend/org/voltdb/plannodes/MaterializedScanPlanNode.java
src/frontend/org/voltdb/plannodes/NestLoopIndexPlanNode.java
src/frontend/org/voltdb/plannodes/NodeSchema.java
src/frontend/org/voltdb/plannodes/OrderByPlanNode.java
src/frontend/org/voltdb/plannodes/PlanNodeTree.java
src/frontend/org/voltdb/plannodes/ProjectionPlanNode.java
tests/frontend/org/voltdb/planner/TestPlansGroupBy.java
tests/frontend/org/voltdb/planner/TestPlansOrderBy.java

Mostly invisible changes for correctness and performance -- sometimes having an actual detectable behavior effect only later when partitioned table queries have replicated table subqueries:
Apply recursive expression searches more consistently and simplify their use and implementation
-- critical to later enabling edge cases of replicated table subqueries with partitioned tables in the parent query. This was especially true when it came to applying algorithms consistently between the structures representing a "normal case" parsed select stmt and the "avg push down special cases".
This should have been done from the start.
Integrate the new differentiator as a first class member of TVE rather than an apparent afterthought.
Normalize use of whitespace and braces.
Unrelated bugs found and …

ENG-8154 precursor work to enabling all subqueries on replicated tables

---

tests/scripts/sql_coverage_test.py

failures in the numeric-decimals and numeric-ints test suites, when running the "extended" SQLCoverage tests against PostgreSQL - which will be fixed later, as ENG-10546.

sql_coverage_test.py: added a temporary kludge to ignore the known

---

src/frontend/org/voltdb/ElasticHashinator.java
src/frontend/org/voltdb/LegacyHashinator.java
src/frontend/org/voltdb/OpsAgent.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/TheHashinator.java
tests/frontend/org/voltdb/TestTheHashinator.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java

JSON Format for the hashinator config
{"count": 16384,
"map": {"token1": partID1,
"token2": partID2,
...}
}
Compressing using GZIP
use "@Statsistics TOPO 1" for retrieving new format
checkForTopologyChanges in ClientIntface still using old binary format

ENG-10383: Support JSON Hashinator config

---

src/frontend/org/voltdb/RealVoltDB.java

If a node fails when another node is still initializing, it may trigger an NPE in the callback on the initializing node because the executor services are not set up yet. Check for this case and avoid submitting any work on the initializing node in that case.

ENG-10584: Fix NPE on node failure during initialization.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java

When a cluster is partitioned due to network failure, we would like to detect that the cluster is not KSafe (all partitions are present) before performing any partition repair process. This patch addresses this issue.

ENG-10486:

---

tests/geb/vmc/server/run_voltdb_server.sh

VoltDB cluster" message (rather than the old "Connection refused"); and
cleaned up to give better feedback, the next time there is a similar
problem, with waiting for the VoltDB server to complete initialization -
e.g., an unrecognized message is assumed to be a problem, not assumed to
be a successful run of ddl.sql in sqlcmd.

run_voltdb_server.sh: fixed to expect the new "Unable to connect to

---

src/ee/structures/CompactingHashTable.h
src/ee/structures/CompactingMap.h
src/ee/structures/ContiguousAllocator.cpp
src/ee/structures/ContiguousAllocator.h
src/frontend/org/voltdb/compiler/PlannerTool.java
tests/ee/structures/CompactingHashTest.cpp
tests/ee/structures/CompactingMapTest.cpp
tests/test_apps/insertdelete/README.md
tests/test_apps/insertdelete/client/benchmark/Benchmark.java
tests/test_apps/insertdelete/client/benchmark/BenchmarkCallback.java
tests/test_apps/insertdelete/client/benchmark/BenchmarkStats.java
tests/test_apps/insertdelete/client/benchmark/SeedTables.java
tests/test_apps/insertdelete/ddl.sql
tests/test_apps/insertdelete/ddl_noindices.sql
tests/test_apps/insertdelete/procedures/InsertDelete.java
tests/test_apps/insertdelete/procedures/InsertDeleteWithString.java
tests/test_apps/insertdelete/run.sh

Some rows add nodes to indices on the table of the row. When the last
row of a table is deleted, the nodes for that row are deleted. If we
delete a row and then add a row repeatedly we will thrash the allocator,
which is expensive.
This commit caches the last allocated block of nodes in the index'
allocator, and reuses it when another node is added to the index. This
costs some memory for empty tables, but is much faster.
https://issues.voltdb.com/browse/ENG-8872

Cache an empty block in indices.

---

src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/planner/TestWindowedFunctions.java

We have added initial support for windowed aggregate functions.  The
planner can plan for them, but the EE cannot execute the resulting
plans.  This commit adds guards in the planner to keep these plans from
being generated.  It's possible to disable the guards in the server by
setting the system property org.voltdb.handlewindowedfunctions to true.
https://issues.voltdb.com/browse/ENG-10602

Add guards for windowed functions.

---

src/ee/common/StreamBlock.h
src/ee/storage/AbstractDRTupleStream.cpp
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/CompatibleDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h

**Problem:**
1. Previously, DR sequence number is only generated for DR table changes when "listen" is set to true in the deployment file. This causes problem in recovery if the command log records corresponding to these unnumbered write transactions are not truncated before the cluster goes down. In this case, they will be newly numbered with the same DR sequence number as transactions after them, which may have already been received and recorded in the IdempotencyFilter in consumer cluster. Thus, when the command log replayed transactions hit the consumer cluster, the cluster will find two inconsistent transactions with the same DR sequence number and throw DR exception.
2. Because of the change, we cannot skip a write transaction immediately if "listen" is set to false since we need to …

ENG-10198: Generate DR sequence number for DR table changes and DR events all the time

---

build.py
src/ee/common/UniqueId.hpp
src/ee/common/executorcontext.cpp
src/ee/common/executorcontext.hpp
tests/ee/common/uniqueid_test.cpp

1. Add a constant VOLT_EPOCH_IN_MILLIS to denote volt epoch in unit of millisecond.
2. Fix the old VOLT_EPOCH constant in UniqueId.cpp to have the correct microsecond-unit volt epoch value.
3. Add a unit test to make sure microsecond-unit timestamp can be extracted from uniqueId correctly.

ENG-10373: Fix XDCR conflict log timestamps to be based on unix epoch

---

src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/utils/CatalogUtil.java

When command logging is turned on, read-write transactions are passed to
the command logging thread. If read-only transactions are not done the
same way, they may be sequenced differently on different replicas,
resulting in hash mismatches. This only affects SAFE consistency level
because reads are sent to all replicas.
Also advance the last spHandle in the TransactionTaskQueue regardless of
the type of transaction. Reads can advance the spHandle in SAFE
consistency level.

ENG-10612: Fix ordering of read-only procedure when CL is on.

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
tests/frontend/org/voltcore/zk/StateMachineSnipits.java
tests/frontend/org/voltcore/zk/TestStateMachine.java

- Upon unexpected exceptions from the StateMachineInstance derived classes' callbacks, remove current instance from the community, initialize the instance with a different member id and triggers predefined reset actions to be executed.
- For DR Producer state machine, the reset action is to break replication so that the conversation on the victim producer node will be reset.
- If the replication mode is active-passive and sync snapshot provided by the victim producer node is still in progress, consumer cluster nodes will go down. In other cases, consumer cluster nodes will remain in RECEIVE state while keep failing to subscribe to the victim producer node because of conversation mismatch.
- In either case, subsystems other than DR in the producer cluster will remain functional.
Tests:
- …

ENG-10229: Break replication instead of crash on unexpected exceptions from the callbacks

---

src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/SpScheduler.java

The initiate response message was still looking for a duplicate counter, even if it was supposed to be a "fast" response. This was dumb oversight.
Also fix typo.
[http://ci/view/Branch-jobs/view/branch-ENG-10634-fastread-mismatch](http://ci/view/Branch-jobs/view/branch-ENG-10634-fastread-mismatch)

ENG-10634: Fix handling of fast read invocation response.

---

src/frontend/org/voltdb/ClientInterface.java

NPE is caused by using default CRUD procedure while elastic joining, CI fails to
lookup default procedure before it thinks this is a sysproc.
Change-Id: Ib82af94954cc63a4d5f6f53b805096ae6bbc18ac

ENG-10354, fix NPE during elastic join.

---

src/frontend/org/voltdb/ClientInterface.java

NPE is caused by using default CRUD procedure while elastic joining, CI fails to
lookup default procedure before it thinks this is a sysproc.

ENG-10354, fix NPE during elastic join. (#3702)

---

src/ee/executors/orderbyexecutor.cpp
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
tests/frontend/org/voltdb/regressionsuites/TestLimitOffsetSuite.java
tests/frontend/org/voltdb/regressionsuites/testlimitoffset-ddl.sql

The algorithm in the order by executor for limit nodes was incorrect.
This commit makes limit 0 do almost no work. It was reading the input
table and sorting it. The sort was a special case which only does a
partial sort, but copying the input table into a std::vector is
unnecessary and can't be zero cost.
https://issues.voltdb.com/browse/ENG-10559

Limit 0 should really return 0 rows.

---

src/frontend/org/voltcore/agreement/MeshArbiter.java
src/frontend/org/voltcore/messaging/HostMessenger.java

On single link failures, a host A may claim another host B is down
because host C witnessed the link failure between B and C. Same goes for
C. In this case, A has the freedom to go with either B or C. Both B and
C should wait until A makes the decision before they continue to make
theirs. Otherwise B and C may both think they still have A in their
subclusters and continue on because they are the majority.
Now it makes local decision, broadcast it and wait for decisions from all
survivors. If disagrees, kill that host's link and repeat the process.

ENG-10618: Fix mesh arbiter fault resolution algorithm.

---

tests/scripts/examples/sql_coverage/basic-upsert.sql
tests/scripts/sql_coverage_test.py

changed '@idcol + 100' to '@idcol + 20'), which reduces the number of
rows created in each table (each UPSERT now does more updating and less
inserting), which solves the slow (PostgreSQL) query problem, so those
query templates are now uncommented. Also uncommented a couple of other
query templates, after tweaking them to generate fewer queries (e.g.,
changed '@cmp' to '@somecmp', and replaced '@columnpredicate' with a
clause using '@somecmp’). And changed 'SELECT *' queries to 'SELECT
@star' (which will make ENG-10464 easier).
sql_coverage_test.py: just fixed the comments for the
print_elapsed_seconds method.

basic-upsert.sql: reduced the numbers added to the ID column (e.g.,

---

src/frontend/org/voltdb/SnapshotSaveAPI.java

Fix SnapshotSaveAPI/startSnapshotting() to show table name when doing partial snapshot only for replicated table(s).
Reason for previous problem: the site who created the snapshot taskList may empty the result table because its own taskList is null. Actual snapshot work is done by other site.

ENG-9244: Partial snapshot missing replicated table name

---

src/frontend/org/voltdb/utils/HTTPAdminListener.java

Manually tested it by: 
* Starting a database with the new cli using 'start' without a deployment file and downloading a default deployment file through VMC (_which is a different default from the one in RealVoltDB but works the same_). 
* Making changes to the deployment through VMC to only some of the fields. 
* Catalog update through voltadmin and download new version on VMC. 
In all cases the file was indented and consistent with the change.

Deployment file pretty print

---

tests/scripts/examples/sql_coverage/advanced-template.sql
tests/scripts/examples/sql_coverage/basic-select.sql

Updated basic-select.sql, advanced-template.sql to include LIMIT 0 and OFFSET 0 as possible options, for various query templates.

Eng 10645 sqlcov limit0

---

tests/scripts/examples/sql_coverage/basic-select.sql

ENG-10733 seems to be fixed (for materialized views).

basic-select.sql: include tests of OFFSET without LIMIT, now that

---

third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/mathutil.h
third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/matrix3x3-inl.h
third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/vector2-inl.h
third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/vector3-inl.h
third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/vector4-inl.h

The GCC version 5.4.0 compiler does not have a global definition of
isnan.  This function is in std::isnan and not global.  The C6, C7
and U14.04 compilers had these functions in the global namespace and
not in std::isnan.  So, we leverage some partial support for this in
the S2 library and expand coverage to other data types which need it.

Fix compilation errors on Ubuntu 16.04.

---

src/frontend/org/voltcore/messaging/ForeignHost.java
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/Consistency.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/iv2/RepairLog.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerSpHandle.java

Add FAST and SAFE read modes in deployment file.
Make SAFE default.
Cut off client networking at the beginning of crashLocal/GlobalVoltDB
Companion pull: https://github.com/VoltDB/pro/pull/1431

ENG-10667: Backports of ENG-10389 and part of ENG-10453 to 5.9

---

src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/planner/TestFunctions.java
tests/frontend/org/voltdb/planner/testplans-functions-ddl.sql

I today found the two bugs are actually the same one.
The parameter problem, although the data type didn't show correct, does not affect the behavior of the EE. So I guess there are some other places in the code that can detect the DECIMAL and BIGINT type issue.
The real problem was serializing TIMESTAMP to JSON, I just added the code to make it support both long value string and date string.

Fix ENG-10749, 10750

---

src/frontend/org/voltdb/RestoreAgent.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

Compare tables in snapshot digest file with tables in catalog jar. If there is a dismatch, ignore that snapshot.
- Create getNormalTableNamesfromInMemoryJar() in CatalogUtil, which returns all the normal table names in a catalog in-memory jar file.
- Call getNormalTableNamesfromInMemoryJar() in RestoreAgent to compare the table names in catalog with table names in digest.

Prevent voltdb to recover from a partial snapshot.

---

src/frontend/org/voltdb/iv2/Scheduler.java

When setting the TxnEgo during leader promotion, recover, or snapshot
restore, only set it if it's moving into the future. Never set the
TxnEgo because that leads to duplicate txnIds down the road.

ENG-10799: Don't set TxnEgo backward.

---

build.py
buildtools.py
tests/ee/common/nvalue_test.cpp
tests/ee/expressions/function_test.cpp
tests/ee/memleaktests/definite_losses.cpp
tests/ee/memleaktests/indirect_losses.cpp
tests/ee/memleaktests/possible_losses.cpp
tests/ee/memleaktests/rw_deleted.cpp
tests/ee/memleaktests/still_reachable_losses.cpp
tests/ee/test_utils/vdbsuppressions.supp

Fixed read-deleted error message in expressions/function_test.cpp.
Apparently the 16.04 version of the C++ compiler, which is version
5.4.0, destroys std::string values earlier than previous versions.  This
means the locution "char *msg = string_value.c_str()" can cause
read-after-delete errors.  If "string_value" is deleted before the end
of the block any use of msg will be in error.  In general these should
be replaced with std::string operations.
Added tests for some more memory leaks and read/write deleted memory,
and changed the buildtools.py program to know when to expect leaks.
The valgrind distributed with Ubuntu 16.04 does not produce the same
output as the valgrind in earlier versions.  This commit parses the
valgrind output somewhat more carefully and finds errors in both …

Fixed valgrind related errors for Ubuntu 16.04.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/AsyncCompilerAgentHelper.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java

Logic updates to ignore admin mode setting via deployment file during voldtb init if different than default.  
Changes have been tested for the following scenario:
- User provides no deployment, the default deployment gets used same as today
- User provides a valid deployment without admin mode settings, deployment file gets copied to voldbroot if voldbroot is not changing
- User provides a valid deployment with admin mode startup set to false, the same deployment file gets copied to voldbroot if voldbroot is not changing
- User provides a valid deployment with admin mode set or different admin port , newly generated deployment file with other default setting gets written to voldbroot similar to case if the voltdbroot directory was different.

ignore being admin-mode being set through deployment when using new verbs 

---

src/frontend/org/voltdb/DRProducerStatsBase.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

Add a new column to the node level and partition level table that adds an entry for the consumer cluster id that the producer is connected to. The id is the integer id of the consumer specified in the deployment.
Andrew said that in the future it would be nice if the rows were in order by the consumer cluster id.

Add consumer cluster id to DRProducer stats

---

tests/scripts/SQLCoverageReport.py
tests/scripts/examples/sql_coverage/join-template.sql
tests/scripts/examples/sql_coverage/normalizer.py
tests/scripts/examples/sql_coverage/not-a-normalizer.py
tests/scripts/sql_coverage_test.py

Added a get_max_mismatches method, and use it to determine whether the tests have failed; and apply this to the current 'known' failures in the basic-joins, basic-index-joins, basic-compoundex-joins, numeric-decimals & numeric-ints test suites (all of these only on PostgreSQL).

Eng 10775 full join postgres

---

src/ee/common/ElasticHashinator.h
src/ee/common/LegacyHashinator.h
src/ee/common/TheHashinator.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/ElasticContext.cpp
src/ee/storage/persistenttable.cpp
src/frontend/org/voltdb/sysprocs/saverestore/IndexSnapshotRequestConfig.java
voltdb/log4j.xml

Change-Id: I31e71b3e0372f176c4d52787e598eecc339c2652

ENG-10358, add diagnostic code to elastic join path.

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/DummyCommandLog.java
src/frontend/org/voltdb/iv2/SpScheduler.java

This PR proposes changing the method signature of Command Log's logIv2Fault method to return a settable future with parameter boolean. The calling thread can block on this future to wait to be told if the fault log was successfully written to disk or not. The status of the write is propagated from the FileWriter in the command log back to the SpScheduler so the caller can decide to block on it or not.
The two cases where blocking was added was:
1. The leader waits for their write to finish after it has commanded the other replicas to do so (updateReplicas)
2. The replicas wait for their write to finish but only when they get that message from the leader (handleIv2LogFaultMessage)
So these block in cases where fault logging races with starting to process transactions again

Eng 10654 fault logging

---

src/ee/common/executorcontext.cpp
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/DRTupleStream.cpp
src/frontend/org/voltdb/PartitionDRGateway.java

1. Add check for MP single hash txn so that if the txn is not for local partition, it will be skipped.
2. For DR binary log record of DR_RECORD_TRUNCATE_TABLE type, ignore the value of skipRows because the hash for this type of record is just a placeholder and meaningless. Table truncation should always be executed.
3. Adjust the behavior of getTestDRBuffer() for both normal and compatible DR tuple stream. A partition key value of -1 for a SINGLE_HASH type txn will now instruct this test method to generate this txn as a MP txn for test purpose. A partition key value of -1 for a MULTI_HASH type txn will now instruct this test method to generate this txn as a SP txn (part of a run-everywhere txns group) for test purpose.
4. Add some version constants for binary log versions from which DR …

ENG-10523: Recognize multi-partition binary log entries in the buffer splitter

---

src/frontend/org/voltdb/compiler/MaterializedViewProcessor.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java

Improve the warning logic for single table views.
Add warnings for join query views.
The ad-hoc DDL warning tests were filed as [ENG-10894](https://issues.voltdb.com/browse/ENG-10894), which will be added after Paul's fix for the warning messages lands in the product.

ENG-10864 view warnings

---

src/ee/common/executorcontext.cpp
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/CompatibleDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h

Make transactionChecks() return a bool indicating if stream state was switched from close to open in this function call.
Register an undo action for BEGINTXN only if it has been written to stream (i.e. transactionChecks() returns true)

ENG-10896: Only register undo action for BEGINTXN when one has been written to the stream

---

src/ee/storage/MaterializedViewTriggerForInsert.cpp
src/ee/storage/MaterializedViewTriggerForWrite.cpp
src/ee/storage/TableCatalogDelegate.cpp

Streams support views as long as the partition column is part of the view. However, for view definitions without any group by columns, there is no way you could have a partition column in the view. (aggregation on a partition column does not count!)
That is, **you cannot define a view without a group by column on a streamed table**.
There was an initializeTupleHavingNoGroupBy() function in the persistent view logic to handle the initialization for views without group-by column because there will always be one row even the source table is empty. This call was persistent view specific when I fist added it in ENG-7872 last year.
During a recent refactoring of the old code, we pulled this logic from persistent view to a common code path shared by both types of views. This accidentally …

Fix ENG-10916

---

tests/sqlcmd/baselines/ddl/load_remove_classes.outbaseline
tests/sqlcmd/baselines/simple/versioncheck.outbaseline
tests/sqlcmd/scripts/ddl/load_remove_classes.in
tests/sqlcmd/scripts/simple/versioncheck.config

'--no-version-check' option), so that the test script will run to the end, even after the expected error, and therefore will clean up after itself, deleting the tables & procedures it creates (which were causing other tests to fail); hence, had to add additional text to versioncheck.outbaseline, for the part after the error; also, deleted the initial WARN, which gets "cleaned" away (which was causing this test to fail).
load_remove_classes.in: also, added drop (if exists) for the my_table_1, my_table_2 & my_table_3 tables, which theoretically could cause this test to fail (though I've not seen this happen); and added corresponding text to load_remove_classes.outbaseline.

versioncheck.config: added the '--stop-on-error=false' option (to the

---

src/ee/common/tabletuple.h
src/hsqldb19b3/org/hsqldb_voltpatches/SetFunction.java

In the backend there was an index on a COUNT(*) field of a MV.  The component type for the index was INTEGER, but we expected BIGINT.  I made HSQL set the output type of COUNT(*) to be BIGINT always.
I also loosened an equality check in `copyForPersistentUpdate`.  We were expecting the same instance of `TupleSchema` when copying tuples, but they really only need to be equivalent.  In particular, if we are copying into a tuple backed by `StandAloneTupleStorage`, the schema instance will never be the same as some persistent table, since the stand alone class allocates its own copy.

ENG-10951: failed assertions in debug build

---

src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/expressions/WindowedExpression.java
tests/frontend/org/voltdb/regressionsuites/TestWindowedAggregateSuite.java

We don't serialize sort directions in windowed RANK() expressions.  So,
when we deserialize plans with PartitionByPlanNodes we pass in a null in
the parameter which holds the list of sort directions.  We needed to be
more careful about testing for this null.
Also, some dead code was eliminated, and some spurious debug printing in
tests was deleted.

Fix an NPE bug for explanations of plans with windowed RANK().

---

tests/testverbs/voltverbstest.py

This script generate ~90 unittests with various opts for each voltdb verbs. 
The mapping (spreadsheet) of verb to its available opts is defined in the beginning section.
Add new verbs or options need to change this section.
Config based (YAML) mapping not choosen. Since that will over-complicated the code.
To run 
python voltverbstst.py

Eng 10869 AAUIW automated testing of voltdb verbs

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
tests/frontend/org/voltdb/planner/TestWindowedFunctions.java
tests/frontend/org/voltdb/regressionsuites/TestWindowedAggregateSuite.java

Table partitioning and window partitioning are related.  If a query has
a windowed aggregate with a PARTTION BY expression which is a reference
to a table partition column, then the PartitionByPlanNode from the
windowed aggregate expression can be pushed down to a distributed
fragment.  Otherwise, the PartionByPlanNode needs to be executed on the
coordinator fragment.
This commit implements this properly.

Table partitioning and window partitioning must match.

---

src/frontend/org/voltdb/expressions/WindowedExpression.java
src/frontend/org/voltdb/plannodes/AggregatePlanNode.java
src/frontend/org/voltdb/plannodes/PartitionByPlanNode.java
tests/frontend/org/voltdb/planner/TestWindowedFunctions.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestWindowedAggregateSuite.java

I added a resolveColumnIndices method to `PartitionByPlanNode`.  I also moved some member variables to the top of classes.  This conventions seems to actually be followed pretty consistently within our code base, so I thought it would be good to follow the trend.

ENG-10972: Resolve column indices for ORDER BY expressions of windowed aggregates

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/regressionsuites/TestWindowedAggregateSuite.java

The issue here is with the generation of the synthesized RANK column produced by PartitionByPlanNode.  When we need to add an extra projection to the plan, we need to update the "differentiator" field of TVEs in order to help us disambiguate columns in some obscure cases.  The code that does this adjustment is confused by synthesized columns.
The fix here was just to avoid doing the differentiator adjustment for synthesized columns, which consistently have the table alias `VOLT_TEMP_TABLE`.
I think that we didn't find this before because we happened to have combinations of column indexes such that things happened to work.
We are close to shipping 6.6, but this seems like it could make RANK very difficult to use for some tables, and this change seems pretty safe to make.

ENG-11029: Planner assertions for some seemingly innocuous RANK queries

---

tests/scripts/examples/sql_coverage/analytic-template.sql
tests/scripts/sql_coverage_test.py

Removes the kludge that expected certain tests of RANK to fail, since the relevant bugs are now fixed; and adds tests of RANK without a PARTITION BY clause - now targeted to merge onto the release-6.6.x branch.

Eng 10980 sqlcov rank failures

---

src/frontend/org/voltdb/expressions/TupleValueExpression.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/regressionsuites/TestWindowedAggregateSuite.java

The test point testEng11029 was failing.  It needed an order by clause
to make it deterministic.  But there was also a problem in fixing up TVE
differentiators.  PartitionByPlanNodes and OrderByPlanNodes following
PartitionByPlanNodes will contain a column which does not have a
differentiator.  We fix this in general by marking the TVE for the rank
expression with a flag saying it does not need its differentiator value
updated.

Fix TestWindowedAggregateSuite test failures.

---

src/ee/storage/persistenttable.cpp
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java

This is analogous to similar issues we saw with MIN/MAX and update.  Here is that change, which is already merged:
https://github.com/VoltDB/voltdb/pull/3864/commits/6ab93a73aa23b9bf2c4030c8eca74847a2260e16

ENG-11048: Fix issue with wrong answers when deleting tuples from MV source tables

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java
src/frontend/org/voltdb/messaging/CompleteTransactionResponseMessage.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java
tests/frontend/org/voltdb/messaging/TestVoltMessageSerialization.java

CompleteTransactionMessage needs to send a response to the SPI to
reliably track MP transaction commit point. Otherwise, it may be racing
with the execution of the FragmentTasks and SpProcedureTasks before the
MP.

ENG-10472: Advance the SPI truncation point when transaction is done.

---

src/ee/common/NValue.cpp
src/ee/common/tabletuple.cpp
src/ee/storage/MaterializedViewHandler.cpp
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/matviewprocs/TruncateMatViewDataMP.java

The symptom was that a view appeared to be nonempty even when all data was deleted from its source tables.  That is, until the transaction is committed.  After the current quantum is released, the view appears empty as it should.
This happened because logic in `handleTupleForDelete` was first deleting the tuple and then updating it.  We should do one or the other but not both.  The processing of updating the tuple changed the "pending delete" bit, such that it was visible again.  But once the transaction committed, the release of the undo action made the view appear empty again.

ENG-11056: Fix logic error in MaterializedViewHandler

---

src/frontend/org/voltdb/iv2/SpScheduler.java

We are duplicate counting the CompleteTransactionMessage for tracking
the locally executed spHandle in SpScheduler. Since the duplicate
counter key is the (txnId, spHandle) pair, if the
CompleteTransactionMessage shares the same spHandle with its last
fragment, such as in the case of an early abort triggered by other
partitions, it will result in duplicate counter collision. We always
increment the spHandle except for command log replay for the
CompleteTransactionMessage. Making it advance the spHandle for replay as
well.

ENG-11184: Advance spHandle for CompleteTransactionMessage on recover.

---

lib/python/voltcli/voltadmin.d/stop.py

Fixes issue where 'hostname' is selected for connection during call to voltadmin stop.   It selects admininterface, if specified.  Otherwise it selects ipaddress.

Eng-11183 Fix problem of voltadmin using 'hostname' to connect to issue a stop node.

---

src/frontend/org/voltdb/iv2/SpScheduler.java

Promotion Related Changes:
1. Remove Complete Transaction Response Message Duplicate Counter, and swollen its repair truncation message on leader; 
2. Repaired MP transaction should use SpHandle from TransactionState other than its newest message SpHandle;
Once a while, I saw a similar truncation handle going backwards during process of rejoin, which seems to be a separate problem. Still working on this issue.

ENG-11185: patch 1

---

src/frontend/org/voltdb/iv2/RepairLog.java
src/frontend/org/voltdb/iv2/SpScheduler.java

Local repair log truncation handle is possible to move backwards. Instead of throwing runtime exception, we can debug logging it. Possible cases are added, like node failure and node rejoin. All of them are related to MP transaction CompleteTransactionResponseMessage with following SP write transaction during leader promotion or early rejoin phase (runForRejoin).

ENG-11233: Change throwing exception case to debug logging case

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InvocationDispatcher.java

A connection with positive id in schema restore will be thrown into  live client statistics. However, the connection (SimpleClientResponseAdapter) does not support stats.  Thus make the connection id as a negative constant to skip the stats collection.

ENG-11231 skip live client stats collection for schema restore.

---

src/frontend/org/voltdb/PostgreSQLBackend.java
tests/scripts/examples/sql_coverage/grammar.sql
tests/scripts/sql_coverage_test.py

operators.
PostgreSQLBackend.java: subtle change to one regex expression, to make
sure that it does not confuse the FROM in IS [NOT] DISTINCT FROM with
the FROM in SELECT ... FROM T1 ... (otherwise, such confusion causes
UPSERT statements to be translated into invalid INSERT / ON CONFLICT DO
statements); and corrected a couple of nearby comments.

grammar.sql: added IS NOT DISTINCT FROM to the list of comparison

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/sysprocs/Shutdown.java

When a cluster in PAUSED mode is force-shutdown, the cluster will be set to SHUTTINGDOWN mode. There may be a window before the cluster process is killed within which transactions can go through.

ENG-11275 block transactions during shutdown

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java

Block transactions during shutdown on dispatcher instead to make unit test happy.

ENG-11275: unit test fix

---

src/frontend/org/voltdb/types/VoltDecimalHelper.java
tests/scripts/sql_coverage_test.py

MathContext constructor (as the precision, in the roundToScale method)
and being used as an array index (of the scaleFactors array, in the
serializeBigDecimal method), since they were causing exceptions, when
running sqlcoverage's numeric-decimals test suite against PostgreSQL.
sql_coverage_test.py: in get_max_mismatches, removed the expected
failures for the numeric-decimals test suite.

VoltDecimalHelper.java: avoid negative values being passed to the

---

lib/python/voltcli/voltdb.d/start.py
src/catgen/spec.txt
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/compiler/ClusterConfig.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/frontend/org/voltdb/utils/CommandLine.java
tests/frontend/org/voltdb/TestMixedSitesPerHostCluster.java
tests/frontend/org/voltdb/compiler/TestClusterCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

This patch provides VoltDB the ability to start with mixed sitesperhost settings. By using the hidden option `-s` or `--sitesperhost` the user can overrides the `sitesperhost` field in deployment file for each host.
The Pro-side pull request is https://github.com/VoltDB/pro/pull/1534

Eng 10842 mixed sph

---

tests/frontend/org/voltdb/regressionsuites/TestCatalogUpdateSuite.java

There is a variable callbackSuccess which is initialized to true and is
set to false if an asynchronous stored procedure call returns an
unexpected result for any reason.  The test does not always wait until
the procedures are done before the variable is checked.  So, the
variable's value may not reflect the correct state of the procedure
execution. Also, the server may be taken down before the message for the
last stored procedure is executed.  If this happens, the last operations
fail and the variable is set to false.
This is all a race condition in the test and does not affect the product
functionality at all, except insofar as the product is not tested
completely.
https://issues.voltdb.com/browse/ENG-11313

Eliminate race conditions in TestCatalogUpdateSuite.

---

src/frontend/org/voltdb/iv2/SpScheduler.java

The MP safe reads jumped the transaction task queue when sync command logging is on, and these reads are buffered without returning to MPI. This commit asks MP safe reads to go though the command logging queue to get guarranteed order

ENG-11372: fix an issue of a possible read only MP deadlock when sync cmdlog is on.

---

tools/kit_tools/build_kits.py

If you want, this can be looked at as two separate commits.
1. Refactored build_kits to use argparse and added a few switches that make debugging easier, such as --nomac, --nopackages, --nocommunity.  It can also use the internal mirror
2. Added code to create the new Pro edition.  This is done by
* un-tgzing the newly built enterprise 
* making a new license 
* re-tgzing the kit as the pro kit
3. Changed the license length
I verified these kits with the following methods:
1. I compared the output of the "new" enterprise build from this script (I rebuilt voltdb-6.7) to the real release.  The only difference was the dates.
2. I compared the output of the new Enterprise release to the new Pro release. The only difference was the license file.

ENG-11297. Create a new Pro edition kit

---

src/frontend/org/voltdb/compiler/VoltCompilerUtils.java
src/frontend/org/voltdb/utils/InMemoryJarfile.java

A customer noted long GC pauses when doing LOAD CLASSES on a largish jar with hundreds of classes.  We were doing a lot of allocating (per class in the jar) of 4MB and 8MB byte buffers.  This changeset addresses that.
The existing unit test, TestInMemoryJarfile, cover this change.

Avoid excessive array allocation in InMemoryJarfile

---

tests/scripts/examples/sql_coverage/analytic-template.sql

list of analytic functions to be tested; and modified some (though not all) of the query templates to have optional ORDER BY clauses, since the old analytic functions (RANK, DENSE_RANK) always require an ORDER BY clause, but this new one does not. (Also tweaked the definition of _analyticfunc to include the parentheses, to support this; plus improved comments and spacing.)

analytic-template.sql: added COUNT(*) and COUNT(_columnorexpr) to the

---

src/frontend/org/voltdb/RealVoltDB.java

If the last rejoin truncation snapshot fails to finish due to a node
failure, the rejoining node would not notice that and hung the
system. Now the rejoining node detects node failures before rejoin fully
completes and aborts rejoin in that case.

ENG-11280: Abort rejoin if another node fails before rejoin completes.

---

build.xml
tools/watch_performance.py

This is a python script that uses voltdbclient.py found in ../lib/python and monitors the performance of procedures every 5 seconds for 30 minutes (configurable).
It supports authentication if enabled, and is configurable with command-line arguments.
Here is example output:
```
time cpu                                procedure label pct  invocations   avgnanos     tps lat_millis     c
-------- --- ---------------------------------------- ----- --- ------------ ---------- ------- ---------- -----
15:15:59   5                                     Vote SP-RW 100      2926823      21985       0          8   0.0
15:15:59   5                             SnapshotSave  None   0            1          0       0          0   0.0
15:15:59   5                               Initialize MP-RW   0 …
```

adds a performance monitoring script to the kit under /tools

---

lib/python/vdm/server/venv_starter.py

It seems venv_start always try to install required packages. We should skip that if already system wide installed (by root).

ENG-11471: skip pip install if the module already installed

---

src/frontend/org/voltdb/ExtensibleSnapshotDigestData.java

When dr Squence numbers were inconsistent, we were logging the inconsistency as an error and always using the last value but we should only ever update the entry if the value is higher as originally implemented before the extra logging.

ENG-10316:

---

tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/StatisticsTestSuiteBase.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

1. Refactor a frequently used snippet into a helper function, createLocalCluster(), in LocalCluster
2. Refactor and fix DRStats test to the new partition stats format and semantic, node stats tests are temporarily disabled as the new format and semantic is not determined yet

ENG-10626: change connect request handling and fix various tests

---

lib/python/voltcli/checkstats.py
lib/python/voltcli/voltadmin.d/pause.py
lib/python/voltcli/voltadmin.d/shutdown.py

added a mechanism to monitor the draining of outstanding transactions.  The command will be timed out if no transactions have been drained within timeout period after the last successfully drained transaction.

ENG-11434 voltadmin shutdown/pause timeout

---

src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/Initiator.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpProcedureTask.java
src/frontend/org/voltdb/iv2/SpScheduler.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java

- Instead of creating the DR gateways when the initiators are
constructed, which is way early than when the DR producer is ready to
do anything, I moved them out of the initiator constructor and create
them when the DR producer is ready.
- The SpScheduler really doesn't care about the DR gateway. Only the
transactions care about it when they are run on the site. So I removed
the reference to the DR gateway from SpScheduler and created a getter
in the Site so that transactions can have access to it.

ENG-11447: Refactor DR producer initialization sequence.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/MaterializedViewHandler.cpp
src/ee/storage/MaterializedViewHandler.h
src/ee/storage/persistenttable.cpp

When tuples are inserted into a base table of a multi-table view, the normal code path is:
`PersistentTable::insertTuple()` => `PersistentTable::insertPersistentTuple()` => `PersistentTable::insertTupleCommon()`
The function call to insert the new tuple into the delta table is in `PersistentTable::insertPersistentTuple()`. 
However, on snapshot restore, `PersistentTable::processLoadedTuple()` directly call `PersistentTable::insertTupleCommon()`, so the new tuple is not inserted into the delta table for view mantainence.
This pull request fixed the bug by adding a `insertTupleIntoDeltaTable()` call in `PersistentTable::processLoadedTuple()`.
The regression test will be added to the pro repository.

ENG-11573 populate joined table view on snapshot restore

---

src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/RestoreAgent.java

My previous patch delayed the initialization of the DR producer until
replay finishes, which lost all replayed transactions' binary logs. I'm
initializing the producer right before replay starts now.

ENG-11447: Initialize the DR producer before CL replay on recover.

---

tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

Add an optional delay between the node startup to help matching the host ids cached on LocalCluster to those in real cluster.

ENG-11616 delay param between node startup

---

tests/frontend/org/voltdb/regressionsuites/TestSqlUpdateSuite.java

10x faster by only bringing up the server once.  This sacrifices test isolation for speed and may not
be what we want to do everywhere, but this particular suite makes calls to a single method, executeAndTestUpdate(), so changes needed for between-testcase cleanup are in that test method.
- On Jenkins this went from 4+ minutes to 25 seconds
- All SQL is in 1 testcase per backend
- Added some println to show what is happening
- Added more info to assert to show failed query
- Added TRUNCATE TABLE at the end of the executeAndTestUpdate call

Make SQLUpdateSuite 10x faster

---

src/frontend/org/voltdb/DRConflictManager.java
src/frontend/org/voltdb/PartitionDRGateway.java

So that the conflict manager can exist without the dependency on PDRG.

ENG-11447: Extract DRConflictManager interface from PartitionDRGateway.

---

src/frontend/org/voltdb/iv2/LeaderAppointer.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

If a replica cluster is promoted before a sync snapshot took place, the
cluster should not crash if a node failure is detected.

ENG-11382: Fix DR sync snapshot node failure check after promotion.

---

tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestPartialIndexesSuite.java
tests/frontend/org/voltdb/regressionsuites/TestProcedureAPISuite.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java

Six tests were calling getClient() prior to checking isHSQL(), resulting in the tests waiting on
the getClient() timeout rather than quickly returning with a PASS for testcases that the HSQL
backend can't run.

Eng-11644 Fix up some HSQLDB tests that were taking 2 min. to timeout the getClient() call

---

build.xml
src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/client/ClientImpl.java
src/frontend/org/voltdb/client/ClientUtils.java
src/frontend/org/voltdb/client/Distributer.java

use env variable VOLT_JUSTATEST in the build as a switch to speed up unit tests.

ENG-11661 use test switch to speedup unit test

---

src/frontend/org/voltdb/iv2/SpDurabilityListener.java

Read-only transactions use UniqueIds for access to Time but the UniqueId is not in fact unique nor is it continuously advancing relative to other transactions. Because we only want durability notifications for write transactions, we need to avoid updating UniqueIds for read-only transactions.
Because of read-write ordering issues identified by Jepsen Synchronous command logging does track read-only transactions. Therefore, even for a read-only workload, the durability listener must still be called to queue the read-only transactions to the Site thread.

ENG-11352:

---

src/ee/common/types.h
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/pmsg/DRAgent.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/protobuf/dragent.proto

1. Add a new ExecuteTask task type INIT_DRID_TRACKER which is used to populating empty trackers in XDCR
2. Add partition count in snapshot request protobuf, include partition count in snapshot requests and start cursor requests (they are not really used for now, will remove them if not needed)

ENG-11647: Pre-populate site trackers for consumer clusters requested in snapshot request and start cursor request

---

src/frontend/org/voltdb/pmsg/DRAgent.java
src/protobuf/dragent.proto

Add the IsSynced flag back to the PartitionInfo message because v5.9
still reads this flag even though it's always true.

ENG-11739: DR protocol message backward compatibility fix.

---

src/ee/storage/persistenttable.h

I had added this superfluous assert on a guess that it was safe. 
Backing it out as it looks like I guessed wrong.
Fixes MOST of the ENG-11745 debug crashes.

Backed out a recent over-aggressive assert causing debug crashes.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/zk/CoreZK.java
src/frontend/org/voltdb/RealVoltDB.java

Removed unnecessary waiting for all the rejoining nodes in RealVoltDB initialization since the scenario has been handled in ElasticJoinCoordinator.

ENG-11752 elastic joining fix

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/DRConsumerStatsBase.java
src/frontend/org/voltdb/DRProducerNodeStats.java
src/frontend/org/voltdb/DRProducerStatsBase.java
src/frontend/org/voltdb/DRRoleStats.java
src/frontend/org/voltdb/ProducerDRGateway.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

- Return one row per conversation in DR producer and consumer node
stats.
- Roll DR producer and consumer node stats into DRROLE stats for each
conversation.
- This patch doesn't contain the work for the STOPPED state on the
producer. It requires break replication to work on the producer.

ENG-11693: DRROLE for multi-cluster XDCR

---

src/ee/common/NValue.hpp
src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h
src/ee/expressions/stringfunctions.h
src/frontend/org/voltdb/planner/ParsedColInfo.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionValue.java

The SPACE sql function did not check for arguments being too large.  As
a result we would try to allocate a large amount of string space, which
caused allocator failures.
These same queries showed up problems in the planner with aliases in
order by lists.  If a select list element is a constant, and there is a
reference to it as an alias in the order by list, we didn't expect it
and we threw an error. There are also cases where data types for select
list aliases are not set in the Volt expression structures when we
expect them to be.  This can cause NPEs when converting from strings to
BIGINT values.  These have been fixed.
FWIW, this fixes ENG-11683, ENG-11684 and ENG-11762.

Fix several problems with strings, and with aliases in order by lists.

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

Rejoining is processed one at a time. Later rejoining hosts may wait for  > 5 min without sending another rejoining request even through no rejoining is in progress in the cluster. Reset waiting time to avoid over waiting.

ENG11616  reset backoff for rejoining

---

src/frontend/org/voltdb/ConsumerDRGateway.java

pauses itself until SS is complete.

We don't need awaitProducerSnapshot flag anymore because the consumer

---

src/catgen/catalog.py
src/catgen/in/javasrc/DRCatalogCommands.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
src/catgen/spec.txt
src/frontend/org/voltdb/dr2/DRProtocol.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

For compatibility mode, we can't generate catalog commands with new
keywords. Fallback to old keyword for XDCR.

ENG-11459: Generate version aware DR catalog commands.

---

src/ee/common/NValue.cpp
src/ee/expressions/datefunctions.h

My last commit related to timestamps improved error reporting but slowed down the agg bench performance test.  My theory was that my improved error reporting (which included function names in error messages) was slower because it was instantiating a `std::string` for each range check.  This refactoring avoids instantiating the function name until a range check fails.
If this doesn't work, I'll roll back the original commit that caused the regression.

ENG-11868: Agg bench performance regression

---

tests/sqlcoverage/config/extended-config.py

numeric-decimals test suite, from 9 to 8 (significant digits), because
Ruth noticed that it was failing often, with tiny decimal differences.

extended-config.py: just reduced the numeric precision of the

---

src/frontend/org/voltdb/expressions/OperatorExpression.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpdateSuite.java

CASE WHEN isn't like other operators, which are mostly binary or unary.
RHS of the CASE WHEN operator is the OPERATOR_ALTERNATIVE, which is what really helps define type of output, so defer to RHS when refining.

ENG-11779: Fix refineValueTypes for CASE WHEN expression

---

tests/geb/vmc/server/ddl.sql

definitions, since this is no longer allowed (& never actually worked), and was causing the tests not to run.

ddl.sql: just removed the PRIMARY KEY from one of the CREATE STREAM

---

tests/test_apps/genqa/ddl-nocat-geo.sql
tests/test_apps/genqa/ddl2.sql
tests/test_apps/genqa/ddl3.sql
tests/test_apps/genqa/ddl4.sql

Changes in ddl for Volt 7 -- export table becomes stream -- also need "export to target <name>". Previously the export would go to "default" if none named in the ddl. Now nothing is actually exported if there no "export to...".
This has caused the Server-Export system test suite to fail.
So this change adds "export to target <name>" where required.
There's a small additional change for one table that had been changed to stream but shouldn't have been.

ENG-11954 add "export to target ..." to ddl files, needed in V7.0 & beyond

---

src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/jdbc/Driver.java
src/frontend/org/voltdb/jdbc/JDBC4ClientConnection.java
src/frontend/org/voltdb/jdbc/JDBC4ClientConnectionPool.java
tests/frontend/org/voltdb/jdbc/JDBCTestCommons.java
tests/frontend/org/voltdb/jdbc/TestJDBCAutoReconnectOnLoss.java
tests/frontend/org/voltdb/jdbc/TestJDBCDriver.java
tests/frontend/org/voltdb/jdbc/TestJDBCMultiConnection.java
tests/frontend/org/voltdb/jdbc/TestJDBCMultiNodeConnection.java
tests/frontend/org/voltdb/jdbc/TestJDBCQueries.java
tests/frontend/org/voltdb/jdbc/TestJDBCSecurityEnabled.java
tests/frontend/org/voltdb/jdbc/TestJDBCStreamQueries.java

Add support for JDBC client to connect to the server over SSL. To connect JDBC client to server over SSL transport following properties key can be supplied along either with jdbc driver url or using system properties (ssl properties specified using system properties takes precedence over url properties):
URL properties for connecting over ssl
- Property: ssl; value description: "true" or "false" specifying whether to connect over SSL transport. Required if want to connect over SSL
- Property: truststore; value description: trust store path (optional)
- Property: truststorepassword; value description: trust store path (optional)
Example: 
Valid urls: 
- jdbc:voltdb://server1:21212,server2?ssl=true&truststore=/tmp/xyz&truststorepassword=password"
- …

ssl support for jdbc

---

tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

summary_number, log, log_number, echo, echo_file; which are mostly about
(optionally) generating a summary output file that includes the last N
SQL statements generated, and the "tail" of the VoltDB server log file,
and/or of other files (and about echoing certain specified SQL
statements); plus code to support the new options; also changed output
files to "flush" output immediately; and tweaked formatting and
comments.
sql-grammar.txt: added (trig & other) functions: SIN, COS, TAN, CSC,
SEC, COT, LOG10, STR.

sql_grammar_generator.py: added several new options: summary,

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java

Use the presence of node /core/rejoin_nodes_blocker as rejoin indicator for cluster safety check.

ENG-11968 fix rejoin node blocker check

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

1. Move initialization of DR ConsumerGateway to the cluster initialization time. This then allows the producer to leak connections and start cursors to the cluster even if no data source has been specified.
2. Enable breaking of producer and consumer connections to isolate a ServerThread or LocalCluster host with hasLocalServer set to true.
3. Change QueryInterval in DRConnectionInterface from static final to instance final so that it can be set to a low value for unit tests that use ServerThread. This accelerates unit tests that require discovery to detect rejoined or recovered hosts.
3. Add a unit test to multiCluster to verify that a joiner cluster and a network isolated mesh leader cluster can find eachother and sync up after the network isolation has been removed.

ENG-11866:

---

src/catgen/in/javasrc/CatalogType.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

Use a white list to filter out information on DR tables that DR doesn't
care about, such as views.
A recent addition to the view catalog commands was made which caused DR
upgrade path to generate catalog commands that older version doesn't
understand. This fixes the backward compatibility issue.

ENG-11999: Don't serialize view info on DR tables for DR schema check.

---

src/catgen/in/javasrc/CatalogType.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

Use a white list to filter out information on DR tables that DR doesn't
care about, such as views.
A recent addition to the view catalog commands was made which caused DR
upgrade path to generate catalog commands that older version doesn't
understand. This fixes the backward compatibility issue.

ENG-11999: Don't serialize view info on DR tables for DR schema check

---

src/catgen/in/javasrc/CatalogType.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

Use a white list to filter out information on DR tables that DR doesn't
care about, such as views.
A recent addition to the view catalog commands was made which caused DR
upgrade path to generate catalog commands that older version doesn't
understand. This fixes the backward compatibility issue.

ENG-11999: Backport for v6.8.x

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

* ENG-11866:
1. Move initialization of DR ConsumerGateway to the cluster initialization time. This then allows the producer to leak connections and start cursors to the cluster even if no data source has been specified.
2. Enable breaking of producer and consumer connections to isolate a ServerThread or LocalCluster host with hasLocalServer set to true.
3. Change QueryInterval in DRConnectionInterface from static final to instance final so that it can be set to a low value for unit tests that use ServerThread. This accelerates unit tests that require discovery to detect rejoined or recovered hosts.
3. Add a unit test to multiCluster to verify that a joiner cluster and a network isolated mesh leader cluster can find eachother and sync up after the network isolation has been removed.

ENG-11866: (#4257)

---

lib/python/voltcli/voltdb.d/get.py
src/frontend/org/voltdb/GetActionArgument.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/regressionsuites/TestInitStartLocalClusterAllOutOfProcess.java
tests/frontend/org/voltdb/regressionsuites/TestInitStartLocalClusterInProcess.java

- Add ddl/schema argument support to get command. By default the sql stored in auto generated ddl file in catalog.jar is stored to the file location provided by user. If not output location is provided, store the file as schema.sql in current working directory.
- Update "get deployment" to output the deployment to deployment.xml in cwd if no output location is specified.

Add ddl/schema argument support to get command

---

tests/sqlgrammar/sql_grammar_generator.py

seed), without crashing (the python test code).

sql_grammar_generator.py: fixed to allow using --seed= (i.e., a blank

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/Benchmark.java

that the System Tests can run without being bothered by ENG-12093 and
ENG-12092.

Benchmark.java: temporarily change txnid2's default swapratio to 0, so

---

src/frontend/org/voltdb/plannodes/MaterializePlanNode.java
tests/frontend/org/voltdb/regressionsuites/TestSqlDeleteSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlInsertSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpdateSuite.java

Mike A suggested this one line change via e-mail and sent these junit test tweaks so that tests do not succeed by relying on column indexes selected by happy accident.
This presented as a SQL ERROR in manual internal testing but generally had cluster crashing potential.

Mike A's fix for SQL ERROR, possible ceash, on INSERT VALUES w/ subquery

---

src/frontend/org/voltdb/HTTPClientInterface.java
src/frontend/org/voltdb/utils/HTTPAdminListener.java
tests/frontend/org/voltdb/TestJSONInterface.java

There are currently 3 HTTP endpoints that handle and process JSONP. They are /api/1.0, /deployment and some of its subresources, and finally /profile.
With this change, /api/1.0 will check JSONP value for "jsonp" key in both headers and parameters, while /deployment and /profile will check it in parameters. If the JSONP value is invalid (only alphanumeric, underscore and dollar sign are allowed), a response with status code 400 and message "Invalid jsonp callback function name" will be sent back.
Added a test case for this in TestJSONInterface.
Also fixed a small bug: for /deployment/users resources, if there is no user, an empty JSON list string should be returned instead of an empty string because an empty string is not a valid JSON string.

ENG-12020: Sanitize JSONP parameter to prevent cross-site scripting

---

src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

And a trivial Pro PR: https://github.com/VoltDB/pro/pull/1787

ENG-12092, fix wrong swap on table for stream indexing when calling @SwapTables along with an onging index snapshot.

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/Benchmark.java

so that the System Tests can test @SwapTables again.

Benchmark.java: change txnid2's default swapratio back to 0.50 (from 0),

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ImporterServerAdapterImpl.java
src/frontend/org/voltdb/InternalAdapterTaskAttributes.java
src/frontend/org/voltdb/InternalClientResponseAdapter.java
src/frontend/org/voltdb/InternalConnectionContext.java
src/frontend/org/voltdb/InternalConnectionHandler.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/importer/AbstractImporter.java
src/frontend/org/voltdb/importer/ImporterServerAdapter.java
tests/frontend/org/voltdb/TestImportSuite.java

Instead of using a global internal adapter for all importer
transactions, create one adapter for each partition lazily. This
relieves the contention on the ClientInterfaceHandleManager because the
usage will be bound to the same thread for each partition.
The adapters are created when partition leaders are elected so that it
can also pick up elastically added partitions.

ENG-11662: Relieve internal adapter lock contention.

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InternalConnectionHandler.java
tests/frontend/org/voltdb/TestJSONInterface.java

Rejoining node won't get notified of partition master promotions. The
internal adapters have to be created during initialization. They are now
created in the constructor of ClientInterface and later can be added if
not exist during master promotion.

ENG-12139: Fix internal adapter initialization error.

---

src/frontend/org/voltdb/export/ExportDataSource.java

On @UAC or during shutdown, some of the export decoder executor services
may be shutdown when the buffer is polled. Setting the buffer on the
future will throw RejectedExecutionException in this case because the
listener tries to schedule itself on those executor services. It has to
catch the exception and properly discard the containers that was just
created to avoid leaking memory.

ENG-12144: Fix memory leak on @UAC in export.

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InternalConnectionHandler.java

Create the per-partition adapters before creating the ClientInterface
mailbox. Once the mailbox is created, the master promotion notification
may be called before the ClientInterface is fully constructed. What a
mess!

ENG-12147: Fix race in internal adapter creation.

---

src/frontend/org/voltdb/RealVoltDB.java

The Consumer was not started on rejoined hosts because they were only initialized on create and recover. In addition, as part of initialization, the DR code determines whether this cluster is the original data source, and if not, it verifies that there are valid site trackers for the data source cluster (implying that the snapshot completed). However, for rejoin, this check would be done on the Site thread causing a deadlock. Therefore, Starting the DR services is now always done on a seperate executor thread.
Note that this is the periodic work thread, which will block until the site trackers are returned. Therefore, scheduled work will also block until DR initialization completes.

ENG-12128:

---

tests/frontend/org/voltdb/regressionsuites/TestBooleanLiteralsSuite.java

This fixes ENG-12167, in which a test is failing 75% of the time in memcheck mode.
Memcheck mode makes row order of result sets less stable.

Fix test so that it passes in memcheck (row order issue)

---

tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

added Window functions (RANK, etc.), and associated syntax; 
expanded the use of aggregate functions, used as Window functions and
otherwise; 
expanded the use of sub-queries, scalar and otherwise.
And multiple minor changes:
added very occasional use of nonexistent table, view, and column names; 
added symbols for byte columns and expressions, and use them as args for
the REPEAT function, to avoid ENG-12118; 
improved UPDATE statements, to get the column types right most of the
time; 
expanded boolean expressions, to include multiple AND or OR, optionally
using parentheses; 
fixed USING clauses, by adding parentheses; 
added EXISTS and IN clauses; 
removed the nonexistent % operator (SQL has the MOD function, but no
remainder op); 
removed the use of CONCAT with only one argument, which …

sql-grammar.txt: 3 major changes:

---

src/frontend/org/voltdb/types/TimestampType.java
tests/frontend/org/voltdb/TestVoltType.java

The test TestVoltType.testTimestampToStringBeforeEpoch failed if it was
run on a machine whose timezone was not America/New_York.  This change
allows the user to choose a SimpleDateFormatter for the toString method,
which lets the test be time zone independent.
This is not actually the most general one could do, but it's better than
before.

Make it possible to format TimestampType independent of time zone.

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java

If the producer is not initialized before the cluster is up, binary logs can arrive before DR is ready and Producer stats are also not initialized early enough. Because of this we reverted back to starting the producer and consumer synchronously for all paths (create, recover and rejoin). However, now we do the sync snapshot completion check once in the initialize path of the gateway and prevent the consumer from starting. The consequence of this is that the producer will be initialized even if we determine later that the sync snapshot was never delivered.

ENG-12172:

---

src/frontend/org/voltdb/RealVoltDB.java

If there is no command log or snapshot data to recover from when
restarting the database, print an INFO level message to the log file and
the console indicating that the database will start empty.

ENG-12094: Add log message when restarting database with no command log.

---

tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexMaterializedViewSuite.java

I should have used `isMemcheckDefined()` instead of `isValgrind()`.
The test is sensitive to how tuple blocks are allocated with regards to truncate and views.  See the older pull request for more details:
https://github.com/VoltDB/voltdb/pull/4355

ENG-12132: Test failing, now in memcheck-nodebug mode

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java

Always update the complete count before the outstanding count so that
when drain() returns, the complete count is accurate.

ENG-11711: Fix BulkLoader accounting race.

---

tools/licensescheck.py

where, when it checks both Community and Pro, the return code pays no attention to failures in Community. This also resolves an edge case where multiples of 256 errors could result in a return code of 0.

ENG-12168 fix a bug in the 'licensescheck' script

---

build.xml
tools/kit_tools/build_kits.py

**Do not squash merge. This will enable us to revert any part individually in the future.**
Removed build and build_kit support for the following builds:
1. voltdb-tools-n.n.tar.gz. This contained voltadmin and vdm. This has not been available for download for years.
2. voltdb-client-java-n.n.tar.gz.  The client is available in the server kit and also in maven. We have not had a separate java-client download for years.
3. .rpm and .deb.  This was removed from the download site at least a year ago.
4. voltdb-ent-n.n.zip.  This used to uploaded to a partner site and needed to be .zip.  That partner site now just has a link, so no .zip is needed.
With this change, the official kit_build job will only make the following:
- voltdb community, pro and enterprise kits
- mavenjars directory that …

ENG-12229. Stop building kits we no longer need.

---

src/frontend/org/voltdb/RealVoltDB.java

During validation of start action, there is a rare window where the node can be disconnected in time frame where it was reported it exists to when it queried for data and currently this gets reported at error level. This showed up in rejoin system tests once where nodes were getting killed in cluster. After logging it at error level, the cluster was operational though test failed due to msg seen at error level. Dropping the severity for the msg at which it gets logged for this particular case. Updated logic to have try/catch block around the accessors which generate the handled exception cases.

Update message severity level during validation of start action

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/Scheduler.java

Change the static variable defined in RealVoltDB to member variable.
Some local cluster unit tests prefer using server thread instead of a voltdb process.
The value of static variables defined in VoltDB code will be carried over to next
unit test, which create many undesired effect. This bug is one of them!

Eng 12113 fix flaky update logging unit test.

---

build.py
buildtools.py
src/ee/common/ValuePeeker.hpp
src/ee/common/executorcontext.cpp
src/ee/plannodes/abstractjoinnode.cpp
src/ee/plannodes/abstractplannode.cpp
src/ee/plannodes/abstractscannode.h
src/ee/plannodes/aggregatenode.h
src/ee/plannodes/deletenode.h
src/ee/plannodes/indexcountnode.h
src/ee/plannodes/indexscannode.h
src/ee/plannodes/limitnode.h
src/ee/plannodes/materializenode.h
src/ee/plannodes/mergereceivenode.cpp
src/ee/plannodes/orderbynode.h
src/ee/plannodes/projectionnode.h
src/ee/plannodes/swaptablesnode.h
src/ee/plannodes/windowfunctionnode.h
tests/ee/common/PerFragmentStatsTest.cpp
tests/ee/executors/OptimizedProjectorTest.cpp
tests/ee/plannodes/PlanNodeUtilTest.cpp
tests/ee/test_utils/LoadTableFrom.hpp
tests/ee/test_utils/plan_testing_baseclass.h

This makes the EE more robust if we happen to get an invalid plan from Java.  If a plan node destructor fired before a plan node is completely initialized (due to wonky JSON), then we were trying to call delete on uninitialized pointers.
I'll make another pull request to fix the bogus plan.

ENG-12105: Fix memory issues in C++ unit tests

---

build.xml

<pathelement location='${build.instr.dir}' />
which was leftover from Peter’s removal of Emma, and was breaking SqlCoverage.

build.xml: the removed line:

---

tests/testverbs/voltverbstest.py

Add tests for "voltdb get" + deployment | schema | classes.
Hard to fit into existing structure since arguments are positional, not arg/value used with other voltdb verbs so there are new methods to handle the "irregular" case.

Eng 11692 voltdb verbs

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

* Use a set of Pair<String, Long> instead of two parameters to make equality check more straightforward and code clearer.
* Add a variant of createLocalCluster() helper function to allow manual specification of callingMethodName, which is used in the output file name.
* Add a helper function to create a client that connects to the admin port of the cluster, which is used to perform some tasks when the cluster is paused.

ENG-12008: DR consumer streams should pause on swap table event and unpause on local swap table callback

---

lib/python/voltcli/voltadmin.d/dr.py
src/ee/common/types.h
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_SP.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
src/frontend/org/voltdb/utils/SQLCommand.java

Pro Side: https://github.com/VoltDB/pro/pull/1790
This PR only handles the case when target cluster haven't finished applied syncSnapshot.
This guarantees the target cluster won't send any binary logs to any cluster in the mesh. So it guarantees there won't be any divergences in the remaining clusters.
The way to detect syncSnapshot haven't applied is by looking at Producer Cluster's Consumer Side partitionReceivers' existence. (Since we on-demand create them.) As well as site's local applied tracker.(Mainly for the recovery case when the target cluster is also down).
changes including following
* executing global reset if clusterId == -1 **or** there's only one consumerCluster Connected
* for single reset, if force == 0, it will pause and check **all** bufferReceivers for whether …

ENG-10627-preSnapshot: reset single DR

---

src/ee/executors/seqscanexecutor.cpp
src/frontend/org/voltdb/compiler/MatViewFallbackQueryXMLGenerator.java
src/frontend/org/voltdb/compiler/MaterializedViewProcessor.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/planner/TestPlansInExistsSubQueries.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java

I fixed an issue in simplifyExistsSubqueryStmt that caused a non-sensical statement to be generated: a groupless agg with passthrough columns.  This was causing the EE to crash.  The fix was to be less aggressive in simplifying exists subqueries.  In particular I removed code that attempted to do away with aggregation altogether.  There are ripple effects to what the old code was doing that seem really difficult to get a handle on.
I encapsulated ParsedSelectStmt.m_groupByColumns and m_distinctGroupByColumns in order to aid my debugging.

ENG-12204: Fix issue with EXISTS simplification

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py
src/frontend/org/voltdb/sysprocs/CheckUpgradePlanNT.java

Now these are following prerequisite checks:
1. Original cluster is licensed for XDCR.
2. Original cluster is running in "xdcr" role.
3. New kit is >=7.2 and is within 1 major release of running version, vice versa for downgrade.
4. Running version is >= 7.2
5. Create warnings if not all the tables are DR tables.

Eng 12296 add prerequisite check to plan_upgrade

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py
src/frontend/org/voltdb/sysprocs/CheckUpgradePlanNT.java

1. In multi-cluster case, plan_upgrade doesn't generate DR reset command for the new cluster (the one to be upgraded).
2. In multi-cluster case, plan_upgrade sometimes choose the wrong host to kill, which StopNode reject to do because it violates K-safety.
3. "not a DR table" Warning also applies to view table, which should be skipped.
4. add a step to disbale DR connection in stand-alone cluster upgrade.
5. reorder steps to seperate prepare and upgrade phase.

Eng 12359 fix several bugs found in manual testing.

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py

A supplement to https://github.com/VoltDB/voltdb/pull/4471, add another two minor fixes.
6. fix a compatibility issue for older version of python (pre-2.7)
7. In single cluster case, add workaround to disable DR connection after upgrade.

ENG-12359, fix compatibilty issue for older version of python (pre-2.7)

---

src/frontend/org/voltdb/export/ExportDataSource.java

There is a race condition during export generation rolling that causes buffers
to not be discarded because the generation signalled done when it's not fully
drained yet. This may cause data loss, or memory leak at the very least.
I added some code to record the stack traces of when a generation signals done
and crash the local node if a buffer was created after that. Hopefully, this
will give us some insights into what is racing.

ENG-12282: Add debug message for export generation rolling.

---

lib/python/voltdbclient.py

Using voltdbclient.py to call stored procedure, I noticed that I get a error in some case.
Usually we use java client program to call stored procedures in our system.
To make a test our stored procedure easy, I have tried to write a script by python.
I got error result sometimes, not always.
Compared to voltdb-client-cpp code, I got idea some sequence mismatch on reading VoltTable from buffer in voltdbclient.py
I summalized that I have faced to situation below.
- The stored procedure on this case, written by java, returns 4 table.
- In the error,the first table returns no record.
- The table's size on wire-protocol message is about more 500 byte by tracing.
- In the timing voltdbclient.py complete to read first table, the buffer pointer do not indicate next table header.
- (It seems no …

Patch for voltdbclient.py

---

tests/sqlcoverage/sql_coverage_test.py

connect/create client" error message, to make it easier to track down
problems like ENG-12319 (which was a ports problem - the 3021 and 7181
ports on the volt12i-U14.04 Jenkins machine were being used by an old
process).

sql_coverage_test.py: better diagnostics to go with the "Unable to

---

src/frontend/org/voltdb/AdmissionControlGroup.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/dtxn/LatencyHistogramStats.java
src/frontend/org/voltdb/dtxn/LatencyStats.java
src/frontend/org/voltdb/dtxn/LatencyUncompressedHistogramStats.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java
third_party/java/src/org/HdrHistogram_voltpatches/AbstractHistogram.java

Rename current @Statistics LATENCY to @Statistics LATENCY_COMPRESSED.
Add new, to-be-documented @Statistics LATENCY that provides human readable latency statistics that are updated every 5 seconds.
Currently git is mangling the rename-and-replace of LatencyStats.java, which moved to LatencyHistogramStats.java. I may need to find a more VCS-friendly approach.
In Pro I updated a single JUnit to reflect the name change, but did not modify code or add tests there.
https://github.com/VoltDB/pro/pull/1867/files

Eng 12082 human readable latency stats

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/iv2/Site.java

* Make populateEmptyTrackersIfNeeded a method in ConsumerDRGateway interface as now it will be called on producer side
* Add API to VoltProjectBuilder to set DR consumer connection to be enabled/disabled in deployment file
* Do not tolerate lack of tracker in site DR idempotency check anymore as there will always be dummy tracker for existing cluster for the joiner cluster even if the leader cluster has DR consumer connection disabled and dummy trackers will be populated in the consumer clusters if needed when consumer goes into RECEIVE state for other replication pairs

ENG-12179: Populate dummy tracker even when consumer gateway is disabled

---

tools/kit_tools/upload_kits.py

Fabric file for uploading kits.  To be use in the kit-tools-upload-to-website job.
Sample usage:
`fab -f upload_kits.py -H <download-site> upload_kits:7.2,upload_type=minimal`
This has 2 upload types are full and miminal. Full will upload all kit types. Minimal is for patches and hotfixes and will only upload the enterprise kit.
Please squash-merge this.

ENG-12230 Kit upload script

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/AsyncCompilerAgentHelper.java
src/frontend/org/voltdb/compiler/CatalogChangeResult.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java

Whenever there is a catalog change, the diff engine will generate the diff commands. However, only some of the diff commands are applicable to EE catalog, others will be ignored. 
Instead of triggering a EE JNI call with unnecessary diff commands, the diff engine will check whether the catalog change requires a EE JNI call or not. And we pass this flag to update catalog.

Eng 12425 ignore ee diff commands if possible

---

src/frontend/org/voltdb/PlannerStatsCollector.java

Trivial change from INTEGER to BIGINT for 3 columns of PLANNER stats that can grow larger than INT max value with enough @AdHoc invocations (it happened at 2 customers already).

ENG-9346: use BIGINT for cache hits and misses which could exceed INT max value

---

src/frontend/org/voltdb/AbstractTopology.java

assign masters more evenly among the nodes during cluster startup with missing nodes.

ENG-12280 improvement of partition master assignment  with missing node startup

---

tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuitePlannerStats.java

Fix 100% failure of TestStatisticsSuitePlannerStats by updating the test to reflect the promotion of several statistics from INTEGER to BIGINT.

ENG-9346 fix junit

---

tests/geb/vmc/server/run_voltdb_server.sh

org/voltdb_testfuncs/IntFunction.class to the jar file, since this is
now required by fullDDL.sql (and therefore by the GEB/VMC's
FullDdlSqlBasicTest).

run_voltdb_server.sh: in GEB tests of the VMC, added the new

---

src/frontend/org/voltdb/NonVoltDBBackend.java
src/frontend/org/voltdb/PostgreSQLBackend.java
tools/killstragglers.sh

add parentheses after NOW when it's a separate word (presumably the NOW
SQL function), rather than in the middle of a word (e.g., in a randomly
generated VARCHAR value).
NonVoltDBBackend.java: modified to limit the number of messages that are
printed about caught exceptions (in a few cases, the console was swamped
with them).
killstragglers.sh: added code to kill any processes that are using any
of the usual VoltDB ports (3021, 7181, 21211, 21212, 8080, 5555).

PostgreSQLBackend.java: modified the nowQueryTransformer, to strictly

---

src/frontend/org/voltdb/client/Client.java

Leave UpdateClasses helper methods intact.

ENG-12374: Deprecate Java client's UAC helper methods.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/DeterminismHash.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java

Also contains two trivial optimizations:
1. In `DeterminismHash`, remove the use of parameter hash. This because we only care about whether two hashes of parameter are the same, not the actual hash.
2. Always return the overall hash to client response, even when there is no per-statement hash.   
Change-Id: I0e63326e59b31361e643aa0bf8b808331fd8aa9c

ENG-10599, show additional information about plan in hash mismatch error message.

---

lib/python/voltcli/voltdb.d/init.py
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
tests/frontend/org/voltdb/TestInitStartAction.java
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/GetGreetingBase.java
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/GetGreetingCaseInsensitive.java
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/GetGreetingExactMatch.java
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/LoadGreetings.java
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/ddl.sql
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/greetinglist.txt
tests/testprocs/org/voltdb_testprocs/fakeusecase/greetings/package-info.java
tests/testverbs/voltverbstest.py

You can now use 'init --classes' when a base class exists.
If --schema is supplied to init but the schema does not use all of the available classes and/or resources, the unused resources are now in the catalog for later use.
Arguably this is just a workaround for the base class issue - VoltCompiler still isn't smart enough to resolve all the dependencies. We just ensure the output staged-catalog.jar contains everything the user's jar did.
The 'fake use case' in the test is not currently 100% functional as a stand-alone app, but it does contain:
- base classes
- utility classes (package-info.java)
- non-class artifacts
This means that the JUnit test is able to cover these cases regardless.

ENG-12504 make 'init --classes' compile using the specified jar file rather than simply adding it to the CLASSPATH.

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDML.java

The fix for this bug is disabling some reference replacement code in HSQL.
The team had the concern that it may affect the answers we collect from the HSQL backend, we will see what the Jenkins say. My current guess is it won't.
Manual test completed:
* TestGroupByComplexMaterializedViewSuite
* TestMaterializedViewNonemptyTablesSuite
* TestMaterializedViewSuite
* TestStreamView

Fix ENG-11832 error in UPDATE stream view

---

tests/frontend/org/voltdb/TestInitStartAction.java

Fix intermittent test failure due to tests getting run out of order. One test assumes there is no voltdbroot in the directory, which was fine when there was only one test but has not been true since 'init --schema' was added.

ENG-12560 fix a JUnit that fails intermittently

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/settings/NodeSettings.java

Added print out message when the properties file is empty or does not contain necessary field. This resolves the print out message problem when the path.properties is empty in some case.

Eng 12112 empty path.properties file

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/licensetool/LicenseApi.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/MockVoltDB.java

Now it prints "pro" when it's a pro trial.
No license schema updates.
Pro pull: https://github.com/VoltDB/pro/pull/1899
JIRA Ticket: https://issues.voltdb.com/browse/ENG-11682

ENG-11682: Add more definitive pro trial license handling.

---

src/frontend/org/voltdb/RealVoltDB.java

Improvement: Crash the database directly in RealVoltDB.java when any exception is caught. Print out the fatal error message.

Eng 12112 missing properties file error message

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
src/frontend/org/voltdb/iv2/Site.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

- Send catalog update events even if DR tables are deleted.
- In XDCR mode, DR schema compatibility check should fail if the producer side deleted DR'ed tables.

ENG-11091:

---

tests/frontend/org/voltdb/planner/TestDeterminism.java
tests/frontend/org/voltdb/planner/testplans-determinism-read-only.sql

The problem has already been addressed in various previous commits. The non-deterministic warning is checked in summarizeSuccess() method and checks if the query is read-only or not.
This PR adds a test method for checking the output of summarizeSuccess() and see if any unwanted warning is given for any non-deterministic read-only queries.

Eng 5532 read-only procedure non-deterministic no warning

---

src/frontend/org/voltdb/PostGISBackend.java
src/frontend/org/voltdb/PostgreSQLBackend.java

connection to the "permanent", "postgres" database is really closed, and set to null; and to save the System.gc() until the end.
PostGISBackend.initializePostGISBackend(): just tweaked by reordering it to be like PostgreSQLBackend.initializePostgreSQLBackend(), by having a separate check as to whether m_permanent_db_backend is null, and putting the try/catch around the whole thing.

PostgreSQLBackend.shutdown(): just tweaked to make sure that the

---

src/frontend/org/voltdb/utils/CSVLoader.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java

None of our command line arguments are mixed case, except the short names that can be a single uppercase character. Otherwise, the options are all lowercase. So I changed "--characterSet" to "--charset"

ENG-12450 fixed command line naming convention conflicts

---

src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/DumpPlanThenExitMessage.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionAggregate.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionOrderBy.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionCustom.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQLInvoked.java
src/hsqldb19b3/org/hsqldb_voltpatches/Session.java
src/hsqldb19b3/org/hsqldb_voltpatches/SubQuery.java

When HSQLDB parse the sql expression, it uses a hash map to cache expression ids it has already computed. But it uses the hash code of object instead of the object itself as the key, which is not guaranteed to be unique for different instances. In some rare cases, this will cause hash key collision which let the SQL parser returns incorrect columns for values to be inserted into the table.

Eng 11957 fix hashmismatch backportv5.8

---

tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/compiler/TestProcCompiler.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestMultipleOuterJoinPlans.java

There are two categories of errors.  The first is TestAdHocPlans,
TestAdHocQueries and TestProcCompiler.  In each of these cases we make
progressively larger SQL strings, with more complicated expressions
until we make one that's big enough that it breaks the parser.  We then
declare victory.  The second class is TestMultipleOuterJoinPlans.  It
seems that the hash collision problem fixed in voltdb commit
4a7020630c047eb5a16c1005f61a99e6aab83ba7 caused an expression to be
hashed differently, which caused an expression to be corrected.
https://issues.voltdb.com/browse/ENG-12683

Fix up some junit test failures.

---

src/frontend/org/voltdb/client/ConnectionUtil.java
src/frontend/org/voltdb/client/Distributer.java
tests/frontend/org/voltdb/client/TestDistributer.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java

Time out authentication on the client side if it takes longer than the
connection timeout setting in case the server dies or the connection is broken
during the authentication process. It is governed by the same connection timeout
setting specified in the ClientConfig.
If authentication times out, it throws an IOException.

ENG-12663: Add authentication timeout to the Java client.

---

src/frontend/org/voltdb/compiler/PlannerTool.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java
tests/testprocs/org/voltdb_testprocs/updateclasses/TestProcWithSQLStmt.java

One of the UpdateClasses optimizations skips HSQLDB compiler reconstruction and also reuse the AdHoc planner cache underneath.
If there is any following AdHoc queries that hit the old AdHoc Planner thread, the cached AdHoc query plan that contains the catalog hash will not match the most recent catalog hash. Thus, the AdHoc query planner thread will keep replanning the work and not return to the client.
Impact:
If this is the case, any following AdHoc queries, DDL changes, deployment changes on the same node will not be executed. Queries issued on the other node can be executed successfully.
Workaround:
Node rejoin and fix the issue, but this is not a good solution.
Fixes:
1. Any non-schema changes that reuse the Hsqldb compiler should clear the AdHoc queries cache.
or
2. Update the …

ENG-12697: reset the AdHoc planner cache after UpdateClasses

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java

BulkLoader keeps track of the outstanding row count and uses it in the drain()
method to make sure everything is processed. Users can also use the counter
directly to track how many rows are in-flight.
If a row fails to be inserted, it will be retried automatically. If the retry
fails, too, a user-specified callback will be invoked to notify the user of the
failed row.
However, the callback is invoked after the outstanding row count has already
been decremented. In other words, a user watching the outstanding row count
could see it go to zero, meaning all rows are processed, but not see the failure
callback to be invoked even if there are failed rows. When the callback will be
invoked depends on thread scheduling, which is nondeterministic.
The outstanding row count is now updated AFTER …

ENG-12677: Fix race condition between BulkLoader accounting and callback

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/settings/ClusterSettingsRef.java

- Added debug log when cluster settings is stored in ZK.
- Fixed create persistent node method so that it doesn't exit prematurely on NodeExists exception.
- If cluster settings loaded from ZK is null, throw a better error message instead of NPE.

ENG-12573:

---

src/frontend/org/voltdb/RealVoltDB.java

If you use the new CLI without command logging, the database will pick the recover start action internally when you "start" after the first time even though there is nothing to recover from. This tricks the DR system into thinking that it can resume replication. It eventually fails of course, but it may confuse the remote cluster and generate confusing error messages.
Now before resuming replication, we check if durability is turned on and if there is a completed snapshot. If durability is off or no snapshot is found, we start fresh.

ENG-11657 do not resume replication for DR consumer if durability is off

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java
src/frontend/org/voltdb/client/VoltBulkLoader/VoltBulkLoader.java
tests/frontend/org/voltdb/utils/TestVoltBulkLoader.java

We allow creating multiple VoltBulkLoaders in the same Java client. They will
share some resources like the PerPartitionTable instances. However, when a batch
of rows are successfully loaded, the callback function only updates the
accounting in one of the VoltBulkLoaders in that batch. This resulted in some
weird values in outstanding row count and completed row count in VoltBulkLoader,
causing VoltBulkLoader.drain() to hang.
This is fixed now by updating the accounting in each VoltBulkLoader involved in
a batch with the proper count.

ENG-11823: Fix concurrent BulkLoader accounting error.

---

src/frontend/org/voltdb/compiler/VoltCompiler.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java

ENG-12772: UpdateClasses skip recompiling single-statement procedure and system procedures. Unfortunately, we clear their statements and parameters members too early.
We do have test case covering the single-statement procedure case, but the NPE exception is thrown on server side and gets caught without fatal exception. So the test case is passed even with this NPE. In this pull, we will call the single-statement procedure again after UpdateClasses and verify its procedure status to make sure everything looks OK.
This NPE bug is introduced by ENG-12027 with commit: 7c155ab93036e62e13e61516d6f5835d4dfe64cb

ENG-12772: fix the NPE during UpdateClasses

---

src/frontend/org/voltdb/DRConsumerMpCoordinator.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java

It is possible to promote the DRConsumerMpCoordinator while a restarted ApplyBinaryLogMP txn is still executing. If the promotion occurs before the restarted txn completes, the trackers used by promoted BufferReceivers will not reflect the restarted ApplyBinaryLog and DR Consumer will stop processing logs. This patch adds a loopback that does nothing to the @ExecuteTask SystemStoredProcedure. The loopback just runs on the MPI and than returns a response. If this SPI completes, it means that any restarted MP TXNs have also completed and that it is safe to inform BufferReceivers that the DRConsumerMPCoordinator is ready to resume.

ENG-11907:

---

src/frontend/org/voltdb/QueueDepthTracker.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SiteTasker.java
src/frontend/org/voltdb/iv2/SiteTaskerQueue.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerSpHandle.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java

Currently we have the following performance statistics:
- Initiator stats or latency stats (intra-cluster latency)
- Procedure stats (partition execution time)
- Command log stats
The closest to client-side latency is the initiator stats. It doesn't include the network round-trip time between the client and the server and any delay incurred on the client. The procedure stats only show the duration of the run() methods of procedures. It only accounts for the computation portion of SPs.
Looking at these stats typically gives a good idea of the cluster performance, but they are not enough to diagnose any latency issues. There is a big gap between the intra-cluster latency and the procedure execution time. They are usually magnitudes apart.
A big portion of the difference between the …

ENG-12779 Queue depth

---

build.xml

this build's off of work done previously to split up the tests to run in docker.  The former junit_other is now available to run in 4 parts, junit_other_p1 ... other_p4 . each part takes about 35 minutes to run.  the tests can also be run as one large group as junit_other.

Eng 10782 split junit other

---

lib/python/voltcli/utility.py
lib/python/voltcli/voltadmin.d/save.py

Check the column of ”RESULT“ from the returned table which tells whether snapshots were successful. If there exists a failed one, return exit code 1.

ENG-12044-Failed-Snapshot-Exit-Code

---

tests/test_apps/kafkaimporter/client/kafkaimporter/KafkaImportBenchmark.java
tests/test_apps/kafkaimporter/kafkaloader10-SSL.props

Changes to setup SSL end to end for the kafkaloader test.
Community side changes:
- add SSL option and setup to Java client
- add SSL properties file for the kafkaloader
- trim obsolete properties from Kafka 10 props file

Eng 12787 kafkaloader ssl

---

src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/SiteTaskerQueue.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/TickProducer.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerSpHandle.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java

If a stored procedure takes a long, long time in Java code, there was nothing in the logfile to indicate that a procedure is doing too much Java. There are only warnings for long-running MP (possible mp deadlock) or long SQL execution times.
This is a watch on the sites to show that there is a long-running txn. A warning is generated if no task was polled from the partition queue in the last {X} seconds, where {X} is configurable from deployment file with default value 10 seconds.

Eng 12769 queue depth with log

---

src/ee/executors/indexscanexecutor.cpp
src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/executors/seqscanexecutor.cpp
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
tests/frontend/org/voltdb/regressionsuites/TestInsertIntoSelectSuite.java

Get tuple schemas right in the scan executors.
The tuple schema handling was incorrect in the scan executors for inline insert into select.
We have three interesing schemas.  One is the schema of the scanned input table, one is the
schema of the insert target table and one is the schema of the derived table of the select
statement.  The latter comes from the expressions in the select list.  We were using the
schema from the target table in the insert statement where the last was wanted.  This
caused wrong answers for sequential scan and a server crash for index scan.
I don't know why this was not caught by the unit tests. If the schema of the scanned
table is not exactly like the schema of the insert's target table something will go wrong.
I think this only affects inline insert.  Without …

Eng 12834 inline insert crash

---

src/frontend/org/voltdb/plannodes/TableCountPlanNode.java
src/frontend/org/voltdb/plannodes/TupleScanPlanNode.java
tests/frontend/org/voltdb/TestAdhocDropTable.java
tests/frontend/org/voltdb/planner/TestGetTablesAndIndexes.java
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java

We weren't reporting the set of tables that are used correctly for plans that have a TABLE COUNT node.  As a result it was possible to drop a table that has a plan with a TABLE COUNT node on that table.

Fix dependency checking for TABLE COUNT plans

---

build.xml
tools/meshmonitor/README.md
tools/meshmonitor/build.xml
tools/meshmonitor/meshmonitorhelper.sh
tools/meshmonitor/src/MeshMonitor.java

Add meshmonitor to the kit in the tools/meshmonitor directory.
When put in the distribution,  this directory will contain
1. meshmonitor.jar which can be put on the machines that user wants to run it on
2. meshmonitorhelper.sh which will user to create the command-lines to run on all test machines
3. README about what it does and how to use it.

Eng 4928 - Add meshmonitor to kit

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java

The errors occurs when VoltDecimalHelper fails to deserialize decimal from a string and throws out a RuntimeException. This exception is not caught in PerPartitionTable.buildTable(), so it will eventually propagate to the console. Also, m_outstandingRowCount is not properly updated, which is why the loader doesn't stop running.

ENG-12778-CSVLoader-Hang-On-Error

---

src/frontend/org/voltdb/importer/ImportManager.java

This is intended as a low risk fix for a crash scenario when the importer sees a UAC during pause and then resumes. It does not eliminate the root cause scenario or resolve importers starting when the database is paused, but the database can now continue into a valid state without crashing.

ENG-12902 resolve importer IllegalStateException by forcing importer into a valid state.

---

tests/frontend/org/voltdb/regressionsuites/TestQueryTimeout.java

Fix authentication credentials in debug.
When this is executed in debug it doesn't actually do the tests.  There is a test for isDebug() and isValgrind() which short circuits any actual testing.  But this also short circuits setting the authentication credentials.  Before, since we had started up a server already, the test couldn't create a client to shut the server down cleanly.  This caused the test to throw an exception and fail.
https://issues.voltdb.com/browse/ENG-12481

Eng 12481 test query timeout

---

tests/test_apps/schemachange/src/schemachange/SchemaChangeClient.java

a one line change to prevent views from being created after the table has data.

only create views before we have data in the tables.

---

tests/test_apps/nptxn-perf-benchmark/client/np/NPBenchmark.java
tests/test_apps/nptxn-perf-benchmark/run.sh

There should be no more conflicts with the existing parameter names.

NP Txn benchmark: changed to a non-conflicting parameter name for clients count.

---

src/frontend/org/voltcore/agreement/AgreementSite.java

I switched to use the second tryLogForMessage() method which includes parameter in the message format.

ENG-12169 fix the ratelimitlogger error

---

CONTRIBUTING.md

Having a CONTRIBUTING.md file in the root of the repository will cause Github to show a link to it on the page when contributors are opening a pull request. See: https://github.com/blog/1184-contributing-guidelines
This is mostly boilerplate I cut and pasted from emails to contributors, our wiki guidelines, and other examples.  Edits welcome!

add contributing guidelines for pull requests

---

src/frontend/org/voltdb/HTTPClientInterface.java
src/frontend/org/voltdb/InternalConnectionHandler.java
src/frontend/org/voltdb/utils/HTTPAdminListener.java

If one calls system procedure from VMC, the INITIATOR stats will show correct ip address of the caller, rather than "+!_InternalAdapter_!+"

ENG-12379-Log-Addr-Match-With-Stats

---

build.xml
tools/meshmonitor/build.xml

{build} is now passed in by the voltdb build.xml. I also removed some extraneous environment stuff from meshmonitor's build.xml.

ENG-12969. Fix meshmonitor build when build= is not default.

---

lib/python/voltcli/checkconfig.py

ENG-12919. Check that tcp_retries2 is at least 8, which is approximately 100 seconds.
The default is 15 and the man page say that 8 or higher is recommended.  ENG-12728 is the
linked doc bug, recommending we mention why this setting shouldn't be too low.

ENG-12919. Add check for tcpretries2 setting.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InternalClientResponseAdapter.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LightweightNTClientResponseAdapter.java

Use internal NT-Procedure connection handler to invoke NT-Procedures and track the call backs. Otherwise the NT-Procedure callAllNodeNTProcedure API ends up keeping all the reference of NT-Procedure internal invocations and eventually hit OOM.

ENG-12968 NT-Procedure memory leak fix

---

src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/utils/TestSqlCommandParserInteractive.java

command lines use a special prompt when you are on a continuation line
For sqlcmd,  we add two few spaces at the beginning of the prompt to indicate a multi-line statement definition is in progress
so for sqlcmd continuation prompt -
two spaces, line number, angle bracket, space.

Eng-12849-sqlcmd-continuation

---

src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/TableCatalogDelegate.hpp

The delta table used in joins in materialized views used to inherit the "DR" catalog attribute from its source table. If the source table is a DR table, so will the delta table, which essentially records all operations on delta table into the DR stream, which is undesirable because 1) it breaks DR binary log structural constraint in case of snapshot restore and 2) it causes the consumer cluster to diverge from the producer cluster.
To fix this, delta tables should always be set as non-DR tables.

ENG-12985: Delta tables used for joins in materialized views should never generate DR records

---

src/catgen/in/javasrc/CatalogType.java

CatalogTypeReference is not thread safe, during UAC both Site thread and Ad Hoc Planner thread may access the same object.
Change-Id: I1f4c8ffa559a24f40ffd0644daa20d4de62f3ebe

ENG-13031, fix NPE found during extensive UAC test.

---

src/frontend/org/voltdb/SQLStmtAdHocHelper.java
src/frontend/org/voltdb/VoltProcedure.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/ReadMPInProcAdHoc.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/ReadSPInProcAdHoc.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateBaseProc.java
tests/testprocs/org/voltdb_testprocs/adhoc/executeSQLMP.java
tests/testprocs/org/voltdb_testprocs/adhoc/executeSQLMPWRITE.java
tests/testprocs/org/voltdb_testprocs/adhoc/executeSQLSP.java
tests/testprocs/org/voltdb_testprocs/adhoc/executeSQLSPWRITE.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/querytimeout/AdHocPartitionReadOnlyProc.java

Moved inside SQLStmtAdHocHelper where some other stuff is "public" but hidden from users.
Tests updated to new location. No functionality changed, just significantly reduced the visibility of a deprecated API.

ENG-12812: Hide voltQueueSQLExperimental from the visible procedure API.

---

README.md
examples/uniquedevices/deployment.xml
examples/voltkv/deployment.xml
examples/voter/deployment.xml
examples/windowing/deployment.xml

1. Deleted deployment.xml files that aren't used and are confusing.
2. Modified VoltDB description in top-level readme slightly.
3. Added section to readme about commercial editions.

ENG-12810 example cleanup + primary readme clarification

---

src/ee/common/executorcontext.cpp
src/ee/execution/VoltDBEngine.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/ExecuteTaskUndoGenerateDREventAction.h
src/ee/storage/persistenttable.cpp
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/ParameterSet.java
src/frontend/org/voltdb/iv2/Site.java

This PR includes work for both ENG-12512 and ENG-12732. It enables elastic add to happen on DR producer cluster while DR is active. In this first phase, it cannot safely replicate producer cluster DR table changes before elastic add finishes yet, therefore it's not really useful yet as elastic add can take a long time. For now, you have to issue new transactions on DR table on producer cluster after elastic add has finished.
It handles DR_ELASTIC_CHANGE event on DR consumer side and adds partition buffer receivers for new producer partitions, it also makes sure consumer will recover partition buffer receivers and proceed correctly in case that any consumer cluster node fails during @ApplyBinaryLogMP for the DR_ELASTIC_CHANGE event.

ENG-12732: DR consumer must add new partition receivers and update partition count on the consumer side

---

src/frontend/org/voltdb/parser/SQLParser.java

The command "file -inlinebatch EOB" failed interactively.  This is
because we create context to remember the name of the input file.  But
an interactive command execution has no input file, so this context is
null.  The NPE is not handled properly.
I don't actually know how to test this other than manually.  The problem
does not show up in sqlcmdtest, since this input is not interactive.

Fix interactive inline batch bug.

---

src/frontend/org/voltdb/NTProcedureService.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/ProcedureStatsCollector.java
src/frontend/org/voltdb/SiteStatsSource.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSource.java
tests/frontend/org/voltdb/TestNTProcs.java
tests/frontend/org/voltdb/TestVoltProcedure.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestProcedureStats.java

During schema change, Site thread starts to update all the related data structures, including clearing the stats sources in StatsAgent class, but there is a race window that in the meantime StatsAgent thread is iteratoring the stats sources to response a statisticss request. Deleting the procedure statisticss source while StatsAgent thread is iteratoring may fooled this thread to think now is in startup time and thus it's better to yield CPU for a little while and retry later, which in current case is hang forever.
ENG-11743 introduced this race window, it is partially reverted because we no longer need to keep @UpdateCore stats during schema change.

ENG-13039, partially revert ENG-11743 to fix a race condition that could leads to StatsAgent thread hang forever.

---

src/frontend/org/voltdb/parser/SQLLexer.java
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java
tests/frontend/org/voltdb/TestAdhocWithOnlyComment.java
tests/frontend/org/voltdb/utils/TestSplitSQLStatements.java
tests/frontend/org/voltdb/utils/TestSqlCmdInterface.java

Made improvements to SQLLexer.splitStatements:
- Don't use any regular expressions
- Remove comments from output
I also added new tests, and moved some tests around.  The test `TestSqlCmdInterface` is kind of awful but having enough testing in this area is important so I am loathe to remove it.  I added a bunch of tests to `TestSplitSQLStatements`.

Fix issues in multi-stmt create procedure branch

---

src/frontend/org/voltdb/DeferredSnapshotSetup.java
src/frontend/org/voltdb/DevNullSnapshotTarget.java
src/frontend/org/voltdb/SiteSnapshotConnection.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/TableStreamer.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/saverestore/CSVSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java

Be more careful about incorrectly reporting success after a snapshot. Specifically, the last reporting host could overwrite a failure with success for snapshot completion listeners such as CommandLogging. In CommandLogging's case, this could cause a trucation even though the snapshot did not complete successfully.
Make sure that any IO errors generated for a Truncation Snapshot brings down the host. Detect IO errors on table, digest, completion, and catalog files.
Add Unit test that uses hacks in table file construction to force an IO exception. Verify that this generates a crash for truncation snapshots only.
Another case was SnapshotStatus Statistics, which could report a successful snapshot if a failure occured during file open or the writing of the initial table header. This is …

Eng 13045 fail host on truncation snapshot failure

---

src/frontend/org/voltdb/export/ExportDataSource.java

Only send acks from master to replicas, never from a replica to other
replicas. This could happen when a node rejoins and drains its on-disk
generations. Other replicas don't expect to receive these acks with Long.MIN as
the USO. If the receiving replica gets promoted due to master failure, the new
master will fail to roll its generation.
All replicas will either receive the acks from the master or drain the
generations themselves.

ENG-12282: Don't send acks from an export replica.

---

src/frontend/org/voltdb/ProcedureRunner.java

After this is merged to master, the system tests can turn on DEBUG level logging for this one-time MISROUTE logger so that we may have more information if this happens again.

ENG-13046: Add WARN log for HOST logger in case of MP routed to SPI

---

tests/frontend/org/voltdb/regressionsuites/TestIndexesSuite.java

I noticed a sporadic failure in TestIndexesSuite when running the HSQL backend.  Yang says that we have looser guarantees of execution order for asyncronous calls to @AdHoc now, so that is likely the culprit.

Fix sporadic test failure by using synchronous procedure calls

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientInterfaceHandleManager.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/NTProcedureService.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
src/hsqldb19b3/org/hsqldb_voltpatches/Session.java
tests/frontend/org/voltdb/TestClientInterfaceHandleManager.java

This patch addresses two different causes of recent hash mismatch exception.
Stored procedure generates inconsistent query plans or catalog hashes on different nodes,
Stored procedure succeed on one side but failed because wrong number of parameters on the other side.
Also just for precaution, this patch reverts a previous commit that allow two NT-threads running in a single node.

Eng 13130 fix issue1 rebase

---

src/frontend/org/voltdb/messaging/Dr2MultipartTaskMessage.java

producer partition id is actually serialized in the SPI, but we have it directly in DRNormalPartitionBufferReceiver anyway, so just pass it in explicitly from `DRConsumerMpCoordinatorImpl.sendMultipartTaskMessage()` and then the constructor of `Dr2MultipartTaskMessage`

ENG-13123: Support execution of non-overlapping NP txns in DRConsumerMpCoordinator

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/BinaryLogSinkWrapper.cpp
src/ee/storage/BinaryLogSinkWrapper.h
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

We were using remote uniqueId to check if local txn was MP or not.
Fixed to use local unique id.

ENG-13229:

---

src/frontend/org/voltdb/iv2/SpInitiator.java

Only set durability listener on PartitionDRGateway if asynchronous command logging is used

ENG-13215: DR producer should treat every binary log as already durable if synchronous command logging is used

---

src/frontend/org/voltdb/types/GeographyPointValue.java

I have a question:
Does the `mul()` function also need to be deprecated?
```java
/**
* Return a point scaled by the given alpha value.
*
* @param alpha  The amount by which to scale this.
* @return The scaled point.
*/
public GeographyPointValue mul(double alpha) {
return GeographyPointValue.normalizeLngLat(getLongitude() * alpha + 0.0,
getLatitude() * alpha  + 0.0);
}
```

ENG-10247 Deprecate GeographyPointValue algebra methods

---

tests/frontend/org/voltdb/TestDeleteInExportRecoverWithView.java
tests/frontend/org/voltdb/TestExportRecoverWithView.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExportRecover.java
tests/frontend/org/voltdb/TestUpdateInExportRecoverWithView.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

When NEW_CLI=false tests doing shutdownSave are not starting with recover and thus failing.

Fix tests failing with NEW_CLI=false and doing community recover.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/utils/CatalogUtil.java

Previously, we generate DR conflicts export group in runtime if DRRole is XDCR.
This additional export configuration will be persistent to local deployment.xml after @UAC even there are no changes to the deployment.
If a user joins (or restarts) with another fresh host using original deployment file, the joining phase won't be progress as it considers the deployment is incompatible.
The solution in this PR is persistenting this additional export configuration in the init phase.

ENG-12806: add default export configuration to DR conflict table in init time

---

lib/python/voltcli/voltadmin.d/status.py

This corrects an issue introduced in v7.7 where "voltadmin status" would throw an error, but it worked correctly with -c or --continuous parameter.
I tested it manually and I no longer get the error, I get the status. I created a separate ticket for new tests to be created for voltadmin status, which will likely be for a later release.

ENG-13257: add available_hosts param to doStatus call

---

build.xml
tools/kit_tools/build_kits.py
tools/kit_tools/upload_kits.py

Community kit will now be voltdb-community-x.ytar.gz and will unpack to a directory of the same name.  I also fixed an arg-parsing bug in build_kits.py.

Eng 13210. Rename community build

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/parser/SQLLexer.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
tests/frontend/org/voltdb/TestAdhocCreateStatementProc.java

When splitting statements, we checked for keywords like "as", "begin", "case", "end" because they could change our semantics for a semicolon that we usually use to determine the end of a statement.
We used `Character.isLetterOrDigit` and `isLetterOrDigitFast` to check whether the token we checked was indeed a standalone token or a part of another token. But those two functions will return wrong answers when the tokens have "_" before or after them.
This pull request updates the functions we use so we can give right answers when underscores are presented.

Fix ENG-13271-check-as-begin-syntax

---

src/ee/storage/BinaryLogSink.cpp

Reverts VoltDB/voltdb#4950.
Probably should only add this after we branch.

Revert "ENG-13229: Adding debug stmts."

---

src/catgen/in/javasrc/CatalogDiffEngine.java
tests/frontend/org/voltdb/TestAdhocAlterTable.java

When we change the type and the size of a column at the same time and both changes are disallowed, we do not throw two separate error messages now because it will be confusing.

Fix error message for ENG-13094

---

lib/python/voltcli/hostinfo.py

If machine has multiple network interfaces, remember to add --externalinterface option in command line arguments to let voltdb know which one you are using. Otherwise voltdb would pick whatever comes first.
Change-Id: Icb28bc41fd2ed0c4192e96e41a6f3b32b3a9f2cb

ENG-13248, allow user to stop node by IP address.

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/Initiator.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SpDurabilityListener.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java

When the Consumer is shut down, due to a reset, a disable, or an ElasticAdd, the objects are not garbage collected because the references for each BufferReceiver are maintained in the Scheduler's DurabilityListener, even when new instances are started. This is fixed by unregistering the listener from the BufferReceiver's shutdown path. Note that the receivers and dispatcher are only leaked when commandlogging is Asynchronous and in a same-size cluster.

ENG-13279:

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
tests/frontend/org/voltdb/planner/TestWindowedFunctions.java

We now do not allow ORDER BY subquery. We add similar guards for ORDER BY and PARTITION BY subqueries for the window functions.
Can Andrew confirm if the message is OK?

ENG-13162 Guard window function partition/order by subquery

---

src/frontend/org/voltdb/dtxn/TransactionState.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java

When MP sites are in the middle of transaction processing, @StopNode  may cause MP deadlock and fail to stope a node. The pull request tries to terminate these transactions with a poison fragment response and then shutdown  MP Ro site pool.  and also offer a fake task to unblock sites to be shutdown.

ENG-13194  Fix failure to shutdown a node with@StopNode

---

src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/exceptions/SerializableException.java
src/frontend/org/voltdb/exceptions/TransactionTerminationException.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java

If the resources can not be released in 5 seconds while a node is being shutdown, force shutdown the node.  Change the affected transactions from RESTART to Unexpected error, transaction interrupted.

ENG-13914 node shutdown

---

src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/exceptions/SerializableException.java
src/frontend/org/voltdb/exceptions/TransactionTerminationException.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java

If the resources can not be released in 5 seconds while a node is being shutdown, force shutdown the node. Change the affected transactions from RESTART to Unexpected error, transaction interrupted.

ENG-13194 backport @StopNode fix

---

src/ee/storage/AbstractDRTupleStream.cpp
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h
src/ee/storage/streamedtable.cpp
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/DRTupleStream_test.cpp
tests/ee/storage/ExportTupleStream_test.cpp

Now allows a single extendBufferChain for defaultSize < minLength <= maxSize.
DR should allow changes where a single tuple size exceeds the default size but is less than the max size. Before this change, extendBufferChain in TupleStreamBase checked if the requested extension is greater than the default size and failed if it was, which is incorrect behavior for DR. This PR changes TupleStreamBase to support maxSize also and changed extendBufferChain accordingly.

ENG-13201:

---

src/frontend/org/voltdb/utils/CSVLoader.java

Added a --kerberos=<jaas file configuration entry id> parameter to CSVLoader. 
Example usage:
kinit someuser@DOMAIN
...
csvloader --kerberos=VoltDBClient -f some_file.csv TABLENAME

ENG-13345: Add kerberos authentication support to CSVLoader

---

src/frontend/org/voltdb/types/GeographyValue.java
src/frontend/org/voltdb/utils/PolygonFactory.java
tests/ee/storage/DRTupleStream_test.cpp
tests/frontend/org/voltdb/types/TestGeographyValue.java
tests/frontend/org/voltdb/utils/TestPolygonFactory.java

In the OGC polygon format, WKT, we represent a polygon as a counter clockwise shell followed by zero or more clockwise holes.  In S2 these are all counter clockwise, and S2 maintains the nesting relationship in a different way.  This means we need to reorder vertices in polygons to send them to S2.  In the Java GeographyValue class we represent polygons using the S2 conventions, but the constructor uses the OGC conventions.  This works alright except for the GeographyValue.add function.  This function is internal, and operates on the loops directly from the internal arrays.   Consequently, the add function does not need to reverse the order of holes.  In this commit we make sure this happens.

Eng 12926 Don't reverse hole loops.

---

src/ee/common/tabletuple.h
src/ee/storage/CompatibleBinaryLogSink.cpp
tests/ee/common/tabletuple_test.cpp

The schema of the conflict export table has changed without updating the
compatibility binary log sink code. Whenever there is a conflict using mixed
version XDCR, it fails to write the conflict and breaks replication. I brought
all the changes in the original commit that updated the schema to the
compatibility mode. The commit that introduced the change was
91a0c902d31d4830313e782403d678225a078683. See the commit message for details of
what's included.

ENG-13366: Fix XDCR conflict log in mixed version mode.

---

src/frontend/org/voltdb/jdbc/Driver.java
src/frontend/org/voltdb/jdbc/JDBC4ClientConnection.java
src/frontend/org/voltdb/jdbc/JDBC4ClientConnectionPool.java

To enable kerberos authentication for the VoltDB JDBC driver, set the JDBC property "kerberos=VoltDBClient". This will use the "VoltDBClient" configuration entry id in your JAAS file, similar to sqlcmd and java clients.

ENG-13363 Add property for kerberos authentication to JDBC driver

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/ThreadLocalPool.cpp
src/ee/common/executorcontext.cpp
src/ee/executors/abstractexecutor.h
src/ee/executors/deleteexecutor.cpp
src/ee/executors/deleteexecutor.h
src/ee/executors/insertexecutor.cpp
src/ee/executors/swaptablesexecutor.cpp
src/ee/executors/updateexecutor.cpp
tests/frontend/org/voltdb/TestTwoSitePlans.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java

PlanNodes allocate TempTables during execution. This can be problematic when making Replicated Table changes because the TempTable rows are allocated in an MP memory context but are cleaned up in the Partitioned memory context during UAC or Shutdown. To resolve this we now only assume the memory context inside the executor either before or after touching the temp table.
Also fixed another unit test that manuplates multiple engines directly by assigning the engines explicitly to threads.

ENG-12540:

---

build-importers.xml

Change from zipgroupfileset to zipfileset. 
I've verified the new build script by building with this branch and diffing the contents of the .jar files in bundles/ against the lastest master distribution build.   All files were the same except for the MANIFEST.MF files.

Eng-13373. Make build-importers.xml fail if libraries are missing.

---

tests/sqlgrammar/run.sh
tests/sqlgrammar/sql_grammar_generator.py

you to search the log (and/or console) after each SQL statement (or
other command) is issued to sqlcmd, to see which statements are causing
certain phrases of interest (e.g. NullPointerException) to appear there,
and output the result in a file(s); note that this is slow, so should
not be used routinely, only when tracking down specific, known issues;
also related options --find_files, to specify the file(s) (defaults to
existing LOG_FILES option value) and --find_number, to specify the
number of lines of the log file(s) to be checked via a 'tail' command
(defaults to 100); added a bunch of new types of ERROR to grep for in
the log (& console), including 'is already defined', 'is not defined',
and 'WARN', among others; added a small kludge to workaround ENG-13416;
modified …

sql_grammar_generator.py: added a new --find_in_log option, which allows

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/planner/QueryPlanner.java
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java
tests/frontend/org/voltdb/planner/PlannerTestAideDeCamp.java

These changes fix sporadic failures in the test TestJSONInterface which were the result of planning of multiple statements happening at the same time.  This test runs a bunch of ad hoc queries in parallel with catalog updates, and so it caused a failed assertion on the expected value of a static variable used in planning, `ParameterizationInfo.curParamIndex`.
The `QueryPlanner` method `plan` was only invoked serially, but the method `parameterize`, which is called for ad hoc planning, was not guarded with a `synchronize` block.  The calls to `parameterize` and `plan` must happen with no other planning happening in between.  This caused a data race on the value of `curParamIndex`.
My fix was to force creation of an instance of `QueryPlanner` to take out a global lock to ensure that …

ENG-13396: Sporadic failure in TestJSONInterface

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h
src/ee/execution/VoltDBEngine.cpp
src/ee/executors/abstractexecutor.h
src/ee/executors/deleteexecutor.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/messaging/RejoinMessage.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataReceiver.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/rejoin/StreamSnapshotSink.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotRequestConfig.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Rejoin does not work for shared replicated tables because the partitions are snapshoted and streamed one at a time. Since Replicated table updates require the same transaction to appear on all partitions at the same time, streaming and replaying one stream at a time will not work. With this fix, all partitions are streamed at the same time.
Also flow control was removed from the Rejoin node because we can't predict how many buffers will be sent to a partition before a replicated table buffer is received that another partition is blocked on in the EE.

ENG-13359:

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/execution/VoltDBEngine.cpp
src/ee/storage/MaterializedViewHandler.cpp
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/persistenttable.cpp

We don't currently assume the MP Memory context when creating Join Views because replicated tables joined with partitioned tables requires us to assume other contexts. However, the statements inside the view need to be allocated in the MP memory context so we assume the memory context after the handler has been registered with all the site sources. Since we assume contexts in a very localized way with views, we may want to consider a global assignment of the MP memory context after all the tests are passing and we understand the dynamics of all the required context switches.
There was also an issue with the deconstructor of the persistent table where JoinViews of replicated tables needed to be cleaned up in the partitioned Memory context. To support this scenario, a new scoped class was …

ENG-12820:

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/spec.txt
src/frontend/org/voltcore/network/CipherExecutor.java
src/frontend/org/voltcore/network/TLSNIOWriteStream.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/compiler/ssl-config
src/frontend/org/voltdb/utils/CatalogUtil.java

1. Added "dr" attribute in <ssl/> element in the deployment file for enabling server-side SSL for DR.
2. Added "ssl" attribute in <connection/> element in the deployment file for providing SSL property file (only needed for self-signed certificates) for client-side SSL for DR.
3. Create server-side SSL context when either external or DR SSL is enabled in the deployment file.

ENG-12228: SSL encrypted connections between replicated clusters

---

src/ee/common/types.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/dr2/DRProtocol.java

Fix DR binary log generation and handling of replicated table changes in non-16383 stream, the hash flag in BEGIN_TXN and HASH_DELIMITER is ANDed with a mask to indicate the next records are for replicated tables until the next HASH_DELIMITER or the END_TXN.
On the receiving side, also avoid calling isLocalSite() if we know the record is for a replicated table.
Backward compatible with old format where there will be no mask and replicated table changes are replicated in a specialized replicated stream, in that case, the hash flag will be TXN_PAR_HASH_REPLICATED and all the records in the txn will be replicated table change and handled accordingly.

ENG-12827 No Replicated Stream

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/stats/StatsAgent.cpp
src/ee/stats/StatsAgent.h
src/ee/stats/StatsSource.cpp
src/ee/stats/StatsSource.h
src/ee/storage/PersistentTableUndoTruncateTableAction.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java

Use a shared stats source for replicated tables that is installed into each partition's stats agent. When a table swap or truncate happens don't delete all the stats sources and rebuild all of them, but just delete and rebuild that table that is being swapped / truncated. Otherwise we need to synchronize partitioned table swaps and truncates to rebuild the replicated table stats.
Also reverse the order of shutting down partitions from lowest partition first to highest partition first down to lowest partition and then lastly the MP Write Site. We do this because we should delete the replicated table (and its stats sources) after all sites have shut down to avoid a tick on a higher partition from trying to get stats for a replicated table that has been deleted by the lowest site.

ENG-13314:

---

tests/sqlgrammar/sql_grammar_generator.py

sql_grammar_generator.py: added 'Invalid parameter index value' to the

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/SocketJoiner.java
src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltcore/messaging/TestHostMessenger.java
tests/frontend/org/voltcore/messaging/TestMessaging.java
tests/frontend/org/voltcore/zk/TestStateMachine.java
tests/frontend/org/voltcore/zk/TestZK.java
tests/frontend/org/voltcore/zk/ZKTestBase.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/TestVoltZK.java

Backport to release-6.3.x, one customer found that simultaneous rejoin will cause missing replicas  problem during initialization.
Original commit message
---
On startup, each node sends a request to rejoin the mesh to the live node. The live node will check if the request can be accepted at the moment. For example, we only allow one node to rejoin at a time. If more than one node tries to rejoin, the first rejoning node will atomically check and set the ZK blocker. Subsequent nodes will fail to do so and be rejected to join the mesh. They will retry after a while until they can succeed.

ENG-10421: allow multiple hosts trying to rejoin at the same time 

---

src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/persistenttable.cpp
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/messaging/RejoinMessage.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
src/frontend/org/voltdb/rejoin/StreamSnapshotAckReceiver.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/rejoin/StreamSnapshotSink.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

When multiple source hosts are involved in a rejoin, knowing when a sink has received all snapshot data is more complicated because the partitioned and replicated table data for one partition can come from 2 hosts. To resolve this all rejoin partitions except the lowest site will receive 2 EOF rejoin messages (One from the replicated table source and one from the partitioned table source). When both EOFs are received, the sink for the partition is cleaned up.
Also, in some cases the source of the replicated table for a rejoin may not be the lowest site of a host. This is problematic because it was previously assumed that only the lowest site could stream the replicated table data. Now any site can stream the replicated table data, but there is an extra check to verify that a new stream is …

ENG-12823:

---

bin/voltdb

make bin/voltdb require and find python2.7 instead of python2.6. A recent change to voltdbclient.py, which is imported here, made it dependent on python2.7. I discussed with JH a few different ways around this, including, restoring the old voltdbclient.py, or shipping it along side the new one. Another way to fix all this, and maybe a better way, is just to specify #!/usr/bin/env python2.7.

ENG-13543_fix_python2.7_required

---

src/frontend/org/voltdb/settings/NodeSettings.java

Reviewed when merged to release-7.9.x

ENG-13535: Add default value for path of large_query_swap

---

src/frontend/org/voltdb/expressions/SelectSubqueryExpression.java
src/frontend/org/voltdb/expressions/TupleValueExpression.java
src/frontend/org/voltdb/planner/parseinfo/StmtCommonTableScan.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/NodeSchema.java
src/frontend/org/voltdb/plannodes/ProjectionPlanNode.java
src/frontend/org/voltdb/plannodes/SchemaColumn.java
src/frontend/org/voltdb/plannodes/UnionPlanNode.java
tests/frontend/org/voltdb/planner/TestPlansInExistsSubQueries.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java
tests/frontend/org/voltdb/regressionsuites/TestCommonTableExpressionsSuite.java

The logic for updating output schemas for sequential scan nodes
with CTEs was incorrect.  I also changed SchemaColumn.getType()
to be SchemaColumn.getValueType() to make the names more similar to
the names in the AbstractExpression they are based on.

Fix ENG13540 and ENG13534.

---

src/frontend/org/voltdb/importclient/kafka10/KafkaStreamImporter.java

System test see NPE with stack trace:
2018-01-11 03:44:11,494   WARN  [ImportProcessor] ImporterTypeManager: Error trying to stop importer resource ID kafka://volt14b_9092_volt14e_9092/partitioned_export_replicated_export/voltdb
java.lang.NullPointerException
at org.voltdb.importclient.kafka10.KafkaStreamImporter.stop(KafkaStreamImporter.java:146)
at org.voltdb.importer.AbstractImporter.stopImporter(AbstractImporter.java:129)
at org.voltdb.importer.ImporterLifeCycleManager.stopImporters(ImporterLifeCycleManager.java:285)
at org.voltdb.importer.ImporterLifeCycleManager.stop(ImporterLifeCycleManager.java:264)
at org.voltdb.importer.ImportProcessor$ImporterWrapper.stop(ImportProcessor.java:84)
at org.voltdb.importer.ImportProcessor$2.run(ImportProcessor.java:131)
at …

ENG-13561: fix the NPE when stopping the KafkaStreamImpoter

---

src/frontend/org/voltdb/importclient/kafka10/KafkaStreamImporter.java
src/frontend/org/voltdb/importer/ImportManager.java
src/frontend/org/voltdb/importer/ImporterLifeCycleManager.java

When cluster state changes, such as @pause, importers will  grab a lock on ImporterManager and will be shutdown. In the meantime, catalog update needs the same lock to proceed. Shutting down importers immediately to avoid blocking catalog update.

ENG-13560 immediate shutdown of Kafka importer to avoid blocking other processes

---

src/frontend/org/voltdb/AbstractTopology.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/Cartographer.java
tests/frontend/org/voltdb/TestAbstractTopology.java

In v6.9 and later versions partition group partitioning is the default partitioning algorithm, however it fails to generate valid partition layout for certain rack-aware group configurations. This patch fixes the issue* with two new preconditions**:
1.  each rack should contains equal number of nodes, e.g. 9-node cluster with 3 racks, each rack should have 3 nodes.
2. number of racks should be divisible to number of partition replicas (equals K + 1). For example, k=1 cluster supports at most 2 racks, k=5 cluster supports rack size 1, 2, 3, 6.
*Subgrouping is still supported but not encouraged, an unique identifier for every node belong to the same rack is enough, for example, "0" or "a" or "rack1".
**If preconditions are not met, partitioning algorithm still try its best to make a viable …

Eng 13436 fix rack-aware partitioning defect in v6.9 and later versions

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/ClusterConfig.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/compiler/TestClusterCompiler.java
tests/frontend/org/voltdb/iv2/TestCartographer.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

ENG-13435, improve rack-aware alogrithm to generate well-balanced partitions assignment.
The original algorithm was using greedy rack-aware algorithm to always assign partitions
to *furthest* node. The problem is that it may not always come up with a feasible partition
assignment even though one exists. And also it doesn't guarantte partition replicas are
well balanced across multiple placement groups, e.g. in 2-rack K=3 configuration one group
may have 3 or 4 replicas for some partitions.
Rejoin may also break the rack-awareness by bring too many replicas to one of the placement
groups.
This patch improves the original algorithm by adding extra step after it couldn't find the
viable solution. First it spreads partition replicas out across placement groups,
until no more partitions can be …

Eng 13435 v6 rackware

---

src/frontend/org/voltdb/importclient/kafka10/KafkaLoader.java

When a connection to voltDB in KafkaLoader10 is refused due to network connection, ignore it (The same behavior as KafkaLoader 8).

ENG-13633 consume the network connection exception

---

tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

and is available in read-only mode', end execution immediately with a
fatal error; moved (in the summary file and to STDOUT) the detailed
"hanging SQL" messages to before the last-n and summary messages, with
only a single line about "hanging SQL" after them (when such messages
appear); added 'Resource limit exceeded' to the list of ERROR messages
to be searched for, in the log and in the console output; in
get_last_n_sql_statements method, added optional times (that SQL was
sent and output received) to be printed out; and added code to save
these times, when we have "hanging SQL"; and therefore moved the
formatted_time method earlier, to be used in print_sql_statement.

sql_grammar_generator.py: when sqlcmd output includes 'Server is paused

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/executorcontext.cpp
src/ee/common/executorcontext.hpp
src/ee/storage/LargeTempTable.cpp
src/ee/storage/LargeTempTable.h
src/ee/voltdbipc.cpp
tests/ee/common/tabletuple_test.cpp
tests/ee/execution/ExecutorVectorTest.cpp
tests/ee/execution/add_drop_table.cpp
tests/ee/execution/engine_test.cpp
tests/ee/indexes/index_test.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/ExportTupleStream_test.cpp
tests/ee/storage/LargeTempTableTest.cpp
tests/ee/storage/PersistentTableMemStatsTest.cpp
tests/ee/storage/StreamedTable_test.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/ee/storage/persistenttable_test.cpp
tests/ee/test_utils/UniqueEngine.hpp
tests/ee/test_utils/plan_testing_baseclass.h

This branch fixes all CPP unit tests besides the dr binary log test. These tests are fixed by resetting the global sites per host value that is checked during engine initialization. Also, there are a few places where replicated tables are inserted into directly by unit tests and for these cases, the table first needs to be locked and the MP Memory context needs to be assumed.

ENG-13625:

---

build.py
src/ee/common/LargeTempTableBlockCache.cpp
src/ee/common/LargeTempTableBlockCache.h
src/ee/common/LargeTempTableBlockId.hpp
src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/common/executorcontext.cpp
src/ee/common/iosflagsaver.h
src/ee/common/lttblockid.h
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/storage/LargeTempTable.cpp
src/ee/storage/LargeTempTable.h
src/ee/storage/LargeTempTableBlock.cpp
src/ee/storage/LargeTempTableBlock.h
src/ee/storage/table.h
src/ee/storage/tableiterator.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/largequery/BlockId.java
src/frontend/org/voltdb/largequery/LargeBlockManager.java
tests/ee/common/LargeTempTableBlockIdTest.cpp
tests/ee/common/lttblockid_test.cpp
tests/ee/storage/LargeTempTableTest.cpp
tests/ee/test_utils/LargeTempTableTopend.hpp
tests/frontend/org/voltdb/largequery/TestLargeBlockManagerSuite.java

We change the block ids for Large Temp Tables from single int16_t values to structured values.
Objects of this class still have by-value semantics.  But they should be globally unique across
the entire cluster.

Eng 13224 Large Temp Table Block Ids

---

lib/python/voltcli/voltadmin.d/stop.py

This corrects a simple omission from when kerberos support was added for voltadmin.

ENG-13699: voltadmin pass in kerberos param when connecting to node for stop

---

src/ee/common/NValue.hpp
src/ee/executors/indexscanexecutor.cpp
src/ee/executors/indexscanexecutor.h
src/ee/indexes/CompactingTreeMultiMapIndex.h
src/ee/indexes/CompactingTreeUniqueIndex.h
src/ee/indexes/tableindex.h
src/ee/plannodes/indexscannode.cpp
src/ee/plannodes/indexscannode.h
src/ee/structures/CompactingMap.h
src/frontend/org/voltdb/planner/microoptimizations/ImproveOffsetQueryByRankValueIndex.java
src/frontend/org/voltdb/planner/microoptimizations/MicroOptimizationRunner.java
src/frontend/org/voltdb/planner/microoptimizations/OffsetQueryUsingCountingIndex.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
src/frontend/org/voltdb/plannodes/LimitPlanNode.java
tests/ee/structures/CompactingMapIndexCountTest.cpp
tests/frontend/org/voltdb/regressionsuites/TestIndexOffsetSuite.java
tests/frontend/org/voltdb/regressionsuites/TestOrderBySuite.java

This PR is to speed up offset query by using counting index, getting O(logN) look up other than sequential index scan O(N). It works for both ascending and descending order when applying offset. 
For example:
select * from t order by col offset N limit 1
If col is an indexed column of table t, EE should utilize the rank of value to find the target tuple directly. Now although the explained plan says this is index scan, EE actually performs N index scan to locate the right tuple.

Eng 13407 index offset log n optimization

---

lib/python/voltcli/voltdb.d/add.py
lib/python/voltcli/voltdb.d/create.py
lib/python/voltcli/voltdb.d/recover.py
lib/python/voltcli/voltdb.d/rejoin.py

Jepsen tests got broken after deprecating the CLI. Let's revert this change and put out warning instead.

Revert "ENG-12441: remove python cli voltdb old cli API (#5113)"

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/StoredProcedureInvocation.java

AdHoc single partition replicate table read only queries currently do not have partition parameter. NULL partition value gets routed to partition 0 always. This means that all AdHoc_SP_RO queries without partition key are only executed on one partition per cluster, which can lead to performance bottleneck. This commit is to address the above performance issue by round robin routing those queries to each partition in the cluster.

ENG-13493: performance greatly improved by balancing replicate table AdHoc read queries

---

src/ee/storage/TupleBlock.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp

There are two maps which track the set of blocks that are non-empty. These maps are used to determine if a block is in a bucket. However, an optimization to keep a cache block around when the table's tuple count goes to zero does not cleanly track this buffer either when the last tuple is deallocated nor subsequently when the first tuple is allocated. Therefore, this block may not participate in subsequent compactions.
This branch adds special checks to ensure that the last empty block is correctly tracked when the last tuple is deleted and when this block is used by the first tuple that is subsequently inserted.

ENG-13701:

---

src/ee/execution/VoltDBEngine.cpp
src/frontend/org/voltdb/ExtensibleSnapshotDigestData.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java

- Save export USOs in snapshot and use it restart from where we left off on snapshot restore.
- Reopen PBD after truncate.
- Stop using PBD.push. Always write to PBD, so that we never need to do a push.
PBD.push doesn't do the correct thing after some blocks are deleted.
- Changed totalUso to totalSize because that is what it actually is.

ENG-13480:

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientInterfaceHandleManager.java
src/frontend/org/voltdb/InvocationDispatcher.java

This pull request creates a separate bucket at CIHM for client handle of NT procedure. When mastership changes, for any inflight transaction send to the down node/partition, its client interface handle will be cleared and send an error response back to the client (or internal client). But so far all NT procedures run locally, even for the runOnAllNode NT procedure, so it means mastership change doesn't necessarily require NT procedure client interface handle cleanup.

ENG-13652, fix a issue that when MPI failover NT procedure that currently running will receive premature failure response.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/MaterializedViewHandler.cpp
src/ee/storage/MaterializedViewHandler.h
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
tests/frontend/org/voltdb/regressionsuites/TestIndexOffsetSuite.java

Fix was to explicitly shutdown the IPC EEs from Java class ExecutionEngineIPC.  This forces synchronous shutdown of all the engines (lowest site last).

ENG-13723: shared replicated: valgrind reports invalid reads during shutdown

---

src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExport.java
tests/frontend/org/voltdb/TestSnapshotWithViews.java

- Fixed off by one error when deciding to discard versus set release offset on a push.
- SBQ.offer now checks if the newly polled value is the same one that was just offered
before setting the release offset.

ENG-13736:

---

tests/sqlgrammar/run.sh
tests/test-tools.sh

ENG-13693: SQL-grammar-gen: modified the run.sh script (and related test-tools.sh), adding build-pro[-if-needed], server-pro[-if-needed], and all-pro options/functions, and now allow all of the build... options to accept arguments (e.g. -Dbuild=debug and/or -DVOLT_POOL_CHECKING=true, which are needed for ENG-13693. [This is already on the ENG-13611-shared-replicated-tables branch; now merging to master.]

Eng 13693 gram shared repl 2m

---

tests/sqlgrammar/run.sh
tests/test-tools.sh

ENG-13693: SQL-grammar-gen: modified the run.sh script (and related test-tools.sh), adding build-pro[-if-needed], server-pro[-if-needed], and all-pro options/functions; and now allow all of the build... options to accept arguments (e.g. -Dbuild=debug and/or -DVOLT_POOL_CHECKING=true, which are needed for ENG-13693). Plus, it distinguishes between build args and other arguments, and passes a
'--build=debug' arg to the build_udf_jar.sh script, when appropriate.

Eng 13693 gram shared repl

---

src/ee/storage/persistenttable.cpp
src/ee/storage/table.cpp

There is a great deal of extraneous output generated by the EE from table data particularly for large tables with many indexes. The Table Data and Table Index data will now only generated in the log message when the TRACE log level is enabled.

ENG-13611:

---

third_party/java/src/org/apache/zookeeper_voltpatches/ClientCnxn.java

Client uses signed 32-int as xids which are assumed to be non-negative. Zookeeper uses some negative values as special XIDs (e.g. -2 for ping, -4 for auth). However, ZK client does not ensure the xids it generates are non-negative, and the server doesn't reject negative xids. If signed 32-int overflows, xids become negative, which will break the system.
The solution is to reset xid to 1 when it overflows.

ENG-13468 ZooKeeper client xid overflow handling

---

src/ee/expressions/datefunctions.h
src/ee/expressions/stringfunctions.h

We didn't return a boolean typed null value from is_valid_timestamp.
I also changed the return types of some other functions which return
null values.  Better the right type than the null type.

Fix ENG-13747.

---

src/ee/common/NValue.hpp
src/ee/execution/VoltDBEngine.cpp
src/ee/indexes/IndexStats.cpp
src/ee/indexes/IndexStats.h
src/ee/stats/StatsAgent.cpp
src/ee/stats/StatsSource.cpp
src/ee/stats/StatsSource.h
src/ee/storage/TableStats.h
src/ee/storage/persistenttable.cpp
src/ee/storage/tablefactory.h
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/fixedsql/fixed-sql-ddl.sql

This is an old problem that manifested recently with the shared replicated table commit.
In EE, there are two types of `StatsSource`: one for tables and one for indexes. Both of them cache the table name in an `NValue` so they don't have to construct one every time when they produce a stats temp table.
Before we have the @SwapTables procedure, a table's name cannot be changed once it is created because we do not support `ALTER TABLE RENAME`. But when you swap two tables, the table names are also swapped. Previously, we forgot to update the cached `NValue` in the index and table stats to reflect the new table name. So the statistics that we have been providing, in this case, is always wrong.
In the shared replicated table work, we have a new change in Java where, before returning the …

ENG-13778-srt-swap-drop

---

build.xml

For a brief period cmake produced .dylib.  This change cleans them up if they are still present in the voltdb/ directory.

ENG-13802. Cleanup .dylib files

---

src/ee/execution/VoltDBEngine.cpp

For DR Consumer Only  Cluster, the drReplicatedStream won't be created. Thus remove the unnecessary check.

ENG-13799: remove invalid assert

---

tests/frontend/org/voltdb/TestAdHocQueries.java

The length prefix was expanded from a 2-byte integer to a 4-byte integer (signed).
Obviously, it now can support way more than 10x longer query string.
Getting a `10 * Short.MAX_VALUE` long query string does not cover that much of this length range, and it brings the timeout issue in the test itself.
Change to the loop condition below, so that it just verifies you can go beyond 2^15 in query string, which is enough for the scope of [ENG-9560](https://issues.voltdb.com/browse/ENG-9560).

Adjust testAdHocLengthLimit

---

src/frontend/org/voltdb/iv2/MpProcedureTask.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpRestartSequenceGenerator.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

When some completions were received by sites and repair completions arrive on other sites, the completions won't match up and the scoreboard advances the Release before all the resubmitted completions arrive. Timestamps need to be added to resubmitted completions to match them up correctly.

ENG-13769:

---

src/ee/common/ExecuteWithMpMemory.cpp
src/ee/common/ExecuteWithMpMemory.h
src/ee/common/SynchronizedThreadLock.cpp
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/executors/deleteexecutor.cpp
src/ee/executors/insertexecutor.cpp
src/ee/executors/sendexecutor.cpp
src/ee/executors/swaptablesexecutor.cpp
src/ee/executors/updateexecutor.cpp
src/frontend/org/voltdb/ProcedureRunner.java
tests/ee/test_utils/plan_testing_baseclass.h
tests/frontend/org/voltdb/regressionsuites/TestLoadingSuite.java

TestLoadingSuite was failing in memcheck mode because of subtle differences in exception handling between the IPC and JNI back ends.  It turns out we were throwing a fatal exception in some cases from non-lowest site threads when encountering a unique constraint violation when loading a replicated table.

ENG-13816: refactor exception handling for VoltDBEngine::loadTable

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/Benchmark.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/NibbleDeleteLoader.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/ddl.sql
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/NIBDPTableInsert.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/NIBDRTableInsert.java

This adds two seperate threads to TxnId2, a loader and a monitor.  The loader thread (NibbleDeleteLoader) can populate one of two new tables 'NIBDP' and 'NIBDR'  who have a TTL set on a Timestamp column.  The NibbleDeleteMonitor thread monitors the data in those tables and fails the test if any data remains in the table past it's TTL plus a little wiggle room - since not all of the data may be deletable in a single Tick.

Eng 1376 nibble delete st

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/BorrowTransactionState.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/FragmentTaskBase.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpInitiatorMailbox.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java
src/frontend/org/voltdb/iv2/ParticipantTransactionState.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestMpPromoteAlgo.java
tests/frontend/org/voltdb/iv2/TestMpTransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerSpHandle.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java
tests/log4j-allconsole.xml

…iteId fix (#5279)
* ENG-13769:
The scoreboard now coordinates all fragment tasks across all sites. However, NP transactions such as @BalancePartitions does not need to be coordinated because it does not modify replicated tables. This change will resolve join failures that currently get blocked by the scoreboard.
* ENG-13769:
Fix some unit tests and use an array instead of an arraylist for the scoreboard so that contiguous siteIds higher then 0 (happens when local serverthread is reused) are tolerated.
* ENG-12628: Pospone ElasticJoinProducer Mailbox initilzation till sp
initors creation
* ENG-12628:
MP Repair algo creates a new timestamp every time the repair is restarted so the same timestamp will be used repeatedly. We now create the timesamp once in the mpinitiator and pass it in …

Eng-13769 cherry-pick to 8.1

---

src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

A stale txn may get into scoreboard in random order.  Check both entries for a completion match and release the completion tasks to avoid transaction lockup.

ENG-13769 check both entries for task completion match in scoreboard

---

src/frontend/org/voltdb/iv2/SpScheduler.java

If repair has receiving the completion Message for a missing np transaction, that txn should already been commit or never seen. We should not put a completeTransactionTask to the scoreboard since it don't need to be coordination.

Eng 13891: Ignore np missingTxnCompletion for Scoreboard

---

src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

ENG-13752:
When writing truncated buffer, export was initializing buffer with compressed size, but writing uncompressed bytes. Fixed to initialize the buffer with the correct size.

Eng 13752 use truncated buffer size in buffer writer (#5305)

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
tests/frontend/org/voltdb/benchmark/tpcc/TPCCProjectBuilder.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

Load table was not generating consistent results on all sites in the event of a failure. While this failure should not happen, it would generate a Hash Mismatch if it does, so this code fixes this path and addes unit tests for both this failure scenario and the exception failure scenario.

ENG-13894:

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java
src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SpTerm.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/sysprocs/PingPartitions.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerSpHandle.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java

1. Disable scoreboard for Join Nodes when initiated
2. Still updateReplicas for new Partititions on join nodes
3. Once all new sites has been initialized, queue one addition @PingPartiton for reenable Scoreboard and queue this very @PingPartitions as first task to the scoreboard.

ENG-13844: Disable/Reenable Scoreboard for join Nodes

---

src/frontend/org/voltdb/sysprocs/SnapshotRestore.java

With the advent of Multi-cluster DR and Mixed-size clusters, snapshot digests can get much larger than in the past, particularly with Export state. Snapshot recover has a limit of 1MB for digests. This limit is now removed.

ENG-12629:

---

src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestScoreboard.java

fix thread-safe issue when we touching transaction backlog,
fix a corner case that fragment message doesn't get cleaned by restart completion message,
fix an issue that we don't flush backlog for certain non-restartable MP sysprocs (e.g. @SwapTablesCore)
Change-Id: I39419514a474bc837c3f9e0f61f8317c5b912fb7

ENG-13856, fix various issues found in system tests.

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/MpProcedureTask.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java
tests/frontend/org/voltdb/iv2/RandomMsgGenerator.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java
tests/frontend/org/voltdb/messaging/TestVoltMessageSerialization.java

Rename restartable in the completion message to indicate that this is a repair completion with an abort.
Also use and advance the timestamp for this use of completions.
Also make sure that abort completions for txns where some sites have the first fragment and some don't, mark the txn state complete in those sites that receive the txn. Otherwise the backlog.flush won't advance the backlog.
Clean up unit tests that flush the backlog at the time the txn is added rather than waiting until the txn has been released by the scoreboard.

ENG-13854:

---

.gitignore
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionCustom.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java

Makes query `SELECT PI FROM T;` work the way as `SELECT PI() FROM T;`.
See [Jenkins](http://ci.voltdb.lan/view/Branch-jobs/view/branch-ENG-11896-pi-function/). Not totally sure if failed ones were ok, but a few, e.g. TestTopologyAwareClient fails both on master branch and this branch on my local machine.

Eng 11896 pi function

---

src/frontend/org/voltdb/utils/SQLCommand.java
tests/sqlcmd/baselines/simple/describetable.outbaseline
tests/sqlcmd/scripts/simple/describetable.in

This fixes the column sizes for fixed-size columns (for which @SystemCatalog COLUMNS has strange values) and GEOGRAPHY datatypes which should be the actual size, not the NULL integer value. Also added VIEW and STREAM examples to the test.

ENG-6163 describe table - corrected sizes

---

tests/geb/vmc/src/pages/VoltDBManagementCenterPage.groovy
tests/geb/vmc/src/resources/sqlQueries.txt

use '@innerHTML' rather than 'text()', because the latter removes
leading and trailing whitespace. In sqlQueries.txt, use '\t' to pass a
tab character to JSON, but not '\\t', since the VMC no longer interprets
'\t' as a tab character, but does work with a literal tab character; and
uncomment the 2 '...EmbeddedWhitespace' tests, since they now work, with
the above changes.

ENG-13654: in VoltDBManagementCenterPage.groovy's 'getTableContents',

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/common/Constants.java
src/frontend/org/voltdb/utils/SQLCommand.java

ENG-13678: Use JVM's trust store and password as the default, if one is not specified.

Eng 13678: (#5381)

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

In the repair process, some sites many have received CompleteTransactionResposneMessage so
the TransactionTaskQueue and outstandingTxn are cleaned on these sites. When a repair CompleteTransactionMessage reache these sites, a CompelteTransactionTask will be placed on ScoreBoard as unmatched (missing). However, if a site still has the transaction state, i.e.in outstanding transaction and TransactionTaskQueue, a CompelteTransactionTask is placed on ScoreBoard as matched, the TransactionTaskQueues on these sites need be flushed to unblock these sites.

ENG-13854 matched complete transaction

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/SpInitiator.java

When a node is down, partitions will promote their new leaders. Before new leaders are fully promoted, the failed node may join back to the cluster, which will interference the partition replica calculations.  A partition replica from the rejoining node may be prematurely added to the partition replica list.  Transaction fragments may be forwarded to the partition replica on the rejoining node which may  fail to complete the scoreboard. And the repair process may hang on the new partition leader. The pull request  will make the rejoining wait until partition leader promotions are finished.

ENG-14154 wait leader promotions completed before rejoining moves forward

---

src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/VerifyCatalogAndWriteJar.java

A customer has a catalog that exceeds the 50MB message size. In most of the paths, catalogs and catalog diffs are passed around compressed but UAC passes the catalog diffs uncompressed to each host. This branch passes the catalog diffs compressed and asks each host to decompress locally before building the local jar file. This reduces the size of the message by half.

ENG-14162:

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/TTLManager.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/Tokens.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/fullddlfeatures/fullDDL.sql
tests/frontend/org/voltdb/sysprocs/TestLowImpactDelete.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/ddl.sql

also do not execute nibble deletes when cluster is paused to allow buffers to be drained for export and dr

ENG-14186 update DDL syntax for TTL

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/iv2/CompleteTransactionTask.java

When a CompleteTransactionTask for restart is processed, skip TransactionTaskQueue flush since  the transaction is not done yet.

ENG-14207 skip TransactionTaskQueue flush with restart

---

src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/Iv2Trace.java
src/frontend/org/voltdb/iv2/JoinProducerBase.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/rejoin/TaskLog.java
src/frontend/org/voltdb/rejoin/TaskLogImpl.java
tests/frontend/org/voltdb/rejoin/TestTaskLog.java

When tasks in task log before stream snapshotting are replayed  in join path, EE could hang since these tasks are not synchronized via score board. Filter out these tasks during replay.

ENG-14213 do not replay logged tasks before snapshotting in join path

---

src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/Iv2Trace.java
src/frontend/org/voltdb/iv2/JoinProducerBase.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/rejoin/TaskLog.java
src/frontend/org/voltdb/rejoin/TaskLogImpl.java
tests/frontend/org/voltdb/rejoin/TestTaskLog.java

When tasks in task log before stream snapshotting are replayed in join path, EE could hang since these tasks are not synchronized via score board. Filter out these tasks during replay.

ENG-14213 do not replay before snapshotted

---

src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

Multiple MP reads can be executed in parallel but the order of execution is not determined. Example,  for MP Read Txns 1,2,3, Txn 2 may be processed before Txn 1.  The fragments of both txn 2 and 1 will be sent to all partition leaders.  When fragments from Txn 2 arrive, a site will put it to backlog and move it to SiteTaskQueue. When fragments from Txn 1 arrive, the site will also put it the backlog and then move it to the SiteTaskQueue.  So the header of backlog is a fragment from Txn 2.  Since the fragments from both Txn 2 and Txn 1 are on the SiteTaskQueue, they can be processed sequentially.  Unfortunately if the final fragment from Txn 1 processed before the final fragment from Txn 2, Txn 1 will try to flush the backlog but fails since Txn 1 is not in the header.  The backlog will …

ENG-14213 prevent multiple mp reads from coexisting in the same site task queue

---

tools/jenkins/junit-stats.py

* Two intelligent queries - check 30 day history of junit tests and files ticket
* if first failure, or
* if most recent failure period exceeds two standard deviations from mean failure period
* Changed to using volt24 mysql database to track junit-test-failures
* before merging with master, need to update Jenkins to log on volt24
* Other
* Tentative support of branch-2-vdm-py-test-master and (root) tests
* Add Jenkins history link to Jira ticket description

ENG-14148: Update to junit auto ticket filer

---

tests/sqlcoverage/config/default-regression-config.py
tests/sqlcoverage/ddl/matview-DDL.sql
tests/sqlcoverage/schema/matview-query-opt-schema.py
tests/sqlcoverage/template/include/matview-query-opt-template.sql
tests/sqlcoverage/template/int/configure-for-matview-query-opt.sql
tests/sqlcoverage/template/int/matview-query-opt.sql

i.e., of queries that (partly) match a query that was defined in a materialized view on the same table. ENG-2878 improved performance by making use of such materialized views; these tests simply ensure that we still get the right answer.

ENG-14187: added SqlCoverage tests of ENG-2878
