tests/frontend/org/voltdb/regressionsuites/TestSqlDeleteSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/delete/DeleteOrderByLimit.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/delete/DeleteOrderByLimitOffset.java

My last commit to master added new files with 2014 in the license.  Updating to 2015.

Fix licensecheck issues for recently added files

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/parseinfo/JoinNode.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Disallow views on subqueries. Only a single source table is allowed in a view

Disallow views on subqueries. Improve the error message

---

src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd

(cherry picked from commit 6bd901a5ca1c2ecaf6dad38de070fc4782d8242c)

ENG-7442.  Remove limit in VoltDB on snapshotpriority.

---

src/frontend/org/voltdb/CommandLogReinitiator.java
src/frontend/org/voltdb/DefaultCommandLogReinitiator.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/RestoreAgent.java

Accompanied by pro pull request 
https://github.com/VoltDB/pro/pull/657

ENG-7488: Remove apparently dead code.

---

tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/fixedsql/fixed-sql-ddl.sql

These are the unit tests I wrote to try and reproduce a user-reported issue that was closed as "not a bug."

Add more unit tests for IN with params

---

src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementDMQL.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/regressionsuites/TestLimitOffsetSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlDeleteSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/sqlfeatureprocs/sqlfeatures-new-ddl.sql

Add unit tests for same, for both SELECT and DELETE.

Make HSQL amenable to OFFSET with no LIMIT clause

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java

Still waiting for junit on Jenkins

ENG-7647 Reject all quoted schema names

---

src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/utils/TestSqlCmdErrorHandling.java
tests/frontend/org/voltdb/utils/TestSqlCmdInterface.java

Add initial support for file batch DDL sqlcmd feature

---

src/frontend/org/voltdb/parser/SQLLexer.java
tests/frontend/org/voltdb/utils/TestSQLLexer.java

The DR DDL statement was not recognized as a DDL statement, added it to
the while list.

ENG-7766: Fix dynamic DR DDL parsing failure.

---

src/frontend/org/voltdb/compiler/AsyncCompilerAgent.java
src/frontend/org/voltdb/parser/SQLLexer.java
src/frontend/org/voltdb/parser/SQLPatternFactory.java
tests/frontend/org/voltdb/utils/TestSQLLexer.java

ENG-7692 Alter rename preparse

---

src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/parser/TestSQLParser.java

Pursuant to ongoing FILE -batch.  I put this method into SQLParser since it seemed to belong there.

Add method batchBeginsWithDDLKeyword to SQLParser

---

src/frontend/org/voltdb/parser/SQLParser.java
tests/test_apps/tpcc/tpcc-partitioning.sql

Accidentally picked up a master change from Ryan -- looks like a non-issue for CORE-team. Please ignore.
Github diff does not show this as well as meld, but this really is (I think) a whitespace/comment change (and breaking strings up with " + ".
I tried not to change the actual regexp content.

Eng 7761 annotate parser

---

src/frontend/org/voltdb/parser/SQLParser.java

Build was failing on CORE-team branch.

Fix typo so build succeeds

---

src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/utils/TestSqlCmdInterface.java
tests/sqlcmd/.gitignore
tests/sqlcmd/baselines/batching/file_batch_positive.outbaseline
tests/sqlcmd/baselines/batching/redundant_table_batch.errbaseline
tests/sqlcmd/baselines/batching/redundant_table_batch.outbaseline
tests/sqlcmd/scripts/batching/file_batch_positive.in
tests/sqlcmd/scripts/batching/redundant_table.sqlfile
tests/sqlcmd/scripts/batching/redundant_table_batch.in
tests/sqlcmd/scripts/batching/successful_batch.sqlfile

I had to do some minor refactoring of Xin's recent commit to make this work.

Show batch file path in error messages for sqlcmd DDL batches

---

src/frontend/org/voltdb/parser/SQLParser.java
tests/frontend/org/voltdb/parser/TestSQLParser.java

I didn't realize PAT_ANY_DDL_FIRST_TOKEN matches any line where a DDL
token is the first token (not just the first line).

Fix issue with finding DDL in the middle of a batch.

---

tests/scripts/sql_coverage_test.py

code, so that any exception will be caught, and will print out debug
info, to help figure out what went wrong, in order to fix ENG-7892.

sql_coverage_test.py: in next_keyStats_column_value(), added defensive

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientInterfaceHandleManager.java
src/frontend/org/voltdb/ClientInterfaceRepairCallback.java
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/Iv2TransactionCreator.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/iv2/SpInitiator.java
tests/frontend/org/voltdb/TestClientInterface.java
tests/frontend/org/voltdb/TestClientInterfaceHandleManager.java
tests/frontend/org/voltdb/TestRateLimitedClientNotifier.java

ENG-7922: Add callback to notify listener of ClientInterface partition

---

build.py
src/ee/storage/DRTupleStream.cpp
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h
tests/ee/storage/DRBinaryLog_test.cpp

Fixes ENG-7979: Erroneous BEGIN_TXN at the start of a DR buffer
ENG-7954: Unit test of binary log serialization/deserialization

ENG-7954 and ENG-7979

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/planner/CompiledPlan.java
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/regressionsuites/TestUnionSuite.java
tests/frontend/org/voltdb/regressionsuites/testunion-ddl.sql

Back port for the Union problem.

Eng 7980 backport

---

src/frontend/org/voltdb/parser/SQLParser.java

there is no eng-7079 branch in the master

Eng   7079

---

src/ee/expressions/bitwisefunctions.h
src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionCustom.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/types/NumberType.java
tests/frontend/org/voltdb/planner/TestFunctions.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java

It's the same as the other pull request, but only contains one commit.

Add bit shift functions support using diff files within one commit

---

tests/frontend/org/voltdb/fullddlfeatures/fullDDL.sql
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java

Add various tests for live schema change for sparse index

---

tests/frontend/org/voltdb/regressionsuites/TestStatisticsSuite.java

Somehow I forgot to push my local branch to github for this ticket.

ENG-8107: Fix broken DR stats test.

---

tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/planner/TestPlansInExistsSubQueries.java
tests/frontend/org/voltdb/planner/TestPlansScalarSubQueries.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

Very small tests code cleanup while doing code review, no functional changes.

small code clean up for the java tests

---

src/frontend/org/voltcore/logging/VoltLog4jLogger.java
tests/frontend/org/voltdb/regressionsuites/TestRollbackSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/rollbackprocs/AllTypesMultiOpsJavaError.java

Also, fixed a bug in allTypesMultiOpsJavaError which caused nothing to actually be tested.

Add a java unit test for rolling back truncate table.

---

src/catgen/in/javasrc/DRCatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

ENG-7985: Address review comment

ENG-7985: Only check DR schema consistency on DDL changes

---

src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionAggregate.java
src/hsqldb19b3/org/hsqldb_voltpatches/SetFunction.java
tests/hsqldb/org/hsqldb_voltpatches/TestHSQLDB.java

I wrote a test to diagnose the problem and implemented a new java junit test.

Eng 7520 better sum star message

---

src/ee/common/types.cpp
src/ee/execution/VoltDBEngine.cpp
src/ee/executors/tuplescanexecutor.cpp
src/ee/expressions/subqueryexpression.cpp
src/ee/expressions/subqueryexpression.h
src/ee/expressions/vectorcomparisonexpression.hpp
src/ee/plannodes/plannodefragment.cpp
src/ee/storage/TableCatalogDelegate.cpp

Not many changes here, I just added some comments to clarify my understanding of the code.

Review EE code in subquery branch

---

src/frontend/org/voltdb/jdbc/JDBC4DatabaseMetaData.java

Sorry, these should have been part of 7020.

Add the bitwise functions to the JDBC metadata.

---

src/frontend/org/voltdb/planner/ParsedInsertStmt.java
src/frontend/org/voltdb/planner/ParsedUpdateStmt.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java

Also, add more tests for DML subquery guards.

Do a better job at finding expressions in parsed statements

---

tests/geb/vmc/build.gradle
tests/geb/vmc/src/tests/SqlQueriesTest.groovy

Fixes the problems with the GEB tests of the VMC, caused by merging the DR changes to the VMC.

Eng 8236 geb dr merge

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.admin.ui.js

ENG-8281: uppercase export type.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/Initiator.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java

Serialize the catalog once and pass the serialized string to each site
for initialization. Catalog serialization is not thread-safe.

ENG-8044: Fix catalog serialization race during initialization.

---

tests/frontend/org/voltdb/jdbc/TestJDBCSecurityEnabled.java

Setup up the sever with security on.
Create Users with of different Perms to System Procedures, SQL Queries , Default Procedures.
Check Sufficient.insufficient privileges for each users for each type of queries

 ENG-8241: add JUnit tests in JDBC test suite with security enabled on server.

---

tests/scripts/examples/sql_coverage/advanced-inexists.sql
tests/scripts/examples/sql_coverage/regression-config.py

Additional tests of IN, EXISTS, ANY and ALL, per ENG-8190.

Eng 8190 sqlcov in exists

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
tests/frontend/org/voltdb/regressionsuites/TestLimitOffsetSuite.java
tests/frontend/org/voltdb/regressionsuites/testlimitoffset-ddl.sql

We can't use EXISTS if the subquery has a limit clause.
Jira Ticket Number: ENG-8439
Jira Ticket Url: https://issues.voltdb.com/browse/ENG-8439

We converted NUM IN (select ... limit 4) to an EXISTS query incorrectly.

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java

@paulmartel @yzhang1991 Please review the pull request.

refactor the big function into pieces

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
tests/frontend/org/voltdb/regressionsuites/TestExistsNotFactoringSuite.java
tests/scripts/examples/sql_coverage/advanced-inexists.sql

Rewriting EXISTS(subquery1 intersect subquery2) as EXISTS(subquery1) and
EXISTS(subquery2) does not preserve the meaning.  We eliminated this
optimization.

Don't rewriting EXISTS(subquery1 intersect subquery2).

---

tests/scripts/SQLCoverageReport.py
tests/scripts/SQLGenerator.py
tests/scripts/examples/sql_coverage/fuzzynormalizer.py
tests/scripts/examples/sql_coverage/normalizer.py
tests/scripts/examples/sql_coverage/not-a-normalizer.py
tests/scripts/sql_coverage_test.py

Pull request for the reporting half of my Innovation Week project. (Normalizer work will be a separate pull request.) Added data for new columns: 'NPE's', 'Crashes'; 'Minimum', 'Maximum' (queries per pattern), '# Inserts' & '# Patterns'; times for 'Generating SQL', 'VoltDB', 'HSqlDB', 'Comparing' & 'Total'. Various values are printed as red, orange or yellow, depending on how serious a problem they represent (or gray, for values not computed due to a crash).

Eng 8166 sqlcov reporting

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionAccessor.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionAggregate.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionArithmetic.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionArrayAggregate.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumnAccessor.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLogical.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionOp.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionOrderBy.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionTable.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionValue.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
src/hsqldb19b3/org/hsqldb_voltpatches/Like.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/QueryExpression.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
src/hsqldb19b3/org/hsqldb_voltpatches/Statement.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementCommand.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementCompound.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementDMQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementHandler.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementSchema.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementSession.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementSimple.java
src/hsqldb19b3/org/hsqldb_voltpatches/VoltXMLElement.java

This commit improves printing of HSQLDB ASTs.

Bwhite better hsqldb printing

---

tests/test_apps/schemachange/src/schemachange/SchemaChangeClient.java

A variant of commit 976046d86c8639ed9f8fed62601c306ebf72b5f5.

ENG-8627. Add retry in schemachange for adhoc planning errors.

---

tests/frontend/org/voltdb/regressionsuites/TestDecimalRoundingSuite.java

ENG-8510: Implement a unit test for overflow (positive and negative) caused by  by Decimal rounding.

Unit Test for Decimal Rounding Overflow.

---

src/frontend/org/voltdb/planner/ParsedSelectStmt.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

Disabled some tests in TestSubQueriesSuite to make Jenkins bluer.  Also,  a Null Pointer Exception in ParsedSelectStmt.java.

Disabled some tests in TestSubQueriesSuite to make Jenkins bluer.

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateBaseProc.java

Changing zero byte arrays used for inserts into tables replicated and partitioned to the value byte array generated for that purpose.

Eng 8640 real

---

build.py
tests/ee/structures/CompactingMapBenchmark.cpp

Add control parameters for the benchmark to run
use 10 seconds to sleep time after data inserts and before data gets destroyed
Add warm up and also resolve the other comments

Add a EE structure benchmark

---

tests/geb/vmc/src/resources/sqlQueries.txt
tests/geb/vmc/src/tests/SqlQueriesTest.groovy
tests/geb/vmc/src/tests/TestBase.groovy
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateBaseProc.java

Modified the SQL query tests listed in sqlQueries.txt, and run in SqlQueriesTest.groovy, to expect a specific error (for those invalid queries that should produce an error); also, the tests now span multiple lines, making them much easier to read, and to modify.

Eng 8617 geb expect error

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/AsyncCompilerAgent.java
src/frontend/org/voltdb/compiler/AsyncCompilerAgentHelper.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/compiler/TestAsyncCompilerAgent.java
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

ENG-8541: Add license check logic for dr active-active

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Unify the semantics for testing legality of display list expression in indices and materialized views.

Unify the semantics for testing legality of display list expressions

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/expressions/AbstractValueExpression.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Unify the semantic checking for testing legality of indices and materialized views.
Jira Ticket Number: ENG-8632
Jira Ticket Url: https://issues.voltdb.com/browse/ENG-8632

Unify the semantic checking for testing legality of indices and

---

src/frontend/org/voltdb/ConsumerDRGateway.java

Conflicts:
src/frontend/org/voltdb/ConsumerDRGateway.java

ENG-8759: Don't track remotely applied DR IDs in the dummy consumer

---

tests/test_apps/matviewbenchmark/ddl.sql
tests/test_apps/matviewbenchmark/src/matviewbenchmark/MaterializedViewBenchmark.java

Let the benchmark cover both MIN and MAX.
Let optimal and sub-optimal cases have same number of indexes with similar structure.

ENG-8641 Add max and indexes to the benchmark

---

build.xml
src/frontend/org/voltdb/RealVoltDB.java

Add test targets to be used by Docker JUnit testing
Add directory creation check for some file writing operations

Docker build xml

---

tests/test_apps/txnid-selfcheck2/run.sh
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/Benchmark.java

can be set from run.sh script, using the string in the below comment.

Added txnid2 thread disabling option from run parameter.

---

tests/test_apps/kafkaimporter/db/procedures/InsertImport.java

ENG-8891 fix deleteCount test.

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/Benchmark.java

Adding some checks to avoid an NPE when Benchmark completes in txnid2-selfcheck

ENG-8733: fix NPE when Benchmark complete in txnid2

---

src/frontend/org/voltdb/VoltTableRow.java
tests/frontend/org/voltdb/TestVoltTable.java

(cherry picked from commit fd3b080daa53a9c78e215edfc0dff4ce8c5a90ae)

ENG-8590: check wasnull to make sure its null

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/VoltTableRow.java

Use slices instead of arrays for blitting rows.

ENG-8824: One more perf optimization.

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/procedures/UpdateReplicatedMP.java

This should be replicated adhoc query

txnid2 test app: fix a typo

---

src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/tablefactory.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/persistenttable_test.cpp

This reverts commit 72fa904cf5541795474f37b2ac308f0a6e70d422, reversing
changes made to 7d3a3d5488691c49540cdb7176111bb1d712c139.

Revert "Merge pull request #2792 from VoltDB/ENG-8872"

---

src/frontend/org/voltdb/VoltSystemProcedure.java

A cut & paste into SnapshotRestore.java (see the matching pro changeset)
except for a ltweak to use the separate TRACE_LOG more consistently tor trace output.

Migrate SnapshotRestore details down out of VoltSystemProcedure.

---

tests/test_apps/s2/web/index.html

This is slightly interesting because the stupid
javascript scoping mechanism makes it harder than
one would think.

Display latitude and longitude in info windows.

---

tests/test_apps/s2/client/iwdemo/Benchmark.java
tests/test_apps/s2/client/iwdemo/TaxiManager.java
tests/test_apps/s2/procedures/iwdemo/GetTaxiInfo.java
tests/test_apps/s2/procedures/iwdemo/InsertRegion.java
tests/test_apps/s2/procedures/iwdemo/Utils.java
tests/test_apps/s2/web/index.html

Add county/state to map marker info windows.
Choose more evenly dispersed cities.

Fix InsertRegion stored procedure

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/common/types.h
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/PartitionDRGateway.java

Change-Id: I09b6b5d47ef66c25b4176e7062275ccf26e229c5

ENG--9078, change the conflict resolution API.

---

tests/test_apps/matviewbenchmark/ddl.sql
tests/test_apps/matviewbenchmark/src/matviewbenchmark/MaterializedViewBenchmark.java

Add another graph for best optimized index for matview min case
refactor the names according to Paul's suggestion

Add multi group matview benchmark

---

tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

Updated result set of a query to be order deterministic. 
Testing:
Verified the junit TestSubQueriesSuite passes with memcheck, debug and release builds.

Update result set of the query in junit to be order deterministic

---

tests/frontend/org/voltdb/iv2/TestRepairLog.java

This test is very flaky. It really belongs to a system test instead of a
unit test. I can't think of a better way to test it in junit
reliably. Removing it for now, leaving the ticket open for a proper
system test.
Change-Id: I34137052c6a02ad17f629a9447b140e0cfc1716c

ENG-9035: Remove RepairLog TestPerformance.

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/SpInitiator.java

Conflicts:
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/SpInitiator.java

ENG-8461: Fix DR partition failover logic for MPI

---

build.py
buildtools.py

I found some merge errors made when I moved these changes to master from the geo branch.  They didn't cause built failures, but they will cause merge problems when we merge the branch, and they were confusing.  Also, they didn't fix the problem caused by upgrades to the newest Xcode in Yosemite.
Jenkins is mostly blue with this.  The only jUnit test failure is one of the usual ones.  Furthermore, this does not affect the Java code, just the EE.

Fix makefile merge errors.

---

tests/geb/vmc/src/tests/FullDdlSqlTest.groovy

refresh the page and make a second attempt at running the
(DDL) SQL.

FullDdlSqlTest.groovy: if an error is detected, 

---

src/frontend/org/voltdb/compiler/PlannerTool.java

Add a couple of log entries in exception handlers.

Eng 9094 planner error stack trace

---

src/frontend/org/voltdb/ParameterConverter.java
src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/types/GeographyValue.java
tests/frontend/org/voltdb/TestParameterConverter.java

In VMC we pass points and polygons to stored procedures by passing a
well known text string.

Added support for point and polygon in VMC.

---

src/ee/common/Geography.hpp
src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/ee/expressions/geofunctions.cpp
src/ee/expressions/geofunctions.h
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

- numInteriorRings(): returns number of loops/rings for the given polygon 
- numPoints(): returns number of points the given polygon has. This is sum of number of points on different loops of polygon
- Longitude() and Latitude():  for longtitude and latitude for the given point

Eng 9363 geo func

---

src/hsqldb19b3/org/hsqldb_voltpatches/FunctionSQL.java
tests/frontend/org/voltdb/TestAdhocCreateStatementProc.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java

- Updated sql function char_length() logic so that it can be accept parameterized value in SP "char_length(?)".
- Update junit tests for char_length and octet_length
- Rearranged TestFunctionsForVoltDBSuite test suite's initialization code.

fix for char_length() and update junit tests

---

src/frontend/org/voltdb/PartitionDRGateway.java

Change-Id: I77145e2ffaa77ba78f773343e67203ef0fbaa341

ENG-9455: Interface changes to match pro.

---

src/frontend/org/voltdb/types/GeographyValue.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/types/TestGeographyValue.java

Add more validation to frontend to check if polygon is valid
- Start and end point of polygon are equal
- Each loop in polygon are composed for 4 vetrices  = First 3 vertices +  end vertex which is same as start vertex.
- There is atleast one loop in the polygon.

Enhance basic validation for polygon in frontend

---

src/ee/executors/nestloopindexexecutor.cpp
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
src/frontend/org/voltdb/plannodes/NestLoopIndexPlanNode.java
tests/frontend/org/voltdb/planner/TestPlansSubQueries.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/fixedsql/fixed-sql-ddl.sql

Also rolled back fixes for ENG-9389 and ENG-9533, which were problematic; I left the tests though, and this fix addresses both of those issues.

Schema of the null_tuple for outer joins should match inner_tuple

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

Updated condition expression evaluation logic to take into Function expression can also return boolean when evaluating NOT operator expression.
- Tests in jenkins are currently underway. Community Junits have completed and is blue

updates for NOT contains()

---

examples/windowing-with-ddl/client/ddlwindowing/Reporter.java
examples/windowing-with-ddl/ddl.sql
examples/windowing/client/windowing/Reporter.java
examples/windowing/ddl.sql

Replaced instances of date computation using TO_TIMESTAMP with DATEADD in SQL. 
Had to modify the Java code in Reporter.java since I couldn't negate the input parameter (amount to add) in SQL.

Updated to_timestamp calls to use the new DATEADD function

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/TableCatalogDelegate.hpp

Huzefa already reviewed these changes months ago, but I never merged it. I have rebased from master and will merge it to master when jenkins goes blue.

Drop do-nothng ee class CatalogDelegate.

---

src/frontend/org/voltdb/utils/PolygonFactory.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java
tests/frontend/org/voltdb/utils/TestPolygonFactory.java

Add some tests for polygons with multiple holes.
Verify that contains works in polygons with multiple holes, and that the
distance and area functions do sensible things with multiple holes.
Verify that the order of the loops is not changed by S2.
Note that I did some testing of areas of polygons with multiple holes.
This was not strictly in the ticket, and was marked as a follow-on
ticket.  However, I misread the ticket in haste, and implemented it
anyway. It was pretty easy, given the remainder of the things I was
doing.
https://issues.voltdb.com/browse/ENG-9634

Eng 9634 polygon testing

---

src/ee/common/executorcontext.cpp

Change-Id: I7b54b9cc25f56045863dcb113de10e323b7ecee5

ENG-9317, always commit before switching DR streams.

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Add guards to prevent DR/export against table containing geo types.

+ Guards to DR and Export for Geo types

---

examples/README.md

Update the top level README too.

ENG-9757 Add geospatial to top level README`

---

tests/test_apps/kafkaimporter/build.xml
tests/test_apps/kafkaimporter/db/procedures/MatchRows.java

And remove a couple of Java 7 directives in build.xml.

ENG-9780 Add table specifier to column ref in join

---

src/frontend/org/voltdb/compiler/VoltCompiler.java

I believe this will fix ENG-9769, ENG-9777, ENG-9778.

Add null pointer check in debugVerifyCatalog

---

lib/python/vdm/server/HTTPListener.py
lib/python/vdm/server/Validation.py

Add tracebacks to all exception handling.
Fixed 2 minor bugs made findable by tracebacks.

VDM-11 add tracebacks to exception handling; fix 2 bugs revealed

---

README.thirdparty

Add OpenSSL to the README.thirdparty file.  This is a modified BSD license.

Add OpenSSL to the README.thirdparty file.

---

build.xml
src/frontend/org/voltdb/PostGISBackend.java
src/frontend/org/voltdb/PostgreSQLBackend.java
tests/scripts/SQLCoverageReport.py
tests/scripts/examples/sql_coverage/fuzzynormalizer.py
tests/scripts/examples/sql_coverage/geo-basic.sql
tests/scripts/examples/sql_coverage/geo-normalizer-4digits.py
tests/scripts/examples/sql_coverage/geo-normalizer.py
tests/scripts/examples/sql_coverage/normalizer.py
tests/scripts/examples/sql_coverage/not-a-normalizer.py
tests/scripts/examples/sql_coverage/nulls-first-normalizer.py
tests/scripts/examples/sql_coverage/nulls-highest-normalizer.py
tests/scripts/examples/sql_coverage/nulls-last-normalizer.py
tests/scripts/examples/sql_coverage/nulls-lowest-normalizer.py
tests/scripts/sql_coverage_test.py

Fixes the problem where an UPDATE was failing on Ubuntu 12.04 (only). Also adds some useful debug print options, and a few queries that Chris suggested in a previous review, which I had thought were already on master.

Eng 9853 sqlcov postgis jenkins

---

src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/CompatibleDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/ElasticHashinator.java
src/frontend/org/voltdb/LegacyHashinator.java
src/frontend/org/voltdb/TheHashinator.java
src/frontend/org/voltdb/jni/ExecutionEngine.java

Change-Id: I4183a3f917dcc9665417fc755fd39c974c0336b3

ENG-9697, generate DR test buffer for given partition.

---

src/ee/storage/persistenttable.cpp
tests/ee/storage/DRBinaryLog_test.cpp

Move the DR stream append around in the UPDATE/DELETE paths to make sure
it won't cause the operation half completed without proper rollback. The
UPDATE/DELETE code paths assume that certain part of the operation will
always succeed. If it fails in the middle of those critical sections,
things won't rollback.

ENG-9830: Fix DR buffer limit error handling.

---

src/ee/common/ElasticHashinator.h
src/ee/common/LegacyHashinator.h
src/ee/common/TheHashinator.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleDRTupleStream.cpp
src/ee/storage/CompatibleDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/storage/persistenttable.cpp
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/DRTupleStream_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

We're going to keep code in integration branch until we don't break the current system.

Eng 9552 revert

---

tests/geb/vmc/server/ddl.sql
tests/geb/vmc/src/resources/sqlQueries.txt
tests/geb/vmc/src/tests/SqlQueriesTest.groovy

Added GEOGRAPHY_POINT and GEOGRAPHY columns to VMC tests; and included tests of Stored Procedures passing null parameters (see ENG-9809, VMC-267). Also, added a new mechanism for specifying variables used repeatedly within the (SQL Query) tests, and used such variables to greatly simplify many of the tests, making them much more readable.

Eng 9506 vmc geb g

---

src/frontend/org/voltdb/NonVoltDBBackend.java
src/frontend/org/voltdb/PostGISBackend.java
src/frontend/org/voltdb/PostgreSQLBackend.java

Added a QueryTransformer class, and updated the transformQuery method to make use of it, adding QueryTransformer object definitions (and a few new query Patterns), and eliminating a bunch of specialized methods that transformQuery used to call.

Eng 9845 postgres backend

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/VoltProcedure.java

Change-Id: Iea192bbd5aeddf720e0a52f5a26e176ff070a2bf

ENG-9784, extend DRConsumerDrIdTracker's public APIs.

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/DRLogSegmentId.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_RO_SP.java

Change-Id: I62ff546589fa8c10182577b8f65a5147185db89c

ENG-9784, create the right intial ack DR id.

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java

Change-Id: I29f033a451078c401966312b080fc892ec9379ff

ENG-9787, add debug output for DRConsumerDrIdTracker

---

build.xml
src/frontend/org/voltdb/PostGISBackend.java
tests/scripts/SQLCoverageReport.py
tests/scripts/SQLGenerator.py
tests/scripts/examples/sql_coverage/advanced-template.sql
tests/scripts/examples/sql_coverage/configure-default.sql
tests/scripts/examples/sql_coverage/configure-for-decimal.sql
tests/scripts/examples/sql_coverage/configure-for-geo-point.sql
tests/scripts/examples/sql_coverage/configure-for-geo-polygon.sql
tests/scripts/examples/sql_coverage/configure-for-ints.sql
tests/scripts/examples/sql_coverage/configure-for-joins.sql
tests/scripts/examples/sql_coverage/configure-for-matview-nonjoin.sql
tests/scripts/examples/sql_coverage/configure-for-matview-subq-nonjoin.sql
tests/scripts/examples/sql_coverage/configure-for-string.sql
tests/scripts/examples/sql_coverage/configure-for-subq-joins.sql
tests/scripts/examples/sql_coverage/configure-for-timestamp.sql
tests/scripts/examples/sql_coverage/configure-for-varbinary.sql
tests/scripts/examples/sql_coverage/fuzzynormalizer.py
tests/scripts/examples/sql_coverage/geo-basic.sql
tests/scripts/examples/sql_coverage/geo-normalizer-4digits.py
tests/scripts/examples/sql_coverage/geo-normalizer.py
tests/scripts/examples/sql_coverage/grammar.sql
tests/scripts/examples/sql_coverage/normalizer.py
tests/scripts/examples/sql_coverage/not-a-normalizer.py
tests/scripts/examples/sql_coverage/nulls-first-normalizer.py
tests/scripts/examples/sql_coverage/nulls-highest-normalizer.py
tests/scripts/examples/sql_coverage/nulls-last-normalizer.py
tests/scripts/examples/sql_coverage/nulls-lowest-normalizer.py
tests/scripts/sql_coverage_test.py

Reduced the number of invalid queries; added tests of DWithin; and various other minor improvements

Eng 9844 sqlcov less invalid

---

src/ee/storage/TableCatalogDelegate.cpp
src/frontend/org/voltdb/utils/CatalogSizing.java

Also set "countable" attribute correctly

Update catalog sizing for geo indexes

---

src/frontend/org/voltdb/client/ClientImpl.java

add guards for non-positive timeout fix

---

build.xml
examples/README.md
examples/contentionmark/ContentionMark.java
examples/contentionmark/README.md
examples/contentionmark/ddl.sql
examples/contentionmark/run.sh

ContentionMark Readme:
> ContentionMark is a small VoltDB application that measures VoltDB throughput under extreme contention. How extreme? By default, ContentionMark creates one row, then updates it as fast as VoltDB will let it, one transaction per update.
Also fix some geospatial example omissions in build.xml

Add a new example named ContentionMark.

---

lib/python/voltcli/checkconfig.py
lib/python/voltcli/environment.py
lib/python/voltcli/utility.py

Seems that voltdb checkconfig does not check JAVA_HOME first.

ENG-9969: AAUIW a better error if I voltdb creat with Java 1.7

---

src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/ee/expressions/geofunctions.cpp
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

Define polygonfromvalidtext, a validating polygonfromtext.
The function polygonfromvalidtext constructs a polygon and the validates
it using the standard isvalid tests.
https://issues.voltdb.com/browse/ENG-9695

Eng 9695 validating polygon

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_RO_SP.java

- Add copy constructor to the tracker.
- Extract tracked data JSON serialization code into a method.

ENG-9849: Tracker collection refactor.

---

src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/ee/expressions/geofunctions.cpp
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/compiler/TestDDLCompiler.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java

https://issues.voltdb.com/browse/ENG-10053

Renamed a misnamed function.

---

src/frontend/org/voltdb/InvocationSysprocPermissionPolicy.java
tests/frontend/org/voltdb/TestInvocationAcceptancePolicy.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java

https://issues.voltdb.com/browse/ENG-9904

Change an error message to avoid using the deprecated sysproc role.

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

- Configurable max clock skew via `MAX_CLOCKSKEW` system property.
- Change default max clock skew to 200ms.
- Change warning threshold to 100ms.

ENG-10049: Change clock skew threshold.

---

src/ee/common/NValue.hpp
tests/ee/common/elastic_hashinator_test.cpp

Correctly calculate the hash token for numbers.

ENG-10019: Fix EE NValue hash token.

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java

Change-Id: I2172906aa99a84ef912e3c19bb86e325bdfe2e6c

ENG-9547, remove unsed function.

---

tests/frontend/org/voltdb/utils/TestVoltBulkLoader.java

We test the bulk loaders with geo types.
https://issues.voltdb.com/browse/ENG-9922

Test the bulk loaders with geo types.

---

src/ee/storage/BinaryLogSink.cpp

Change-Id: I244a153c8c23ac0a362a0020ad58c6c11959b921

ENG-9547, fix assertion failure.

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

Change-Id: Ia97d04e28e19313b048ffac2b4599dac157d8c83

ENG-9977, stores table name to partition column mapping in dispatcher.

---

src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java

Change-Id: I04af1103989da1cf5d542d4c2d7542eb3d97981e

ENG-10144, fix the case that DR can't recover right after sync snapshot.

---

src/frontend/org/voltdb/RealVoltDB.java

Use the correct set of partition leaders to initialize DR consumer on
catalog update.

ENG-10173: Fix DR consumer enablement.

---

src/catgen/in/javasrc/CatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java

Allow users to locally add, drop and modify columns in DR tables

ENG-10222: Allow all supported online schema change on DR tables

---

src/ee/storage/BinaryLogSink.cpp
src/ee/storage/CompatibleBinaryLogSink.cpp

Include the table name and the action type in the deserialization
exception.

ENG-10235: Add context to DR binary log deserialization errors in EE.

---

src/frontend/org/voltdb/InternalAdapterTaskAttributes.java
src/frontend/org/voltdb/InternalClientResponseAdapter.java
src/frontend/org/voltdb/importer/AbstractImporter.java
src/frontend/org/voltdb/importer/formatter/builtin/VoltCSVFormatter.java

Log warn message in callbacks rather than InternalClientResponseAdapter

ENG-10074 error logging for importers

---

tests/frontend/org/voltdb/utils/TestCSVLoader.java

Modified TestCSVLoader.java (base class of TestCSVLoaderSnapshot.java): added Geo column types (GEOGRAPHY_POINT and GEOGRAPHY) to most test methods; then fixed two (testNULL, testColumnLimitSize); improved one (testNoQuotesSpecialSeparator); and added new ones: testNoQuotesNonCommaSeparator, testGeographyPointStringRoundTrip, testGeographyStringRoundTrip.

Eng 9939 geo csv snapshot loader

---

src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/executors/updateexecutor.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/temptable.cpp
src/ee/storage/temptable.h
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/ee/storage/persistenttable_test.cpp
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestJoinsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpsertSuite.java

* ENG-10072 upsert and defaults
Conflicts:
src/ee/storage/persistenttable.h
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
* Fix licensecheck
* Fix ee test build error

Eng 10072 upsert backpatch for 5.8.x -- cherry pick of the 5.9.x backpatch.

---

src/frontend/org/voltdb/importclient/kafka/KafkaTopicPartitionImporter.java
src/frontend/org/voltdb/importclient/socket/PullSocketImporter.java
src/frontend/org/voltdb/importclient/socket/ServerSocketImporter.java

Consume data transform exceptions and let importer continue its service.

ENG-10280 Kafka/PullSocket importers Data Format 

---

src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java

Change-Id: I99ba2ea48e9cfc2ae696f8df1695bff952e874be

ENG-10287, fix a bug that causing dr reset crashes EE.

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

add a blocker for each rejoin node (/db/rejoin_nodes_blocker/host_x) during rejoining process
I used hostId as the identifier for each blocker.. So I just used  CreateMode.EPHEMERAL.

ENG-10194; disable @StopNode while rejoining node still in process

---

src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/executors/updateexecutor.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/temptable.cpp
src/ee/storage/temptable.h
src/frontend/org/voltdb/planner/PlanAssembler.java
tests/ee/indexes/CoveringCellIndexTest.cpp
tests/ee/storage/persistenttable_test.cpp
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpsertSuite.java

Cwolff upsert backport 6.1.x

---

tools/ycsb-graphs.py

a tool for generating ycsb graphs with zipfian values

Eng 10297 ycsb graphs

---

src/ee/storage/BinaryLogSink.cpp

In this version, the compatible protocol version is the same as the
latest protocol version, so it will never use the compatible sink during
up/downgrade.

ENG-10219: Add optimized DR deserialization back to the sink.

---

src/frontend/org/voltdb/InternalConnectionHandler.java
tests/frontend/org/voltdb/TestImportStatistics.java

fixing broken TestImportStatis Test due to ENG-10064 backpressure change

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

ENG-10194: disable @StopNode while rejoining node still in process

ENG-10335: Backport ENG-10194

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

* ENG-10194: disable @StopNode while rejoining node still in process
* address the review
* safe error handling for check rejoin nodes existence

ENG-10335: Backport ENG-10194 to V6.2.x

---

tests/frontend/org/voltdb/TestImportStatistics.java

second attempt to fix broken TestImportStatistics test

Use Statistic Initior Invocation for TestImportStatistics

---

src/ee/storage/AbstractDRTupleStream.cpp

Change-Id: Ia98e9f61fe3a03f34a68ffd9d3dd121e50844446

ENG-10422, fix TestHiddenColumnSnapshot test failure.

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserCommand.java
src/hsqldb19b3/org/hsqldb_voltpatches/Statement.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementManager.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementSchemaDefinition.java
src/hsqldb19b3/org/hsqldb_voltpatches/scriptio/ScriptReaderText.java

getSchemalName() ===> getSchemaName()

Fix a typo in HSQL Statement.java

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java

Remove extra debug logging.
Rework partition detection error messages.
Add warning if you config the partition snapshot prefix.
Possibly better PD+Graceful shutdown path.

ENG-10453: Some post-master-merge updates to the lost writes issue.

---

src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/utils/HTTPAdminListener.java

and truststore instead of trustStore.

ENG-9908: Changed xml element names to keystore instead of keyStore

---

tests/geb/vmc/build.gradle
tests/geb/vmc/src/resources/sqlQueries.txt
tests/geb/vmc/src/tests/SqlQueriesTest.groovy

Replaced the failing verifyTestForSingleQuote() test, and updated the (default) seleniumVersion to the current one (2.53.0), and likewise httpunitVersion (2.21).

Eng 10137 vmc geb minor fixes

---

src/frontend/org/voltdb/plannodes/AbstractJoinPlanNode.java

Removed code repeated for no apparent reason from 40 lines prior. Jenkins passes fine without it.

resolveColumnIndex Experiment 1

---

src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SysProcDuplicateCounter.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java
src/frontend/org/voltdb/sysprocs/AdHocBase.java

Even the SQL you were running for adhoc.
This will hopefully come in handy if we can reproduce ENG-10518 again.

ENG-10518: Lots more debugging and general safety for hash mismatch code

---

src/frontend/org/voltdb/export/ExportDataSource.java

ENG-10545: Make truncate as first stashed task.

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompilerErrorMsgs.java

Add unit tests for same (there were none).

Fix logic for row length check

---

src/ee/storage/persistenttable.cpp

Verified accuracy of log statements manually.

Added duration of forced compaction to log message

---

src/frontend/org/voltcore/messaging/ForeignHost.java
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
tests/frontend/org/voltdb/utils/OverprintingStatusListener.java

ENG-10486: Remove temporary timer from test case
ENG-10486: Add utility class that prints client events.
ENG-10486: Remove changes to LocalCluster
ENG-10486: Add some newlines to print stmts
ENG-10486: Make link-cut code in foreign host work correctly.

ENG-10486: Support code for test that so far fails to reproduce issue.

---

src/frontend/org/voltdb/client/VoltBulkLoader/VoltBulkLoader.java
src/frontend/org/voltdb/utils/CSVBulkDataLoader.java
src/frontend/org/voltdb/utils/CSVDataLoader.java
src/frontend/org/voltdb/utils/CSVFileReader.java
src/frontend/org/voltdb/utils/CSVLoader.java
src/frontend/org/voltdb/utils/CSVTupleDataLoader.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java
third_party/java/src/org/supercsv_voltpatches/tokenizer/Tokenizer.java

ENG-9000: csvloader with --header option

ENG-9000: csvloader with --header option

---

lib/python/vdm/server/HTTPListener.py
lib/python/vdm/server/voltdbserver.py

(1)flip force stop server flag
(2)fix VoltDatabase.kill_server()

VDM-127 VDM stop node REST API

---

tests/frontend/org/voltcore/zk/TestStateMachine.java

Fix one of the unit test to account for the race condition

ENG-10229: Fix TestStateMachine

---

buildtools.py
src/ee/common/NValue.hpp
src/ee/expressions/datefunctions.h
src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/frontend/org/voltdb/expressions/FunctionExpression.java
src/frontend/org/voltdb/jdbc/JDBC4DatabaseMetaData.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
template.classpath
tests/ee/expressions/function_test.cpp
tests/ee/test_utils/vdbsuppressions.supp
tests/frontend/org/voltdb/fullddlfeatures/fullDDL.sql
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java

This commit adds the timestamp validity functions MIN_VALID_TIMESTAMP,
MAX_VALID_TIMESTAMP and IS_VALID_TIMESTAMP.
Along with this we added a valgrind suppression file which suppresses
false positive memory leak warnings. We also added a boolean comparison
in the EE. This is necessary to test the results of boolean valued
functions. Finally, we added a testNullary() test operation in the EE
tests.
https://issues.voltdb.com/browse/ENG-10559

Add time stamp validity functions.

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/iv2/SpDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java

Added the guard against no-op CompletionChecks

ENG-10443: restore uses excessive heap gc time

---

src/frontend/org/voltdb/ProcedureRunner.java

If the partitioning of a procedure is changed from MP to SP or vice
versa while there are in-flight transactions, these transactions should
be gracefully failed. Restarting them as mispartitioned invocations
enters an infinite loop of retry.

ENG-10639: Gracefully fail transaction on partitioning change.

---

src/frontend/org/voltdb/ConsumerDRGateway.java

Change-Id: I871311a24f4d77911e317c83d91b2ee4e315a16e

ENG-9665, add dispatcher isLeader() public API to dr gateway.

---

src/frontend/org/voltdb/DRLogSegmentId.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

make debug output more readable.
Change-Id: I9dcdcbd26a0d9fa18437a6acddef23e5995d922b

ENG-10481, change the covering host computing algorithm.

---

src/ee/voltdbipc.cpp
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
tests/frontend/org/voltdb/regressionsuites/EEProcess.java
tests/frontend/org/voltdb/regressionsuites/TestQueryTimeout.java

When enabled, it now crawls a few more steps forward before hanging.

ENG-7843 fix ipc hang by disabling fragmentProgressUpdate ipc callback

---

tests/ee/storage/serialize_test.cpp

Both fixes reviewed in separate pull requests.

ENG-10770 ENG-10784 Combined Fix

---

build.py
src/frontend/org/voltdb/planner/PlanSelector.java
tests/ee/execution/engine_test.cpp
tests/ee/executors/TestGeneratedPlans.cpp
tests/ee/test_utils/LoadTableFrom.hpp
tests/ee/test_utils/plan_testing_baseclass.h
tests/ee/test_utils/plan_testing_config.h
tests/ee/test_utils/testing_topend.h
tests/frontend/org/voltdb/planner/PlannerTestAideDeCamp.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java
tests/frontend/org/voltdb/planner/TestPlansEEGenerators.java
tests/frontend/org/voltdb/planner/testplans-ee-generators.sql

See TestPlansEEGenerators.java for an example.

Add the ability to create EE unit tests to execute plans from Java.

---

tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

Change-Id: Ia9fe448de8a00083d8fa4e37b39796118dd4f20e

ENG-10358, fix eecheck.

---

lib/python/voltcli/utility.py

simply convert all args to string type for starting as daemon.
Otherwise need to change hostcount option in "start.py" verb.

ENG-10871: fix newCLI background mode (-B)

---

src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/client/ClientImpl.java
src/frontend/org/voltdb/client/Distributer.java
tests/frontend/org/voltdb/client/TestDistributer.java

Offer clientconfig option to round-robin them among replicas like previous behavior.
No real tests :-(, but a pretty trivial change that should show up in perf numbers if right.

ENG-10679: Route reads to SPIs by default.

---

src/frontend/org/voltcore/network/VoltNetwork.java
src/frontend/org/voltcore/network/VoltNetworkPool.java

Add method to VoltNetworkPool to get all connections an instance is managing

ENG-10816: Close stale DR producer connections when new connection comes

---

src/frontend/org/voltdb/jdbc/JDBC4Connection.java

Eng 10824 spark tweak to make JDBC in spark work

---

tests/ee/executors/TestGeneratedPlans.cpp
tests/frontend/org/voltdb/planner/EEPlanTestGenerator.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java

For review only.
Before merging to master, any generated EE test files currently checked into github should be re-generated based on the new template introduced here. I don't yet know how to do that.

Add Copyright generation to EE test generator to satisfy license check.

---

tests/test_apps/ycsb/README
tests/test_apps/ycsb/run.sh
tests/test_apps/ycsb/src/com/yahoo/ycsb/db/VoltClient4.java

- Make our client compatible with newest ycsb distribution (ycsb-0.10.0).
- Change script path to reflect path changes in newest ycsb version.
- Modify README to download newest ycsb version.

ENG-9289: Update YCSB driver and run script.

---

build.py
src/ee/common/GeographyPointValue.hpp
third_party/cpp/google-s2-geometry/geometry/include/s2geo/util/math/mathutil.h

No clue if this will break old stuff yet.

Small fixes for xcode 8.

---

tests/sqlcmd/baselines/errors/stackoverflow.outbaseline
tests/sqlcmd/scripts/errors/stackoverflow.in

I added 100 more predicates to the statement that is supposed to fail with a stack overflow error.  Hopefully this will make the test pass consistently.

ENG-11104: sqlcmdtest sporadically fails

---

tests/scripts/examples/sql_coverage/analytic-template.sql

tests of SQL Analytic (Window) functions.

analytic-template.sql: added DENSE_RANK, as an alternative to RANK, in

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/compiler/ClusterConfig.java
src/frontend/org/voltdb/iv2/Cartographer.java
tests/frontend/org/voltdb/compiler/TestClusterCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

Companion pro PR https://github.com/VoltDB/pro/pull/1483

Eng 10842 mixed sph

---

lib/python/voltcli/cli.py
lib/python/voltcli/voltadmin.d/save.py
src/frontend/org/voltdb/SnapshotInitiationInfo.java
src/frontend/org/voltdb/utils/SQLCommand.java

Revert "ENG-11036: voltadmin save with no arguments"

---

src/ee/storage/DRTupleStream.h
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/DRConsumerMpCoordinator.java
src/frontend/org/voltdb/DRIdempotencyResult.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/UniqueIdGenerator.java
src/frontend/org/voltdb/messaging/Dr2MultipartResponseMessage.java
src/frontend/org/voltdb/messaging/Dr2MultipartTaskMessage.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
tests/frontend/org/voltdb/TestDRConsumerDrIdTracker.java

- Upped the protocol version.
- Added two message types.
- New internal mailbox ID for the coordinator.
- Pushed the producer partition ID into the tracker.

ENG-10524: MP support for DR

---

src/ee/execution/ProgressMonitorProxy.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/executors/abstractexecutor.h
src/ee/storage/temptable.h
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

Reviewed on separate branch, #3966

ENG-11180: Avoid crash during long-running view creation

---

src/ee/storage/AbstractDRTupleStream.h
src/frontend/org/voltdb/StoredProcedureInvocation.java
tests/frontend/org/voltdb/TestStoredProcedureInvocation.java

We already support deserializing different versions of SPI. This is to
add serialization of different versions for DR.

ENG-11259: Support versioned StoredProcedureInvocation serialization.

---

tests/geb/vmc/src/tests/NavigatePagesBasicTest.groovy
tests/geb/vmc/src/tests/TestBase.groovy

This should fix the test-nextrelease-vmctest-headless-basic Jenkins job, which has been failing ever since my Innovation Week work.

Johnc innov vmcgeb navpages

---

lib/python/voltcli/hostinfo.py
lib/python/voltcli/voltadmin.d/rebalance.py
lib/python/voltcli/voltadmin.d/stop.py
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/SystemProcedureCatalog.java

Created infrastructure for new stored proc @Rebalance.

ENG-11055: Infrastructure for @Rebalance

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java

https://issues.voltdb.com/browse/ENG-10939

Fix ENG-10939 stored procedure has wrong parameter count

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SystemInformationAgent.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/settings/DbSettings.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestPlannerTool.java

Address @vtkstef 's comments on mixed sph PR. 
Pro-side PR: https://github.com/VoltDB/pro/pull/1542
Change-Id: Icf5ea9efe3e20286f2406c2585c5f4e572ff5ad9

ENG-11322, cache local sites count into catalog context.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SystemInformationAgent.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/settings/DbSettings.java
src/frontend/org/voltdb/settings/PathSettings.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestPlannerTool.java

Revert "ENG-11322, cache local sites count into catalog context."

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SystemInformationAgent.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/settings/DbSettings.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestPlannerTool.java

plus some other optimizations.
Change-Id: Icf5ea9efe3e20286f2406c2585c5f4e572ff5ad9

ENG-11322, integrate mixed sites per host support with the new CLI framework.

---

src/frontend/org/voltdb/AdHocAcceptancePolicy.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InternalClientResponseAdapter.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/Iv2TransactionCreator.java
src/frontend/org/voltdb/RestoreAgent.java
src/frontend/org/voltdb/UpdateCatalogAcceptancePolicy.java
src/frontend/org/voltdb/UpdateClassesAcceptancePolicy.java
src/frontend/org/voltdb/dtxn/TransactionCreator.java

related to [pro pull request](https://github.com/VoltDB/pro/pull/1551)

ENG-11348 allow recover snapshot restore for replica clusters

---

src/frontend/org/voltdb/RealVoltDB.java

Change-Id: I21be7d4fdf9d9003dc5d32c44964465135904549

ENG-11363, fix failing unit test.

---

src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/IndexCountPlanNode.java
src/frontend/org/voltdb/plannodes/IndexScanPlanNode.java
src/frontend/org/voltdb/plannodes/PlanNodeTree.java
third_party/java/src/org/json_voltpatches/JSONObject.java
third_party/java/src/org/json_voltpatches/JSONStringer.java
third_party/java/src/org/json_voltpatches/JSONWriter.java

This may be easier to review commit-by-commit. 
All-at-once, it diffs like a complete rewrite -- which it really isn't (quite).

Rework json writer before performance tweak.

---

src/ee/storage/persistenttable.cpp

I committed this change in my changeset for [ENG-11017](https://issues.voltdb.com/browse/ENG-11017), but it was not finally merged.
The change is a logic flaw in truncate table code. Our compromised fix for ENG-11017 prevented this flaw to manifest as a bug. But I think we need to merge this anyway.

Logic fix for view source table truncate

---

lib/python/voltcli/checkstats.py
lib/python/voltcli/voltadmin.d/pause.py
lib/python/voltcli/voltadmin.d/shutdown.py

graceful shutdown: 
wait for in-flight txns, importer, dr consumer, async cmdlog txns fsynced.
shutdown --save and voltadmin pause --wait: 
wait for in-flight txns, importer, dr consumer, async cmdlog txns fsynced, exporter, and dr producer.

ENG-11432 check various stats for shutdown and pause

---

src/frontend/org/voltdb/AbstractTopology.java
src/frontend/org/voltdb/utils/TopologyZKUtils.java
tests/frontend/org/voltdb/TestAbstractTopology.java

merge to master without any integration first, work on improvement/integration iteratively.

Eng 11089 bg merge to master branch

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/compilereport/ReportMaker.java
src/frontend/org/voltdb/compilereport/ViewExplainer.java
tests/frontend/org/voltdb/compilereport/TestReportMaker.java
tests/frontend/org/voltdb/regressionsuites/TestExplainCommandSuite.java
tests/geb/vmc/README.md
tests/sqlcmd/baselines/simple/explain.outbaseline

This pull request addressed the following issues:
* Integrated Andrew's comments about the presentation of the table.
* Refactored the code for generating the `ExplainView` table. A new class `ViewExplainer` was created so that both `ReportMaker` and `ExplainView` system procedure and share the same code for table generation.
* Added a ReportMaker test case to verify the HTML table generated in VMC is correct.

ENG-11149 explainview vmc

---

lib/python/voltcli/checkstats.py
lib/python/voltcli/voltadmin.d/shutdown.py

The messages have been updated per specification.

ENG-11432 update shutdown messages

---

lib/python/voltcli/voltadmin.d/pause.py

remove the newly added stats check for voltadmin pause --wait

ENG-11465  remove stats check

---

lib/python/voltcli/checkstats.py
lib/python/voltcli/voltadmin.d/shutdown.py

move dr consumer stats check to **voltadmin shutdown --save**

ENG-11480 move dr consumer stats check to voltadmin shutdown

---

src/frontend/org/voltdb/pmsg/DRAgent.java
src/protobuf/dragent.proto

Removed unused fields and added support for multiple clusters.
**PLEASE DON'T DELETE THE BRANCH AFTER MERGE.**

ENG-11263: DR query response format change.

---

src/frontend/org/voltdb/client/ClientImpl.java
src/frontend/org/voltdb/client/Distributer.java

Change the executor service termination waiting time from seconds to days.

ENG-11131 change executor service termination waiting time on client

---

tests/test_apps/txnid-selfcheck2/run.sh
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/ddl.sql

no catalog, use build.xml,
use init/start,
fix log4j client issue if running from the pro kit.

ENG-11498 Fix and update run.sh --

---

src/ee/common/types.cpp
src/frontend/org/voltdb/compiler/VoltCompilerUtils.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/utils/InMemoryJarfile.java

This is a backport of two fixes cherry-picked from master:
ENG-10722
and
ENG-11362

Backport optimizations for catalog update

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/licensetool/LicenseApi.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

Add more fields.
Change logic a bit.
Preliminary support for AWS license.
Needs a few more tests.
Companion pro pull: https://github.com/VoltDB/pro/pull/1599

ENG-11431: License file format next-gen

---

src/ee/common/types.h
src/ee/storage/DRTupleStream.cpp
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/pmsg/DRAgent.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/protobuf/dragent.proto

Leader cluster determination, joiner stream_start event, multicluster snapshot process.
- New DR_STREAM_START event creation on setDRProtocolVersion.
- Exposed setDRProtocolVersion in ProducerDRGateway interface to be called by joiner consumer.
- Exposed createDispatcher and startCursor methods in ConsumerDRGateway interface.

ENG-11492, ENG-11267:

---

src/frontend/org/voltdb/InvocationDispatcher.java

Change-Id: I40bbe33de5b8086497ff849d9116e2d3fd0e590b

ENG-11596, remove a misuse of Precondition.checkArgument() on performance-critical path.

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/DRProducerNodeStats.java
src/frontend/org/voltdb/DRRoleStats.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

- Moved DRNodeStats to community.
- Consolidated DR producer states with the state in DRROLE class.
- The DRROLE stats reported by each node will be aggregated into a
single cluster-wide row in the response.

ENG-11458: Add DRROLE statistics.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/SocketJoiner.java
src/frontend/org/voltcore/zk/CoreZK.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/TestClientInterface.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestPlannerTool.java

FYI, the original PR is here https://github.com/VoltDB/voltdb/pull/4101

ENG-11595, address review comments left on ENG-11442.

---

src/frontend/org/voltdb/RealVoltDB.java

Remove rejoin blocker on Zk when a rejoin is done.

ENG-11667 remove blocker for rejoin

---

src/ee/storage/ElasticContext.cpp
src/frontend/org/voltdb/compiler/VoltCompilerUtils.java
src/frontend/org/voltdb/utils/InMemoryJarfile.java

ENG-10358 - deletes/compaction/scan problem
ENG-11362 - less memory use when updating procedures

Multibug backportv6.6

---

src/frontend/org/voltdb/RealVoltDB.java

Leave the deregistration to the consumer DR gateway.

ENG-11629: DR consumer dummy statistics registration refactor.

---

tests/test_apps/uacbench/README
tests/test_apps/uacbench/classtemplate.txt
tests/test_apps/uacbench/client/uac/UpdateClassesBenchmark.java
tests/test_apps/uacbench/run.sh
tests/test_apps/uacbench/uacbench.py

TODO: delete/update procedures.
It's a UAC benchmark specifically for UpdateClasses.

ENG-11472: Add a UpdateClasses benchmark for creating procedures.

---

src/frontend/org/voltdb/AbstractTopology.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/utils/TopologyZKUtils.java
tests/frontend/org/voltdb/TestAbstractTopology.java
tests/frontend/org/voltdb/iv2/TestCartographer.java

Change-Id: Ie9074faf89254deaa4a58f02c0dfad18fc41bcfc

ENG-11587, fix the rack-aware rejoin issue on partition group algorithm.

---

src/frontend/org/voltdb/ConsumerDRGateway.java

Add more debug output to initialization and minor cleanup previously merged pull request

ENG-11705:

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/zk/CoreZK.java
src/frontend/org/voltdb/RealVoltDB.java

back port the fix for the joining issue (ENG-11752)

ENG-11752-fix-join backport a fix for joining

---

tests/test_apps/adhocbenchmark/run.sh
tests/test_apps/measure-overhead/run.sh
tests/test_apps/overhead/ddl.sql
tests/test_apps/overhead/run.sh
tests/test_apps/scans/run.sh
tests/test_apps/schemachange/run.sh

more tests that need legacycompile option added.

Eng 11768 use legacycompile system tests

---

src/frontend/org/voltdb/compiler/VoltProjectBuilder.java

ENG-11459: Fix TestVoltLicense

---

build.py
tests/ee/storage/persistenttable_test.cpp

Also make ee tests build in non-debug mode.

Make system build on GCC 6.x and on U16.10.

---

src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/AbstractScanPlanNode.java
src/frontend/org/voltdb/plannodes/MaterializePlanNode.java
tests/frontend/org/voltdb/compilereport/TestReportMaker.java
tests/frontend/org/voltdb/planner/TestPlansDML.java
tests/frontend/org/voltdb/planner/TestUnion.java
tests/frontend/org/voltdb/regressionsuites/TestSqlUpdateSuite.java

Made The ReportMaker to reflect subquery plans within DML/DQL statements.
Addressed code review comments

Eng 6281 subquery expression dml

---

tests/frontend/org/voltdb/regressionsuites/TestSqlUpdateSuite.java

Fix broken junit test

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

skip VoltLog4jLogger class loading for sqlcmd.

ENG-11932 skip class loading for sqlcmd

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

backport:  skipping VoltLog4jLogger lookup with sqlcmd.

ENG-11932 backport skip class loading

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

backport: skip VoltLog4jLogger lookup with sqlcmd

ENG-11932 skip VoltLog4jLogger lookup with sqlcmd

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

Revert "ENG-11932 skip VoltLog4jLogger lookup with sqlcmd"

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

Revert "ENG-11932 backport skip class loading"

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/utils/SQLCommand.java

Revert "ENG-11932 skip class loading for sqlcmd"

---

src/frontend/org/voltdb/planner/PlanAssembler.java
tests/frontend/org/voltdb/planner/TestPlansSetOp.java

Reset Set Op partitioning from the common partitioning only if plan compiled

PlanAssebler Set Op NPR

---

src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/ProcedureStatsCollector.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SiteStatsSource.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSource.java
tests/frontend/org/voltdb/TestVoltProcedure.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestProcedureStats.java

Keep UAC stats after catalog update.

Eng 11743 stats no reset

---

tests/test_apps/uacbench/client/uac/UpdateClassesBenchmark.java

Instead of only reporting end to end time, we want to know the block time of UAC as well.

ENG-11865: Report UAC block time

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/ProcedureRunnerFactory.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/VoltProcedure.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/AdHocBase.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_SP.java
src/frontend/org/voltdb/sysprocs/LoadMultipartitionTable.java
src/frontend/org/voltdb/sysprocs/LoadSinglepartitionTable.java
src/frontend/org/voltdb/sysprocs/Pause.java
src/frontend/org/voltdb/sysprocs/PrepareShutdown.java
src/frontend/org/voltdb/sysprocs/ProfCtl.java
src/frontend/org/voltdb/sysprocs/Quiesce.java
src/frontend/org/voltdb/sysprocs/Resume.java
src/frontend/org/voltdb/sysprocs/Shutdown.java
src/frontend/org/voltdb/sysprocs/Statistics.java
src/frontend/org/voltdb/sysprocs/SystemCatalog.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/sysprocs/UpdateLogging.java
src/frontend/org/voltdb/sysprocs/UpdateSettings.java
src/frontend/org/voltdb/sysprocs/ValidatePartitioning.java

This PR does not have functional changes, but only code cleanup. It tries to simplify the LoadedProcedureSet.java and make it less dependent or correlated with other members. 
It has a corresponding PR on Pro.

Eng 11642 code cleanup

---

src/ee/execution/ProgressMonitorProxy.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/executors/abstractexecutor.h
src/ee/storage/temptable.h
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

ENG-11180 started on V6.6 and was causing a junit test to fail, so I am opportunistically backporting to give to customer who requested another fix.

Eng 11180 backport6.6

---

src/frontend/org/voltdb/HealthMonitor.java

manual tested with 2nk1 fail one

ENG-12033: change logging level when DRrole query timeout

---

lib/python/voltcli/voltdb.d/start.py

show --missing option via "voltdb help start"

ENG-11637 reveal --missing option on cli help

---

lib/python/voltcli/voltdb.d/get.py
src/frontend/org/voltdb/GetActionArgument.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/regressionsuites/TestInitStartLocalClusterAllOutOfProcess.java
tests/frontend/org/voltdb/regressionsuites/TestInitStartLocalClusterInProcess.java

Support for "voltdb get classes" command

Get classes cli command

---

tests/sqlgrammar/sql_grammar_generator.py

Modified sql_grammar_generator.py, adding a 'seed' option - and print out the random seed that was used (and whether it was specified via the option or generated randomly), so that we can replicate the results (just as SqlCoverage already does).

Eng 12081 grammar seed

---

tests/sqlgrammar/sql_grammar_generator.py

the number of certain types of error messages found in the log or
console output files, e.g.:
Number of 'Error compiling query' errors: 2
Number of 'ERROR: IN: NodeSchema' errors: 5
Number of all other error messages      : 0
Total Number of all 'ERROR' messages    : 7
(that example is from a one-minute run on my laptop).

sql_grammar_generator.py: added (to the summary file) messages giving

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/TruncateTableLoader.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/TxnId2Utils.java

problem (I think); and it now double-checks that there are zero rows,
after a TRUNCATE (except with SP).

txnid2: fixed the 'call to TruncateTable or SwapTable changed row count'

---

src/frontend/org/voltcore/logging/VoltLog4jLogger.java
src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/sysprocs/UpdateLogging.java
tests/frontend/org/voltdb/MockVoltDB.java

Change-Id: I42294f3d45473e10158ed8b139295cc139464b68

ENG-12115, make default for relative path used in file based log4j logger to voltDB root

---

src/frontend/org/voltdb/RealVoltDB.java

The Consumer was not started on rejoined hosts because they were only initialized on create and recover. In addition, as part of initialization, the DR code determines whether this cluster is the original data source, and if not, it verifies that there are valid site trackers for the data source cluster (implying that the snapshot completed). However, for rejoin, this check would be done on the Site thread causing a deadlock. Therefore, Starting the DR services is now always done on a seperate executor thread.
Note that this is the periodic work thread, which will block until the site trackers are returned. Therefore, scheduled work will also block until DR initialization completes.

ENG-12128:

---

src/frontend/org/voltdb/planner/ParsedSelectStmt.java
tests/frontend/org/voltdb/planner/TestWindowedFunctions.java

We never intended to support group by with window functions.  Aggregate
functions are a kind of implicit group by, so they are not supported
either.
https://issues.voltdb.com/browse/ENG-12146

Aggregate functions and window functions together are not supported.

---

tests/test_apps/kafkaimporter/client/kafkaimporter/KafkaImportBenchmark.java

benchmark constructor in offset test, a special case.

ENG-12148 Pass config to endTest since it can recede setting in

---

src/frontend/org/voltdb/RealVoltDB.java

Change-Id: I91575d053551ea5ff6e0946d7af2f55887951b83

ENG-12065, skip the ascii art if start action is initialize.

---

lib/python/voltcli/clusterinfo.py
lib/python/voltcli/runner.py
lib/python/voltcli/voltadmin.d/status.py
src/frontend/org/voltdb/sysprocs/SystemInformation.java

to monitor multiple-cluster status.
Companion pro branch https://github.com/VoltDB/pro/pull/1823

ENG-12050, new command "voltadmin status" 

---

build.xml
src/frontend/org/voltdb/InProcessVoltDBServer.java
src/frontend/org/voltdb/ServerThread.java
src/frontend/org/voltdb/client/AllPartitionProcedureCallback.java
src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/types/TimestampType.java
src/frontend/org/voltdb/utils/SQLCommand.java

ENG-12219: Add InProcessVoltDBServer to regular voltdb.

---

src/frontend/org/voltdb/HTTPClientInterface.java
src/frontend/org/voltdb/dbmonitor/js/voltdb.admin.ui.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.core.js
src/frontend/org/voltdb/utils/HTTPAdminListener.java
tests/frontend/org/voltdb/TestJSONInterface.java

[PLEASE DON'T MERGE. We need to fix VMC before this can be merged on to master]
Now returns status code 401 for authentication and authorization failures
and 404 for invalid URIs.

ENG-12021:

---

examples/voter/client/voter/AsyncBenchmark.java

ENG-12260, fix the problem that voter asyncBenchmark doesn't set --ratelmit in its client setting,

---

tools/kit_tools/build_kits.py

ENG-11993. Add sha256sum calculation to the builds for enterprise and pro. Kit builds will now produce new files:
- voltdb-ent-x.y.SHA256SUM	
- voltdb-pro-x.y.SHA256SUM	
After downloadking the kit and downloading the .SHA256SUM file to the same directory, the user can then use sha256sum -c to have it check the sum.  For example:
```
>sha256sum -c voltdb-pro-7.2.SHA256SUM
voltdb-pro-7.2.tar.gz: OK
```
Note: There is also a small logic bug fixed. This only affects when the command-line switches are used to limit the kits being built.

ENG-11993.  Add sha256sum to build for enterprise and pro.

---

src/frontend/org/voltdb/iv2/MpRoSite.java
tests/frontend/org/voltdb/TestCSVFormatterSuite.java
tests/frontend/org/voltdb/TestImportStatistics.java
tests/frontend/org/voltdb/TestImportSuite.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/StatisticsTestSuiteBase.java
tests/frontend/org/voltdb/regressionsuites/TestAdminMode.java
tests/frontend/org/voltdb/regressionsuites/TestCatalogUpdateSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexMaterializedViewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSecuritySuite.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateDeployment.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDatabaseElementStats.java

Waiting for Jenkins to verify this works.
On my own Macbook, TestMaterializedViewSuite took 215 seconds to run on master, but it took only 52 seconds on this branch (**75.8%** improvment).
Jenkins found several failures, will tune this branch a little bit to address them.

ENG-11648 accelerate regression suites

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

Close the socket when exception happens by adding a try catch block.
Sadly the diff is not so clear.

close the socket when exception happens

---

src/frontend/org/voltdb/sysprocs/UpdateLogging.java

Change-Id: Ibe2b093f8ec8e981ab6bb701b2a84672083b08cd

ENG-12279, reset the barrier every time after update the logging.

---

build.xml

build.xml: changed sqlcmdtest (& sqlcmdtestrefresh) executable from

---

lib/python/voltcli/voltadmin.d/dr.py
src/frontend/org/voltdb/utils/SQLCommand.java
tests/sqlcmd/baselines/ddl/load_remove_classes.outbaseline
tests/sqlcmd/baselines/errors/create_proc.outbaseline

pro side:
https://github.com/VoltDB/pro/pull/1855
manually tested and add a junit for negative test

ENG-12326: add an --all option for Reset all DR connections

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/frontend/org/voltdb/export/ExportDataSource.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java

- Keep require roll generation there in catalog diff but return true for now.
- Update test to expect roll everytime.

ENG-12334: Revert optimization.

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py

Also fix a bug in ping test for the new node.
Change-Id: I2a3edd63415aa06f55886cebc49e9129e36faee2

ENG-12353, change the format and wording according to Andrew's review comments.

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py

Change-Id: Ic628792d7530d4ec18e871b687ec001594645fb2

ENG-12359, fix another python compatibility issue in pre-2.6 version.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
tests/frontend/org/voltdb/regressionsuites/TestStartWithSchema.java

Make sure catalog-report.html always ends up in catalog.jar since VMC needs it there.

ENG-12375 fix vmc with staged schema in 7.2.x

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/spec.txt
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

New preferred-source attribute in <dr> <connection> to specify the snapshot source
for joining cluster.

ENG-12068:

---

src/frontend/org/voltdb/ProcedureRunnerNT.java

The callbacks could return before it was even done sending messages, leading to a CME.

ENG-12417: Fix concurrent modification exception in NT procedures

---

src/frontend/org/voltdb/compiler/ClassMatcher.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/compiler/VoltDDLElementTracker.java
src/frontend/org/voltdb/compiler/statements/CatchAllVoltDBStatement.java
src/frontend/org/voltdb/compiler/statements/CreateFunctionFromMethod.java
src/frontend/org/voltdb/compiler/statements/CreateProcedure.java
src/frontend/org/voltdb/compiler/statements/CreateProcedureAsSQL.java
src/frontend/org/voltdb/compiler/statements/CreateProcedureAsScript.java
src/frontend/org/voltdb/compiler/statements/CreateProcedureFromClass.java
src/frontend/org/voltdb/compiler/statements/CreateRole.java
src/frontend/org/voltdb/compiler/statements/DRTable.java
src/frontend/org/voltdb/compiler/statements/DropFunction.java
src/frontend/org/voltdb/compiler/statements/DropProcedure.java
src/frontend/org/voltdb/compiler/statements/DropRole.java
src/frontend/org/voltdb/compiler/statements/DropStream.java
src/frontend/org/voltdb/compiler/statements/ImportClass.java
src/frontend/org/voltdb/compiler/statements/PartitionStatement.java
src/frontend/org/voltdb/compiler/statements/ReplicateTable.java
src/frontend/org/voltdb/compiler/statements/SetGlobalParam.java
src/frontend/org/voltdb/compiler/statements/VoltDBStatementProcessor.java
src/frontend/org/voltdb/parser/SQLParser.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java
tests/sqlcmd/baselines/ddl/load_remove_classes.outbaseline
tests/sqlcmd/scripts/ddl/load_remove_classes.in

This is reviewed in https://github.com/VoltDB/voltdb/pull/4477

ENG-12246, Refactor DDLCompiler

---

src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
tests/frontend/org/voltdb/TestJSONInterface.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/LocalSingleProcessServer.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/regressionsuites/TestGeospatialFunctions.java
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewNonemptyTablesSuite.java
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesNewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSystemProcedureSuite.java
tests/frontend/org/voltdb/regressionsuites/VoltServerConfig.java

It is indeed related to the regression suite optimization.
There is one test case that uses "ALTER TABLE" statements to change the constraint.

ENG-12399 Fix TestSQLFeaturesNewSuite

---

src/frontend/org/voltdb/importclient/kafka/KafkaTopicPartitionImporter.java

{ SAME FIX AS https://github.com/VoltDB/voltdb/pull/4495 BUT JIRA TICKET WAS CORRECTED }
This fixes a race between the VoltDB procedure callback threads trying to set the paused offset. It was reliably set to the FIRST value seen, but not reliably set to the LOWEST value seen across all threads.
I introduce a synchronization mechanism to ensure the paused offset is reliable before using it to commit any offsets to Kafka.
Some design decisions behind the PendingWorkTracker object, which should be reusable:
* Routine adjustment of pending callback counters is lockless and fast
* Producer needs to reliably know when all callbacks are done without periodic sleeps
* Need to be able to get the number of callbacks called at the end of the run, regardless of whether or not waitForWorkToFinish() …

ENG-12348: fix KafkaImporter occasionally losing small numbers of rows when server transitions to unavailable

---

lib/python/voltcli/voltadmin.d/shutdown.py

Update "voltadmin shutdown" logic to take into account kit type (community or not) before invoking features which are community specific.  For example features like export queise, snapshot save and command logs will not be invoked if it's community version.
Output of "voltdbadmin shutdown": 
Community Version:
```
$ voltadmin shutdown 
INFO: Cluster shutdown in progress.
INFO: Preparing for shutdown...
INFO: The cluster is paused prior to shutdown.
INFO: Completing outstanding client transactions...
INFO: Completing outstanding importer requests...
INFO: Shutting down the cluster...
Status: -1
Information: Connection broken
$ voltadmin shutdown -s
WARNING: Snapshots not supported in the community edition. The --save option is being ignored.
INFO: Cluster shutdown in progress.
INFO: …
```

Eng 12351 - update voltadmin shutdown script logic to take into kit type

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/SQLStmtAdHocHelper.java
src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/iv2/DeterminismHash.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/ProcedureTask.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SysProcDuplicateCounter.java
src/frontend/org/voltdb/messaging/InitiateResponseMessage.java
src/frontend/org/voltdb/sysprocs/LoadSinglepartitionTable.java
tests/frontend/org/voltdb/TestTwoSitePlans.java

This isn't really enough, but it's a lot more to go on.
pro: https://github.com/VoltDB/pro/pull/1889

ENG-10599: Print way more info on hash mismatch.

---

src/ee/storage/DRTupleStream.cpp

manual test with debug and memcheck build.

ENG-12478: ignore assertion open txn for generate swaptable event

---

src/ee/storage/DRTupleStream.cpp

manual test with debug and memcheck build.

ENG-12478: fix eecheck

---

src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/SQLStmtAdHocHelper.java
src/frontend/org/voltdb/iv2/FragmentTask.java

Change-Id: Idf2e29b2211effaae1ee51e1a42fac25e738268b

ENG-12500, resolve the MP peformance regression introduced by ENG-10599.

---

src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/SQLStmtAdHocHelper.java
src/frontend/org/voltdb/iv2/FragmentTask.java

Change-Id: Icebb0ab8d591176d07968591e34467ea24c18fb1

ENG-12500, avoid another performance bottleneck of unnecessary memory allocation.

---

lib/python/voltcli/voltadmin.d/plan_upgrade.py

Change-Id: I985bde85f992bed638a3b96dbaab42ef6ede83f4

ENG-12476, plan_upgrade command supports SSL-enabled VoltDB cluster.

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java

Add exclusive access check between node rejoin and UpdateApplicationCatalog using ZK nodes

Eng 12454 mismatch uac zk fix

---

build.xml
src/frontend/org/voltdb/NonVoltDBBackend.java
src/frontend/org/voltdb/PostgreSQLBackend.java
tests/sqlcoverage/start_postgresql.sh
tests/sqlcoverage/stop_postgresql.sh
tools/killstragglers.sh

Attempt to avoid SqlCoverage failures caused by PostgreSQL port issues.

Eng 12552 kill postgres ports

---

tests/sqlcoverage/start_postgresql.sh

start_postgresql.sh: just added -w (wait) when starting PostgreSQL (at

---

lib/python/voltcli/voltadmin.d/status.py

Pro PR https://github.com/VoltDB/pro/pull/1904/files

ENG-12301, import python class.

---

src/frontend/org/voltdb/sysprocs/AdHocNTBase.java

ENG-12273: Fix adhoc failure when debug logging is enabled

---

src/frontend/org/voltcore/utils/CoreUtils.java

[ENG-11258] Fixed message printing issue.

---

lib/python/voltcli/checkstats.py
lib/python/voltcli/voltadmin.d/dr.py
src/ee/common/types.h
src/ee/storage/DRTupleStream.cpp
src/frontend/org/voltcore/zk/ZKCountdownLatch.java
src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java

This PR adds graceful dr reset.
pro side: https://github.com/VoltDB/pro/pull/1866

ENG-11308: Coordinated DR reset

---

src/frontend/org/voltdb/ParameterConverter.java
tests/frontend/org/voltdb/TestParameterConverter.java

Added support for converting from BigDecimal to long/double in java.
The use case has been verified in command line.
- Should I add a unit test for this ?

Eng 12522 jdbc bigdecimal support

---

src/frontend/org/voltdb/JdbcDatabaseMetaDataGenerator.java
tests/frontend/org/voltdb/regressionsuites/TestSystemCatalogSuite.java

fixed reference to primary key for materialized views

SystemCatalog PRIMARYKEYS return wrong column names for matviews

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionAggregate.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java

Change-Id: Iba23169cbc3e58e7354394204fc11337de7c4896

ENG-12614, add hashCode() to Expression and its subclasses.

---

bin/kafkaloader10

Fix support for supercsv by adding supercsv jar file in lib directory to classpath

add super csv to kafkaloader10 classpath

---

src/frontend/org/voltdb/RealVoltDB.java

Revert "ENG-12666: Fix startup catalog causing junit to fail."

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/SQLStmtAdHocHelper.java
src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/DeterminismHash.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/ProcedureTask.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SysProcDuplicateCounter.java
src/frontend/org/voltdb/messaging/DumpPlanThenExitMessage.java
src/frontend/org/voltdb/messaging/InitiateResponseMessage.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
src/frontend/org/voltdb/sysprocs/LoadSinglepartitionTable.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/TestTwoSitePlans.java
tests/frontend/org/voltdb/compiler/TestProcCompiler.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestMultipleOuterJoinPlans.java

Pro PR: https://github.com/VoltDB/pro/pull/1929/files

Eng 12665 enrich hashmismatch message backportv6.6

---

src/frontend/org/voltdb/iv2/LeaderAppointer.java

ENG-12281-fix unit test

---

src/frontend/org/voltdb/iv2/LeaderAppointer.java

simplified the logic to check missing partitions.

ENG- 12281 fix a test case

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/utils/CatalogUtil.java

Revert "ENG-12542"

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/CatalogChangeResult.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
src/frontend/org/voltdb/sysprocs/Promote.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/sysprocs/UpdateClasses.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
tests/frontend/org/voltdb/MockVoltDB.java

For review only.
- Use a new unique id when replaying UAC to generate generation higher than current generation.

ENG-9932: Add ccrTime as generation.

---

src/frontend/org/voltdb/importer/ChannelDistributer.java

This addresses a multiple node kill scenario where the Zookeeper data went stale midway through sending the assignments.
When the leader is distributing a new set of importer channel assignments, it will retry sending ALL assignments if ANY fail. This is fine if the first assignment fails, but in this scenario there is a race condition between the distribution of channel assignments and a mesh monitor responding to the node failure. In the original problem report, the leader has sent roughly 2/3 of the assignments out before Zookeeper throws a "bad version" error. When the entire re-send gets retried, the very first assignment gets flagged as a duplicate resulting in the reported error. The retry is aborted, meaning the remaining channel assignments don't get distributed.
Anyone who sees …

ENG-12034 fix only

---

src/frontend/org/voltdb/AuthSystem.java

Pro PR for new test case:  https://github.com/VoltDB/pro/pull/1953

added a log message when VoltDB is running as root

---

tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

i.e., within INSERT, UPSERT, UPDATE, and DELETE statements, including the possibility of "correlated" sub-queries, referencing a table (or view or alias) used in the outer SQL statement; and other improvements.

Allow the use of sub-queries within DML (SQL) statements,

---

src/frontend/org/voltdb/parser/SQLLexer.java
tests/frontend/org/voltdb/utils/TestSplitSQLStatements.java

Eng 12784 multi stmt proc

---

lib/python/voltcli/voltadmin.d/stop.py

Change-Id: I026c9a146f5e5255dc750e4b427ce9b7eddbc02e

ENG-12851, allow "voltadmin stop" to connect to ssl-enabled server.

---

lib/python/voltcli/voltadmin.d/stop.py

Change-Id: Ia3788dce5cc9b0c72c6901fae0dc1914ce5997cf

ENG-12766, return non-zero value when "voltadmin stop" fails.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/PersistentTableUndoSwapTableAction.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

Generate transactions and events into drstream only after receiving DR_STREAM_START event.

ENG-12786:

---

tests/sqlcmd/baselines/simple/testidenticalproc1.outbaseline
tests/sqlcmd/baselines/simple/testidenticalproc2.outbaseline
tests/sqlcmd/baselines/simple/testidenticaltable1.outbaseline
tests/sqlcmd/baselines/simple/testidenticaltable2.outbaseline
tests/sqlcmd/baselines/simple/testidenticalview1.outbaseline
tests/sqlcmd/baselines/simple/testidenticalview2.outbaseline
tests/sqlcmd/scripts/simple/testidenticalproc1.in
tests/sqlcmd/scripts/simple/testidenticalproc2.in
tests/sqlcmd/scripts/simple/testidenticaltable1.in
tests/sqlcmd/scripts/simple/testidenticaltable2.in
tests/sqlcmd/scripts/simple/testidenticalview1.in
tests/sqlcmd/scripts/simple/testidenticalview2.in
tests/sqlcmd/sqlcmdtest.py

Drop table, procedure and views left in between sqlcmdtest to avoid any cross contamination.

Eng 12695 sqlcmdtest droptableprocedure

---

buildtools.py
tests/ee/expressions/expression_test.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/CopyOnWriteTest.cpp
tests/ee/test_utils/plan_testing_baseclass.h

Report valgrind error messages.
Don't depend on the return code from valgrind only to determine valgrind errors.

Eng 12901 valgrind botch

---

src/frontend/org/voltdb/AuthSystem.java

This reverts commit 9042750747f2753024a8387f18b1ba062eb37ab2.

Revert "added a log message when VoltDB is running as root (#4679)"

---

tests/test_apps/nptxn-perf-benchmark/client/np/NPBenchmark.java
tests/test_apps/nptxn-perf-benchmark/run.sh

- Now use a separate thread for sending SP txns only. The other clients that send NP/MP txns will be limited by a max tps provided by the user.
- See https://github.com/VoltDB/pro/pull/2002

Updated the np txn benchmark

---

src/frontend/org/voltdb/utils/CatalogUtil.java

Character Ctrl-A can be used as a file export delimiter

Eng 12528 file export delimiter patch

---

lib/python/voltdbclient.py

- Allow ssl_config_file to have environment variables or ~
- Better error message when pyjks module is missing

ENG-12976.  Better SSL usability in for python client

---

tests/frontend/org/voltdb/TestLiveDDLAfterAutoUpgrade.java

Forget to merge the local test fix for #4799

Fix the test case by not renmaing the autogen ddl file in the jar

---

src/catgen/in/javasrc/CatalogType.java

CatalogTypeReference is not thread safe, during UAC both Site thread and NTPService thread may access the same object.

ENG-13031, fix NPE found during extensive UAC test.

---

src/frontend/org/voltdb/client/ConnectionUtil.java

Wrap all socket accept before finishing authentication in the try/catch block to
make sure if the timeout fires, it throws the proper exception.

ENG-12991: Fix Java client authentication timeout detection.

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/UserDefinedFunctionManager.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/regressionsuites/TestUserDefinedFunctions.java
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-DDL.sql
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions.java

This pull request enables the UDF buffer to resize when needed.
The resizing could be the result of having larger-than-capacity parameters or return values.

ENG-12973 UDF buffer resizing

---

tests/frontend/org/voltdb/regressionsuites/TestCatalogUpdateSuite.java

test case update with catalog update

ENG-13082 test case update

---

src/frontend/org/voltdb/AbstractTopology.java

avoid IndexOutOfBoundsException

ENG-12928 proper exception handling

---

src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
tests/frontend/org/voltdb/TestImportSuite.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateDeployment.java

Added exception handling when detecting site per host change in deployment file

Eng 12920 change sph on the fly

---

tools/docker/custom/README.md
tools/docker/custom/src/build.sh
tools/docker/custom/src/common/include/ubuntu-14.04.m4
tools/docker/custom/src/common/include/ubuntu-16.04.m4
tools/docker/custom/src/run.sh
tools/docker/custom/src/run/include/volt.m4
tools/docker/custom/src/run/make-run-image.sh
tools/docker/custom/src/run/ubuntu-14.04/Dockerfile.m4
tools/docker/custom/src/run/ubuntu-16.04/Dockerfile.m4

Add helper scripts and docker config to allow easier creation of custom Volt docker images. Useful for spinning up desired distributions of Volt for testing.

Custom Docker Image helper scripts

---

src/frontend/org/voltdb/export/ExportDataSource.java

A race condition between export data source master promotion and getting acks
from the previous failed master can occur. The failed master could have sent out
an ack with Long.MIN and fails immediately after that, which causes a new master
to be elected. The election and the receiving of this ack message happens on two
different threads on the new master. If it's promoted while processing the ack,
the ack may call `m_onDrain` while the other thread is polling buffers, which
may never get discarded.
Check to see if we are already promoted to be the master. If so, ignore the ack.

ENG-12282: Fix export promotion and ack race condition.

---

src/ee/common/UndoLog.h

Performance test shows there is degradation with limited undo cached pool size. increase cached pool size to 2048 with which the performance is comparable with no size limit.

ENG-13144 undo cached pool size optimzation

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java

accept mastership for non-drained non-continueing generation.

ENG-12282: accept mastership for non-drained non-continueing generation.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
src/hsqldb19b3/org/hsqldb_voltpatches/RangeVariable.java
src/hsqldb19b3/org/hsqldb_voltpatches/Session.java

Eng 13130 fix issue1 to master

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
tests/frontend/org/voltdb/planner/PlannerTestAideDeCamp.java

Serialize all planning/HSQL access. Multi-threaded planning is not supported, so before we can do it all accesses to the planner need to be serialized.

Eng 13180 fix issue2

---

src/frontend/org/voltdb/StartAction.java

Change-Id: Ia59e1d90c4f3000e9c89c11a027ee4f3984bb98c

ENG-13179, lift enterprise restriction on some verbs.

---

tests/frontend/org/voltdb/catalog/TestResourcesInUpdateClasses.java
tests/testprocs/org/voltdb_testprocs/catalog/resourceuse/SwitchResourceProc.java

Add unit test to verify that catalog diffs correctly remove resource files.

ENG-12572:

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ClientInterfaceHandleManager.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/NTProcedureService.java
src/frontend/org/voltdb/iv2/SpScheduler.java
tests/frontend/org/voltdb/TestClientInterfaceHandleManager.java

Change-Id: I2b1563852c3fbd1d1a2efa55044aa8d79e381d1d

ENG-13212, Re-apply ENG-12852 due to a merge accident.

---

src/frontend/org/voltdb/DiskResourceChecker.java

Change-Id: Ia81609f1f0a63b9dba3d0c0220ce9e0d764325e3

ENG-13147, simple fix to isSupportedFeature() function.

---

src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/dr2/DRIDTrackerHelper.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/frontend/org/voltdb/sysprocs/ExecuteTask_SP.java
src/frontend/org/voltdb/utils/MiscUtils.java

Still testing, for preliminary review only.
Some code can be further refactored, but will probably not be addressed in this PR.

ENG-13107: Restart DR consumer on elastic join

---

tools/kit_tools/build_kits.py

Also changed builddir on remote machines to have correct username.

ENG-13233. Add RabbitMQ export connector to community build.

---

src/frontend/org/voltdb/dtxn/TransactionState.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java

ENG-13194 backport fix to 7.8

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/largequery/LargeBlockManager.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/frontend/org/voltdb/utils/CommandLine.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/largequery/TestLargeBlockManagerSuite.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/TestLargeBlockManagerStartUpSuite.java
tests/frontend/org/voltdb/utils/TestCatalogUtil.java

Reviewed on a separate branch.

ENG-12555: Large block manager

---

src/ee/common/NValue.hpp
src/ee/executors/indexcountexecutor.cpp
src/frontend/org/voltdb/expressions/AbstractExpression.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestIndexCountSuite.java
tests/frontend/org/voltdb/regressionsuites/TestInsertIntoSelectSuite.java

https://issues.voltdb.com/browse/ENG-13304

Backport ENG-13059, ENG-12992 to release-6.6.x

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java

* ENG-11602: When durablity is off let db start with export_overflow.
* ENG-11991: Load terminus if present and no durability. move snapshots.
* ENG-11602: Add durable checks for DR
* ENG-11602: Sep out shutdown save in diff ticket.
* ENG-11602: Review changes.

ENG-11602 (#4298)

---

src/frontend/org/voltdb/iv2/MpTransactionState.java

add a system property to make fragment response timeout configurable

ENG-13369 make fragment response timeout configurable

---

src/frontend/org/voltdb/SnapshotSaveAPI.java

Add a timeout for the sites to come together in 30 seconds to break out possible deadlock upon node failure.

ENG-13347 timeout the snapshot save barrier

---

src/frontend/org/voltdb/SnapshotSaveAPI.java

Revert part of previous changes and synchronize MpRoSitePool shutdown.

Revert "ENG-13347 timeout the snapshot save barrier"

---

src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java

Revert part of previous changes and synchronize MpRoSitePool shutdown.

ENG-13348 synchronize RO site pool shutdown

---

src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java

back port the fix from ENG-13448

ENG-13348 back port fix

---

lib/python/voltcli/daemon.py

voltdb will now pick up user's current umask setting.

ENG-13370. Remove umask(0) in daemonize.

---

src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java

safe site shutdown in MpRoSitePool.

ENG-13383 properly shutdown MpRoSitePool

---

src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java

backport change  for MpRoSitePool shutdown

ENG-13383 backport fix

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/AbstractDRTupleStream.cpp
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/ExportTupleStream.cpp
src/ee/storage/ExportTupleStream.h
src/ee/storage/TupleStreamBase.cpp
src/ee/storage/TupleStreamBase.h

so ExportStream and DRStream don't have to expose own API to each other.
Change-Id: I48f5fdc28135b6dec1dea99082ed4617e4bcd99c

ENG-9295, refactor TupleStreamBase

---

README.md

This pull request updates the README to use the new CLI (init/start). I also added more to the description of shutdown to suggest --save for open-source users.
All comments welcome.

Update to README to new CLI

---

src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

Add deprecation warning message at start up time for fast read consistency level.

Eng 13103 deprecate warning fast reads

---

src/frontend/org/voltdb/client/Distributer.java

Instead of Exception
https://issues.voltdb.com/browse/ENG-13443

ENG-13443: Catch Throwable in java client when wrapping user callbacks

---

third_party/java/src/org/apache/zookeeper_voltpatches/ClientCnxn.java
third_party/java/src/org/apache/zookeeper_voltpatches/ZooKeeper.java
third_party/java/src/org/apache/zookeeper_voltpatches/version/Info.java

Also apply some of patch from: https://issues.apache.org/jira/browse/ZOOKEEPER-1063

ENG-13468: Beef up synchronization in internal ZK client

---

src/catgen/in/javasrc/CatalogChangeGroup.java
src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/spec.txt
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/CatalogChangeResult.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java

HTTP sessions will be cleaned up only if security users are updated in catalog update.

ENG-13390 fix catalog diff engine to evaluate the security user change with catalog update

---

build.py

Change-Id: If308f8698600e5babf24ab90645af458799b0407

ENG-13490, fix compilation errors using Clang version 7+.

---

lib/python/Query.py
lib/python/voltdbclient.py

And some geo thrown in for good

ENG-12437 python3 compatibility

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
tests/frontend/org/voltdb/planner/TestPlansCommonTableExpression.java
tests/frontend/org/voltdb/regressionsuites/TestCommonTableExpressionsSuite.java

Add a minimal test for this as well.

Fix HSQL so that it parses subqueries for the base case.

---

src/frontend/org/voltdb/AbstractTopology.java
src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/TestAbstractTopology.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

Change-Id: Ib92cb2a48a2c8c1f9d9d197cb92e7e11375cca5f
Companion Pro PR: https://github.com/VoltDB/pro/pull/2188

ENG-13608, fix startup failure when using --missing node option.

---

src/frontend/org/voltdb/importclient/kafka10/KafkaConsumerRunner.java
src/frontend/org/voltdb/importclient/kafka10/KafkaStreamImporter.java

check if cluster is being shutdown or paused and exit

ENG-13622 kafka importer pause or shutting down

---

src/frontend/org/voltdb/export/ExportManager.java

Change-Id: If8a6307242d98b3a6bf833ffbfe5206cb2c28d62

ENG-13538, get ride of Export UAC handler thread.

---

tests/geb/vmc/src/resources/sqlQueries.txt

SelectInsertedEmbeddedWhitespace and CrudRoundTripEmbeddedWhitespace
tests, since they've been failing for months.

sqlQueries.txt: for now, just commented out the

---

src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/SQLStmt.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/compiler/StatementCompiler.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/NibbleDeleteBase.java
src/frontend/org/voltdb/sysprocs/NibbleDeleteMP.java
src/frontend/org/voltdb/sysprocs/NibbleDeleteSP.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/sysprocs/TestNibbleDelete.java

The sysproc copies pattern from windowing app, it has three statements:
select numbers of rows that meet the delete criteria, find the value sits on boundary of delete chunk size, if rows to be deleted are more than chunk size, delete rows based on the value given in parameter, or the boundary value.

Eng 12877 nibbledelete sysproc

---

tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

Added "basic" (non-recursive) CTE statements to grammar; and tweaked some Recursive CTE definitions to make them usable for non-recursive CTEs too; plus some small python code changes to facilitate those changes.

Eng 13658 gram cte nonrec

---

src/ee/CMakeLists.txt
src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/UndoReleaseAction.cpp
src/ee/common/UndoReleaseAction.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/ConstraintFailureException.cpp
src/ee/storage/ConstraintFailureException.h
src/ee/storage/ExecuteTaskUndoGenerateDREventAction.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/table.cpp
src/ee/storage/table.h
src/ee/structures/CompactingPool.cpp
src/ee/structures/ContiguousAllocator.cpp
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/DeprecatedProcedureAPIAccess.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/sysprocs/LoadMultipartitionTable.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/regressionsuites/TestLoadingSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSystemProcedureSuite.java

Eng-12821 Optimzed SynchronizedUndoAction and  Change LMPT use voltLoadTable path

---

src/frontend/org/voltdb/export/ExportDataSource.java

Fixed another off by one error.

ENG-13758:

---

tests/geb/vmc/src/resources/expectedSystemStoredProcs.txt

expectedSystemStoredProcs.txt.

ENG-13771: added new @Ping to list of System Stored Procedures in

---

src/frontend/org/voltcore/zk/ZooKeeperLock.java
src/frontend/org/voltdb/VoltZK.java

add a locking mechanism to avoid stepping on each other while creating blockers on ZooKeeper for  exclusive validations of rejoining, UAC, etc

ENG-13582 locking mechanism for uac, rejoining etc

---

build.xml
tests/sqlcoverage/SQLCoverageReport.py
tests/sqlcoverage/normalizer/normalizer.py
tests/sqlcoverage/normalizer/not-a-normalizer.py
tests/sqlcoverage/normalizer/nulls-lowest-normalizer.py
tests/sqlcoverage/sql_coverage_test.py

HTML pages, with links). Main changes to sql_coverage_test.py &
SQLCoverageReport.py (also removed an obsolete try/except); plus extra
args in normalizer.py, not-a-normalizer.py, nulls-lowest-normalizer.py,
and also build.xml.

ENG-11221: Added 'Steps to Reproduce' to SqlCoverage output (on separate

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java

to clear up the site outstanding transaction queue and dupilcate counter

ENG-13769 deliver CompleteTransactionResponseMessage when scoreboard releases CompleteTransctionTask 

---

src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java

deliver complete transaction message during repair to help up clean up transaction state.

ENG-13854 handling non-restartable in repair

---

tools/VoltDBCompilation.cmake

[Jenkins](http://ci.voltdb.lan/view/Branch-jobs/view/branch-ENG-13903-GCC-7.3/) has only 1 failure in [pro-junit](http://ci.voltdb.lan/view/Branch-jobs/view/branch-ENG-13903-GCC-7.3/job/branch-2-pro-junit-ENG-13903-GCC-7.3/2/).

Eng 13903 - Support gcc-7.3

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementDMQL.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java

These changes already reviewed by Bill.

ENG-13801: Properly set display columns when there is an agg in an order by

---

src/frontend/org/voltdb/SnapshotSiteProcessor.java

Change-Id: I48ad334598b600e2fdf5b35e97a7470f0ea39587

ENG-13922, Fix NPE in node shutdown path.

---

src/frontend/org/voltdb/RealVoltDB.java

Change the name when starting up with AWS Marketplace license.

ENG-13755. Change the name on AWS.

---

lib/python/voltcli/runner.py
lib/python/voltcli/verbs.py
src/frontend/org/voltdb/importclient/kafka/KafkaLoader.java
src/frontend/org/voltdb/importclient/kafka/util/BaseKafkaLoaderCLIArguments.java
src/frontend/org/voltdb/importclient/kafka10/KafkaLoader.java
src/frontend/org/voltdb/utils/CSVLoader.java
src/frontend/org/voltdb/utils/JDBCLoader.java
src/frontend/org/voltdb/utils/MiscUtils.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/jdbc/TestJDBCSecurityEnabled.java
tests/frontend/org/voltdb/utils/TestCSVLoaderSecurityEnabled.java

Added an optional flag called "--credentials" to sqlcmd, voltadmin, csvloader, jdbcloader, kafkaloader to enable users login with credentials file and thus avoiding exposing username / password in linux system processes

Eng 13432 - Hide Password

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/frontend/org/voltdb/DependencyPair.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/StoredProcedureInvocation.java
src/frontend/org/voltdb/exceptions/SQLException.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java
src/frontend/org/voltdb/messaging/FragmentTaskMessage.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java

binary log size exceeds 50 MB.

ENG-13638: Disallow transaction on the producer side if the combined

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/client/ClientConfig.java
src/frontend/org/voltdb/common/Constants.java
src/frontend/org/voltdb/utils/SQLCommand.java

Changed the logic in ssl setup so server can start up without configuring truststore property.
Fixed default truststore path

Eng 13678 clean

---

examples/adperformance/README.md
examples/adperformance/client/adperformance/AdTrackingBenchmark.java
examples/adperformance/ddl.sql
examples/adperformance/procedures/adperformance/InitializeCreatives.java
examples/adperformance/procedures/adperformance/TrackEvent.java
examples/adperformance/run.sh

ENG-13965: Update adperformance to show off TTL

---

lib/python/voltcli/voltadmin.d/restore.py
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
tests/frontend/org/voltdb/regressionsuites/TestRestoreSysprocSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java

ENG-11437NEW

---

src/frontend/org/voltdb/RealVoltDB.java

ENG-13881:

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java

When SPI migration completes or fails, remove migation info ZK node as well.

ENG-14257:

---

src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

The previous boolean logic was correct but obscure because an arriving MP Read with the same TxnId as the MP Read TxnId would evaluate correctly only because the set of != txnIds is a superset of > txnIds:
if ((txnState.isReadOnly()) && headTask.getTransactionState().isReadOnly() &&
TxnEgo.getSequence(task.getTxnId()) != TxnEgo.getSequence(headTask.getTxnId())
|| (TxnEgo.getSequence(task.getTxnId()) > TxnEgo.getSequence(headTask.getTxnId()))) {
While the expression could semantically resolve (true && true && false || true) to true, in practice if the third term is false, the fourth term must be false. However, the intent of the code is more precise with this change.

ENG-14292:

---

tools/jenkins/sql-grammar-reporter.py

* not all test failures will result from problematic frame, so remove dependency to split summary_report on it
* consequently, might not always have sigsegv_message; enable N/A

ENG-14149: Fix failing sql-grammar-reporter

---

src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpRepairTask.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/RepairAlgo.java
src/frontend/org/voltdb/iv2/RepairLog.java
src/frontend/org/voltdb/iv2/SpPromoteAlgo.java

to allow more control of debug logging

ENG-14262 use its own logger for txn repair

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/TupleStreamBase.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
tests/frontend/org/voltdb/TestTheHashinator.java
tests/frontend/org/voltdb/TestTwoSitePlans.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

- Restored code that was accidentally deleted
- Removed personal comments
- Renamed variable s_maxBufferAge to s_exportFlushTimeout

ENG-8191. A cleaned up version of branch ENG-8191-AAUIW.

---

src/frontend/org/voltdb/export/ExportGeneration.java
tests/frontend/org/voltdb/export/ExportMatchers.java

Change-Id: I75f15257893c0ac557cbb5b2cbb6a5b8a4b66d76

ENG-14347, fix failing unit test.

---

src/frontend/org/voltdb/rejoin/StreamSnapshotSink.java

Change-Id: I866d94eb75e493302fa32c73ff22676b1928d0bc

ENG-14304, downgrade unnecessary debug logs in rejoin path.

---

src/frontend/org/voltdb/ClientInterface.java

use less and equal instead less

ENG-14443 update compairon operator for ttl

---

src/frontend/org/voltcore/zk/BabySitter.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java

[backport MPI promotion fix](https://github.com/VoltDB/voltdb/pull/5540)

ENG-12549 back port mpi promotion fix

---

src/frontend/org/voltdb/export/ExportDataSource.java

Initialization and catalog update setup new runnable so won't be affected.
Change-Id: I87a697d7d4d7c94a73788b9a17d5d80fcbc11641

ENG-14347, keep mastership designation runnable when give up mastership.

---

src/frontend/org/voltdb/ExtensibleSnapshotDigestData.java
src/frontend/org/voltdb/SnapshotCompletionMonitor.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Change-Id: Ieb764822346c4588d83f9d979f9279cbefd19254

ENG-14447, add more debug log coverage on snapshot post completion path.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

also block  uac during promotion and repair

ENG-14511 add a blocker to ZooKeeper before partition callbacks are registered.

---

src/frontend/org/voltdb/iv2/MpTransactionState.java

Add more output to MP Deadlock messages to indicate if the dependency ids have changed because of a misrouted resend.

ENG-14553:

---

src/frontend/org/voltdb/LoadedProcedureSet.java

Revert "ENG-14550, put nibble delete procedure into default procedure list."

---

src/frontend/org/voltdb/iv2/DeterminismHash.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java

It causes hash mismatch check is bypassed if the indeterministic statement is not in the first 32 statements.
Pro: https://github.com/VoltDB/pro/pull/2332

ENG-14573, fix hash mismatch check.

---

src/ee/storage/BinaryLogSink.cpp

Empty binary logs were being properly handled when there was more than
one binary log but not when there was only one binary log. Update the
single binary log path to properly handl empty binary logs.

ENG-14616: Handle empty binary logs

---

src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/sysprocs/ExplainProc.java
src/frontend/org/voltdb/sysprocs/NibbleDeleteBase.java

Also make explainproc works for nibble delete.

ENG-14615, rename nibble delete defeault procedure.

---

src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

It is possible to release or undo the same transaction twice if the repair completions are received on all sites before the CompletionReponse messages are processed on any of the sites. To ensure that we don't execute the completion twice we should check the transaction state of the transaction that releases the completion to make sure that it is not marked as DONE. If it is marked as DONE, the completion has already been processed and the execution of the transaction should be skipped.

ENG-14637:

---

src/frontend/org/voltdb/iv2/MpScheduler.java

ENG-14566 misrouted every partition

---

src/frontend/org/voltdb/DefaultProcedureManager.java

Test update: https://github.com/VoltDB/pro/pull/2346

ENG-14636, append sql text of nibble delete to hash mismatch dump.

---

src/frontend/org/voltdb/calciteadapter/rel/AbstractVoltDBTableScan.java
src/frontend/org/voltdb/calciteadapter/rel/logical/VoltDBLRel.java
src/frontend/org/voltdb/calciteadapter/rules/VoltDBRules.java
src/frontend/org/voltdb/calciteadapter/rules/logical/VoltDBLSortRule.java
src/frontend/org/voltdb/calciteadapter/rules/logical/VoltDBLTableScanRule.java
src/frontend/org/voltdb/calciteadapter/rules/physical/VoltDBPSortIndexScanRemoveRule.java
src/frontend/org/voltdb/calciteadapter/rules/physical/VoltDBPSortScanToIndexRule.java

some notes about calcite optimizer, not necessarily need to be merged.

Calcite optimizer notes

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java

Tentative pr for fixing the bug introduced by ENG-14316-revert-replicate-stream ticket

Eng 14316 fix

---

src/frontend/org/voltdb/PostgreSQLBackend.java
tests/sqlcoverage/config/postgis-analytic-config.py
tests/sqlcoverage/config/postgis-analytic-int-config.py
tests/sqlcoverage/template/default/configure-default.sql
tests/sqlcoverage/template/default/configure-for-joins.sql
tests/sqlcoverage/template/default/configure-for-subq-joins.sql
tests/sqlcoverage/template/geo/configure-for-geo-point.sql
tests/sqlcoverage/template/geo/configure-for-geo-polygon.sql
tests/sqlcoverage/template/include/analytic-template.sql
tests/sqlcoverage/template/int/configure-for-ints.sql
tests/sqlcoverage/template/int/configure-for-matview-nonjoin.sql
tests/sqlcoverage/template/int/configure-for-matview-query-opt.sql
tests/sqlcoverage/template/int/configure-for-matview-subq-nonjoin.sql
tests/sqlcoverage/template/numeric/configure-for-decimal.sql
tests/sqlcoverage/template/string/configure-for-string.sql
tests/sqlcoverage/template/timestamp/configure-for-timestamp.sql
tests/sqlcoverage/template/varbinary/configure-for-varbinary.sql

Mostly refactored analytic-template.sql; minor changes to 3 other files.

ENG-14459: Add row_number() to SqlCoverage

---

src/frontend/org/voltdb/importclient/kafka10/KafkaStreamImporter.java

Handle case that cluster is pausing while kafka importers are being created.

ENG-14677 synchronization of kafka importer creation and shutdown

---

build.xml

And force remove Calcite build directory on ant target "clean"

Cleanup Calcite build directory upon refresh_calcite;

---

lib/python/voltsql/voltsql/voltexecutor.py
lib/python/voltsql/voltsql/voltsql.py

Change voltsql argument `--server` to `--servers` to match the sqlcmd.

ENG-14849: change voltsql argument --server to --servers

---

src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java

can use either IMPORT or  IMPORTER as stats selector

ENG-14864 add a synonym for importer stats selector

---

src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/StreamBlockQueue.java

We discussed offering this option for customers that want to try improving export throughput at the expense of their disk space.

ENG-14766: add VoltDB option to disable compression

---

tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java

Add an optional collection that can be passed into
MultiConfigSuiteBuilder which specifies which tests should be ignored.

MultiConfigSuiteBuilder: Add ability to ignore tests

---

src/frontend/org/voltdb/AbstractTopology.java

partition group is the standard name for grouping partitions on the same
hosts. Rename all references of protection group to partition group.

Rename protection group to partition group

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java
tests/test_apps/genqa/src/genqa/ExportKafkaOnServerVerifier.java
tests/test_apps/genqa/src/genqa/ExportRabbitMQVerifier.java
tests/test_apps/genqa/src/genqa/JDBCBenchmark.java
tests/test_apps/genqa/src/genqa/JDBCVoltVerifier.java
tests/test_apps/genqa/src/genqa/SyncBenchmark.java

exit with non zero exit status when then clients don't see any or enough rows.

Eng 14888 fix genqa error detection 2

---

src/frontend/org/voltdb/export/ExportDataSource.java

Change-Id: I543da7d9204a42899b75fea7328c2fc169180104

ENG-14941, bug fix stream gap stops re-polling.

---

src/frontend/org/voltdb/export/ExportDataSource.java

Change-Id: Ia30e27b2d1d24f2098b165a246ed2bb8c7e9d5fc

ENG-15021, add logging when gaps are skipped or covered.

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java

filter out the unaffected streams in the response

ENG-14687 filter out the unaffected streams in the response

---

lib/python/voltsql/voltsql/voltsql.py

immediately return when the input is an empty line instead of sending it to voltdb server

ENG-14933: voltsql blank line reacts slowly

---

src/frontend/org/voltcore/messaging/TransactionInfoBaseMessage.java
src/frontend/org/voltdb/iv2/SpPromoteAlgo.java
src/frontend/org/voltdb/iv2/SpScheduler.java

We think we have identified the actual root cause of this hash mismatch.

ENG-14744, revisit initial fix, root cause identified

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java

Change-Id: Ibf28c72c0254696b7247b1e2b61655fb60caab6e

ENG-14941, review comments update and bug fixes.

---

src/frontend/org/voltdb/export/ExportDataSource.java

Change-Id: Iefc4133d93a7f7bfbfa23b5d87245340d31125f4

ENG-15100, fix the issue that causing last released seqeunce number goes backward.

---

src/frontend/org/voltdb/export/ExportGeneration.java

Change-Id: I58b3b2b790c771221b8ad94f935e2ef3a4516bc1

ENG-15111, Synchronize access around m_dataSourcesByPartition.

---

src/frontend/org/voltdb/utils/PBDSegment.java

Change-Id: Ief5a14c841d1e8efa9bdfd0fe7eaab382f64c069

ENG-14941, close PBD segment before truncating.

---

src/ee/storage/TupleStreamBase.cpp
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/planner/SelectSubPlanAssembler.java
src/frontend/org/voltdb/plannerv2/VoltPlanner.java
src/frontend/org/voltdb/plannerv2/guards/CalciteCompatibilityCheck.java
src/frontend/org/voltdb/plannerv2/rules/PlannerRules.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
tests/frontend/org/voltdb/plannerv2/TestAdHoc.java

Fixed failed Jenkins tests, and merged from latest master branch (to fix another Jenkins error).
Relevant fixes are in `Adhoc.java` and `CalciteCompatibilityCheck.java`.

Eng 15149.rectify.calcite.branch

---

build.xml
src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltcore/zk/BabySitter.java
src/frontend/org/voltcore/zk/CoreZK.java
src/frontend/org/voltdb/AbstractTopology.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/elastic/BalancePartitionsStatistics.java
src/frontend/org/voltdb/elastic/ElasticService.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
src/frontend/org/voltdb/rejoin/JoinCoordinator.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/utils/TopologyZKUtils.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteRebalanceStats.java

Minor utility additions and plumbing for elastic remove feature that is needed in the community edition. As well as rebranding join to elastic for everything except logging.
Required by https://github.com/VoltDB/pro/pull/2437

ENG-14909 elastic remove operator

---

src/ee/storage/TupleStreamBase.cpp

Change-Id: I365288e46edc3569ed1c2e085cdf21a9bb04950d

ENG-15078, correct an assertion condition.

---

src/frontend/org/voltdb/export/ExportDataProcessor.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java

Change-Id: I471c2af4f11af59ec4df746eb9ab4922b8111b71

ENG-15142, set runEverywhere at ExportDataSource constructor.

---

tests/test_apps/genqa/src/genqa/JDBCGetData.java

* delay prepared statement initialization until we need them incase db isn't initialized yet.

Eng 15153 st jdbc vertica startup failure (#5836)

---

src/frontend/org/voltdb/export/processors/GuestProcessor.java

Change-Id: Icfb68808b8cb5c96e9e6004b689de1fb4a65e342

ENG-15180, fix NPE in UAC.

---

src/frontend/org/voltdb/export/ExportGeneration.java

Change-Id: I841553758d024ed2d02c12068447f6fa82139542

ENG-15100, fix NPE, skip truncating empty dangling pbd.

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/zk/CoreZK.java
src/frontend/org/voltcore/zk/MapCache.java
src/frontend/org/voltcore/zk/ZKUtil.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/iv2/InitiatorLeaderMonitor.java
src/frontend/org/voltdb/iv2/LeaderCache.java
tests/frontend/org/voltdb/export/TestExportGeneration.java

Remove unused method and reduce code duplication around some zoo keeper utilities

Zookeeper util cleanup

---

src/frontend/org/voltdb/settings/NodeSettings.java

saving path.properties (after normalizing paths, etc.) was not atomic. This showed up on k8s with path.properties being left empty. k8s has a tendency to kill the process at unexpected times. The fix is to create the new file as a temp file and then use atomic rename operation to update the file. Atomicity of the rename operation is platform dependent, however.

Eng 15212 path.properties not atomic

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/SpProcedureTask.java
src/frontend/org/voltdb/iv2/SpPromoteAlgo.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/messaging/CompleteTransactionResponseMessage.java
src/frontend/org/voltdb/messaging/FragmentResponseMessage.java
src/frontend/org/voltdb/messaging/FragmentTaskMessage.java
src/frontend/org/voltdb/messaging/InitiateResponseMessage.java

Revert "ENG-15073  prevent replicas from initializing repair log truncation unless"

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/DummyCommandLog.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotRequestConfig.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotRequestConfig.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/rejoin/TestStreamSnapshotRequestConfig.java

Update NativeSnapshotWritePlan to be able to update the partition count in the system
Make Cartogropher the authoritative place to retrieve the partition count from
Do not pass partition count into CommandLog

ENG-14773: Add final snapshot to elastic remove

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java

Refactored E3 export to get rid of E3ExportGeneration and E3GuestProcessor.

Eng 15011 bye bye export generation

---

src/frontend/org/voltdb/iv2/SpScheduler.java

ENG-15339 consume complete transaction responses from replicas and do not forward

---

tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

Cherrypicked from feature-elastic_remove branch.

LocalCluster: Add ability to override calling class name

---

src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PairSequencer.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPairSequencer.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

* Add a segment finalization mechanism: any file segment marked as "finalized" can be polled  without checking its internal consistency.
* Change the PBD file naming scheme to create an explicit linkage between PBD segments.

Eng 15337 pbd file management

---

lib/python/voltcli/cli.py
lib/python/voltcli/voltdb.d/init.py
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/utils/CommandLine.java
tests/frontend/org/voltdb/TestInitStartAction.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/testverbs/voltverbstest.py

Add support for providing multiple schema and jar files during the voltdb initialization

ENG-12733: Support multiple schema and procedure files

---

src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

See also https://issues.voltdb.com/browse/ENG-15429 which defines an improvement that will be implemented later.

ride through errors on finalization operations

---

tools/kit_tools/build_kits.py

Change the pinned build machine from volt15a to volt14c.

ENG-15430.  Make the official kit build on Centos7.

---

src/frontend/org/voltdb/OpsAgent.java
src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/utils/VoltTableUtil.java
tests/frontend/org/voltdb/TestVoltTable.java

When an error occurs log a detailed message and return an error response to the client. Also, track the timer future and cancel the timer when the operation completes.

ENG-13631: Improve error handling while aggregating results 

---

src/catgen/in/javasrc/CatalogType.java

CatalogTypeReference is not thread safe, during UAC both Site thread and NTPService thread may access the same object.
Change-Id: I9ad30dd89e91598e6a9506339de20a75a5b5eb0c

ENG-13031, fix NPE found during extensive UAC test. (#4817)

---

src/frontend/org/voltdb/RealVoltDB.java

Change-Id: Ib087bcf5c3166ad18831be381950887790cd6f24

ENG-13435, fix failing unit tests.

---

src/frontend/org/voltdb/AbstractTopology.java

to fix unit tests (TestStartupRecoverWithMissingHosts) and hopefully recover system tests.

ENG-15328 Set host missing correctly when recovered with missing hosts.

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

fix an issue which blocks setting a table as dr when TTL export is configured.

ENG-15408 allow TTL export on replicated tables

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

The exception toString by default is the exception class and the exception
message. Use toString to log the exception. Also, only log the error every 8th
failure instead of every failure after the 8th.

ENG-11599: Log the exception toString

---

tests/frontend/org/voltcore/agreement/TestFuzzMeshArbiter.java
tests/frontend/org/voltdb/FlakyTestStandardRunner.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExport.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExportRecover.java
tests/frontend/org/voltdb/TestReplicatedTableSnapshotRestore.java
tests/frontend/org/voltdb/export/TestExportV2Suite.java
tests/frontend/org/voltdb/exportclient/TestExportDecoderBase.java
tests/frontend/org/voltdb/exportclient/TestExportToFileClient.java
tests/frontend/org/voltdb/jdbc/TestJDBCSecurityEnabled.java
tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java
tests/frontend/org/voltdb/regressionsuites/TestStopNode.java
tests/frontend/org/voltdb/sysprocs/saverestore/TestReplicatedTableSaveFileState.java

Added @Flaky annotations (& other related stuff, like @Rule, @Test) to
methods in 9 (voltdb) JUnit classes; plus tiny DEBUG tweaks to
FlakyTestStandardRunner.java & MultiConfigSuiteBuilder.java.

ENG-15391: Identify and mark @Flaky tests

---

src/catgen/in/javasrc/CatalogType.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java

ignore tableType to allow catalog to be synchronized between clusters

ENG-15512 ignore newly introduced tableType on DR catalog diff

---

src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

fix DDL compiling for TTL export

ENG-15048 update DDL compiler

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/ee/common/CatalogUtil.h
src/ee/storage/TableCatalogDelegate.cpp
src/frontend/org/voltdb/export/AdvertisedDataSource.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/Generation.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/exportclient/DiscardingExportClient.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/TestExportStatsSuite.java
tests/frontend/org/voltdb/TestExportSuite.java
tests/frontend/org/voltdb/export/ExportMatchers.java
tests/frontend/org/voltdb/export/ExportTestClient.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/frontend/org/voltdb/exportclient/ExportClientTestBase.java
tests/frontend/org/voltdb/exportclient/TestExportDecoderBase.java
tests/frontend/org/voltdb/exportclient/TestExportDecoderBaseLegacy.java

PBD  life-cycle changes to be merged on Nibble Export Integration branch

Eng 15355 pbd life cycle ib

---

src/ee/CMakeLists.txt
src/ee/common/types.cpp
src/ee/common/types.h
src/ee/executors/executorfactory.cpp
src/ee/executors/migrateexecutor.cpp
src/ee/executors/migrateexecutor.h
src/ee/plannodes/migratenode.cpp
src/ee/plannodes/migratenode.h
src/ee/plannodes/plannodeutil.cpp
src/frontend/org/voltdb/expressions/ExpressionUtil.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/ParsedMigrateStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/QueryPlanner.java
src/frontend/org/voltdb/plannodes/MigratePlanNode.java
src/frontend/org/voltdb/types/PlanNodeType.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserCommand.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDML.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementDML.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementDMQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementTypes.java
tests/ee/common/pool_test.cpp
tests/ee/storage/ExportTupleStream_test.cpp
tests/frontend/org/voltdb/TestAdhocMigrateTable.java
tests/frontend/org/voltdb/regressionsuites/TestFailuresSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/frontend/org/voltdb/regressionsuites/TestTypeConversionSuite.java

(Task ENG-15528: the DML part)
See added tests for usage (and try out on `sqlcmd`).
On success, it returns an empty table with 1 column named _modified_tuples_.

Eng 15519.migrate.dml.support

---

src/frontend/org/voltdb/sysprocs/MigrateRowsAcked_MP.java
src/frontend/org/voltdb/sysprocs/MigrateRowsAcked_SP.java

Include sysprocs needed for processing the Acks from export

ENG-15590:

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

now compiler does not enforce the order of  BATCH_SIZE and MAX_FREQUENCY, will take MAX_FREQUENCY 1 BATCH_SIZE 3 or BATCH_SIZE MAX_FREQUENCY 1 . These two parameters must  positive integer.

ENG-15539 update TTL parameter parsing logic

---

src/frontend/org/voltdb/RestoreAgent.java

Added missing table details into snapshot restore error on partial snapshot.

ENG-15614:

---

src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java

This is a 2 line change that creates @Statistics IDLETIME as a synonym for STARVATION.

ENG-1655 Add IDLETIME to @Statistics as synonym for STARVATION

---

src/ee/expressions/expressionutil.cpp
tests/frontend/org/voltdb/TestAdHocQueries.java

Allow either sides of LIKE/STARTWITH expression to be sub-query

Fixed ENG-15572

---

src/ee/storage/ExportTupleStream.cpp
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/iv2/Site.java
tests/frontend/org/voltdb/TestExportConstraintsSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuiteLegacy.java
tests/frontend/org/voltdb/export/ExportLocalClusterBase.java
tests/frontend/org/voltdb/export/ExportTestExpectedData.java
tests/frontend/org/voltdb/export/ExportToSocketTestVerifier.java
tests/frontend/org/voltdb/export/TestExportAlterStreamEndToEnd.java
tests/frontend/org/voltdb/export/TestExportBaseSocketExport.java
tests/frontend/org/voltdb/export/TestExportEndToEnd.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/frontend/org/voltdb/export/TestMigrateExport.java

Pro side PR: https://github.com/VoltDB/pro/pull/2531

Eng 15356 alter shadow stream

---

src/frontend/org/voltdb/ClientInterface.java

Fix invalid assertion.
Log unexpected exception.

ENG-15691:

---

src/ee/execution/VoltDBEngine.cpp

Change-Id: Ie4823c2a2136d721f9526c5dd1f2a25ea612df17

ENG-15711, fix SIGSEGV in quiesec().

---

build.xml
tests/frontend/org/voltdb/AdhocDDLTestBase.java
tests/frontend/org/voltdb/fullddlfeatures/TestDDLFeatures.java
tests/frontend/org/voltdb/fullddlfeatures/fullDDL.sql

fullDDLpro.sql ... and to associated JUnit TestDDLFeatures.java and (new)
TestDDLProFeatures.java, respectively, testing the new ALTER STREAM
(DDL) statement and the new MIGRATE TO TARGET clause, following a TTL
clause in a CREATE TABLE statement; also added some convenience methods
to super-class AdhocDDLTestBase.java; plus some comments.

ENG-15520: Added STREAM and TTL tests to fullDDL.sql and new

---

tests/frontend/org/voltdb/TestExportLiveDDLSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuiteLegacy.java

Fix Special extra code that only the PRO Versions of the JUNIT test execute

ENG-15337:

---

src/frontend/org/voltdb/export/ExportDataSource.java

Add temporary debug code to help hunting down mysterious assertion failure.

ENG-15740, add debug log at failed assertion.

---

src/frontend/org/voltdb/plannerv2/NonDdlBatchPlanner.java
src/frontend/org/voltdb/plannerv2/VoltPlanner.java
src/frontend/org/voltdb/plannerv2/VoltRelOptCost.java
src/frontend/org/voltdb/plannerv2/rel/logical/VoltLogicalRel.java
src/frontend/org/voltdb/plannerv2/rel/physical/VoltPhysicalRel.java
tests/frontend/org/voltdb/regressionsuites/TestMaxSuite.java

Introduced VoltRelOptCost which mimics Calcite's VolcanoCost but throws an OverflowException if cost is about to overflow.
Attempt to propagate an error message thrown by the Calcite all the way to a ClientResponse

Added VoltRelOptCost

---

src/frontend/org/voltdb/AuthSystem.java

If the servers login to kerberos fails there is not much information printed.
Always add the configuration entry name and if possible some of the
configuration entry information.

ENG-15288: Print more details when krb login fails

---

src/frontend/org/voltdb/sysprocs/MigrateRowsBase.java

Log each step of the migrate to track down hash mismatch in parameters to migrate statement.

ENG-15809:

---

src/frontend/org/voltdb/export/ExportDataSource.java
tests/frontend/org/voltdb/export/TestExportDataSource.java

The new test case introduced in this PR allowed fixing both ENG-15808 and ENG-15804.

Eng 15808 fix gap release, Eng 15804 NPE after gap release

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/rejoin/JoinCoordinator.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

On host being joined validate that the license allows the number of hosts being added.

ENG-15748: Enforce license host limit during join

---

src/frontend/org/voltdb/ClientInterface.java

ClientInterface.startMigratePartitionLeader() did not handle some error cases
which could lead to the method throwing a runtime exception. Primarly the issue
is around getting the response. getResponse returns null on timeout but that
condition was never handled and an NPE would be thrown by the method which
would cause it to never be run again. The result of createTransaction was not
being checked so when that failed the timeout would always occur. Check the
result of createTransaction and handle a null result on timeout.
I don't know if this actually fixes the issues seen by ENG-15792 but it does fix issues in the area

ENG-15792: Handle error cases while migrating

---

src/frontend/org/voltdb/compiler/MaterializedViewProcessor.java
tests/frontend/org/voltdb/TestAdhocCreateDropView.java

Prohibit creating views with COUNT DISTINCT, since we should not
support it (yet).

Fixed ENG-15870

---

src/ee/expressions/functionexpression.cpp

by adding "override" keywords where warned.

Fixed MacOS compilation errors

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

Even though an individual read cursor could be closed the read cursor was not
aware of it being closed. Add an explicit close method to ReadCursor and use
the reader closed state to determine when to throw an error on reader methods.
On close always close all readers too.

ENG-15832: Track close of each ReadCursor

---

src/frontend/org/voltdb/VoltTable.java

Reverts VoltDB/voltdb#6144.  Many failing tests.

Revert "ENG-15842 getColumnIndex() optimization"

---

src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
src/frontend/org/voltdb/utils/VoltTrace.java

This consists mostly of minor cleanup and some simplification of the initialization state for the ProducerDRGateway

ENG-15092: Always read pbd on start

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/export/AckingContainer.java
src/frontend/org/voltdb/export/ExportCoordinator.java
src/frontend/org/voltdb/export/ExportDataProcessor.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java
src/frontend/org/voltdb/export/Generation.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/export/TestExportCoordinator.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/log4j-allconsole.xml
voltdb/log4j.xml

Refactored the interface between ExportDataSource and GuestProcessor. Implemented a new ExportCoordinator class to coodinate export mastership, gap detection and gap correction.

ENG-15811, close potential race conditions on m_pollTask

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

A completed and fleshed out version of my (J. Crawford's) Innovation
Week project.

ENG-15956: Major rewrite of the JUnit auto-filer.

---

tools/jenkins/jenkinsbot.py

Modified find_jira_bug_tickets's Jira query to use 'ORDER BY key DESC'
and create_jira_bug_ticket's linked-tickets query to not use 'reporter
in (voltdbci)'; and clarified/neatened both, putting project first, etc.

ENG-16021: First minor tweaks to the JUnit Auto-filer:

---

src/frontend/org/voltdb/exportclient/JDBCExportClient.java

The AutoCommit assignment was moved because some JDBC clients (specificallly volt's) do not support AutoCommit=false. Since this needs to be set before the first command and Initialize (which identifies the database target), can create a table, the create table code needed to be moved to a point after the AutoCommit was reset.

ENG-15988:

---

src/catgen/in/javasrc/CatalogDiffEngine.java

Ensure ALTER TABLE .. COLUMN on exporting table gets handled as a change requiring a new export generation.

ENG-16025, update export subsystem on alter column of exporting table

---

tests/frontend/org/voltdb/export/TestPersistentExport.java

Verify that streams from migrate and change of data capture are included in the stream limit calculation.

ENG-16080 verify migrate streams are accounted for in stream limits

---

src/frontend/org/voltdb/planner/MVQueryRewriter.java
tests/frontend/org/voltdb/regressionsuites/TestMVOptimizationSuite.java

Remove the creation of unnecessary streams, Pairs and collections while
handling materialized view query rewrites.

ENG-14531: Reduce the number of intermidiary objects

---

src/frontend/org/voltdb/client/ClientImpl.java
src/frontend/org/voltdb/client/Distributer.java

which causes some unit test failures.

ENG-16085 Client affinity and topology update during client shutdown prevent client from being promptly shutdown

---

src/frontend/org/voltdb/export/ExportCoordinator.java

Improve testability with INFO level messages

ENG-16143, report gap coverage at INFO level for better testability

---

src/ee/storage/persistenttable.cpp

[ backport 3c1e34558ab81fa0a60877ee2d848a205a61eed6 ]
notifyTupleInsert is used to notify table streams of tuples which were
inserted. However this method was being called prior to inserting the tuple
into the indexes. If the tuple violated any unique constraints of an index then
the tuple would be removed from the index but the table stream would not be
notified. This is an issue for elastic operations since notifyTupleInsert adds
the tuple into the elastic index.
Moving the call notifyTupleInsert to after index insertion guarantees that the
tuples in the elastic index are all valid tuples part of a table and two
entries in the index do not point to the same tuple.

ENG-16125: Call notifyTupleInsert after indexing

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java

Backport rate-limiting export messages

ENG16023, limit some export warning messages

---

src/frontend/org/voltdb/export/ExportGeneration.java

The message is reporting a transient condition, and should not be an error IMO.

ENG-15849, turn error into warning and rate limit them

---

src/ee/common/UndoQuantumReleaseInterest.h
src/ee/common/types.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/DRTupleStream.h
src/ee/storage/ExportTupleStream.cpp
src/ee/storage/ExportTupleStream.h
src/ee/storage/persistenttable.cpp
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h

Pro side: https://github.com/VoltDB/pro/pull/2606

Eng 15560 nibble migrate dr safe guard

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

1. Fixed the "Traceback" I've seen in memcheck (-pro & -nodebug),
following "tweak2". This was caused by an extremely long Stack Trace,
which it is trying to add multiple times (with slight differences),
which caused the Description to exceed Jira's limit, so I shortened
those.
2. No longer file a new ticket for Jenkins tests with status 'FIXED'
(nor for 'PASSED', but that's not new).
3. Make sure it does not change "Fix Version" to "Backlog", if it was
changed (presumably manually, similar to the "Blocker" issue above); it
probably should (and perhaps already does??) only set the "Fix Version"
to "Backlog" when the ticket is created.
4. Put the failure history link before the Stack Trace (in new tickets,
at least).
5. Fix an issue with URL's for tests named junit.framework/TestSuite/... …

ENG-16021: Third set of tweaks to the JUnit Auto-filer:

---

src/ee/execution/VoltDBEngine.cpp
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/JoinProducerBase.java
src/frontend/org/voltdb/iv2/RejoinProducer.java

https://github.com/VoltDB/voltdb/pull/6232/files

Refactor according to pull request review

---

src/frontend/org/voltdb/export/AckingContainer.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/exportclient/ExportRow.java
src/frontend/org/voltdb/exportclient/ExportRowSchema.java
src/frontend/org/voltdb/exportclient/ExportRowSchemaSerializer.java
src/frontend/org/voltdb/utils/BinaryDequeDeferredSerializer.java
src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java

Refactor schema management to leverage ENG-16231

Eng 16256 export schema metadata

---

tests/log4j-allconsole.xml
voltdb/log4j.xml

Revert debug level of Export to normal

Reset logger level for Export

---

src/frontend/org/voltdb/iv2/ElasticJoinProducer.java

During an elastic join the new partition leaders are promoted one at a time.
This means there a points in time when an mp request can get to a subset of the
new partitions. The previous invocation location of setViewsEnabled could
result in a subset of the new partitions waiting in the ee at the count down
latch. Then if another MP transaction was executed those sites would not
process the fragment task and cause an MP deadlock.
Do not call setViewsEnabled until all partitions are participating in the MP
transactions and this known when the first block of snapshot data is processed.

ENG-16304: Disable views just before snapshot processing

---

tools/jenkins/junit-stats.py

Just fixed a problem when there is no last_build_recorded (in the 'qa'
database), which was affecting test-nextrelease-nonflaky-pro-junit
builds.

ENG-16021: Fifth set of tweaks to the JUnit Auto-filer:

---

src/frontend/org/voltdb/iv2/JoinProducerBase.java

This reverts commit effdcb7f6fd0ad10abaae293d8d0ef1cff713b6f.

Revert "Fix ENG-16220-TestJoinProducer"

---

src/ee/common/ThreadLocalPool.cpp

ThreadLocalPool.cpp:getAllocationSizeForObject adds
CompactingPool::FIXED_OVERHEAD_PER_ENTRY() as part of the overhead for the
allocation size. Then that value is rounded up to the nearest power of 2 and
passed into the CompactingPool constructor. The CompactingPool constructor then
adds CompactingPool::FIXED_OVERHEAD_PER_ENTRY() to the allocation size again
causing it to be double counted.
Subtract CompactingPool::FIXED_OVERHEAD_PER_ENTRY() from the allocation size
before constructing CompactingPool.

ENG-16420: Do not double count CompactingPool::FIXED_OVERHEAD_PER_ENTRY

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java

Change-Id: Idaa72f0e47951f5469dac75ef2309dcf193ae947

ENG-15814, reset export state after cleanup stale buffers.

---

tools/jenkins/jenkinsbot.py

Just a minor improvement to the previous change, involving re-raising
any exception more consistently, in modify_jira_bug_ticket. (But this
time, based on master, not the previous tweak.)

ENG-16021: Seventh set of tweaks to the JUnit Auto-filer:

---

src/ee/common/tabletuple.h
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Update the logic for deserialization of stream snapshot on BalancePartitions with migrate tables.

ENG-16379 deserialization on cluster resize

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/exportclient/ExportDecoderBase.java
src/frontend/org/voltdb/exportclient/ExportRowSchema.java
src/frontend/org/voltdb/exportclient/JDBCExportClient.java

Preliminary code review to validate approach, more testing needed.

ENG-16385: implement logic detecting schema changes in JDBC connector

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/licensetool/LicenseApi.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/MockVoltDB.java

Added license info to daily logging.

Added license info to daily logging.

---

lib/python/voltcli/voltadmin.d/resize.py

resize.py uses str.find() to test if a sub string is in a string but this
method is more equivalent to indexof which means performing an if on the result
will be false if "host ids" is at the start of the string or be true if it
isn't in it at all.
Use the keyword in to test if a sub string is part of another string.
Do not use the variable name type since that is python builtin.

ENG-16553: Use in to test for substring

---

src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpProcedureTask.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TickProducer.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java

Set correct status on the new partition leader when the host with previous partition leader is down.

ENG-15584 leader migration status upon node failure

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/sysprocs/ExportControl.java

Change-Id: I4728ca244a0073ae1d2bb3d4dc107142c03a4209

ENG-16532, fix the gap release issue..

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

Fixed issue with non-numeric build number (e.g., when followed by
'---...' rather than \n); added better debugging for 'limit' failure
issue; added get_modified_labels function and related code; and other
minor tweaks.

ENG-16021: Ninth set of tweaks to the JUnit Auto-filer:

---

lib/python/voltcli/voltadmin.d/show.py
lib/python/voltcli/voltdb.d/get.py
src/frontend/org/voltdb/GetActionArgument.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java

Sample output for show license (community license):
-- License Information --
PROPERTY                VALUE                        
----------------------- -----------------------------
PERMIT_VERSION          0                            
PERMIT_SCHEME           0                            
TYPE                    Community Edition            
ISSUE_DATE              Wed Jun 26, 2019             
LICENSEE                VoltDB Community Edition User
EXPIRATION              Sun Jun 26, 2039             
HOSTCOUNT_MAX           2147483647                   
FEATURES_TRIAL          false                        
FEATURES_UNRESTRICTED   false                        
FEATURES_COMMANDLOGGING false                        
FEATURES_DRACTIVEACTIVE false                        
NOTE …

ENG-16283 Add license command

---

tools/jenkins/junit-stats.py

ENG-16021: Fixed the 'labels' failure issue (in junit-stats.py's

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

Change-Id: Iaae9fd8acecacdd3c43049463ec04fb37dde7ca9

ENG-16609, add diagnostical logs.

---

lib/python/voltcli/voltadmin.d/resize.py

When a host is down converting the host ID to a hostname fails and throws an
exception. If the hostname is not known return UNAVAILABLE as the hostname.

ENG-16898: Handle host down

---

tests/frontend/org/voltdb/AdHocQueryTester.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/TestLikeQueries.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestAdHocPlannerCache.java
tests/frontend/org/voltdb/regressionsuites/TestApproxCountDistinctSuite.java
tests/frontend/org/voltdb/regressionsuites/TestComparisonOperatorsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestConcurrentUpdateCatalog.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForJSON.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsSuite2.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyPointValue.java
tests/frontend/org/voltdb/regressionsuites/TestGeographyValueQueries.java
tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexMaterializedViewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexSuite.java
tests/frontend/org/voltdb/regressionsuites/TestJoinsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java
tests/frontend/org/voltdb/regressionsuites/TestUnionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestUserDefinedFunctions.java
tests/frontend/org/voltdb/regressionsuites/testjoins-ddl.sql
tests/sqlcmd/baselines/simple/testcte.errbaseline
tests/sqlcmd/baselines/udf/tuple_limit_delete_using_udf.errbaseline
tests/testprocs/org/voltdb_testprocs/regressionsuites/fixedsql/fixed-sql-ddl.sql

Going through JUnit tests to make sure that all changes made, or tests skipped on calcite integration branch should still persist if git branch name contains "**calcite_**"; but should otherwise behave the same way as master branch.

Calcite fixup for junit

---

src/frontend/org/voltdb/CLIConfig.java
tests/frontend/org/voltdb/plannerv2/CalcitePlannerTestCase.java
tests/frontend/org/voltdb/plannerv2/PlanChecker.java
tests/sqlgrammar/plan-checker

Fixes of plan-checker

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/dbmonitor/index.htm
src/frontend/org/voltdb/dbmonitor/js/voltdb.ui.js

Add license type to VMC

---

src/frontend/org/voltdb/VoltDB.java

to allow apprunner to collect these testing artifacts.

ENG-16967 update stack dump file name upon detection of DEAD HOST

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

print out action blocker info when rejoining timeout

ENG-16577 added more logging around action blockers

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h

2 commits, to be merged as is (no squash, rebase, etc.)

Fix broken pool build

---

src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java

In this pr I tentatively delete the **resolve having condition** code which only repeats the work that `queryCondition.resolveTypes()` does. As for now, NPE gone, tests all passed, review needed.

ENG-16930 Fix NPE with HAVING, Like

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/in/javasrc/DRCatalogDiffEngine.java
src/ee/common/CatalogUtil.h
src/frontend/org/voltdb/DefaultProcedureManager.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/TableType.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/sysprocs/MigrateRowsBase.java
src/frontend/org/voltdb/sysprocs/MigrateRowsNT.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/frontend/org/voltdb/utils/CatalogUtil.java

Ensure the snapshot contains information allowing truncating all the types of tables that can be exporting to a PBD. 
Rename and refactor some methods identifying the table type.
Ignore truncation of replicated tables on partitions other than 0.

Eng 17168 what are streams really

---

src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/utils/CatalogUtil.java

do not delete tuples from tables exported via create table <table> export to target.

ENG-17387 do not issue delete for persist export 

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLogical.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/SubQuery.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

Revert "ENG-16927 Fixed NPE caused by sub-query"

---

src/ee/common/ExecuteWithMpMemory.h
src/ee/executors/insertexecutor.cpp

Make locking on insertexecutor for static std::string more fine-grained, by
moving it to ConditionalSynchronizedExecuteWithMpMemory templated constructor.

Addressed Walter PR comments

---

tests/test_apps/genqa/src/genqa/procedures/JiggleMultiPartitionWithDeletionExport.java
tests/test_apps/genqa/src/genqa/procedures/JiggleSinglePartitionWithDeletionExport.java

fixed table/column mismatches in the stored procedures

ENG-17593 match sql statements with DDL

---

src/ee/common/SynchronizedThreadLock.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/BinaryLogSinkWrapper.cpp
src/ee/storage/BinaryLogSinkWrapper.h
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

Broken PR #6492 into 3 smaller PRs in succession (i.e. commit dependency).
This is the first of 3 PRs. Centers on clean up/refactory of VoltDBEngine.*.

Refactory on VoltDBEngine

---

build.xml
src/frontend/org/voltdb/sched/Action.java

ENG-17627:

---

src/frontend/org/voltdb/VoltDB.java

By restoring return statement this pr should fix unit test failure in both TestInitStartLocalClusterInProcess and TestInitStartLocalClusterOutOfProcess

ENG-16288 Fixed TestInitStartLocalCluster In/Out of Process failure

---

src/frontend/org/voltdb/dbmonitor/css/layout.css
src/frontend/org/voltdb/dbmonitor/css/tablesorter.css
src/frontend/org/voltdb/dbmonitor/index.htm
src/frontend/org/voltdb/dbmonitor/js/nv.d3.min(modified).js
src/frontend/org/voltdb/dbmonitor/js/template.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.graph.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.render.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.service.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.ui.js

Work still to be done:
* Support for Type Column that displays type of target (Possible solution - parse http://localhost:8080/deployment/?admin=true)
* Radio buttons for turning graph lines on and off in table instead of legend

Vmc export

---

src/frontend/org/voltdb/sysprocs/SwapTables.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/regressionsuites/TestSystemProcedureSuite.java

to prevent their PBD files from being messed up.

ENG-17761 disallow table swap between migrate tables

---

src/catgen/spec.txt
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/ImporterServerAdapterImpl.java
src/frontend/org/voltdb/InternalClientResponseAdapter.java
src/frontend/org/voltdb/InternalConnectionHandler.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/JdbcDatabaseMetaDataGenerator.java
src/frontend/org/voltdb/ParameterSet.java
src/frontend/org/voltdb/ProcedurePartitionData.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/StoredProcedureInvocation.java
src/frontend/org/voltdb/client/ClientImpl.java
src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/client/ProcedureInvocation.java
src/frontend/org/voltdb/client/ProcedureInvocationExtensions.java
src/frontend/org/voltdb/compiler/ProcedureCompiler.java
src/frontend/org/voltdb/compiler/statements/CreateProcedure.java
src/frontend/org/voltdb/compilereport/ReportMaker.java
src/frontend/org/voltdb/exportclient/loopback/LoopbackExportClient.java
src/frontend/org/voltdb/importer/AbstractImporter.java
src/frontend/org/voltdb/importer/ImporterServerAdapter.java
src/frontend/org/voltdb/messaging/InitiateTaskMessage.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java
src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
tests/frontend/org/voltdb/TestStoredProcedureInvocation.java
tests/frontend/org/voltdb/client/PartitionedTestProc.java
tests/frontend/org/voltdb/client/TestAllPartitionProcedureCalls.java
tests/frontend/org/voltdb/client/allpartitioncall.sql

Add the ability to create and invoke procedures which are partitioned but do not require a partition parameter. These procedures need to be directed to a partition by using a new partition destination extension of StoredProcedureInvocation.

ENG-15906: Directed procedures

---

src/frontend/org/voltdb/export/ExportCoordinator.java
src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java

Minor changes to support E3 design. Preserve current E2 behavior.

ENG-17853: refactor sequence number tracker to support specialization

---

src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

Validate that the user specified to be used by a task exists

ENG-17780: Validate that a user exists

---

build.xml
src/catgen/catalog.py
src/catgen/spec.txt
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/JdbcDatabaseMetaDataGenerator.java
src/frontend/org/voltdb/compiler/statements/CreateTask.java
src/frontend/org/voltdb/task/Initializable.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskManager.java
src/frontend/org/voltdb/task/TaskScope.java
src/frontend/org/voltdb/task/TaskStatsSource.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

Add a setScopeId method to Initializable with a default implementation of a no-op. An impelemantation of Initializable can implement setScopeId to capture the scope and ID of the scope.

ENG-17936: Pass the scope and scope ID to the class instance

---

tools/datagen-with-ddl.py
tools/datagen.py

- Added tool datagen-with-ddl.py
Usage: datagen-with-ddl.py ddl.sql 500
This will modify ddl.sql to add 500 INSERT statements after each CREATE TABLE statement
Note: we have yet another python parser...
(and some gotchas, see comments in script for details)
- Fixed bug on varchar with no width

More on datagen prototyping tools

---

tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

globalFlushInterval and exportFlushInterval

ENG-18063: Fixed sqlcmdtest, 2 explaincatalog additions:

---

tests/test_apps/genqa/ddl1.sql
tests/test_apps/genqa/src/genqa/procedures/JiggleExportMultiPartition.java

Small changes to genqa to all replicated table option for serverexport tests.

ENG-18000: add replicated vs partioned table choice.

---

src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestTransactionTaskQueue.java

organize scoreboards and task queues to allow easy removal and addition

ENG-18061 scoreboard refactoring

---

tests/frontend/org/voltdb/jdbc/TestJDBCSecurityEnabled.java

Unit tests are failing intermittently with host shutdowns but it is unclear if this is a test interdependency issue so there are not println's between tests so the test interactions can be identified.

ENG-14250:

---

src/frontend/org/voltdb/iv2/DuplicateCounter.java

check the hashes before they are compared on rejoining or not

ENG-18135 handle the corner cases for hash comparison

---

src/frontend/org/voltdb/export/ExportCoordinator.java
src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java
tests/frontend/org/voltdb/export/ExportTestExpectedData.java
tests/frontend/org/voltdb/export/ExportToSocketTestVerifier.java
tests/frontend/org/voltdb/export/TestExportBaseSocketExport.java
tests/frontend/org/voltdb/export/TestExportCoordinator.java
tests/frontend/org/voltdb/export/TestExportRejoin.java
tests/frontend/org/voltdb/export/TestExportSequenceNumberTracker.java

Fixed a couple bugs in ExportCoordinator on edge cases.
Fixed bug in test infrastructure.

ENG-17776: fix corner cases in export coordination

---

src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/exportclient/SocketExporterLegacy.java
tests/frontend/org/voltdb/TestExportLiveDDLSuiteLegacy.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java

Tested with TestExportLiveDDLSuiteLegacy and TestRejoinEndToEnd

ENG-18202: call legacy onBlockStart and add test cases

---

tests/frontend/org/voltcore/agreement/TestFuzzMeshArbiter.java

TestFuzzMeshArbiter has a corner case that is unhandled. When only hosts are dropped and no links are broken, the pruneDeadHosts does not remove the dead hosts from the live hosts list. This in turn cases a convergence failure bacause the dead host's mesh looks different from the convereged live hosts list.

ENG-15555:

---

tests/frontend/org/voltdb/plannerv2/TestPhysicalJoin.java

By adding another possible plan

Fixed TestPhysicalJoin

---

src/frontend/org/voltdb/InvocationDispatcher.java

InvocationDispatcher will update parameters of procedures when a partition
parameter is given for a directed procedure or the partition paramter does not
match the partition destination. When this happens the serializedParameters in
the invocation are null which can cause an NPE when the commang log tries to
record them.

ENG-18243: Make sure serialized params is not null

---

tools/jenkins/junit-stats.py

Mainly, changed dbhost back to always being 'junitstatsdb.voltdb.lan';
also improved error messages for 'Could not connect to qa database' and
'Build range too large'.

ENG-17694: Auto-filer: fixed what I broke yesterday

---

src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltcore/utils/UnsafeDirectBufferCleaner.java

The container is responsible for cleaning up native allocated direct memory.

ENG-17757 use designated container for native direct allocated memory

---

tests/frontend/org/voltdb/export/TestExportClientBasic.java

- Added code to make sure that code waiting to drain does not call it success before EE has started pushing records out for a partition.
- Use AtomicInteger for variable used from multiple threads.

ENG-18355: Fixing possible causes for intermittent test failures:

---

src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/HashMismatchMessage.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
tests/frontend/org/voltdb/dtxn/Deterministic_RO_SP.java
tests/frontend/org/voltdb/dtxn/NonDeterministicSPProc.java
tests/frontend/org/voltdb/dtxn/NonDeterministic_RO_MP.java
tests/frontend/org/voltdb/dtxn/NonDeterministic_RO_SP.java
tests/frontend/org/voltdb/dtxn/TestNonDetermisticSeppuku.java

This feature is a pro only feature. Test cases were updated.

ENG-18449  set the state of replica sites to be eligible for removal when hash mismatch is detected

---

src/frontend/org/voltdb/exportclient/ExportRow.java

Small changes to support incremental fetch

Use row timestamp

---

src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

Add a method to PBD to support assertion in E3

ENG-18497: simplify E3 readers

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java
tests/test_apps/genqa/src/genqa/procedures/MigratePartitionedExport.java
tests/test_apps/genqa/src/genqa/procedures/MigrateReplicatedExport.java

ENG-18495:  use a separate timer object for the manual migration task

---

tests/test_apps/genqa/src/genqa/ExportRabbitMQVerifier.java

>$ ant -f build.xml  licensecheck 
>...
>licensecheck:
>     [exec] SUCCESS. Found 0 license text errors, 0 files containing tabs or trailing whitespace.
>
>BUILD SUCCESSFUL
>Total time: 23 seconds

ENG-18543: fix whitespace issues

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
src/frontend/org/voltdb/iv2/MpInitiator.java
tests/frontend/org/voltdb/dtxn/TestNonDetermisticSeppuku.java

Add test cases with higher site per host and kfactor to verify multiple replica removal.

ENG-18493 accumulate replica removal tasks to avoid task over-scheduled

---

src/ee/CMakeLists.txt
src/ee/common/NValue.hpp
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/ElasticIndex.h
src/ee/storage/SystemTableFactory.cpp
src/ee/storage/SystemTableFactory.h
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/persistenttable.cpp
src/ee/structures/CompactingHashTable.h
src/ee/structures/CompactingMap.h
tests/ee/CMakeLists.txt
tests/ee/storage/SystemTableFactoryTest.cpp
tools/VoltDBCompilation.cmake

Create SystemTableFactory to create the system tables and create the tables during catalog load in VoltDBEngine

ENG-18401: Add system tables to EE

---

src/frontend/org/voltdb/exportclient/ExportDecoderBase.java
src/frontend/org/voltdb/exportclient/loopback/LoopbackExportClient.java

Changes to class to support a pause/restart operation.

Eng 18582 e3 locked in loopback

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/settings/DbSettings.java
src/frontend/org/voltdb/settings/NodeSettings.java
tests/frontend/org/voltdb/dtxn/TestHashMismatches.java

added test case for snapshot save and restore in master-only mode

ENG-18598 keep track of local active site count

---

src/frontend/org/voltdb/exportclient/ExportToFileClient.java

ENG-18599: detect file name conflict when finalizing active files, and rename to a revised file name that doesn't conflict

Eng 18599 closefiles assert

---

src/frontend/org/voltdb/exportclient/ExportToFileClient.java

* ENG-18599: detect file name conflict when finalizing active files, and rename to a revised file name that doesn't conflict

Eng 18599 closefiles assert (#6733)

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/DummyCommandLog.java
src/frontend/org/voltdb/LogEntryType.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
tests/frontend/org/voltdb/dtxn/NonDeterministicSPProc.java
tests/frontend/org/voltdb/dtxn/TestHashMismatches.java

register IV2Fault for master only change. Updated  test cases to shutdown and recover with command log enabled.

ENG-18637 log entry for master only mode

---

build.xml
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/task/DurationIntervalGenerator.java
src/frontend/org/voltdb/task/SingleProcGenerator.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskHelperImpl.java
src/frontend/org/voltdb/task/TaskManager.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/frontend/org/voltdb/utils/CompoundErrors.java
src/frontend/org/voltdb/utils/RetentionPolicyMgr.java
tests/frontend/org/voltdb/utils/TestMaxBytesRetentionPolicy.java
tests/frontend/org/voltdb/utils/TestTimeBasedRetentionPolicy.java

Eng 18613 topic groups

---

src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/DummyCommandLog.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/SpScheduler.java

to allow snapshot complete check

ENG-18713 notify CommandLog of partition decommission

---

src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPBDsWithIds.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDequeCorruption.java

- Read and verify start and end ids on PBD segments on recover
- seek implementation on PBD

Eng 18583 recover and seek

---

src/frontend/org/voltdb/utils/SQLCommand.java

correct error message, and comment out undocumented/nonfunctional argument CONFIG

Fixed SHOW/LIST processing to be case insensitive,

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltcore/messaging/BinaryPayloadMessage.java
src/frontend/org/voltcore/zk/ZKUtil.java
src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/sysprocs/VerifyCatalogAndWriteJar.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateClasses.java

Each catalog update still need to under than 50 MB, but the change is incremental, the total size of catalog can go beyond 50 MB.

ENG-18429, support catalog bigger than than 50 MB.

---

src/frontend/org/voltdb/ProcedureRunner.java

Reverts VoltDB/voltdb#6767, the stack trace is used for testing

Revert "ENG-18669 log stack trace only when debug is enabled."

---

src/frontend/org/voltdb/InvocationDispatcher.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/regressionsuites/TestRestoreSchema.java

When restore schema from a snapshot errors out reset state so it can be retried.

ENG-18697: Reset state if snapshot recovery errors out

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java

Add to suppressed message list
Fix suppressed spelling
Better highlighting of metadata count mismatch

Eng 18736 tableexport test

---

src/frontend/org/voltdb/export/StreamBlock.java

- Accept sequence number for releaseTo > lastSequenceNo
- New method to get a read only buffer with refcount incremented

ENG-18825: StreamBlock changes:

---

src/frontend/org/voltdb/utils/Mutex.java

If the thread is set after the state is set to UNHELD there is a small
race where another thread could grab the mutex and set the owner thread
before the thread performing the race has a chance to clear the owner
thread. When this happens a thread owns the lock but owner thread is set
to null. While this has no affect on the lock behavior it does cause
lock info in stack traces and Mutex.isHeldByCurrentThread to not be
correct.

ENG-18980: Reset thread before setting state to UNHELD

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

In the new compacting storage module.

Deprecate tail compaction

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Not to be merged yet.
Added chunk id to list to facilitate tuple addr comparison (and snapshot iterator comparison).

Snapshot iterator aware hook

---

tests/test_apps/txnid-selfcheck2/build.xml
tests/test_apps/txnid-selfcheck2/run.sh
tests/test_apps/txnid-selfcheck2/src/bigjar/CreateLargeFiles.java
tests/test_apps/txnid-selfcheck2/src/bigjar/procedures/Insert.java
tests/test_apps/txnid-selfcheck2/src/bigjar/procedures/SelectLEtbd.java

Community (VoltDB): in txnid-selfcheck2, added CreateLargeFiles.java,
which creates large files, currently 'large-random-textX.txt' (where X
is 1, 2, 3, or 4); and added, to the run.sh, file, a 'function
big-jars', which calls CreateLargeFiles.java, and uses its large text
files to generate 4 different jar files ('txnid-big-textX.jar'), each a
little less than 50Mb (compressed from the text files, which are a
little bigger than 50Mb); plus a few cosmetic changes.

ENG-18527-ap-large-jar4:

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

As per @wweiss-voltdb requested.

Added allocator statistics

---

src/frontend/org/voltdb/utils/PbdSegmentName.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPbdSegmentName.java

Port removal of software version from PBD filename from the kipling branch

ENG-19060: Removed version number from PBD filename.

---

src/ee/executors/seqscanexecutor.cpp
src/ee/executors/seqscanexecutor.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

Add missing code not found in last commit

ENG-18744:

---

src/frontend/org/voltdb/export/ExportAvroSerializer.java
src/frontend/org/voltdb/exportclient/ExportRow.java

Eng 19016 topic key columns

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/indexes/tableindex.cpp
src/ee/kipling/GroupStore.cpp
src/ee/kipling/GroupStore.h
src/ee/kipling/TableFactory.cpp
src/ee/kipling/TableFactory.h
src/ee/kipling/orm/Group.cpp
src/ee/kipling/orm/Group.h
src/ee/kipling/orm/GroupOffset.cpp
src/ee/kipling/orm/GroupOffset.h
src/ee/kipling/orm/GroupOrmBase.cpp
src/ee/kipling/orm/GroupOrmBase.h
src/ee/storage/SystemTableFactory.cpp
src/ee/storage/SystemTableFactory.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/KiplingSystemTableConnection.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
tests/ee/kipling/GroupStoreTest.cpp
tests/ee/kipling/GroupTestBase.h
tests/ee/kipling/KiplingTableFactoryTest.cpp
tests/ee/kipling/orm/GroupOrmTest.cpp

ENG-19093: Add partial index to track standalone groups
ENG-19094: Add delete for expired offsets
ENG-19095: Add procedure and ee method for expiring offsets

ENG-19092: Add methods to delete expired offsets

---

src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/utils/VoltTableUtil.java

Related https://github.com/VoltDB/pro/pull/3005

ENG-19076: Persist offsets

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java

I noticed that some unit tests were failing because of the getData call
from the assert check was throwing a connection loss exception. This can
occur when the ssm is concurrently running while shutdown is being
called. Wrap the getData call in a try block which catches the commonly
ignored exception types.

SSM: Do not throw zookeeper exceptoins from assert check

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp

Enable using thread local pool as alternative for heap allocator.

Eng 19128 customize allocator behavior

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp

on Chunks id generation and testing;
and enable the check only for debug build

Fixed racing condition

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/exportclient/PersistedMetadata.java
src/frontend/org/voltdb/serdes/EncodeFormat.java

Store the encoding format for a topic in the PBD. Add the encoding
format to PersistedMetadata and add it to the serdes.

ENG-19131: Store encoding format in PBD

---

src/frontend/org/voltdb/exportclient/ExportRow.java
src/frontend/org/voltdb/exportclient/ExportRowSchema.java
src/frontend/org/voltdb/exportclient/PersistedMetadata.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/utils/SerializationHelper.java

PersistedMetadata: Add topic key columns
SerializationHelper: Added utility method to get the size of serialized string and remove unused features in 
ExportRowSchema: Use ImmutableLists for publicly accessible fields

ENG-19139: Persist key columns in PBD

---

src/catgen/spec.txt
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/export/ExportAvroSerializer.java
src/frontend/org/voltdb/exportclient/ExportRow.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/utils/CatalogUtil.java

- Modify deployment to define an avro element and add thread pool name to topics
- handle changes to avro element 
(thread pool is not handled, will be provided in a later update)

Eng 18611 18747 avro and thread config

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

the STL collections (ordered set/map).

Add b+ tree as alternative of

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

-  **API changes on batch removal operations**
- **NOT tested on MacOSX, C7, etc**

Allocator batch removal optimization

---

tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

Fixed broken test, passed on branch

ENG-19145: fix baseline adding topic-related fields

---

src/frontend/org/voltdb/Inits.java

now updated based on dependencies declared in code.
comment-only change.

comment about dependencies was incomplete. 

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java

Extend the ExportManagerInterface to  allow propagating listener creation to Kipling

ENG-18998: support for kipling partition migration listener

---

src/frontend/org/voltdb/utils/SerializationHelper.java
tests/ee/kipling/GroupStoreTest.cpp

Add utility method to get serialized size of array
Related https://github.com/VoltDB/pro/pull/3038

ENG-19077: Persist groups

---

src/frontend/org/voltdb/utils/SerializationHelper.java

Add ByteBuf serialization helpers for writing byte[] and String into
ByteBuf. Also, remove duplicate code between reading Strings and reading
byte[]
Related https://github.com/VoltDB/pro/pull/3046

ENG-19191: Add serialization helpers for ByteBuf

---

src/frontend/org/voltdb/SnapshotTableInfo.java
src/frontend/org/voltdb/TheHashinator.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/messaging/RejoinMessage.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/rejoin/TestIv2RejoinCoordinator.java
tests/frontend/org/voltdb/rejoin/TestIv2RejoinCoordinatorLive.java

ENG-19133: Add method to get hashToken of Object
SytemTables: With system tables there is always persistent tables
Related https://github.com/VoltDB/pro/pull/3050

ENG-19133: Integrate kipling with elastic

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Changed APIs for batch remove_add and update, so that they return something indicating a few things (if the table is currently frozen; if there is a freshly created copy in the hook, etc; and the location of that copy -- see document for details).
Added API for the constructor of `HookedCompactingChunks` with a call back that is responsible for the deep clean of shallow tuple address not tracked by the allocator. Tests ensure that the call back (if set) are called at appropriate time.
Minor: now the `remove_add` method changed from normal method to templated method (since it returns indicators for the copy in hook memory); and `remove_force` method changed from templated method to normal method (since the hook call is moved to `remove_add`). This implies that exceptions rising from either …

Added new APIs for remove/delete with callback

---

src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/utils/CatalogUtil.java

- remove the <defaults> element
- allow all retention updates when profile is not in use
- prevent declaring profiles with blank names

ENG-19220:

---

build.xml
lib/python/voltcli/voltadmin.d/resize.py

Add --delay argument to resize command.
Reorganize the junit tests so that they different groups are a little more even
Related https://github.com/VoltDB/pro/pull/3053

ENG-19134: Add shutdown delay to elastic remove

---

src/ee/kipling/GroupStore.cpp
src/ee/kipling/orm/Group.h
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/task/CompositeActionScheduler.java
src/frontend/org/voltdb/task/TaskManager.java
src/frontend/org/voltdb/task/TaskStatsSource.java
tests/ee/kipling/GroupStoreTest.cpp
tests/frontend/org/voltdb/task/TestTaskManager.java

Add system tasks to TaskManager
Update group commit timestamp with offsets
Related https://github.com/VoltDB/pro/pull/3059

ENG-19090: System tasks and update group timestamp

---

tests/test_apps/kafkaimporter/client/kafkaimporter/MatchChecks.java

. log a warning if we find a blocked export stream while processing stats
. remove unused isExportDrained method
. increase timeout waiting for drain to 3 minutes

ENG-19228: longer time to wait for export stream to drain

---

lib/python/voltcli/voltadmin.d/gshutdown.py
lib/python/voltcli/voltadmin.d/gstop.py
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/sysprocs/GracefulShutdown.java
src/frontend/org/voltdb/sysprocs/GracefulShutdownWait.java
src/frontend/org/voltdb/sysprocs/GracefulStopNode.java
src/frontend/org/voltdb/utils/SQLCommand.java

Moves the procedure that's in voltadmin into an NT sysproc.
(Note this is a merge into the KO integration branch, not master)

add GracefulStopNode

---

src/frontend/org/voltdb/VoltTableRow.java
src/frontend/org/voltdb/utils/SnapshotComparer.java

This should show the diffs between vpt files in the console
```
Finished comparing table AREA_CODE_STATE.
Finished comparing table VOTES.
Finished comparing table V_VOTES_BY_PHONE_NUMBER.
Diffs between file ./host0/MANUAL1581622336043-CONTESTANTS.vpt and file ./host1/MANUAL1581622336043-CONTESTANTS.vpt
1,Edwina Burnam
2,Tabatha Gehling
3,Kelly Clauss
-4,Jessie Alloway
+4,Jessie Eichman
5,Alana Bregman
-6,Jessie Eichman
+6,Jessie Alloway
WARN: Replicated Table CONTESTANTS is inconsistent between host0 with host1 on partition 16383
Finished comparing table CONTESTANTS.
```

ENG-18715: enhance snapshot compare result output, diff style

---

src/frontend/org/voltdb/e3/GapFillContinue.java
src/frontend/org/voltdb/e3/GapFillMessage.java
src/frontend/org/voltdb/e3/GapFillRequest.java
src/frontend/org/voltdb/e3/GapFillResponse.java
src/frontend/org/voltdb/e3/HeapPBDEntry.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/exportclient/PersistedMetadata.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/e3/TestGapFillMessages.java

Add messages to the system which can be used to request blocks to fill gaps and respond to those requests.
Related https://github.com/VoltDB/pro/pull/3078

ENG-19239: Add messages for gap filling

---

tests/test_apps/oneshotkv/ddl.sql
tests/test_apps/overhead/ddl.sql
tests/test_apps/scans/ddl.sql

VoltDB (community): added, to tests/test_apps/FOO/ddl.sql (where FOO is
oneshotkv, overhead, and scans), a 'LOAD CLASSES FOO.jar;' line, which I
expect will fix ENG-19174.

ENG-19174-ap-legcy-broke-perf:

---

src/ee/common/tabletuple.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

ENG-18744 logging context mismatch and update snapshot coping

---

src/frontend/org/voltdb/e3/GapFillRequest.java
src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/export/TestExportGap.java
tests/frontend/org/voltdb/export/TestExportSequenceNumberTracker.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/utils/TestPBDGapWriter.java

ExportSequenceNumberTracker.intersectionSizeInSequences
Use utility methods to request closed ranges
Related https://github.com/VoltDB/pro/pull/3088

ENG-19289: Integrate gap fill

---

src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/iv2/UniqueIdGenerator.java
src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/BinaryDequeGapWriter.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
src/frontend/org/voltdb/utils/RetentionPolicyMgr.java
tests/frontend/org/voltdb/export/TestExportSequenceNumberTracker.java
tests/frontend/org/voltdb/rejoin/TestPauselessRejoinEndToEnd.java
tests/frontend/org/voltdb/utils/TestPBDGapWriter.java
tests/frontend/org/voltdb/utils/TestPBDsWithIds.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestTimeBasedRetentionPolicy.java

Related: https://github.com/VoltDB/pro/pull/3095

ENG-19302: Use timestamp in PBD header for retention

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Disabled a few tests, need to add them back by making test logic aware of deep copy.

Always finalize

---

src/frontend/org/voltdb/compiler/DDLCompiler.java

Related https://github.com/VoltDB/pro/pull/3098

ENG-19344: Use role not user group

---

src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltdb/e3/HeapPBDEntry.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java

Move checkDoubleFree into DBBDelegateContainer.discard
Add a way to free an Entry
Allow seek for non transient readers

ENG-19400: Gap filling fixes

---

src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

check corner cases to thaw iterator

ENG-19333 verify tuples streamed and iterator state

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp

address in batch removal which helps differentiate what to finalize, to
track remove addresses.
Also track by using position_type to help diagnose the conflict

Changed from tracking compacted

---

src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/iv2/Scheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/DumpMessage.java

ENG-19422 log JStack upon mp deadlock

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/operator/OpPesudoShutdown.java
src/frontend/org/voltdb/operator/OpPseudoShutdown.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
tests/frontend/org/voltdb/MockVoltDB.java

Call by k8s controller, do minimum cleanup (but don't kill database) so the system is ready to
call initialize again.

KO-135, add @OpPesudoShutdown system procedure.

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
src/ee/storage/persistenttable.cpp
tests/ee/storage/TableTupleAllocatorTest.cpp

batch-removal; and un-conditional finalize of frozen, non-txn regions.
Tests partially updated

Changes on conditional deep-copy of

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

Allow seeks with outstanding buffers in PBD

ENG-19413: Rejoin system tests failures

---

lib/python/voltcli/voltadmin.d/status.py
src/frontend/org/voltdb/utils/SQLCommand.java

A fourth argument was added to @ElasticRemoveNT but not all callers were updated. Update all callers and references to have the fourth argument.

ENG-19415: @ElasticRemoveNT now has 4 arguments

---

src/frontend/org/voltdb/export/ExportDataSource.java
tests/sqlcmd/baselines/ddl/load_remove_classes.outbaseline
tests/sqlcmd/baselines/errors/create_proc.outbaseline

Related https://github.com/VoltDB/pro/pull/3116

ENG-19453: Update log to match message in e3

---

src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java

Related https://github.com/VoltDB/pro/pull/3124

ENG-19402: Add a contains all method to export tracker

---

src/frontend/org/voltdb/utils/PBDRetentionPolicy.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
src/frontend/org/voltdb/utils/RetentionPolicyMgr.java
tests/frontend/org/voltdb/utils/TestMaxBytesRetentionPolicy.java
tests/frontend/org/voltdb/utils/TestTimeBasedRetentionPolicy.java

ENG-19426:
- Always start retention at the beginning on PBD to account for gaps
- Make the tasks in retention key-ed by current retention reader to account for stopping and starting retention.

ENG-19306: Test retention gap filling

---

src/frontend/org/voltdb/SnapshotCompletionMonitor.java
src/frontend/org/voltdb/SnapshotDaemon.java
src/frontend/org/voltdb/SnapshotSaveAPI.java
src/frontend/org/voltdb/sysprocs/SnapshotSave.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotRequestConfig.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotUtil.java

The name "truncReqId" is used here and there in the code, assign it a variable name like other snapshot properties.

Make snapshot propery "truncReqId" a variable.

---

src/frontend/org/voltdb/sysprocs/QueryStats.java

Eng-18588: collect stats from all hosts & ENG-18574: additional table selector (#7069)
* ENG-18588: collect stats from all hosts
* ENG-18574: add optional tableId selector
* fix format

ENG-19496: Backport QueryStats fix 

---

src/frontend/org/voltdb/iv2/ElasticJoinProducer.java

[ backport a1f46fed77dc98ba0a6dfdb55a9be4258ea28a7e ]
During an elastic join the new partition leaders are promoted one at a time.
This means there a points in time when an mp request can get to a subset of the
new partitions. The previous invocation location of setViewsEnabled could
result in a subset of the new partitions waiting in the ee at the count down
latch. Then if another MP transaction was executed those sites would not
process the fragment task and cause an MP deadlock.
Do not call setViewsEnabled until all partitions are participating in the MP
transactions and this known when the first block of snapshot data is processed.

ENG-19501: Backport: Disable views just before snapshot processing

---

src/frontend/org/voltdb/RealVoltDB.java

[ backport 71121a61b1bfffc54f0e118aefdd530c0b99f1bf ]

ENG-19512: Backport: Shutdown client interface after dr

---

lib/python/voltcli/checkconfig.py
src/frontend/org/voltdb/RealVoltDB.java

Add a host log when root user logged in

Eng 11877 rootuser

---

src/frontend/org/voltdb/iv2/MpScheduler.java

MP initiator could get responses after a transaction is marked as complete when a partition master is migrated to a host which is then immediately shutdown: response from original partition master arrives after duplicate counter is cleaned for the transaction upon the node failure.

ENG-19566 response comes after transaction is marked as complete

---

src/frontend/org/voltdb/DefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DeprecatedDefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DevNullSnapshotTarget.java
src/frontend/org/voltdb/SimpleFileSnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/SnapshotRegistry.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java

Add 'PROGRESS' column in Statistics SNAPSHOTSUMMARY.

KO-34, track snapshot save progress.

---

tests/frontend/org/voltdb/TestExportRejoinWithView.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExport.java
tests/frontend/org/voltdb/TestJSONInterface.java
tests/frontend/org/voltdb/TestMidRejoinDeath.java
tests/frontend/org/voltdb/TestMixedPauseModeCluster.java
tests/frontend/org/voltdb/TestMixedVersionClusters.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java
tests/frontend/org/voltdb/TestRejoinFuzz.java
tests/frontend/org/voltdb/TestRejoinFuzz2.java
tests/frontend/org/voltdb/TestRejoinWithCatalogUpdates.java
tests/frontend/org/voltdb/export/TestExportGap.java
tests/frontend/org/voltdb/export/TestExportRejoin.java
tests/frontend/org/voltdb/exportclient/VoltDBFickleCluster.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/rejoin/LiveRejoinFailureTests.java
tests/frontend/org/voltdb/rejoin/LiveRejoinOverflowTests.java
tests/frontend/org/voltdb/rejoin/TestPauselessRejoinFuzz.java

- Removed ununsed rejoinHost parameter from recoverOne
- Renamed rejoinHostId to leaderHostId

ENG-19567:

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/utils/SnapshotComparer.java

Leftover commit for snapshot comparing tool from master to 8.4.

Eng-19543 backportv8.4

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java

Create asynchronous version of shutdown (#7176)

---

src/frontend/org/voltdb/DefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DeprecatedDefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DevNullSnapshotTarget.java
src/frontend/org/voltdb/SimpleFileSnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotDaemon.java
src/frontend/org/voltdb/SnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/SnapshotStatus.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/SnapshotRegistry.java
src/frontend/org/voltdb/sysprocs/saverestore/CSVSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/IndexSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Sample output:
```
exec @Statistics Snapshotsummary 0;
NONCE                   TXNID             TYPE    START_TIME     END_TIME       DURATION  PROGRESS_PCT  RESULT
----------------------- ----------------- ------- -------------- -------------- --------- ------------- --------
MANUAL1590477185430      3619631925526527 AUTO     1590477185507  1590477186037         0         100.0 SUCCESS
MANUAL1590477195591      3619631926886399 AUTO     1590477195672  1590477195983         0         100.0 SUCCESS
Rejoin_2_1590477158801   3619631923298303 REJOIN   1590477158906  1590477159218         0         100.0 SUCCESS
(Returned 3 rows in 0.00s)
```

Eng 19673 snapshot summary

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/MaterializedViewTriggerForInsert.h
tests/ee/expressions/function_test.cpp

Originally https://github.com/VoltDB/voltdb/pull/7049 which was off of the ENG-18744 branch

VoltDBEngine: Misc cleanup

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java

* avoid failing test when connection lost on trigger_migrate

Eng 19663 defer coordinator creation (#7201)

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/sysprocs/saverestore/TableSaveFile.java
src/frontend/org/voltdb/utils/SnapshotComparer.java
tests/frontend/org/voltdb/TestVoltTable.java
tests/frontend/org/voltdb/test/utils/RandomTestRule.java

Backport: Deepscan feature
Backport: Always visit all chunks
Backport: Improve table checksum

ENG-19646: Backport: Always visit all chunks

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/sysprocs/saverestore/TableSaveFile.java
src/frontend/org/voltdb/utils/SnapshotComparer.java

Backport closeable TableSaveFile 
Always visit all chunks
Improve table checksum

ENG-19646: Always visit all chunks

---

lib/python/voltcli/voltadmin.d/show.py

* Use SnapshotSummary to display more compact snapshot info.
* Fix date format issue for license expiration date, reword screen output.

ENG-19671, trivial fixes for "voltadmin show".

---

src/ee/storage/persistenttable.h
tests/ee/storage/CopyOnWriteTest.cpp

* ENG-19517: Notify streamers when removing block pending snapshot
* Add unit test case exercising original bug

Eng 19517 empty blocks pending snapshot (#7196)

---

src/frontend/org/voltdb/sysprocs/SystemInformation.java

Documentation says this is auto snapshot path, but it isn't just that. It's also the default path for manual and shutdown snapshots.

KO-281, always show snapshot path in "@systeminformation deployment".

---

src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/ProcedureRunnerNT.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java
tests/frontend/org/voltdb/iv2/RandomMsgGenerator.java
tests/frontend/org/voltdb/iv2/TestDurabilityListener.java
tests/frontend/org/voltdb/iv2/TestMpTransactionState.java
tests/frontend/org/voltdb/iv2/TestRepairLog.java
tests/frontend/org/voltdb/iv2/TestSpSchedulerDedupe.java
tests/frontend/org/voltdb/messaging/TestVoltMessageSerialization.java
tests/frontend/org/voltdb/rejoin/TestRejoinTaskBuffer.java
tests/frontend/org/voltdb/rejoin/TestTaskLog.java

Avoid performing a SystemProcedureCatalog search on every transaction just in case the current transaction is a RunEveryWhere transaction.

ENG-19650:

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

The UnsafeOutputContainerFactory doesn't add anything to the wrapped
container, so remove it to reduce the overhead caused by wrapping
containers in java memcheck mode.

ENG-19636: Remove UnsafeOutputContainerFactory

---

lib/python/voltcli/voltadmin.d/show.py

Change-Id: I2547301385e60c8d4f0dbc208b9786936aa14da6

ENG-19689, fix date format issue in "voltadmin show license" command.

---

src/frontend/org/voltdb/sysprocs/SystemInformation.java

Change-Id: I6cd16d5abf4e69d75d390db4d8ab34bcf1c2376c

ENG-19688, add dr information in "@SystemInformation License".

---

src/frontend/org/voltdb/sysprocs/SystemInformation.java

Change-Id: I6cd16d5abf4e69d75d390db4d8ab34bcf1c2376c

ENG-19688, add dr information in "@SystemInformation License". (#7213)

---

src/frontend/org/voltdb/RealVoltDB.java

Pointing one of the VoltDB managed paths at a dedicated volume can fail if the root directory contains system-mandated files such as lost+found.
This change adds a hardwired list of names that can be ignored.  The list contains one entry, lost+found, but others can easily be added.
Also adds code to log the names of (up to 10) files that we find and didn't want to ignore.

KO-278, ignore lost+found in check for empty managed directory

---

tests/frontend/org/voltdb/TestNTProcs.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

ENG-19652 & ENG-19667 junits

---

src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/lib/OrderedHashSet.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexSuite.java
tests/frontend/org/voltdb/regressionsuites/TestGroupBySuite.java
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSqlAggregateSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java
tests/testprocs/org/voltdb_testprocs/regressionsuites/aggregates/aggregate-sql-ddl.sql

Fixed based on commit ad50217, where part of refactory introduced this
delicate bug in a HSQL function.

ENG-19702 complex group-by with columns using decode

---

src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

When creating a native truncation snapshot alongside a streaming snapshot create a new snapshot configuration which includes all tables.

ENG-19554: Create a new config with all tables for native snapshot

---

third_party/java/src/org/json_voltpatches/JSONObject.java

[ backport 398e725e2366ff54a73c4c31ad06f399d50d25dd ]

ENG-19440: Backport: Use TreeMap to guarantee iteration order

---

third_party/java/src/org/json_voltpatches/JSONObject.java

[ backport 398e725e2366ff54a73c4c31ad06f399d50d25dd ]

ENG-19440: Use TreeMap to guarantee iteration order

---

tests/test_apps/genqa/ddl-migrate-nottl.tmplt
tests/test_apps/genqa/src/genqa/AsyncExportClient.java
tests/test_apps/genqa/src/genqa/procedures/MigratePartitionedExport.java

add NOT MIGRATING  index  and invoke partitioned procedureS

ENG-18396 migrating rows

---

tests/test_apps/kafkaimporter/client/kafkaimporter/KafkaImportBenchmark.java

Make topo aware default, allow auto reconnect to be used through command line option.

ENG-19097: Make topo aware the default connection option.

---

src/frontend/org/voltdb/InvocationDispatcher.java

Add a log messsage for the case that @PrepareStopNode refuses to stop.
This will help me correlate what goes on in the operator versus VoltDB.

log failure from PrepareStopNode

---

src/frontend/org/voltdb/iv2/SpTerm.java

ENG-19741 missed replica update

---

src/ee/kipling/messages/Message.h
src/ee/kipling/messages/OffsetCommit.cpp
src/ee/kipling/messages/OffsetCommit.h
src/ee/kipling/messages/OffsetFetch.cpp
src/ee/kipling/messages/OffsetFetch.h
src/frontend/org/voltdb/utils/VoltTableUtil.java
third_party/java/src/com/google_voltpatches/common/util/concurrent/RateLimiter.java

Move throttle concept out of EE and enhance guava RateLimitter to have features needed to support the quota management we need.
Related https://github.com/VoltDB/pro/pull/3250

ENG-19096: Add quota management and throttling to topics

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

The host list on voltdb start can have hostnames in place of IP addresses.  Prior to this fix the joiner looks up a host name once only, and thereafter uses the resulting IP address to form the mesh.
This causes occasional problems running under Kubernetes due to restart races. Either a host name is not yet visible in the container, or else the name-to-address mapping is changed as a container restarts.
The solution is to redo the name-to-address resolution in retry loops.
There used to be a retry loop (which could be activated or not per a caller parameter!) in createLeaderSocket, called from connectPrimary, called from start().  To facilitate hostname lookup reattempts, that low-level retry loop was removed and made the responsibility of start(), along with other retry reasons.
Also I …

Retry resolution of host names in joiner.

---

src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/VerifyCatalogAndWriteJar.java
src/frontend/org/voltdb/utils/CatalogUtil.java

from [the commit](https://github.com/VoltDB/voltdb/pull/7246)

ENG-19749 backport changes

---

src/frontend/org/voltdb/exportclient/JDBCExportClient.java

Back port from [commit 905d4e5](https://github.com/VoltDB/voltdb/pull/7281/commits/905d4e5d89c97a159480e0e346ea4399b7e5f7a0)

ENG-19758 reset PreparedStatement upon schema changes

---

src/frontend/org/voltdb/sysprocs/SystemInformation.java

Change-Id: Ib13269d6ee87a6e619bfe98d558945260550727a

KO-386, add "CREATIONTIME" to SystemInformation Overview.

---

tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

Change-Id: Ifb0b9f8cbfe43d78f165110121a9779cb8308b2c

Add new statistics column in unit test.

---

src/frontend/org/voltdb/RealVoltDB.java

fixes odd little glitch in rejoining a paused cluster

set node state to paused on rejoin if mode says paused

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
tests/frontend/org/voltdb/test/utils/ClientTestUtils.java

Related https://github.com/VoltDB/pro/pull/3303

ENG-19450: Remove StreamStartAction from ExportManager.startPolling

---

src/frontend/org/voltdb/RealVoltDB.java

A couple of times Ryan has got a mysterious NullPOinterException from the rather nasty Lists.newArrayList method. This at least gives a nicer error message.
The problem would seem to be topo.getPartitionIdList returning null.  My first guess for that is a bad host id. We shall see.

attempt to diagnose an occasonal NPE

---

src/ee/execution/VoltDBEngine.cpp
src/frontend/org/voltdb/VoltUDAggregate.java
src/frontend/org/voltdb/compiler/statements/CreateAggregateFunctionFromClass.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
tests/frontend/org/voltdb/regressionsuites/TestUserDefinedAggregates.java
tests/testfuncs/org/voltdb_testfuncs/UminWithException.java
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestAggregates-DDL.sql

ENG-19788 Propagate exception from Java UDAF

---

src/frontend/org/voltdb/iv2/Site.java
tests/test_apps/genqa/src/genqa/KafkaClientVerifier.java
tests/test_apps/kafkaimporter/ddl-kipling2tables.sql
tests/test_apps/topicbenchmark/procedures/topicbenchmark/InsertTopic1.java
tests/test_apps/topicbenchmark/procedures/topicbenchmark/SampleRecord.java
tests/test_apps/topicbenchmark/topicTable.sql

Routine merge from master prior to beta6 build

Merge from master (comm ed.)

---

src/frontend/org/voltdb/ClientInterface.java

For easier (we hope) diagnosis, add the client address into SSL-related error messages.

Add client socket address to TLS/SSL failure messages

---

lib/python/voltdbclient.py

I have a better plan.
What I wanted to do actually needed a lesser change, but it took some while to figure out the existing logic.
Copying @n3world FYI, but I'm just going to push this change. KO-integration is identical to master again. New code coming soon.

revert yesterday's changes to voltdbclient.
