VoltDB/voltdb

src/frontend/org/voltdb/types/PlanMatcher.java
src/frontend/org/voltdb/types/PlanNodeType.java
tests/frontend/org/voltdb/planner/PlannerTestCase.java
tests/frontend/org/voltdb/planner/TestValidatePlan.java

We have a small framework for testing plans.  This is not plannertester tests, but it's for describing and matching expected plans.
The existing framework just matched on plan node types.  I wanted to match other things, kind of like hamcrest testing, so I refactored this to have a more general plan matcher, which PlanNodeType implements.  This lets us have matchers which have a plan node type and require inline nodes of a given type.  In subsequent commits I have added some more functionality, but that is not easily separated into this commit.

Eng 14251 Better Planner Testing Framework

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/iv2/SpInitiator.java
voltdb/log4j.xml

When newly joined or rejoined streams miss any RELEASE_BUFFER event, and client is stopped, it causes
export buffers on rejoined nodes never get drained. Forwarding an ACK from master stream fixes the edge case.
Change-Id: If14d0a2a36e8835f7ad3e6b660af19d0ee5d9118

ENG-14347, master stream forwards an ACK to newly rejoined streams.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/sysprocs/MigratePartitionLeader.java
voltdb/log4j.xml

On host failure, every partition leader sends QUERY message to collect whether the local stream has an remote
master, if none of the replicas has master, promote the local stream as master. If one of the replicas is master,
ask that stream to transfer mastership back when export buffer is drained.
Change-Id: I104f78aa78563f85d3dd406a398b437af80e3a35

ENG-13766, fault handling of export stream migration.

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.service.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.ui.js

It seems a small javascript issue, not a jetty one.
I also noticed the bug happened since **7.7.2**, should I also backport it?

ENG-14332-DR Tab not appearing in VMC since jetty sessions was changed

---

src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
tests/frontend/org/voltdb/regressionsuites/TestFixedSQLSuite.java

Dummy PR for Chirs' work on HSQL to disallow OBY aggregate without GBY clause.
Synced to latest master and resolved conflicts.

ENG-13929: don't allow queries with no GB clause to order by aggregates

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py
tools/jenkins/sql_coverage_reporter.py

Ready for review
- includes failure % and type (Intermittent, Consistent) in summary
- now supports including attachments to tickets for uploading countGraphs
- now supports linking tickets on same job
- displays countGraphs and adds link to Jenkins updatedGraph
- if test failing (but tickets already exists) on different job, will comment on existing ticket
- only counts failures that exceed threshold (default 2)
- for Consistent failure cases, only significant if 2SD above mean (not below)

ENG-14315: Update JUnit auto-filer Jira ticket design

---

src/frontend/org/voltdb/ImporterServerAdapterImpl.java
src/frontend/org/voltdb/importclient/kafka10/KafkaStreamImporter.java
src/frontend/org/voltdb/importer/AbstractImporter.java
src/frontend/org/voltdb/importer/ImporterServerAdapter.java
src/frontend/org/voltdb/importer/ImporterStatsCollector.java

This issue is related to the behavior of `@Statistics IMPORTER`
We won't have anything in `Statistics` until we successfully insert a record from Kafka into the target table, which is  considered as a bug.
This PR fix this behavior, once we have the Kafka importer successfully initialized (Kafka server is started and the target table is existed), we will have a record in `@Statistics IMPORTER`, and the "import tab" will appear.

ENG-14334-The vmc "Import" tab is missing

---

tests/sqlgrammar/DDL.sql
tests/sqlgrammar/run.sh
tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py
tests/test-tools.sh
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-DDL.sql
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-batch.sql
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-drop.sql

Also made some unrelated, minor improvements: added code in
sql_grammar_generator.py to support a new syntax, e.g.,
{table-name;t1,t2,t3,t4,t5}, to allow a table name to refer to one of
several table names that may have been previously used (and similarly
for column aliases, etc.), similar to the existing {table-name:t1}
syntax, but with multiple options; modified sql-grammar.txt to make use
of this new syntax to improve the validity percent for all SQL statement
types, as well as adding STARTS WITH and LIKE; and improved comments;
also changed the seconds to wait for sqlcmd to respond to 60 (was 15):
it's rare that a query takes longer than 15 seconds, but when it does
it's generally because of a join of 5 or more tables, so allowing up to
60 seconds will still detect a real 'hang', …

ENG-14252: added STARTS WITH and LIKE to SQL-grammar-gen tests.

---

tests/sqlgrammar/DDL.sql
tests/sqlgrammar/run.sh
tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py
tests/test-tools.sh
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-DDL.sql
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-batch.sql
tests/testfuncs/org/voltdb_testfuncs/UserDefinedTestFunctions-drop.sql

* ENG-14252: added STARTS WITH and LIKE to SQL-grammar-gen tests, for V8.3.
Also made some unrelated, minor improvements: added code in
sql_grammar_generator.py to support a new syntax, e.g.,
{table-name;t1,t2,t3,t4,t5}, to allow a table name to refer to one of
several table names that may have been previously used (and similarly
for column aliases, etc.), similar to the existing {table-name:t1}
syntax, but with multiple options; modified sql-grammar.txt to make use
of this new syntax to improve the validity percent for all SQL statement
types, as well as adding STARTS WITH and LIKE; and improved comments;
also changed the seconds to wait for sqlcmd to respond to 60 (was 15):
it's rare that a query takes longer than 15 seconds, but when it does
it's generally because of a join of 5 or …

ENG-14252: added STARTS WITH and LIKE to SQL-grammar-gen tests. (#5497)

---

src/frontend/org/voltdb/planner/MVQueryRewriter.java
src/frontend/org/voltdb/planner/ParameterizationInfo.java
src/frontend/org/voltdb/planner/QueryPlanner.java
tests/frontend/org/voltdb/regressionsuites/TestMVOptimizationSuite.java

The parameter number decreases when MV optimization rewrites a query. In that case, the assertion check needs updated.

Fixed bug on nested optimized query

---

src/frontend/org/voltdb/VoltTable.java

This adds a map to cache the column index for a given column name.
The map is not even created unless you use a column name to retrieve a value, and only caches columns as they are accessed, so this shouldn't add any undue overhead.

ENG-14464 VoltTable get by column name optimization

---

src/frontend/org/voltdb/LightweightNTClientResponseAdapter.java
src/frontend/org/voltdb/SimpleClientResponseAdapter.java

Client Interface may prematurely send response back to client due to leader changes. Responses could then be routed to client interface which could not locate the transaction and does no know how to allocate buffer.

ENG-14468 verify buffer length before allocation to handle late arrived responses

---

src/frontend/org/voltdb/LightweightNTClientResponseAdapter.java
src/frontend/org/voltdb/SimpleClientResponseAdapter.java

Client Interface may prematurely send response back to client due to leader changes. Responses could then be routed to client interface which could not locate the transaction and does no know how to allocate buffer.

ENG-14468 verify buffer length before allocation

---

src/frontend/org/voltdb/client/ConnectionUtil.java
tests/frontend/org/voltdb/client/TestConnectionUtilDelayedExecutionThread.java

The implementation of using a ScheduledThreadPoolExecutor with a core
pool size of 0 and keepAliveTime is 0 any thread in the pool will do
spin loop until the queue is empty. Instead of using a thread pool which
has no real defined start and end to its lifetime use a thread to track
handle tracking the timeout.
Create DelayedExecutionThread which wait for a delay to pass and then
invokes a runnable. The delayed thread can be canceled while waiting for
the delay to pass but not before.

 ENG-14408: Use a thread to wait for timeout 

---

src/frontend/org/voltdb/export/ExportDataSource.java

Initialization and catalog update setup new runnable so won't be affected.
The cause of the issue is that when export master give up mastership, it somehow also clears the mastership promotion callback, which is installed only during initialization or catalog update. When the old master was asked to be master again, the promotion will fail because it couldn't find the callback, in turn blocks export buffer to drain.

ENG-14347, keep mastership designation runnable when give up mastership.

---

src/frontend/org/voltdb/VoltDB.java

A node may be programmatically shutdown.  Under such certain circumstances,   the thread dump of this node won't be collected. The dump may also be of help for the analysis of issues from productions and  system tests.

ENG-14471 printout thread dumps while a node is programmatically terminated. 

---

src/frontend/org/voltdb/planner/MVQueryRewriter.java
tests/frontend/org/voltdb/planner/TestMVOptimization.java

Added check against LIMIT/OFFSET of SELECT stmt. When SELECT contains LIMIT and/or OFFSET, it skips materialized view matching.

Bug fix for ENG-14415 core dump when using materialized view to rewrite SELECT query.

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java

* Update setOnMastership to pass the runAnyWhere argument into setRunAnyWhere so that all ways to supply that configuration are handled the same.
* Remove variable m_runAnyWhere and remove _set_ prefix from the method which handles that value since it is no longer a setter.
If we want to keep m_runAnyWhere I will drop the last commit and only update the handling the argument.

ENG-14470: Consistently handle runAnyWhere in ExportDataSource

---

src/frontend/org/voltdb/BackendTarget.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/LocalSingleProcessServer.java
tests/frontend/org/voltdb/regressionsuites/TestGroupBySuite.java

There is no test for this really.  The queries in TestOrderBySuite
don't actually work in large temp table mode.  But the test in
TestAdHocLarge runs and passes when we use the new enumerator,
and I can see that the plans are large temp table plans in the
TestGroupBySuite tests, even when we use "@AdHoc".  The tests
fail in the EE, though.
I also added some more properties to BackendTarget.  This makes it
slightly more abstract.

Added a new enumerator to force large temp table queries.

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java

THere are two problems under the hood, first export doesn't set m_pendingContainer properly during export processor shutdown, it may cause data lose in downstream export client. Second, when export master gives up mastership, it no longer needs the m_pollFuture, set to null unconditionally.
Change-Id: Iaf17be7011aba0698da11d756b9c00f5babe8199

ENG-14488, fix export poll data source twice issue.

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/probe/MeshProber.java

If the current node hasn't finished rejoin when another node fails, this rejoining node should be shutdown to prevent locking up of the cluster.  If  the host failure notification could come before mesh determination: that is, the current node does not know it is rejoining, and the shutdown is skipped.  The host failure  processing is handed off to a shared executor which could be blocked by other running tasks. To ensure the accurate and timely rejoining node shutdown, use a dedicated executor instead.

ENG-14480 stop rejoining node when it sees another node failure

---

src/ee/storage/BinaryLogSink.cpp

Disabling skip for transactions with TXN_PAR_HASH_SPECIAL caused row
moditications to be applied to partitions which they should not be. Allowing
skip for this transacations allows truncates to be applied to all
partitions but only applies modifications to the correct partition.

ENG-14481 - Allow skipping during mp non replicated binary log apply

---

src/ee/storage/BinaryLogSink.cpp

Only apply truncate for replicated tables on lowest site. Make sure it is skipped on all other sites. Update truncate case to skip if it is a replicatedTableOperation and if it is a replicatedTable just skip all operations on the non lowest sites.

ENC-14490 skip truncate on replicated tables

---

src/ee/storage/BinaryLogSink.cpp

Do not process binary log for replicated tables on non lowest site.

Eng 14490 skip truncate on replicated tables 8.3

---

src/ee/storage/BinaryLogSink.cpp

Do not process binary log for replicated tables on non lowest site.

Eng 14490 skip truncate on replicated tables 8.2

---

src/ee/storage/BinaryLogSink.cpp

Do not process binary log for replicated tables on non lowest site.

Eng 14490 skip truncate on replicated tables 8.1

---

src/frontend/org/voltdb/export/ExportDataSource.java

It's possible to have the export master gives up mastership but still try to poll immediately after that, e.g. from Pico Network thread the master gives up mastership, from decoder thread it tries to poll periodically, they won't overlap but poll can happen after giving up mastership. If it happens m_pollFuture can be mistakingly set, and when the old master retakes mastership again it refuses to export because m_pollFuture should be false on a fresh master.
Change-Id: I8e02c10044e940eb5976488059eb9163b3bd1539

ENG-14488, fix export poll more than once issue.

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/SpInitiator.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/SpTerm.java

Old partition leaders could regain leadership upon the failure of  the hosts with new partition leaders acquired via leader migration. The old leaders may miss replica list update.  In this case, the older leaders should  synch their replica list upon re-promotion.

ENG-14491 recreate term if a site regains leadership after leader migration

---

src/frontend/org/voltdb/sysprocs/MigratePartitionLeader.java

quiesce on the old leader is done as part of rejoin's streaming snapshot, so additional quiesc is not required.

ENG-14347:

---

build.xml
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/PlannerTool.java
tests/frontend/org/voltdb/planner/TestAdHocPlans.java
tests/frontend/org/voltdb/planner/TestLargeModeRatio.java

- `LARGE_TABLE_RATIO` is a system property that will force execution of SQL queries to use the "large" path (for read-only queries) a certain percentage of the time. It can be used for any tests that are invoked using ant, or for system tests. 
- The default value is 0, means no query will use large mode. If set it to 1, all queries will use large mode.
usage
------
It can be set either from system property:
```bash
export VOLTDB_OPTS="-DLARGE_TABLE_RATIO=0.5"
```
or from ant
```bash
ant -Dlarge_mode_ratio=0.75 ...
```

ENG-13873-system property for sql execution to use large mode

---

src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java
src/frontend/org/voltdb/messaging/CompleteTransactionResponseMessage.java
tests/frontend/org/voltdb/messaging/TestVoltMessageSerialization.java

After MpPromoteAlgo collects repair logs, it identifies the incomplete, non-restartable sysprocs and generates a rollback message to all partitions to clear out the transaction. However, it does not assign the truncation handle to the completion which can cause a random value to be in the truncation handle (in some cases). If the random value happens to be large enough, the partitions can truncation in progress transactions from the repair log ultimately causing mp deadlocks. To ensure that these rollback completions never alter the repair log, the truncation handle must be explicitly assigned to Long.MIN_VALUE.

ENG-14541:

---

tests/sqlcoverage/SQLCoverageReport.py
tests/sqlcoverage/sql_coverage_test.py

For SqlCoverage test suites with expected mismatches, do not produce any
'reproducer' files; and delete any specific query result files (assuming
the expected number of mismatches is not exceeded), to save space in
Jenkins.
Also slightly increased the number of expected mismatches for the
'joined-matview-default-full' test suite, based on a recent run; and
fixed a small issue where the number of columns printed was one too
small (in sql_coverage.test.py); and improved 'Key' text (in
SQLCoverageReport.py).

ENG-14543: reduce space taken up by sqlcov *.html files (on Jenkins)

---

src/frontend/org/voltdb/iv2/MpTransactionState.java

Add more output to MP Deadlock messages to indicate if the dependency ids have changed because of a misrouted resend.

ENG-14553:

---

src/frontend/org/voltdb/LoadedProcedureSet.java

When system detects hash mismatch exception, it prints all user procedures and default procedures, nibble delete procedures are in neither of them.

ENG-14550, put nibble delete procedure into default procedure list.

---

src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpRepairTask.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

Provide MpRepairTask with partition leader promotion status. If all the partitions have been promoted, then the MpRepairTask is the last repair task in this round of repair process. Then after this MpRepairTask is completed, remove mp repair blocker.

ENG-14547 block rejoin or uac during tx repair

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/BinaryLogSinkWrapper.cpp
src/ee/storage/BinaryLogSinkWrapper.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp

Only perform truncate table once when applying an MP transaction with truncate. This is accomplished by applying all operations in all logs before the truncate applying the truncate once and then apply the next set of operations in each log until another truncate if it exists is encountered. This is done until the end of each log is reached.
This method works as long as there is a truncate in every log, which is not guaranteed.

Eng 14444 perform truncate once

---

src/frontend/org/voltcore/messaging/TransactionInfoBaseMessage.java
src/frontend/org/voltdb/ProcedureRunnerNT.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpProcedureTask.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/messaging/InitiateResponseMessage.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java

Don't disable the truncation handle in all messages generated by the mp repair / mp promote algorithms. Inadvertently advancing the handles can remove repair messages that are needed by partitions that have not completed repair yet.
Also don't all MP transactions that have no fragments for MP transactions from advancing the MP repair truncation point. Otherwise we may remove completions from some parititons that have not been seen at all by other partitions.

ENG-14563:

---

src/ee/storage/BinaryLogSink.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

Sort logs so that logs with truncates are processed first until all of the truncates are encountered and then process the remainder of all logs.
Update persistent table to always add a truncate to the binary log even if the partition is empty.

ENG-14528 truncate on empty partition

---

src/frontend/org/voltdb/iv2/DeterminismHash.java
src/frontend/org/voltdb/iv2/DuplicateCounter.java

It causes hash mismatch check is bypassed if the indeterministic statement is not in the first 32 statements.
Pro change: https://github.com/VoltDB/pro/pull/2331

ENG-14573, fix hash mismatch check.

---

src/frontend/org/voltdb/iv2/LeaderAppointer.java

During elastic join and re-balance partitions, a joining node failure will reject the whole joining
and bring down all joining nodes. In the meantime, other nodes could check the cluster viability and could encounter the removal of newly elastically added partitions. Ignore these partitions check and do not bring cluster down.

ENG-14567 handling join failure

---

src/frontend/org/voltdb/iv2/LeaderAppointer.java

During elastic join and re-balance partitions, a joining node failure will reject the whole joining
and bring down all joining nodes. In the meantime, other nodes could check the cluster viability and could encounter the removal of newly elastically added partitions. Ignore these partitions check and do not bring cluster down.

ENG-14567 join failure handling

---

src/ee/CMakeLists.txt
src/ee/common/Pool.cpp
src/ee/common/Pool.hpp
src/ee/common/UndoLog.cpp
src/ee/common/UndoLog.h
src/ee/common/UndoQuantum.h
src/ee/common/VoltContainer.hpp
src/ee/storage/persistenttable.cpp
tests/ee/common/pool_test.cpp
tests/ee/storage/StreamedTable_test.cpp

1. Clean up of Pool.hpp:
- Put bulk implementation into .cpp file. I don't understand why so many of function/method definitions are in the .h/.hpp file instead of .cpp file. Maybe we were more comfortable writing Java code? Or maybe we want compiler to `inline` those methods? But we lose so much more clarity by doing that, and for C++ code, class layout as API is much more important than Java. (Welcome to compare changes to Pool class before/after)
- Commented out unused build condition (`USE_MMAP`), to make it easier to follow.
- Fixed a small bug that we almost always waste 8 bytes between different allocations.
- Use `std::unique_ptr<char[]>` in place of manual `new`/`delete` invocations to the OS.
- Changed container type from `std::vector` to `std::list` and `std::deque` for the …

Eng 14520 ee memory pool for stl container

---

src/frontend/org/voltdb/iv2/MpProcedureTask.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java
src/frontend/org/voltdb/messaging/Iv2InitiateTaskMessage.java

It is possible for the MP Deliver and the MP Site threads to debug print the Invocation for the same transaction at the same time. When this happens the parameters can be printed as well. It appears that some parameters (specifically VoltTable) are not thread safe at least for ToString(). To avoid this, only the TxnSummary will be printed out on non site threads and the invocation will only be printed out in detail on the site thread.

ENG-14614:

---

src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/MpScheduler.java

For EveryPartition stored procedures, Initial task message could be misrouted back to MpScheduler upon leader migration, resulting in no hash exception.  Upon leader migration, Now the misrouted message will be routed to the new partition leader for transactional processing.

ENG-14566 misrouted every partition proc

---

src/frontend/org/voltdb/iv2/DuplicateCounter.java
src/frontend/org/voltdb/iv2/MpScheduler.java

For EveryPartition stored procedures, Initial task message could be misrouted back to MpScheduler upon leader migration, resulting in no hash exception. Upon leader migration, Now the misrouted message will be routed to the new partition leader for transactional processing.

ENG-14566 handle misrouted message for EveryPartitionTask

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/UndoQuantum.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/persistenttable.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java

truncateTable was always being called with replicatedTable false by applyRecord. This was causing memory corruption when a replicated table was being truncated.
Also, remove unused argument from applyBinaryLog.

ENG-14577 - 14613: correctly pass replicated table into truncate table

---

tests/frontend/org/voltdb/exportclient/TestExportToFileClient.java

I don't see reason to only check the first file for match.
On rare cases (say running this test for 40 times, the expected file might
come in the middle and the 1 minute limit is passed, therefore fails the
testcase.
With this fix, I have run the test for 100 times (with `-Dbuild=memcheck`) and did
not see failures. (But the original code wasn't failing quite frequent either).
@luyangco Please confirm that the test logic for the `testFileRollingUnbatched()`
method is not compromised.

ENG-14355 Timeout waiting for file to roll over

---

lib/python/voltcli/voltadmin.d/update.py

The original request was to fix the help. But since I was in there, it seemed better
to actually correct the processing to only accept one file, a deployment/config file.
Since I changed the actual code, thought it would be good to have it reviewed before merging.
--Andrew

Fix help and code for voltadmin update to only accept config file

---

tests/sqlgrammar/sql-grammar.txt

Simply added ROW_NUMBER() to the list of Window (analytic) functions, in
sql-grammar.txt.

ENG-14460: Add row_number() to SQL-grammar-gen

---

src/ee/common/executorcontext.hpp
src/ee/execution/VoltDBEngine.cpp
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

Currently startTime is only cleared when executePlanFragment,
loadCatalog or updateCatalog is called. That means that if a procedure
runs in the EE and does not go through one of those paths it will have a
bogus start time. Rename setProcedureName to setupProcedure and update
it so that it reset startTime and logDuration for the procedure to be
executed. Also, add a completeProcedure to clear the procedure name.

ENG-14622: Add setupProcedure method to the EE

---

src/ee/common/NValue.hpp
tests/frontend/org/voltdb/TestLikeQueries.java

Fix a bug that LIKE operator does not handle two or more consecutive '%' characters correctly.
The patterns `abc%%`, `%%abc`, `a%%bc`, `%%` should all match the string `abc`.

ENG-14485: LIKE operator handles two or more consecutive '%' 

---

src/ee/storage/BinaryLogSink.cpp
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
tests/ee/storage/DRBinaryLog_test.cpp

ExecuteTask: Only put integers in result table
When a binary log contains a transaction for another partition throw SerializableEEException with a type of VOLT_EE_EXCEPTION_TYPE_TXN_MISPARTITIONED.

ENG-14690: detect mispartitioned transaction

---

src/frontend/org/voltdb/iv2/MpTransactionState.java

DR buffer change variables need to be reset and updated only on a write fragment, which happens in recursableRun.
Do not reset drBufferChangedAgg in setupResume because this resets it for reads and the value will not be
updated to correct value in recursableRun for reads.

ENG-14739:

---

src/frontend/org/voltdb/iv2/MpTransactionState.java

ENG-14739:
- DR buffer change variables need to be reset and updated only on a write fragment, which happens in recursableRun. Do not reset drBufferChangedAgg in setupResume because this resets it for reads and the value will not be updated to correct value in recursableRun for reads.
- Reset the DR buffer change variable on a restart.

ENG-14739: (#5675)

---

tests/sqlgrammar/sql_grammar_generator.py
tools/killstragglers.sh

Added "Single partitioned procedure: FOO has TRUNCATE statement" to the
list of known error messages.

ENG-14745: grammar-gen hangs on CREATE PROCEDURE / TRUNCATE

---

src/ee/common/StreamBlock.h
src/ee/execution/VoltDBEngine.cpp
src/ee/storage/ExportTupleStream.cpp
src/ee/storage/ExportTupleStream.h
src/ee/storage/TupleStreamBase.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/exportclient/ExportEncoder.java
src/frontend/org/voltdb/exportclient/ExportRow.java
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/ExportTupleStream_test.cpp
tests/ee/storage/StreamedTable_test.cpp
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java
tests/frontend/org/voltdb/exportclient/TestElasticSearchHttpExportClient.java
tests/frontend/org/voltdb/exportclient/TestExportDecoderBase.java
tests/frontend/org/voltdb/exportclient/TestExportDecoderBaseLegacy.java
tests/frontend/org/voltdb/exportclient/TestExportToFileClient.java
tests/frontend/org/voltdb/exportclient/TestHttpExportClient.java

As export streams build buffers, the number of records in buffers can diverge on different hosts due to the timing of the Tick() calls on the individual sites of each host. This in turn can result in different buffer counts for the same stream and partition on different hosts although the total number of records (sequence number) are the same. The first row of each buffer contains the streams schema, but this schema data is included in the USO calculation. Because we use stream offset (USO) to coordinate acknowledgements between hosts, the different number of buffers can result in the same record on different hosts starting at different USOs resulting in acking the wrong record. At promotion or SPI migration time, we can either skip past a record or send the same record twice with …

Eng 14347 exclude schema from usos 84

---

src/ee/CMakeLists.txt
src/ee/common/StackTrace.cpp
src/ee/common/StackTrace.h
src/ee/common/ThreadLocalPool.h
src/ee/common/debuglog.h

When the logger was implemented as a pure macro a cycle was created
between debuglog.h and ThreadLocalPool.h. This was resolved by removing
the include of debuglog.h from ThreadLocalPool.h. However, the
StackTrace class is used by ThreadLocalPool.h when pool checking is
enabled.
In order to keep the logging as a macro and still use the StackTrace in
ThreadLocalPool.h, StackTrace is being extracted to its own header and
source file. This allows both debuglog.h and ThreadLocalPool.h to
include StackTrace.h and not have a cycle.

ENG-14787: Extract StackTrace to its own file

---

src/frontend/org/voltcore/logging/VoltLogger.java
src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/iv2/Site.java

* Avoid throwing RejectedExecutionException out of logger after executor shutsdown
* Correct DRConsumerDrIdTracker.toShortString to include both sp and mp unique ID
* Remove some dangling code for removal of replicated stream

MInor miscenalious cleanup and fixes

---

src/frontend/org/voltdb/DefaultProcedureManager.java
src/frontend/org/voltdb/OpsAgent.java

Send an error response when hitting exception in runnable executed in OpsAgent. This should prevent sqlcmd from hanging forever and system tests to report failures faster.
Use ConcurrentHashMap to support updates from LoadedProcedure.getNibbleDeleteProc

Send an error response to avoid sqlcmd hanging, and support concurrent default procedures updates

---

tests/test_apps/genqa/build.xml
tests/test_apps/genqa/ddl-all-nocat-stream.sql
tests/test_apps/genqa/ddl-all-nocat.sql
tests/test_apps/genqa/deployment-kafka.xml
tests/test_apps/genqa/deployment-rabbitmq.xml
tests/test_apps/genqa/deployment.xml
tests/test_apps/genqa/deployment_custom.xml
tests/test_apps/genqa/deployment_mysql.xml
tests/test_apps/genqa/deployment_pg.xml
tests/test_apps/genqa/deployment_pg_nocat.xml
tests/test_apps/genqa/deployment_vertica.xml
tests/test_apps/genqa/run.sh
tests/test_apps/genqa/src/genqa/AsyncExportClient.java

This will remove the catalog creation from the run.sh and use voltdb init/start instead of create.  It also creates a single ddl with the combination of all the old ddls ddl.sql ddl2.sql ddl3.sql etc.

remove old features legacy-compile and create from run.sh,

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/NodeStateTracker.java
src/frontend/org/voltdb/RealVoltDB.java

NodeStateTracker.setNodeStatus could fail but no callers were checking
for failure. Simplify NodeStateTracker to be a type safe AtomicReference
with a utility method to get a Supplier.

Correct and simplify NodeStateTracker

---

src/frontend/org/voltdb/iv2/SpScheduler.java

In this fix we release the pending buffered reads regardless of our partition leadership status. Therefore a leader losing leadership can still reply to pending MP RO transactions and avoid deadlock.

ENG-14553: fix avoiding deadlock on MP RO transaction

---

src/frontend/org/voltdb/ProcedureRunnerNT.java

The allHost* member variables were sometimes protected by a synchronize on
m_allHostCallbackLock and sometimes on this. Update the locking to be
consistently on m_allHostCallbackLock.
Use compareAndSet to set m_outstandingAllHostProc so that way there is
race between checking the state and setting it.

ProcedureRunnerNT: Consistent synchronization

---

tests/sqlcoverage/sql_coverage_test.py
tests/sqlcoverage/template/include/join-template.sql

in join-template.sql, because they fail in PostgreSQL when using FULL
JOIN; and removed associated kludges in sql_coverage_test.py's
get_max_mismatches function, which are no longer needed.

ENG-10775: removed use of FULL JOIN from 3 problematic query templates

---

src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestScoreboard.java

The scoreboard for SRT can hold complete transaction messages from 2 transactions. However the  complete transaction messages could come from more than 2 transactions.  For example, node failure occurs when t1 is processing CompleteTransactionMessage, t2 is processing FragmentTaskMessage. t2 is a non-restartable system store procedure. When repair process kicks in,  CompleteTransactionMessages for both t1 and t2 will be broadcasted.  Since t2 is the ongoing transaction, t2 will be restarted, and then immediately aborted since it is non-restartable.  Then  t3 will kick in and will send out CompleteTransactionMessage if restarted.  Thus 3 CompleteTransactionMessages will reach the scoreboard but one of them will be ignored since the scoreboard can only take 2.  Under this circumstance, t3 …

ENG-14925 Scoreboard refactoring to accommodate more than 2 transactions

---

tests/frontend/org/voltdb/MockVoltDB.java

Fix testMeshQuery failure. MockVoltDB must also include drPublic host and port into local metadata.

ENG-14937:

---

src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
tests/frontend/org/voltdb/iv2/TestScoreboard.java

The scoreboard for SRT can hold complete transaction messages from 2 transactions. However the complete transaction messages could come from more than 2 transactions. For example, node failure occurs when t1 is processing CompleteTransactionMessage, t2 is processing FragmentTaskMessage. t2 is a non-restartable system store procedure. When repair process kicks in, CompleteTransactionMessages for both t1 and t2 will be broadcasted. Since t2 is the ongoing transaction, t2 will be restarted, and then immediately aborted since it is non-restartable. Then t3 will kick in and will send out CompleteTransactionMessage if restarted. Thus 3 CompleteTransactionMessages will reach the scoreboard but one of them will be ignored since the scoreboard can only take 2. Under this circumstance, t3 will hit …

ENG-14925 backport scoreboard refactoring

---

src/frontend/org/voltdb/export/ExportDataSource.java

So far I identified two problems: 1) auto release feature checks cluster completeness meanwhile gap detection/resolution checks export mailboxes list, so it’s possible that before gap resolution gets a chance to query other nodes, cluster completeness check is passed. This causes premature gap release which lead to missing rows.
2) There is a race window between updating export mailboxes list and receiving query message, if query message is received before export mailboxes update, it causes blocked stream failed to find missing data on other nodes.

Eng 14941 export blocked

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/ExportControl.java
tests/frontend/org/voltdb/export/ExportMatchers.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/frontend/org/voltdb/export/TestExportSequenceNumberTracker.java

This patch includes five changes:
1) completely reply on export sequence tracker to compute pending data,
2) fix a race condition that sometimes replica stream fails to retrieve local mailbox to send back gap query response,
3) fix the accounting problem in export sequence tracker itself,
4) fix the wrong ‘blocked’ status in some cases for active non-blocking stream.
5) fix a pre-8.0 bug that in `m_dataSourcesByPartition` it uses table signature as key but in snapshot digest the key of exportSequence map is table name, causing truncateToSeqNo never find the right stream.
Pro PR: https://github.com/VoltDB/pro/pull/2416

Eng 15019 incorrect stat

---

tests/sqlgrammar/sql-ddl-grammar.txt
tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

Modified sql-grammar.txt to include CREATE (and DROP) INDEX statements,
and organized them into a new "DDL" section, along with the existing
CREATE (and DROP) PROCEDURE AS statements, with a few other minor tweaks
(and deleted a few things from sql-ddl-grammar.txt, which were moved
into sql-grammar.txt, with modifications). Modified
sql_grammar_generator.py to include multiple new error messages that we
see in response to CREATE INDEX statements; and to keep track of, and
for the summary to list, certain statement sub-types separately, e.g.
CREATE PROCEDURE vs. CREATE INDEX vs. CREATE UNIQUE/ASSUMEUNIQUE INDEX,
which are all quite different.

ENG-13811: added randomized Indexes to grammar-gen

---

src/frontend/org/voltdb/StoredProcedureInvocation.java

Deserialize params immediately in initFromBuffer because
sometimes the buffers are returned back to the pool before the bytes are used for deserialization.

ENG-14559:

---

build.xml
tests/sqlcoverage/sql_coverage_test.py
tests/test-tools.sh

Added, to SqlCoverage, a new 'hsql' option (in both sql_coverage_test.py
and build.xml), so you can still use HSQL as your comparison database if
you wish; but made 'postgresql' the default option (though not
'postgis', FYI).

ENG-11349: Make PostgreSQL, not HSQL, the default sqlcov comparison DB

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/RestoreAgent.java
src/frontend/org/voltdb/iv2/JoinProducerBase.java
src/frontend/org/voltdb/iv2/MpScheduler.java
src/frontend/org/voltdb/utils/MiscUtils.java
src/frontend/org/voltdb/utils/ProClass.java

Currently there is a single method which assits in loading a pro class but that
still requires the caller to retrieve the constructor and do the construction.
The ProClass utility class wraps that and simplifies the error handling for
the common use cases.

 Add a utility class to handle pro classes

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/compiler/SqlPlanner.java
src/frontend/org/voltdb/newplanner/AbstractSqlTaskDecorator.java
src/frontend/org/voltdb/newplanner/NonDdlBatchCompiler.java
src/frontend/org/voltdb/newplanner/SqlBatch.java
src/frontend/org/voltdb/newplanner/SqlBatchImpl.java
src/frontend/org/voltdb/newplanner/SqlTask.java
src/frontend/org/voltdb/newplanner/SqlTaskImpl.java
src/frontend/org/voltdb/newplanner/guards/CalciteCheckImpl.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
tests/frontend/org/voltdb/TestAdhocDropTable.java
tests/frontend/org/voltdb/regressionsuites/TestAdHocPlannerCache.java

With the last switch left in CalciteCheckImpl.doCheck() method.
Also spent some amount of effort on refactoring how PlannerTool plans with caches.
(And fixed a bug on TestAdhocDropTable for the error message mismatch.)

Basically enable the DQL code path through Calcite

---

src/frontend/org/voltdb/InvocationDispatcher.java

handled no partition leader case in createTransaction() and will return mis-partitioned client response accordingly

Eng 14912 - Handle Mis-parition for Elastic Shrink

---

src/ee/common/Topend.h
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/Generation.java
tests/frontend/org/voltdb/export/TestExportDataSource.java

There is a race between UAC notifcations to export and EOS notifications from Sites. This means that if either is used to trigger the removal of the ExportDataSource, the other fails an assertion. This is exposed with the TestExportStatsSuite which is currently failing.
However, the m_eos flag is no longer used so the notification of the EndOfStream is no longer necessary. There is a small chance that the Export streams may start injecting events into the PBD. If this ends up being the case, we will still need the CPP api so the Topend callback will be kept until the need for this is decided.

ENG-15083:

---

src/frontend/org/voltdb/ConsumerDRGateway.java
src/frontend/org/voltdb/ProducerDRGateway.java
src/frontend/org/voltdb/RealVoltDB.java

Log the clusters that DR producer and consumer are talking with, at startup time and for daily logging task.
- At server initialization time, producer and consumer will not be ready. So the initial log message happens when the producer and consumer are initialized.
- Added log conversation calls to daily logging task

ENG-15080:

---

src/frontend/org/voltdb/RealVoltDB.java

When the ClientInterface is shutdown before dr the responses to the requests which the consumer has sent out will never be delivered which can block a graceful shutdown which waits for outstanding requests.

ENG-12409: Shutdown client interface after dr

---

tests/frontend/org/voltdb/utils/TestCollector.java

The test was always creating a log file for January 2 of this year and
December 31 and 27 of last year and then would collect the last 3 days of logs.
This would work most days except the first few days of the new year when those
hard coded dates would be in the three day range. The test for specifically
collecting over the year boundry had a similar issue. Instead of using any hard
coded dates pass in a date for now and make all log files relative to that date
so that the number of files being collected are consistent regardles of what
the current date is.

TestCollector: Make all test logs relative to testing date

---

src/frontend/org/voltdb/planner/SelectSubPlanAssembler.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/types/JoinType.java
tests/frontend/org/voltdb/regressionsuites/TestJoinsSuite.java
tests/frontend/org/voltdb/regressionsuites/testjoins-ddl.sql

Changed exhaustive planning To periodically estimate heap memory usage
against maximum allowed memory in planning. Stop further plan searching
when the limit is reached.

ENG-15030 Query with many joins drains during planning

---

src/ee/common/StackTrace.cpp
src/ee/common/StackTrace.h
src/ee/common/debuglog.h
src/ee/expressions/expressionutil.cpp

Since stack traces are written as multiple printf statements their
printing could be interrupted by other log statements. To prevent this
from happening build a single string stack trace and log that in one
printf.
Reduce the implementations of rendering a stack trace down to one method
which operates on an ostream.

Log a stacktrace as a single printf

---

src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java

The root cause of the issue was that there were two queues one for the partition
data and one for the children data. If an ignored exception was thrown
retrieving the partition data then the item in the children queue was not
removed which caused the two queues to become out of sync.
This change simplifies the async retrieval of partition information by making a
single utility method which returns a list AsynPartitions. This ties the async
request for the partition data to the child request so that the processing of
both will not get out of sync. Also, this condenses two different implementation
of this algorithm down to one common implementation.

ENG-15166: Always consume partition data and replicas

---

src/frontend/org/voltcore/zk/LeaderElector.java
src/frontend/org/voltcore/zk/LeaderNoticeHandler.java
src/frontend/org/voltdb/GlobalServiceElector.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltType.java
src/frontend/org/voltdb/elastic/ElasticService.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/MpInitiatorMailbox.java
src/frontend/org/voltdb/iv2/MpScheduler.java
tests/frontend/org/voltcore/zk/TestZK.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

Only allow hosts that are in the partition group with partition 0 be eligible to be leaders of services. This is being done so that a service leader is not killed during elastic removal.

ENG-15167: MpInitiator and elastic coordinator colocation with p0

---

src/frontend/org/voltdb/export/processors/GuestProcessor.java

Use Export onBlockStart() only on block boundaries for legacy connectors.

ENG-15121:

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/MpInitiator.java
src/frontend/org/voltdb/iv2/SpInitiator.java
tests/frontend/org/voltdb/TestMixedPauseModeCluster.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestProcedureDetails.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuite.java

Do not assume that MpI is on host 0
Change expected partition count based on kfactor with respect to MpI
Always initialize MpI starting transaction

Fix unit tests broken by MpInitiator only existing on the first partition group

---

tests/sqlgrammar/sql-ddl-grammar.txt
tests/sqlgrammar/sql-grammar.txt
tests/sqlgrammar/sql_grammar_generator.py

Modified sql-grammar.txt to include CREATE (and DROP) VIEW statements,
and put them in the "DDL" section, along with the existing CREATE (and
DROP) INDEX and PROCEDURE AS statements; and greatly improved the use of
GROUP BY clauses (which are needed by CREATE VIEW). With a few other
minor tweaks, such as: more use of reusable table and column names; and
reducing the frequency of joins, views, sub-queries, nonexistent column
names. (And deleted a few things from sql-ddl-grammar.txt, which were
moved into sql-grammar.txt, with modifications). Modified
sql_grammar_generator.py to include multiple new error messages that we
see in response to CREATE VIEW statements; and to allow some new syntax
involving reusable symbol names.

Eng 14998 gram views

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/expressions/AbstractExpression.java
tests/frontend/org/voltdb/TestAdhocCreateDropIndex.java

The cause for the crash is at partial index creation time, DDLCompiler failed to check predicate for unsafe operations.

ENG-15213.partial.index.creation.with.unsafe.function.crashes.database

---

tests/frontend/org/voltdb/TestMixedPauseModeCluster.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

The paused flag cannot be used on the commandline with the rejoin start action.
Before perforing the rejoin test clear the overrides so it is not appended to
the end of the command line.
Also, rename the test to testRejoins because that is what it is testing.

TestMixedPauseModeCluster: Do not append paused on rejoin commandline

---

tools/kit_tools/upload.gradle

The client needs to use the netty library for SSL but the library was not added
to the POM as a dependency. Add both netty-all and
netty-tcnative-boringssl-static as optional dependencies for the client
library.

ENG-Add netty deps to maven POM

---

src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/messaging/DumpMessage.java

Threads for MP, RO MP and SP sites will be dumped per transaction when MP deadlock shows up so that no additional jstack is needed.

ENG-15246 include site thread dump in the site dump with deadlock warning

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/CreateTransactionResult.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/Iv2TransactionCreator.java
src/frontend/org/voltdb/dtxn/TransactionCreator.java
src/frontend/org/voltdb/dtxn/TransactionInitiator.java

With the ability to remove partitions from the system a boolean is not
descriptive enough of a return code for InvocationDispatcher.createTransaction().
Instead return an enum which allows the caller to determine the cause of the
error better.

ENG-15141: createTransaction use return code

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/elastic/BalancePartitionsStatistics.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
voltdb/log4j.xml

Use the log component ELASTIC instead of JOIN for all elastic operatins.
Also change references to elastic join to elastic operation when it is
not specifically about joins.

ENG-15070: Rename JOIN log facility to ELASTIC

---

tests/frontend/org/voltdb/client/TestClientClose.java

Instead of sleeping and checking if threads are gone block on the threads until
the thread is dead or the timeout occurs.

TestClientClose: Use common method to wait for threads to die

---

src/frontend/org/voltdb/ParameterSet.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/messaging/FragmentTaskMessage.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/frontend/org/voltdb/sysprocs/ExportControl.java
src/frontend/org/voltdb/sysprocs/LoadMultipartitionTable.java
src/frontend/org/voltdb/sysprocs/PingPartitions.java
src/frontend/org/voltdb/sysprocs/PrepareShutdown.java
src/frontend/org/voltdb/sysprocs/Quiesce.java
src/frontend/org/voltdb/sysprocs/Shutdown.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/SnapshotSave.java
src/frontend/org/voltdb/sysprocs/SwapTablesCore.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/sysprocs/UpdateSettings.java
src/frontend/org/voltdb/sysprocs/ValidatePartitioning.java
src/frontend/org/voltdb/sysprocs/saverestore/PartitionedTableSaveFileState.java
src/frontend/org/voltdb/sysprocs/saverestore/ReplicatedTableSaveFileState.java
src/frontend/org/voltdb/sysprocs/saverestore/TableSaveFileState.java
tests/frontend/org/voltdb/iv2/TestMpTransactionState.java
tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java
tests/frontend/org/voltdb/sysprocs/saverestore/TestPartitionedTableSaveFileState.java
tests/frontend/org/voltdb/sysprocs/saverestore/TestReplicatedTableSaveFileState.java

ParameterSet: Add static empty instance
FragmentTaskMessage: Only supports one inputDepId
VoltSystemProcedure.SynthesizedPlanFragment: remove suppressDuplicates
VoltSystemProcedure.SynthesizedPlanFragment: remove inputDepIds
TableSaveFileState: remove m_planDependencyIds
TestSaveRestoreSysprocSuite: move test from TestIV2BlacklistSaveRestore
MultiConfigSuiteBuilder: Use a more generic predicate
SystemProcedureCatalog.Config: remove skipReplication
SysProcFragmentId: Change all IDs to int
Remove unnecessary int casting on SysProcFragmentIds
VoltSystemProcedure: Add more utility methods
VoltSystemProcedure: Subclasses use utility method

Misc cleanup and enhancements

---

src/frontend/org/voltdb/ParameterSet.java

ParameterSet is used by the client but the client is not suppose to depend upon
commons-lang3. The client now will throw ClassNotFoundError when ParameterSet
is loaded but commons-lang3 is not on the classpath. To avoid referencing
commons-lang3 during class initialization use a new empty Object array instead
of the static instance in ArrayUtils.

ParameterSet: Do not use commons-lang during class initialization

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
tests/frontend/org/voltdb/TestAbstractTopology.java
tests/frontend/org/voltdb/TestNTProcs.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

Move current testRestorePlacementOnRecovery to
TestAbstractTopologyImplementation and implement a test which generates a
topology and validates that the recovery puts the partitions back on the
original hosts.

TestAbstractTopology: Fix unit tests

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/JoinAcceptor.java
src/frontend/org/voltdb/probe/MeshProber.java
tests/frontend/org/voltcore/messaging/TestHostMessenger.java

There is a time when a the zk rejoin node exists for a rejoining host but the
host is not in zookeeper. If the host failed in this window the rejoin node
would be left in zookeeper not allowing any other hosts to rejoin.
Update MeshProber.detract(int) to also take in a zookepeer instance and call
CoreZK.removeRejoinNodeIndicatorForHost to remove the rejoin node from
zookeeper.

ENG-12876: Remove rejoin node from zk on failure

---

build.xml
tests/frontend/org/voltcore/agreement/TestFuzzMeshArbiter.java
tests/frontend/org/voltdb/FlakyTestRule.java
tests/frontend/org/voltdb/FlakyTestStandardRunner.java
tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java
tests/sqlgrammar/run.sh
tests/test-tools.sh

ENG-15035-junit-flaky2, v2 after review commments:
Added FlakyTestRule (including @Flaky annotation) and
FlakyTestStandardRunner, to allow marking of Flaky tests as such;
included modifications of TestFuzzMeshArbiter to show how to use @flaky;
and minor changes to MultiConfigSuiteBuilder (including debug print) and
build.xml. Also modified test-tools.sh: added a tt-set-test-args function,
to set a TEST_ARGS environment variable, based on a value passed to it
(which will probably be called TEST_OPTS), for passing @Flaky-related
command-line args to the JUnit tests (very similar to the way the
tt-set-build-args function works for VoltDB builds args).

Eng 15035 junit flaky2

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/ClusterConfig.java
src/frontend/org/voltdb/iv2/Cartographer.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/compiler/TestClusterCompiler.java
tests/frontend/org/voltdb/iv2/TestCartographer.java
tests/frontend/org/voltdb/iv2/TestLeaderAppointer.java

* ENG-13435, improve rack-aware alogrithm to generate well-balanced partitions assignment.
The original algorithm was using greedy rack-aware algorithm to always assign partitions
to *furthest* node. The problem is that it may not always come up with a feasible partition
assignment even though one exists. And also it doesn't guarantte partition replicas are
well balanced across multiple placement groups, e.g. in 2-rack K=3 configuration one group
may have 3 or 4 replicas for some partitions.
Rejoin may also break the rack-awareness by bring too many replicas to one of the placement
groups.
This patch improves the original algorithm by adding extra step after it couldn't find the
viable solution. First it spreads partition replicas out across placement groups,
until no more partitions can …

Eng 13435 v6 rackware (#5134)

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/exportclient/SocketExporter.java
tests/frontend/org/voltdb/export/ExportToSocketTestVerifier.java

A JUnit test failure for Export identified an issue with the Quiesce command, which did not ensure that flushed export buffers had been delivered to the Export persistence layer.
This did not fix the JUnit test, which found additional issues with the synchronization of socket connection initialization as well as synchronization of the writes but this issue was only in the socket exporter used for testing.

ENG-15396:

---

src/frontend/org/voltdb/plannerv2/VoltSqlToRelConverterConfig.java
src/frontend/org/voltdb/plannerv2/rel/physical/AbstractVoltPhysicalAggregate.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/plannerv2/TestInlineRules.java
tests/frontend/org/voltdb/plannerv2/TestLogicalRules.java
tests/frontend/org/voltdb/plannerv2/TestPhysicalConversion.java
tests/frontend/org/voltdb/plannerv2/TestPlanConversion.java
tests/frontend/org/voltdb/regressionsuites/TestMaxSuite.java

By default, calcite will convert the IN expression with size > 20 to a join against a `LogicalValues`.
But 
First, we won't get any benefit from this transform.
Second, calcite has some bugs when we put a column reference in that `LogicalValues` tuple.
Therefore, I simply disable that transform and force usage of OR in all cases (` a IN (1, 2, 3)` will become `a=1 OR a=2 OR a=3`). And we can get rid of the `LogicalValues`.

ENG-15258: support IN expression through calcite

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

* Fix a bug where a PBD instance was deleting a PBD file that belonged to another instance.
* Enhanced directory parsing logic to support detecting PBD nonces that have a common root such as "foo_bar" and "foo_bar_I_am_a_different_pbd".

Eng 15424 promiscuous pbd delete

---

tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

set $PREV schemaCheckMode ""
One-line fix to explaincatalog.outbaseline - test was broken by Manju's
check-in for ENG-15192.

ENG-15469: sqlcmdtest broken by explaincatalog addition:

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/ExportTupleStream.h
tests/ee/storage/ExportTupleStream_test.cpp

Fix corner case of list processing where tick went through the whole flush list but some streams were not flushable because they were in the middle of an MP Txn.

ENG-15084:

---

tests/frontend/org/voltdb/regressionsuites/TestMVOptimizationSuite.java

The original comparison that matches with only one of the eligible views could fail for different JDK.

Fixed view selection non-determinism when multiple views can be used

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/utils/CatalogUtil.java

If the DR role of a cluster was ever updated to xdcr the error message which
was printed reported errors because export was misconfigured for DR. This error
message is confusing especially because export is reporting invalid dr changes.
Create a check in the dr validation method that checks if the role is xdcr the
cluster was correctly initialized for xdcr. Remove DR specific checks from
export configuration validation.

 ENG-15435: Provide a clear error message when role is changed to xdcr

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

Compiler throws errors if nibble export is configured on replicated table.

ENG-15408 restrict nibble export for replicated tables

---

src/hsqldb19b3/org/hsqldb_voltpatches/ErrorCode.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/resources/sql-state-messages.properties
tests/frontend/org/voltdb/TestAdhocCreateTable.java

Disable creation of zero-column tables, because we do not support zero-column table.
Actually, we have the assertion in EE and will crash the server when trying to create a zero-column table in debug build. Now we are checking it in the parsing stage before getting to the EE.
We already have a guard when we try to drop the last column in the table. So guard the zero-column table creation is enough.

ENG-14890: Table defined with no columns causes crash when preparing to take command log truncation snapshot

---

src/frontend/org/voltdb/AuthSystem.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/client/ConnectionUtil.java

When a connection is encrypted the only way to send messages through that
connection is by using the MessageChannel. Kerberos authentication methods were
all using the raw SocketChannel and were sending unencrypted messages on an
encrypted connection. Always use the MessagingChannel to send messages over a
connection.

ENG-13605: Use MessagingChannel for kerberos auth

---

lib/python/voltcli/environment.py

Determine the temp directory to be used by java and if it is not on a tmpfs
filesystem set the option -XX:+PerfDisableSharedMem to disable JVM stats.

ENG-14942: Disable JVM stats if tmp is not a tmpfs

---

tests/sqlgrammar/sql_grammar_generator.py

... by adding 2 missing error messages that currently go unrecognized;
also a minor tweak to fix the fact that 'show' commands were not being
counted.

ENG-15503: fix grammar-gen failures due to sqlcmd hanging

---

src/catgen/spec.txt
src/ee/storage/DRTableNotFoundException.cpp
src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/exceptions/DRTableNotFoundException.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

- Removed configuration for flexible vs. strict schema mode and always use flexible mode.
- Pause DR streams when we receive a binary log record for which schema does not match and
unpause on local catalog update.

ENG-15193:

---

tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

One-line fix to explaincatalog.outbaseline, which was broken by Zeeman's check-in for ENG-15408.

ENG-15532: sqlcmdtest broken by explaincatalog addition: set $PREV tableType 0

---

src/frontend/org/voltdb/utils/PbdSegmentName.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

Add a utility class for parsing a file name into the parts of a PBD segment
file name. The utility class can be used by other classes to determine if a
file is a PBD and what are the components of the name.

PersistentBinaryDeque: Use utility class for segment names

---

src/ee/execution/VoltDBEngine.cpp
src/ee/executors/deleteexecutor.cpp
src/ee/executors/insertexecutor.cpp
src/ee/executors/swaptablesexecutor.cpp
src/ee/executors/updateexecutor.cpp
src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/MaterializedViewHandler.cpp
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/test_utils/plan_testing_baseclass.h

There were two methods which implied they were testing if a table was
replicated isReplicatedTable and isCatalogTableReplicated. The first one tested
if there wasn't a partition column while the second actually returned if the
table was replicated. The results of these methods can disagree for views.
Having the two methods was confusing and resulted in asserts checking the wrong
value. All callers of isReplicatedTable didn't actually care about the
partition column state and really wanted to know if the table was marked
replicated. To simplify the methods the original implementation of
isReplicatedTable was reaplaced with the implementation of
isCatalogTableReplicated and isCatalogTableReplicated was removed.

PersistentTable: Simplify isReplicatedTable vs isCatalogTableReplicated

---

src/ee/storage/MaterializedViewTriggerForWrite.cpp

fix the assertion failure on my previous commit https://github.com/VoltDB/voltdb/commit/145d53ce21d9e98f2826c9891af875628577af81.
Now the index type checking will work both for the index with/without min/max aggregate column.

ENG-15273: fix the assertion failure

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/Table.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

The pull request addressed the issue that TTL definition is accidentally dropped  while a table is altered. And enforce a restriction that a column used by TTL is not allowed to be dropped.

ENG-15557 retain TTL while table is altered. 

---

src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java

Add a tearDown which always reverts the catalog at the end of a test so that
catalog changes from one test do not bleed into another.
Remove catch blocks which surround the test and swallows the exception, making
the test always pass.
Remove unnecessary try/catch blocks which just print the exception and fail the
test. Just let junit do its job and fail when it encounters an exception.
SnapshotRestore: Should not restore randomly partitioned views

 TestSaveRestoreSysprocSuite: Fix up tests and fix one bug in restore

---

src/ee/storage/streamedtable.cpp

m_sequenceNo is the current sequence number and not the next number. The
provided seqNo should match m_sequenceNo prior to being decremented not after.

ENG-15583: Assert that seqNo matches before decrement

---

src/frontend/org/voltdb/TableType.java
src/frontend/org/voltdb/compiler/VoltCompiler.java

Persistent table with migrate should not auto partitioned. This pull fixes this issue.

ENG-15347 fix auto partition issue

---

src/ee/common/tabletuple.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/rejoin/StreamSnapshotSink.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

The migrate hidden column holds transaction ids. While tuples are streamed over to a new elastically joined node, the transaction ids are not relevant on the new node since the new node hosts new partitions and partition ids are part of transaction ids. The values of migrate hidden column will be reset to null while tuples are streamed over to newly joined hosts.

ENG-15347 reset migrate hidden column value for elastic join

---

src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/ElasticIndexReadContext.cpp
tools/VoltDBCompilation.cmake

Disable warning about parentheses.
Do not error when memcpy or memset could be violating invariants of the class
Fix passing a very large string buffer as a format argument to the exception
Correct catching of polymorphic exception

GCC 8 adds some new warnings

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java

Fixes:
1- On GuestProcessor starting after shutdown, the pending container that was processed first didn't have a schema
2- The PDBRegularSegment.SegmentReader.reopen() method was flawed because its call to PDBRegularSegment.open() didn't clear the m_closed flag of the segment reader.

Eng 14565 pending container

---

src/catgen/in/javasrc/DRCatalogDiffEngine.java
tests/frontend/org/voltdb/catalog/TestDRCatalogDiffs.java

Send remote cluster id also to DRCatalogDiffEngine so that it can use

---

src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/ee/expressions/logicfunctions.h
src/ee/expressions/numericfunctions.h
src/frontend/org/voltdb/compiler/PlannerTool.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java

Create a SQL function: 
```
MIGRATING()
```
that returns whether the migrating hidden column of the table is NOT NULL. It returns TRUE if the hidden column is NOT NULL, and FALSE otherwise.
The function then can be used like:
```sql
SELECT COUNT(*) FROM tbl WHERE MIGRATING() AND TTL < 1000;
SELECT TTL FROM tbl WHERE NOT MIGRATING();
```
Note that the `MIGRATING()` is **NOT SUPPORTED** in the SELECT clasue and Joined tables, such as
```sql
SELECT MIGRATING() FROM tbl;
SELECT * FROM t1, t2 WHERE NOT MIGRATING();
```
Why? 
Because supporting them will significantly increase the complextiy of the implementation, and there is no obvious use cases.

ENG-15591: MIGRATING SQL function

---

build.xml
tools/copy-lib.sh

The libcatalog is checked out of source control for both the Mac( .jnilib) and the Linux (.so) versions.  But during the ant build, only the version for the current OS was being put in the right place.
There is a step for official final kit builds that calls the tools/lib-copy.sh script and it was attempting to get the libcatalog, but unfortunately, it wasn't in place for the copy at this step. Rather than fix that problem, I reverted lib-copy.sh to its old task of just making libvoltdb get from the Mac into the final Mac/Linux kit.
The real fix is that now build.xml put the libcatalog into a Mac and Linux dir regardless of which build is being done.

ENG-15608. Fix libcatalog placement.

---

tests/sqlgrammar/run.sh
tests/sqlgrammar/sql_grammar_generator.py

... by adding 2 more missing error messages that currently go
unrecognized; also tweaked one line of run.sh (echo was missing -e).

ENG-15503: fix more grammar-gen failures due to sqlcmd hanging

---

src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/messaging/RejoinMessage.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java
tests/frontend/org/voltdb/rejoin/TestIv2RejoinCoordinator.java
tests/frontend/org/voltdb/rejoin/TestIv2RejoinCoordinatorLive.java

Snapshot streams only send data if there are persistent tables. Rejoin handled
when there were no tables in the cluster but not when there were only streams
in the system. Instead of checking if there are tables, check if there are any
persistent tables.

ENG-15630: Rejoin snapshot timeout

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

PersistentBinaryDeque.writeTruncatedObject(): Set limit after write
PBD: Integrate extra header metadata into segment header
PersistentBinaryDeque: Split offer from updateExtraHeader 
Add test for changing the extra header

DR PBD fixes

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.render.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.service.js

The VMC's stream status is broken due to the change of `@Statistics EXPORT`.
What I found is that if I create a stream with an export target, that stream won't show up in
1. `SQL Query -> Streams`
2. `Admin -> Export -> Export Streams`
This PR try to fix these issues.

ENG-15617: VMC doesn't recognize export.

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
src/frontend/org/voltdb/planner/QueryPlanner.java
src/frontend/org/voltdb/types/QueryType.java

For the need of "MIGRATE TO tbl WHERE ..." statement, where we need to inspect the predicate.
The fix is needed to infer parameters that could appear in the expression, where we may need to
retrieve from the table catalog to get its type.

Fix for the VoltXMLElement -> AbstractExpression conversion

---

src/ee/execution/VoltDBEngine.cpp
src/ee/executors/migrateexecutor.cpp
src/ee/executors/migrateexecutor.h
src/frontend/org/voltdb/export/MigrateRowsDeleter.java

The migrate executor to only change the hidden column and there should be no other changse. Also report the number of rows modified, not the number of rows that are passed to the executor.
Have the Migrate Delete path restart a txn if the failed because the int we use to route to our partition has been moved by elastic grow (causing mispartitioned response). For this case we should resubmit the txn to the original partition.
Also make sure Quiesce Txn executes on ExportDataSource (not just the ones with pending data in the EE).

ENG-15349:

---

tests/frontend/org/voltdb/plannerv2/MPChecker.java
tests/frontend/org/voltdb/plannerv2/PlanChecker.java
tests/sqlgrammar/mp-checker

A command line tool to check a query that Calcite planner considers as MP is indeed MP and vice versa. You can use the script at `tests/sqlgrammar/mp-checker` to run it.
```
usage: mp-checker
-d,--ddl <arg>     File path for the DDLs.
-f,--file <arg>    The input file path that contains SQL query statements
(If -q/--query is used, this option will be ignored).
-q,--query <arg>   Single SQL query statement string.
```
If the query is planable and there is a difference in MP/SP decision between the orignal volt plan and the new calcite plan, it will print out the query in **STDERR**. Otherwise, it will print nothing in STDERR. For example:
```console
foo@bar:~$ mp-checker -d testcalcite-ddl.sql -f tests.sql
select * from P1 where id in (1) 
```

ENG-15158: Ensure that all fall-back ad-hoc DQL queries are indeed MP queries.

---

src/frontend/org/voltdb/iv2/RejoinProducer.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java

The same timeout was being used to wait for the initial data from a snapshot as
the next block of data. This doesn't work if a snapshot is currently being
performed since that delays the snapshot from starting. Instead of using the
same timeout value create a new one which defaults to 1 hour for the initail
data to be received.

ENG-15641: Make initial watchdog timeout higher

---

src/ee/expressions/functionexpression.cpp
src/ee/expressions/functionexpression.h
src/ee/expressions/logicfunctions.h
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/hsqldb19b3/org/hsqldb_voltpatches/FunctionForVoltDB.java
src/hsqldb19b3/org/hsqldb_voltpatches/Tokens.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java

**The MIGRATING() function returns true for rows with hidden columns _NOT NULL_**.
And removed guard against "NOT" before the function
As a side-effect, the parser now rejects "CREATE MIGRATING INDEX ..."
usage, which is what we plan to deprecate: we can just create normal,
partial index like:
`CREATE INDEX ii ON tbl(ttl) WHERE NOT MIGRATING AND ttl > 50;`
which should be like what we do with migrating index:
`CREATE MIGRATING INDEX ii ON tbl(ttl) WHERE ttl > 50;` (but this is no-longer supported)

ENG-15696 Reversed SQL function NOT_MIGRATED() to MIGRATING

---

src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java
src/hsqldb19b3/org/hsqldb_voltpatches/resources/sql-state-messages.properties
tests/frontend/org/voltdb/TestLikeQueries.java

Removed obsolete and no-longer-valid check, and let user
escape whatever they want to escape

Fixed ENG-15682

---

src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLike.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
tests/frontend/org/voltdb/TestLikeQueries.java

unless the like pattern is constant; and made error message (hopefully) clear.
That means, should a query contain `LIKE ... ESCAPE 'x'`, the escaped string must not contain magic characters: (`_` or `%`). We still need handling of the escape mechanism in EE, and until then, either the (escaped or not) LIKE pattern must be constant, or the LIKE pattern could contain magic characters, but user cannot use ESCAPE.

Reverted to disallow LIKE...ESCAPE

---

src/frontend/org/voltdb/export/ExportSequenceNumberTracker.java

Why was this assert put in? It seems we now can get gap queries when our gap tracker is empty.

ENG-15606, remove assertion generating backtrace in tests

---

src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/rejoin/TaskLogImpl.java
src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PBDUtils.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPBDMultipleReaders.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

Add a length and CRC field in the header for the extra header
Remove checkCRC from the poll api since the only valid places to check crc are either parseAndTruncate and scanForGap
When a CRC error is found in a segment entry report back to the PBD the number of entries truncated
Only mark a segment final if all of the data has been syned to disk and there were no errors writing the data

PBD harden a bit more and handle check errors

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/MigrateRowsDeleter.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
src/frontend/org/voltdb/sysprocs/saverestore/SavedTableConverter.java
tests/frontend/org/voltdb/sysprocs/saverestore/TestSavedTableConverter.java

Reset back to NULL any rows that were marked as migrating in a Snapshot when that row is being Restored (as opposed to recovered) from a Snapshot.
Updated the unit test (in Pro) that verifies the row counts of non-migrating rows in the face of Joins, Rejoins, Recover, and Restore. Note that this test will break when and if the migrate index is implicitly created by the compiler as it does today for the primary key column(s) because it explicitly removes the index to hold the migrating row count constant.

ENG-15721:

---

tests/ee/storage/DRTupleStream_test.cpp
tests/ee/storage/ExportTupleStream_test.cpp

Fix Cpp Unit tests that were using a test function but that is now used in other paths and therefore renamed.

ENG-15711:

---

tests/sqlgrammar/sql_grammar_generator.py

... by adding 2 more missing error messages that currently go unrecognized.

ENG-15503: fix 2 more grammar-gen failures due to sqlcmd hanging

---

tests/sqlcoverage/sql_coverage_test.py

test suite, which is a workaround for occasional failures caused by
ENG-11086, based on build #531 of sqlcoverage-matview-postgres:
http://ci.voltdb.lan/view/Branch-jobs/view/CORE-team-extended/job/test-nextrelease-sqlcoverage-matview-postgres/531/
which had 4390 failures caused by ENG-11086 (way more than usual).

ENG-11086: Increased max_mismatches for the joined-matview-default-full

---

tests/frontend/org/voltdb/TestExportLiveDDLSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuiteLegacy.java
tests/frontend/org/voltdb/export/TestExportBaseSocketExport.java

There are some tests that wait for tuple counts to go to 0, in the Export Statistics after the Export Stream is dropped. However, when the stream is dropped the EDS and PBD is immediately removed and therefore the stats will have no rows for the Stream. The tests that look for rows have been updated to look for no rows instead.

ENG-15337:

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java

… it's possible for the decoder thread to queue two poll requests on EDS thread's task queue. When EDS thread detects reentrant poll it throws ReentrantPollException which is captured by decoder thread, try hard to not leak BBContainer in this scenario.
Change-Id: I660c8c0ba7fff4cc72540bd849e33c8d15537573

Fix BBContainer leak on integration branch

---

src/ee/storage/TableCatalogDelegate.cpp

An assert is hit trying to update a wrapper that is being moved from one StreamTable to another. Rather than updating the state, we should set the StreamTable state before assigning the wrapper to that StreamTable.

ENG-15776:

---

src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PbdSegmentName.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPBDMultipleReaders.java
tests/frontend/org/voltdb/utils/TestPbdSegmentName.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDequeCorruption.java

Add an optional flag encoded into a segment name to mark the segment as quarantined
If there is an IOError reading a segment header or crc checksum fails mark the segment as quarantined. Change deletion of segment to be when all readers discard the first entry from the next segment.
Add a little more paranoia around the isFinal flag
This is the successor to https://github.com/VoltDB/voltdb/pull/6076

PBD quarantine unreadable

---

src/ee/common/types.h
src/frontend/org/voltdb/TableType.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

Make the default table type of 0 an invalid value.
This way we can distinguish between unset table types
from tables from older version snapshots and tables that
are actually persistent tables.

ENG-15714:

---

src/frontend/org/voltdb/export/ExportGeneration.java

Disable Catalog Version Check. It prevents rejoin nodes from draining because they are not synced with other nodes on the current catalog version.

ENG-15780:

---

src/ee/storage/AbstractDRTupleStream.cpp

extendBufferChain() calls checkOpenTransaction which basically asserts that if
m_opened than m_currBlock is not null and m_currBlock->hasDRBeginTxn() is true.
AbstractTupleStream::fatalDRErrorWithPoisonPill() was setting m_currBlock to
NULL and immediately calling extendBufferChain which was causing this assert to
be hit on a debug build. Instead of calling extendBufferChain immediatly call
it after committing the current transaction which sets m_opened to false.

AbstractDRTupleStream: Do not extend buffer when opened and null currBlock

---

src/frontend/org/voltdb/export/ExportDataSource.java

Also undo change from commit 6f36002f03356428cf59496a58f47737368bc83f that broke recover scenarios in releaseExportBytes

Eng 15769 initialize committed seq no

---

src/frontend/org/voltdb/plannerv2/rel/logical/VoltLogicalAggregate.java
src/frontend/org/voltdb/plannerv2/rules/PlannerRules.java
src/frontend/org/voltdb/plannerv2/rules/logical/RelDistributionUtils.java
tests/frontend/org/voltdb/plannerv2/TestMPQueryFallbackRules.java

Update distribution trait of aggregation:
Set distribution trait to SINGLETON (corresponding to replicated table) only if all the aggregation function appeared in the aggregation node refer to the partition column(s) of the child distribution.

Aggregate distribution

---

src/frontend/org/voltdb/ClientInterface.java

Cartogropher.getHSIDForPartitionHost(long, long) returns a Long and can
return null if the given partition does not exist on on the given host
or the host is down.
Handle when the host site ID is null by returning from the method and
letting the next pass handle any changes.

ENG-15792: Handle null host site ID

---

tests/frontend/org/voltdb/regressionsuites/TestSystemProcedureSuite.java

testSwapTables verifies modified tuple count, which is complicated by TTL delete. Tuples may be deleted before table swap and the test still expects original tuple count.  Delay TTL delete to ensure that tables have expected count in swap.

ENG-15680 fix intermittent test failure testSwapTables

---

src/frontend/org/voltdb/iv2/CompleteTransactionTask.java
src/frontend/org/voltdb/iv2/RepairLog.java
src/frontend/org/voltdb/iv2/ReplaySequencer.java
src/frontend/org/voltdb/iv2/SpScheduler.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java
tests/frontend/org/voltdb/iv2/TestReplaySequencer.java

Log messages from MP dump messages (after a possible MP Deadlock) don't include the current repair log. This makes it harder to detect inconsistencies between the repair log and the transaction task queue. This branch adds additional log output as well as cleaning the formatting of some of the more common task messages that are logged.

ENG-15233:

---

lib/python/voltcli/environment.py

Temporarily suppress the illegal reflective access warnings for third party lib.
The clean up should be address in https://issues.voltdb.com/browse/ENG-15831

ENG-15830: Suppress Illegal reflective access warning in JAVA 11

---

src/frontend/org/voltdb/plannerv2/VoltPlanner.java
src/frontend/org/voltdb/plannerv2/rel/physical/VoltPhysicalTableScan.java
tests/frontend/org/voltdb/plannerv2/TestInlineRules.java
tests/frontend/org/voltdb/plannerv2/TestLogicalRules.java
tests/frontend/org/voltdb/plannerv2/TestPhysicalConversion.java

Do not trim columns when the rel itself is an aggregation, or
when its input is (recursively) an aggregation.

Fixed ENG-15802

---

src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltdb/sysprocs/saverestore/TableSaveFile.java
tests/ee/catalog/ExportTupleStreamTest.cpp

There is a race between TableSaveFile.close() discarding all buffers and
TableSaveFile.Container.discard(). discard() can m_hasMoreChunks prior to
close() setting it to false but insert the buffer into m_buffers after close()
has drained m_buffers(). By synchronizing the body of discard() that race goes
away and the buffers is guaranteed to be discarded and not leaked.

 ENG-15826: Access to m_hasMoreChunks and m_buffers

---

src/ee/storage/persistenttable.cpp

Add Assert in Delete phase of the Migrate to verify that the TxnId of the row is consistent with the txnId of the batch that is being targetted for delete.

ENG-15809:

---

src/ee/storage/persistenttable.cpp

Add tuples loaded from stream snapshot to migrating index if the tuples have been migrated  to avoid data divergence which causes hash mismatch.

ENG-15809 migrating index on rejoining streamed tuples

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java

Rejoining node was getting a newer catalog than the rest of the clusters. It looks like
the cluster started UpdateClasses NTProc, which called UpdateCore sysproc as the final step.
UpdateCore wrote the new catalog to ZK node, but the MPI node failed before any fragments were run.
Node rejoined a few seconds later and picked up the new catalog from ZK, while the
rest of the cluster stayed on the old catalog. To avoid this, write new catalog bytes
to ZK node, only after the first fragment of UpdateCore completes, thus ensuring that UpdateCore
will be restarted on the new MPI even on an MPI node failure.

ENG-15827:

---

src/ee/executors/updateexecutor.cpp
src/ee/executors/updateexecutor.h
src/ee/expressions/abstractexpression.cpp
src/ee/expressions/abstractexpression.h
src/ee/expressions/expressionutil.cpp
src/ee/expressions/expressionutil.h
src/ee/expressions/functionexpression.cpp
src/ee/indexes/CompactingTreeMultiMapIndex.h
src/ee/indexes/tableindex.h
src/ee/storage/persistenttable.cpp
tests/frontend/org/voltdb/TestAdhocCreateDropIndex.java

that crashes when removing a tuple not present in some partial index
Renamed the branch, since branch name containing `.` confuses Jenkins (hence previous PR was automatically closed).

Fixed ENG-15734

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java

Fixes an issue in PerPartitionTable.buildTable() where VARCHAR/STRING column values >1MB result in the bulk loader (and by relation the CSV loader) hanging indefinitely during drain while waiting for m_outstandingRowCount to be decremented to zero.

Fix hang when importing >1MB VARCHAR/STRING columns

---

src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java

If uac kicks in after a rejoining node fails but before its stream snapshot is completed, uac could be blocked by the stream snapshot, which may trigger mp deadlock warning if uac is blocked by more than 5 min.  If the uac requires snapshot isolation and snapshot is in progress, abort the uac.

ENG-15819 check snapshot for uac

---

tools/docker/docker-entrypoint.sh

Fix re-using variable between methods. Stops the no such option -C if not yet initialized
This is due to the OPTIONS variable being used several places (could also be local variable, but i changed it to INIT_OPTIONS)

Fix re-using variable between methods

---

src/frontend/org/voltdb/client/VoltBulkLoader/PerPartitionTable.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java

* Fix hang when importing >1MB VARCHAR/STRING columns
Fixes an issue in PerPartitionTable.buildTable() where VARCHAR/STRING
column values >1MB result in the bulk loader (and by relation the CSV
loader) hanging indefinitely during drain while waiting for
m_outstandingRowCount to be decremented to zero.
* Switch to the patched version of Guava's Strings class

Fix hang when importing >1MB VARCHAR/STRING columns (#6148)

---

src/frontend/org/voltdb/TheHashinator.java
src/frontend/org/voltdb/elastic/ElasticService.java
src/frontend/org/voltdb/iv2/LeaderAppointer.java

On some error and recovery paths completed migrated partitions were not being correctly handled while an elastic remove operation was on going. Prevent the removal of partitions until elastic remove is ready for them to occur and be able to determine easily which partitions are part of the system but not in the hashinator.

ENG-15883: On error and recovery handle fully migrated partitions

---

src/frontend/org/voltdb/VoltTable.java

This improves performance significantly for getting many column values from a VoltTable by column name, even for single-row tables, but has no effect if you only use the column index based get methods.

ENG-15842 getColumnIndex() optimization

---

src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
src/frontend/org/voltdb/sysprocs/saverestore/ClusterSaveFileState.java

1) Add warning messages for @SnapshotRestore response if path to snapshot files doesn't exist or not executable.
Currently if path to snapshot files doesn't exist, server will stop restoring snapshot regardless there are following checks on
snapshot consistency and integrity. Since this may not be fatal, lower it to warning and append the warning message to response.
2) Error message `Path doesn't exist` should supersede other minor issues like `Path is not executable`.

ENG-15816, fix a sharp edge when @SnapshotRestore fails on path check.

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltdb/RealVoltDB.java

A rejoining node could still wait for stream snapshot from a failed node and end up 60 second no-data timeout.  Shutdown it early to avoid the error warning.

ENG-15584 shutdown rejoining node without going through agreement process

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltdb/RealVoltDB.java

Reverts VoltDB/voltdb#6167
Change was causing NPE in implementation of disconnect which assumed that failed hosts could not be null

Revert "ENG-15584 shutdown rejoining node without going through agreement process"

---

examples/bank-offers/ddl.sql
examples/bank-offers/procedures/bankoffers/CheckForOffers.java

Old schema exported a table AND ran selects on it.
Added parallel stream and updated Java proc to insert into both tables.
Tested run.sh and with apprunner.

ENG-15854: Remove deprecated "EXPORT" with updated STREAM syntax

---

tests/ee/storage/CompactionTest.cpp

Remove dummy assignment of ShadowStream in compaction test because tablefactory now creates it explicitly when the tableType requires it.

ENG-15765:

---

src/ee/executors/OptimizedProjector.cpp

When using c++17 and gcc8 comparison functions must be declared as
consts otherwise a static assert is thrown.

OptimizedProjector: Comparison functions must be const

---

src/ee/common/tabletuple.cpp
src/ee/common/tabletuple.h

"Double free or corruption". The stacktrace leads to my recent changes on
JSON serialization, and I think it could have been because of the static
local variable scope, hence changed to static member variable.
Pending system test. @jwiebema1

Fix for ENG-15989

---

CMakeLists.txt
build.xml
src/ee/CMakeLists.txt
tools/build_cmake.py

To get better memory leak analysis tools during tests, we have a mechanism for tracking each allocation. However, the option is not available through the build tool. This commit enables direct manipulation of the compile time otion with the following config:
-DVOLT_TRACE_ALLOCATIONS=true

ENG-15989:

---

src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java

On rejoin without any persistent tables the snapshot completion event was
not being processed. When the system does not have persistent tables
only skip waiting for streams from other hosts but not processing the
snapshot completion.
Update rejoin with only stream tests to confirm that the sequence id
continues to increase.

ENG-15945: On rejoin always monitor snapshot

---

src/frontend/org/voltdb/export/ExportCoordinator.java
src/frontend/org/voltdb/export/ExportDataSource.java
tests/frontend/org/voltdb/export/TestExportCoordinator.java

bug fixes:
1- fixes the case where the system test reported "No streams are active in export stats, this shouldn't happen": the root cause was that export mastership would reset to the default value of 'false'. It should reset to the partition leader by default.
2- fixes ArrayAoutOfBoundsException, caused by lack of up-to-date schema when a node transitions to Export Master after several PBD segments were acknowledged, and an ALTER changed the stream columns. The fix forces the schema on the first block after transitioning to Export Master.
3- fix a couple bugs in mastership determination, added unit test cases to validate

Eng 15820 error processing block

---

src/frontend/org/voltdb/elastic/BalancePartitionsStatistics.java
tests/frontend/org/voltdb/TestRejoinEndToEnd.java

Throughput was not reset when the stats were initialized causing previous throughput to roll into next run. This made the current runs throughput seem much higher and caused the throttling to kick in and slow down balance partitions.
Also, some minor improvements to the stats class including reusing result of nanoTime() and a deque instead of TreeMap

ENG-16016: Reset throughput when stats are initialized

---

src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/plannerv2/NonDdlBatch.java
src/frontend/org/voltdb/plannerv2/SqlBatch.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java
src/frontend/org/voltdb/sysprocs/Explain.java
tests/frontend/org/voltdb/regressionsuites/TestExplainCommandSuite.java

Change the behavior of EXPLAIN_ADHOC to uses Calcite planner to generate the plan and print the explained plan, instead of the old code path.
Note: we currently always fallback at the end of the calcite planner, you can only see the plan difference if you comment out the fallback  https://github.com/VoltDB/voltdb/blob/1e27131d9f052cdae584a390361760718b08f9a4/src/frontend/org/voltdb/compiler/PlannerTool.java#L308.

ENG-15923: Explain a calcite plan

---

src/ee/storage/persistenttable.cpp

When elastic remove is running it is easy to go over a tables tuple limit. It
is possible to try and maintain under the limit by running the delete clause if
it exists but it is questionable when it should be run and if it will do the
right thing, especially since it will not be running under the documented
conditions. Also, dr already ignores the limit. The limit will be checked an
enforced on the next insert into the table.

ENG-16015: Ignore tuple limit during elastic ops

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

Modified to recognize the "type" (e.g. CONSISTENT, INTERMITTENT) of
older Jira tickets; and to not "downgrade" tickets that are already
marked as "Blocker" (presumably manually).

ENG-16021: Auto-filer tweak 2

---

src/frontend/org/voltdb/export/ExportCoordinator.java

Close a window where ExportCoordinator would not be shut down because initialization wasn't completed; later on in the test the ExportCoordinator would re-create the same State Machine instance, and hit some pre-existing state in ZK.

Eng 16008 state machine 2 results

---

src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/messaging/FragmentTaskMessage.java
tests/frontend/org/voltdb/iv2/TestMaxMpResponseSize.java

Add response size limit to each fragment task request so that no single partition can return a response which is too large. Be default the total max response size is 65% of heap. That value is then divided by the number of partitions involved in the transaction and that value is divided by 3 if the transaction is a read only mp in case multiple ro transactions are being performed. The value can be changed by setting the environment variable or java property MP_MAX_TOTAL_RESP_SIZE. The value can either be a percentage of heap or an absolute number of bytes.

ENG-15498: Limit mp responses

---

src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/exportclient/JDBCExportClient.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
tests/hsqldb/org/hsqldb_voltpatches/TestHSQLDB.java

This PR implements the following features:
According to the SQL-99 standard, the following delete statements are valid:
DELETE FROM x y WHERE key = 2;
DELETE FROM x y WHERE y.key = 2;
DELETE FROM x AS y WHERE key = 2;
DELETE FROM x AS y WHERE y.key = 2;
and they should just work like:
DELETE FROM x WHERE key = 2;
They following should be errors in the WHERE clause with error messages saying X.KEY cannot be found:
DELETE FROM x y WHERE x.key = 2;
DELETE FROM x AS y WHERE x.key = 2;

Eng 11701 support table aliases in delete statements

---

src/ee/storage/persistenttable.cpp

notifyTupleInsert is used to notify table streams of tuples which were
inserted. However this method was being called prior to inserting the tuple
into the indexes. If the tuple violated any unique constraints of an index then
the tuple would be removed from the index but the table stream would not be
notified. This is an issue for elastic operations since notifyTupleInsert adds
the tuple into the elastic index.
Moving the call notifyTupleInsert to after index insertion guarantees that the
tuples in the elastic index are all valid tuples part of a table and two
entries in the index do not point to the same tuple.

ENG-15991: Call notifyTupleInsert after indexing

---

tests/frontend/org/voltdb/TestRejoinEndToEnd.java

rejoinOne does not work with old cli and is not actually doing a rejoin. Use
recover to do a rejoin.

ENG-16034: Use recoverOne instead of rejoinOne

---

src/frontend/org/voltdb/client/Distributer.java
src/frontend/org/voltdb/iv2/InitiatorMailbox.java
voltdb/log4j.xml

There could be a small window with leader promotion and host failure, within which a site could end up rerouting transactions. Now the state update is synchronized to eliminate the window.

ENG-16085 synchronize the leader migration state change 

---

lib/python/voltcli/voltadmin.d/stop.py

The following message in lib/python/voltcli/voltadmin.d/stop.py is changed 
from
"This may be caused by a disabled export target; the node shutdown process will proceed."
to 
"This may be caused by an export target either disabled or removed from the configuration. No action is required; the stop node process will proceed."

stop node messages to inform on disabled export targets

---

src/frontend/org/voltdb/export/ExportDataSource.java

It is useless to check isShutdown as it's done after closing the PBDs. Beter check m_closed

ENG-16200: refactor EDS closed status to avoid racing with SSM callbacks

---

src/ee/execution/VoltDBEngine.cpp
src/ee/storage/MaterializedViewHandler.h
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/JoinProducerBase.java
src/frontend/org/voltdb/iv2/RejoinProducer.java
tests/frontend/org/voltdb/TestSnapshotWithViews.java

This pull request fixes two issues:
* Materialized views that are included in the elastic join stream snapshots are not paused during stream snapshot restore.
* EE ignores the view pause request for joined views in snapshot restore if any of the view source tables are not empty. But the loadTable() request is not ignored in this case where it should be.

ENG-15918 Constraint violation while restoring joined views from snapshot

---

src/ee/storage/persistenttable.cpp
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/export/TestPersistentExport.java

Updates migrating indexes after constraint violation is checked. Also used MP partition id as a partition key for migrated row deletion.

ENG-16199 TTL migrate: only insert to shadow stream on partition 0 from replicated source table

---

tests/frontend/org/voltdb/iv2/TestMaxMpResponseSize.java

Any test suite which uses LocalCluster needs to extend JUnit4LocalClusterTest.

ENG-16123: Extend JUnit4LocalClusterTest

---

src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/rejoin/TaskLogImpl.java
src/frontend/org/voltdb/utils/BinaryDeque.java
src/frontend/org/voltdb/utils/BinaryDequeReader.java
src/frontend/org/voltdb/utils/BinaryDequeSerializer.java
src/frontend/org/voltdb/utils/DeferredSerializationBinaryDequeSerializer.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/test/utils/RandomTestRule.java
tests/frontend/org/voltdb/utils/TestPBDMultipleReaders.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDequeCorruption.java

Instead of a separate getter for the extra header add a new pollEntry
method which returns an entry object that bundles any associated extra
header metadata with the data entry.
Add generic support for the extra header metadata so that the update
method and the Entry instance consumes and returns a specified type.
Use a builder to create a PersistentBinaryDeque instead of adding more
constructors with different optional arguments.

ENG-16231: Bundle extra header with entry on poll

---

tests/ee/test_utils/testing_topend.h
tests/frontend/org/voltdb/compiler/procedures/InsertAggregatesOfFloatInHaving.java
tests/frontend/org/voltdb/planner/TestPlansCommonTableExpression.java
tests/frontend/org/voltdb/planner/TestPlansENG10022.java
tests/frontend/org/voltdb/planner/TestPlansInsertIntoSelect.java
tests/frontend/org/voltdb/planner/TestValidatePlan.java
tests/frontend/org/voltdb/planner/eegentests/EEPlanGenerator.java
tests/frontend/org/voltdb/regressionsuites/TestCommonTableExpressionsSuite.java
tests/frontend/org/voltdb/regressionsuites/TestWindowFunctionSuite.java
tests/frontend/org/voltdb/regressionsuites/TestWindowFunctionSuiteMinMaxSum.java
tests/frontend/org/voltdb/regressionsuites/TestWindowFunctionsWithIndexes.java
tests/frontend/org/voltdb/regressionsuites/ValgrindXMLParser.java
tests/frontend/org/voltdb/types/TestDateParsing.java
tests/frontend/org/voltdb/utils/TestValgrindParser.java
tests/test_apps/polygonBenchmark/procedures/polygonBenchmark/InsertPolygonAsObject.java
tests/test_apps/polygonBenchmark/procedures/polygonBenchmark/InsertPolygonAsString.java
tools/approved_licenses/gpl3_base64_and_voltdb.txt
tools/approved_licenses/gpl3_evanjones_and_voltdb.txt
tools/approved_licenses/gpl3_hstore_and_voltdb.txt
tools/approved_licenses/gpl3_voltdb.txt
tools/approved_licenses/gpl3_voltdb_python.txt
tools/approved_licenses/mit_x11_evanjones_and_voltdb.txt
tools/approved_licenses/mit_x11_hstore_and_voltdb.txt
tools/approved_licenses/mit_x11_michaelmccanna_and_voltdb.txt
tools/approved_licenses/mit_x11_voltdb.txt
tools/approved_licenses/mit_x11_voltdb_and_apache.txt
tools/approved_licenses/mit_x11_voltdb_and_clearspring.txt
tools/approved_licenses/mit_x11_voltdb_python.txt
tools/licensescheck.py

Interpret the approved licenses as templetes with template variables for the
start and end year for the copyright. Allow the start year to be any value
between 2008 and the current year and allow the end value to be any year
between 2019 and the current year.

 ENG-16194: Allow licensecheck to allow range of years

---

tools/approved_licenses/gpl3_base64_and_voltdb.txt
tools/approved_licenses/gpl3_evanjones_and_voltdb.txt
tools/approved_licenses/gpl3_hstore_and_voltdb.txt
tools/approved_licenses/gpl3_voltdb.txt
tools/approved_licenses/gpl3_voltdb_python.txt
tools/approved_licenses/mit_x11_evanjones_and_voltdb.txt
tools/approved_licenses/mit_x11_hstore_and_voltdb.txt
tools/approved_licenses/mit_x11_michaelmccanna_and_voltdb.txt
tools/approved_licenses/mit_x11_voltdb.txt
tools/approved_licenses/mit_x11_voltdb_and_apache.txt
tools/approved_licenses/mit_x11_voltdb_and_clearspring.txt
tools/approved_licenses/mit_x11_voltdb_python.txt
tools/licensescheck.py

[ backport f69f30409c4ed0a4ad0e790c7487b2acf29bb86a  ]
Interpret the approved licenses as templetes with template variables for the
start and end year for the copyright. Allow the start year to be any value
between 2008 and the current year and allow the end value to be any year
between 2018 and the current year. If the year is a single year it has to be
one of the years in the end year value.

ENG-16194: Allow licensecheck to allow range of years or single year

---

src/catgen/in/javasrc/CatalogDiffEngine.java
src/catgen/spec.txt
src/frontend/org/voltdb/TTLManager.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/planner/QueryPlanner.java
src/frontend/org/voltdb/sysprocs/SwapTables.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/frontend/org/voltdb/utils/CatalogUtil.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/StatementSchema.java
src/hsqldb19b3/org/hsqldb_voltpatches/Table.java
src/hsqldb19b3/org/hsqldb_voltpatches/TimeToLiveVoltDB.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/regressionsuites/TestFunctionsForVoltDBSuite.java
tests/test_apps/genqa/ddl-all-nocat-migrate.sql

The v9.0 syntax:
```sql
CREATE TABLE tbl (...) USING TTL ... MIGRATE TO TARGET target;
```
The new syntax:
```sql
CREATE TABLE tbl MIGRATE TO TARGET target (...) USING TTL...;
```
I also move the attribute `migrationTarget` from `TimeToLive` catalog to `Table` catalog, which will make it cleaner when implementing the non-ttl migration feature.
- JUnit tests are updated with the new syntax.
- System tests updated.

ENG-16140: Move "MIGRATE TO" of TTL table DDL to before column declaration

---

src/frontend/org/voltdb/ProcedureRunner.java
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/BaseInitiator.java
src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/MpRoSitePool.java
src/frontend/org/voltdb/iv2/MpTransactionState.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/messaging/FragmentTaskMessage.java
tests/frontend/org/voltdb/iv2/TestMaxMpResponseSize.java

Backport of bb25880406b32b4b006ce9f58036fcdb88ccde10 812db8877654ad14578ee866f49b8e13f7244654 0bd42dbeab4dabf990f0aef2e33f978efb764713 7b9b1f7b3e57a6eb7bc8c7c7837987e104c1d1ed 8039fde851cdd6bd3bd652e75d7ff916b89b72b5
Add response size limit to each fragment task request so that no single partition can return a response which is too large. Be default the total max response size is 65% of heap. That value is then divided by the number of partitions involved in the transaction and that value is divided by 3 if the transaction is a read only mp in case multiple ro transactions are being performed. The value can be changed by setting the environment variable or java property MP_MAX_TOTAL_RESP_SIZE. The value can either be a percentage of heap or an absolute number of bytes.

ENG-16138: Limit mp responses backport 8.4

---

tests/sqlcmd/baselines/sysproc/explaincatalog.outbaseline

Update the `explaincatalog.outbaseline` since I have added the `migrationTarget` attribute to the Table catalog.

fix broken sqlcmdtest

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/iv2/Cartographer.java

With elastic remove it is now normal for there to be no partition master for a
partition which use to exist. Update the methods in Cartogropher
getHSIdForSinglePartitionMaster and getHSIdForMaster to return a Long and let
the callers handle the missing master. This prevents a NullPointerException
from being thrown when an auto unboxing would occur trying to return a long.

ENG-16302: Partition masters can be removed

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/iv2/Cartographer.java

Catch all exceptions from startMigratePartitionLeader and handle them. Handle null return from Cartogropher.getHostsByPartionMasterCount() and some minor Cartogropher cleanup changes.

ENG-16252: Handle migration failures

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

In junit-stats.py:
Added new and improved get_modified_description function (and
truncate_if_needed, used by it), which does a much better job of
combining the old, existing description for a Jira ticket and the new
pieces we want to add based on the latest failure; and modified
file_jira_issue, etc., to make use of it.
Changed the failure percentage format so that single-digit percentages
are preceded by a 0, e.g. Summaries with: "INTERMITTENT 08% ..." rather
than "INTERMITTENT 8% ...", which should result in better sorting.
In jenkinsbot.py:
In find_jira_bug_tickets, changed ORDER BY from DESC to ASC, so that
when there is more than one relevant ticket, the older one will be
chosen: this is a partial fix for a problem where failing tests that
have essentially the same class and method …

ENG-16021: Fourth set of tweaks to the JUnit Auto-filer:

---

src/ee/common/tabletuple.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/executors/migrateexecutor.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/MigrateRowsDeleter.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/sysprocs/MigrateRowsAcked_MP.java
src/frontend/org/voltdb/sysprocs/MigrateRowsAcked_SP.java
src/frontend/org/voltdb/sysprocs/MigrateRowsBase.java
src/frontend/org/voltdb/sysprocs/MigrateRowsDeleterNT.java
tests/ee/catalog/ExportTupleStreamTest.cpp

The data in the persistent source table are deleted when external system acknowledges that the data have been received.  Export system sends one block of data at a time to external systems. The data from multiple transactions (migrations) could be accumulated into one single block. The acknowledgement is only issued with the last committed transaction, even a block contains multiple transactions.  Thus the tuples migrated in multiple transactions could be deleted  in one batch, which could pose issues with 50 MB DR size limit. The issue is resolved by deleting the migrated tuples with transaction awareness, matching migrated batch to delete batch.

ENG-15570 migrate delete one batch at a time

---

src/frontend/org/voltdb/InvocationDispatcher.java

Before completing BalancePartitions update the list of partitions in the system in InvocationDispatcher. Also, do not return mispartitioned to the client from InvocationDispatcher.

ENG-16346: Update partitions before removal

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/parser/SQLParser.java
src/frontend/org/voltdb/utils/CatalogSchemaTools.java
src/hsqldb19b3/org/hsqldb_voltpatches/HSQLInterface.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/Table.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java
tests/frontend/org/voltdb/export/TestPersistentExport.java

Update ddl parser to take ddl syntax with   CREATE TABLE {table}  [ EXPORT TO TARGET {target}  [ ON {dml} [,...] ( column-definition ,... ) and ALTER TABLE {table} ALTER EXPORT TO TARGET {target}  [ ON {dml} [,...]  ].

ENG-16264 persistent table export DDL update

---

src/frontend/org/voltdb/exportclient/ExportToFileClient.java
third_party/java/src/au/com/bytecode/opencsv_voltpatches/CSVWriter.java

Fixing this ticket with 2 separate commits:
1- fix the handling of extra escape characters, which was totally busted
2- change export to use a TSV writer doing no escaping at all, which allows preserving JSON contents:
Thus if you insert this:
2> insert into stream_towns (town, state) values ('{"foo":"bar","bar":"glo\n"}', '01');
(Returned 1 rows in 0.00s)
You get that 
3619631923494912	1199506655149680	8	0	0	1	{"foo":"bar","bar":"glo\n"}	  01

Eng 16336 tsv escape bugs

---

src/frontend/org/voltcore/network/TLSEncryptionAdapter.java

VoltTLSNIOWriteStream.drainTo maintains the backpressure with the assumption
that the delta is always reported upfront. To maintian that behavior add the
delta when the next buffer to send is retrieved from the queue.

ENG-15983: Add delta to ledger before sending data

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

In jenkinsbot.py: change modify_jira_bug_ticket, to try twice to update
the Jira ticket: once without email notification, and if that does not
work (as seems to happen sporadically), a second time with email
notification. Also, modify that function, and also
create_jira_bug_ticket and close_jira_bug_ticket, to re-raise the caught
exception, if the basic functionality does not work, so that the Jenkins
build will fail.
In junit-stats.py: check for any /tmp/*.tmp files (which a JIRAError
sometimes leaves behind), and if found, print their contents.

ENG-16021: Sixth set of tweaks to the JUnit Auto-filer:

---

tools/jenkins/jenkinsbot.py

Just a minor improvement to the previous 2 changes: when not using
'notify=False', don't even use a notify value (True seems to cause as
much trouble as False), in modify_jira_bug_ticket.

ENG-16021: Eighth set of tweaks to the JUnit Auto-filer:

---

src/frontend/org/voltdb/exceptions/SerializableException.java
src/frontend/org/voltdb/exceptions/SpecifiedException.java

Before changed for ENG-15731, VoltAbortException super class would return
client response status of USER_ABORT and its subclass SerializableException
would return UNEXPECTED_ERROR. After the change, SerializableException also started
return USER_ABORT status, which was indicating some failures as aborts to stats.
Fixed that to keep the original behaviour.

ENG-16399:

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
tests/frontend/org/voltdb/TestAdhocMigrateTable.java

The XML attribute -> OPERATOR_TYPE mapping:
`"is_null" -> OPERATOR_IS_NULL` is missing.

ENG-16463: NPE in MIGRATE FROM

---

src/ee/execution/VoltDBEngine.cpp
tests/frontend/org/voltdb/TestCatalogUpdateDuringSnapshot.java

Decrement the refcount of a table has the potential to delete and free that
table. All calls to Table::decrementRefcount must be done under with the
appropriate context installed.
There was an issue with replicated tables being dropped while a snapshot was
being performed. This could cause the table to be deallocated when it completed
streaming without using the mp memory context.

 ENG-16382: Decrement replicated tables with mp context

---

src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
tests/frontend/org/voltdb/catalog/TestCatalogDiffs.java
tests/frontend/org/voltdb/compiler/TestVoltCompiler.java

This PR concludes the DDL feature for **Migrate Table**.
The latest syntax rule will be: You cannot alter the MIGRATE TO TARGET attribute of the table. You also cannot alter any attributes of the table that affect migration. For example, you cannot add, drop, or alter the USING TTL clause if the table is declared with MIGRATE TO TARGET. And if the table has both MIGRATE TO TARGET and USING TTL, you cannot add, drop, or alter the TTL column. However, you can alter the TTL value, batch size and frequency.

Eng 15612 - Fix "Alter Table Alter Using MigrateTarget" bug

---

tests/frontend/org/voltdb/TestCatalogUpdateDuringSnapshot.java

Since voltdb instance in class global the temporary folder for the snapshots
should also be class global. If it isn't then the folder could be deleted whild
snapshot work is still on going and cause the host to crash.

ENG-16514: Use a class temporary folder

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
tests/frontend/org/voltdb/TestAdhocMigrateTable.java

This pr added support for dynamic parameter used in sql function when running `"create procedure .. as migrate from .." `

Eng 16508 - Fix "Create procedure as Migrate from" bug 

---

src/ee/common/TupleSchema.cpp
src/ee/common/TupleSchema.h
src/ee/common/TupleSchemaBuilder.h
src/ee/common/tabletuple.h
src/ee/expressions/functionexpression.cpp
src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/persistenttable.cpp
src/frontend/org/voltcore/network/NetworkDBBPool.java
src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltcore/utils/Pair.java
src/frontend/org/voltdb/rejoin/StreamSnapshotAckReceiver.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java

When deserializing a tuple for balance partitions if there is a migrate column consume the value from the input array but discard it and set the column in the tuple to null.
When balance partitions times out make sure the ack receiver is stopped so that two ack receivers are not running concurrently possibly consuming the messages intended for the new new receiver.
Other clean up includes using a queue which can efficiently calculate size and using the term isTableWithMigrate instead of isTableWithStream

ENG-16415 & ENG-16440: Balance partitions fixes

---

examples/adperformance/ddl.sql

The syntax was not quite correct in previous releases and was changed by the fix for ENG-15612.

ENG-16571.  Fix the ALTER TABLE command for adperformance example.

---

src/ee/common/NValue.hpp
src/ee/common/tabletuple.h
src/ee/executors/indexscanexecutor.cpp
src/ee/executors/nestloopindexexecutor.cpp
src/ee/indexes/CompactingTreeMultiMapIndex.h
src/ee/indexes/CompactingTreeUniqueIndex.h
src/ee/indexes/indexkey.h
src/ee/indexes/tableindex.h
src/ee/storage/MaterializedViewTriggerForWrite.cpp
src/ee/structures/CompactingMap.h
tests/frontend/org/voltdb/TestAdHocQueries.java

The root cause is a bug in the `nestloopindexexecuter`,  literally the `initial_expression`.
We extract all the predicate exprs that have the indexed column and concatenate them with **AND** to build the `initial_expression`.
When we doing an index scan with a LTE(less than or equal to) operator, we find the entry whose key is greater than search key, then do a forward scan using `initial_expression`(we evaluate the `initial_expression` for each input tuple, move forward until it returns false, indicate that we just pass the first failed entry, then we move 1 step backward) to find the correct start point to do a reverse scan.
```sql
CREATE TABLE T1 (
a integer NOT NULL,
b INTEGER,
);
CREATE INDEX T1_IDX ON T1 (a, b);
INSERT INTO T1 VALUES( -1, 9);
INSERT INTO T1 VALUES( 0, 1);
INSERT …
```

ENG-15836: Wrong answer with "IN", and "<=" when index is present

---

tools/jenkins/junit-stats.py

issue (in junit-stats.py's close_jira_issue function).

ENG-16021: Fixed the "global name 'jenkins_job' is not defined" failure

---

bin/sqlcmd
build.xml
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/regressionsuites/RegressionSuite.java

1. Added mechanisms to make Jenkins run tests based on Git branch name: choose Calcite parser/planner when the branch name contains "**calcite-**" (case sensitive); choose legacy parser/planner otherwise
2. Documented how developer can switch which parser/planner to use in `sqlcmd` and IDE as well. See `src/frontent/org/voltdb/sysprocs/AdHocNTBase.java`:
>  There are two ways to set planning with calcite: either by setting the JAVA properties; or by setting the
>  environment variable.
>
>  The first way is used by build.xml to make Jenkins be Git branch aware, and only use Calcite planner when the
>  branch it is in contains "calcite-" string (case sensitive). You don't need to do anything to make it work that
>  way.
>
>  The second way is needed for developer that run some quick test …

Branch aware calcite switch

---

src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/DRTupleStream.h
src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/SnapshotCompletionMonitor.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
tests/ee/storage/DRBinaryLog_test.cpp
tests/ee/storage/table_and_indexes_test.cpp
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java

Because the drVersion in the snapshot digest was not zero setDRProtocolVersion is called which initializes the replicated DR stream. When the DR replicated stream is initialized it is then included in the snapshot digest.
To avoid this happening initialize the DR version to 0 so that it is only not 0 when dr is enabled. Also, do not even include and of the DR tuple stream state info if DR is not active.

ENG-16548: Do not always call setDRProtocolVersion on restore

---

src/frontend/org/voltdb/LoadedProcedureSet.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/VoltSystemProcedure.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/sysprocs/AdHoc_RW_MP.java
src/frontend/org/voltdb/sysprocs/ExecuteTask.java
src/frontend/org/voltdb/sysprocs/LoadMultipartitionTable.java
src/frontend/org/voltdb/sysprocs/MigrateRowsAcked_MP.java
src/frontend/org/voltdb/sysprocs/MigrateRowsMP.java
src/frontend/org/voltdb/sysprocs/NibbleDeleteMP.java
src/frontend/org/voltdb/sysprocs/SwapTables.java
src/frontend/org/voltdb/sysprocs/SwapTablesCore.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/sysprocs/UpdateLogging.java
src/frontend/org/voltdb/sysprocs/UpdateSettings.java
tests/frontend/org/voltdb/iv2/TestSite.java

During rejoining, sites may have different loads, some sites may enter normal running state to process tasks while other sites still replay tasks from TaskLog.  Within this window, a MP transaction could send fragments to a rejoining node and release fragments from scoreboard.  The fragments will be processed right away on those sites which have entered normal running state. The fragments must be specifically instructed to be processed on those sites which are still replaying.  If any MP fragment is not replayed, the  mp transaction is dead locked.  The fragments which require replay are cached during boot up and used for lookup.

ENG-16441  durable fragments to be replayed from TaskLog on rejoining to avoid mp deadlock

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java

This NPE is happening because `<>` (not equal) is used but not registered in `ExpressionUtil :: mapOfVoltXMLOpType`. The fix includes only 1-line change that adds `<>` operation type.
Also added `is not distinct from` into op map.

ENG-12484 Fixed NPE in Migrate using <>

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java

When a new member joins the state machine, it could join just as a previous task or state change has completed but before all the nodes have processed the change. At this point in time the Initializing node might grab the distributed lock and request the current state from other members before they are ready causing a number of different failure conditions including multiple results from the same state machine instance and multiple participant nodes from the same state machine instance. The fix is for a newly initializing member to initialize the local participant count before attempting to grab the distributed lock. That way even if it is the lowest lock, it won't be successful until the participant node count goes to zero.

ENG-16610:

---

src/frontend/org/voltcore/network/TLSEncryptionAdapter.java

The cause is we shut down the same `TLSEncryptionAdapter` more than once and double release the message buffer.
Guard added.

ENG-16576: TLSPicoNetwork Error shutting down Volt Network

---

src/frontend/org/voltdb/exportclient/loopback/LoopbackExportClient.java

Remove hard coded skipinternals value and pick it up from export properties. The default is not changed.
This will be useful for tests that can use the metadata, especially VOLT_EXPORT_OPERATION to determine the correctness of conditional exports as in:
CREATE TABLE x EXPORT TO TARGET y ON INSERT | DELETE | UPDATE | UPDATE_NEW | UPDATE_OLD ...

ENG-16889: Loopback exporter use skipinternals property

---

src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
tests/frontend/org/voltdb/TestAdhocMigrateTable.java

The root cause is there is no null checking when `ORDER BY NULL` is being parsed.
Fix includes adding a null checking.

ENG-16879 Fixed NPE when order by NULL

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
tests/frontend/org/voltdb/planner/TestSelfJoins.java

This fix handles NPE when self join is used without aliasing the table name differently. 
For example, `SELECT * FROM R1 JOIN R1 USING (ID);` is not valid since compiler can only find 1 column reference: R1.ID. 
The correctly way is to use alias after the table name. `SELECT * FROM R1 a JOIN R1 b USING (ID);`

ENG-13412 For self-join, throw an error when no table name alias is used

---

src/ee/storage/persistenttable.cpp
src/ee/storage/temptable.cpp

TableIterator::hasNext() can return true but
TableIterator::next(TableTuple) return false if all of the remaining
tuples are pending delete. Since the result of TableIterator::hasNext()
is not reliable just use the result of TableIterator::next(TableTuple)
to determine if iteration should continue.

ENG-5891: Rely on TableIterator::next() result

---

src/ee/common/NValue.cpp
src/ee/execution/VoltDBEngine.cpp

The cause being in my refactory of NValue::serializeSize() for commit
092deeed6c22cdf5bbae807eece829138dd7205d, I accidentally dropped the switch
case for VALUE_TYPE_GEOGRAPHY

ENG-16633 Fixed failed EE assertion

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionColumn.java
tests/frontend/org/voltdb/planner/TestSelfJoins.java
tests/frontend/org/voltdb/regressionsuites/TestGroupBySuite.java

This PR fixed the NPE caused by queries like:
`SELECT * FROM R1 A JOIN R2 B USING (ID) GROUP BY A.BIG;`
This query should fail because **select list** should **match group by list**
The NPE is caused by lack of null check for alias.

Eng 16925 - Fix NPE when join + group by

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/network/PicoNetwork.java
src/frontend/org/voltdb/iv2/SpProcedureTask.java
src/frontend/org/voltdb/iv2/SpScheduler.java

I found two issues in HostMessenger.presend():
1. AtomicInteger.getAndIncrement() doesn't guarantee each caller to get an unique integer because integer increments atomically doesn't mean get() is synchronized. It's possible to have multiple thread get the same value at same time then increment atomically. This issue leads to uneven distribution of hsid to network thread.
2. Only network threads talk to the same node should be bound evenly,  if we use a global counter it may also lead to uneven distribution of hsid to network thread.

ENG-16899, fix a race condition when assigning network thread to remote HSIDs.

---

src/frontend/org/voltcore/messaging/HostMessenger.java

In the rejoin case, the new hostId is not exist in s_nextForeignHost map, end up causing NPE and crash local host.
There also seems no cleanup for dead hostId from s_nextForeignHost.

ENG-16965: Fix uncaught NPE in hostMessenger

---

src/frontend/org/voltdb/export/ExportDataSource.java

@SnapshotRestore would trigger truncateExportToSeqNo on existing Eds.
Since restore can act  upon empty stream, the InitialSequenceNumber should be 0L, no need to set again. Skip the set to avoid an assertion that assume ExportCoordination haven't been initialized.
Not sure other side affects in truncateExportToSeqNo() are necessary for the restore path.

ENG-16950: skip set IntialSequenceNumber for snapshot Restore path

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDDL.java
src/hsqldb19b3/org/hsqldb_voltpatches/Table.java
tests/frontend/org/voltdb/export/TestPersistentExport.java

Export connectors are dropped while adding new column to persistent export tables because the export clause is processed after tables are parsed and hold on session.  Now the export clause is parsed while tables are created to prevent  export connector  from being dropped.

ENG-17024 alter persistent table

---

tests/sqlgrammar/run.sh
tests/sqlgrammar/sql_grammar_generator.py
tests/test-tools.sh

Added new function test-tools-server-count to test-tools.sh; and now use
it in test-tools-server-if-needed and test-tools-server-pro-if-needed,
to more reliably detect whether a VoltDB server is already running. Also
added improved error messages, particularly in
test-tools-wait-for-server-to-start (& its call to tt-exit-script).

ENG-16468: Fix grammar-gen to not run 'voltdb init' twice

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
tests/frontend/org/voltdb/TestAdhocMigrateTable.java

Add like operator in `XMLOpType` map and switch statement so statement 
`MIGRATE FROM TABLE WHERE COL LIKE "SSS%"` 
won't throw NPE

Eng 17049 - Fix NPE when LIKE "%" used in migrate statement

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java
tests/frontend/org/voltdb/TestAdhocMigrateTable.java

Add like operator in `XMLOpType` map and switch statement so statement 
`MIGRATE FROM TABLE WHERE COL LIKE "SSS%"` 
won't throw NPE

Eng 17049 - Fix NPE when LIKE "%" used in migrate statement 

---

src/ee/execution/VoltDBEngine.cpp

This crash happens when EE is updating catalog and replaying the SQL Statement, migrate table's companion stream might be dropped if the table is empty. 
Will add a test case.

ENG-17013 Fix Crash When Companion Stream Dropped in non-stream Catalog Update

---

src/frontend/org/voltdb/compiler/ProcedureCompiler.java

As from @zeemanhe 's reply on customer's bug:
**INTERNAL:
There is an error thrown: 
VOLTDB ERROR: UNEXPECTED FAILURE:
java.lang.NoSuchMethodError: com.i2i.fcbs.voltdb.procedure.aom.ProcAOMOperationTransaction.generateSQLStmtForProcedure(Ljava/lang/String;)Lorg/voltdb/SQLStmt;
at com.i2i.fcbs.voltdb.procedure.aom.ProcAOMOperationTransaction.<init>(ProcAOMOperationTransaction.java:53)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at …

Catch NoSuchMethodError and NoSuchClassError

---

tests/sqlgrammar/run.sh
tests/sqlgrammar/sql_grammar_generator.py

... encountered while writing up the 'SQL Grammar Generator' Wiki page:
sql_grammar_generator.py: split existing '--max_save=' option into 2
separate options: '--max_save_sql=' and '--max_save_sqlcmd=', which
separately determine the number of SQL statements, and their results in
the latter case, that will be saved in their distinct output files (the
latter also determines how often TRUNCATE statements are called); thus
making it easier to save all SQL statements for crash reproducers.
run.sh: for the 'help' option, include info about the (relatively new)
'test-pro' option; and in the event of an error, include the error code
for running the DDL-pro.sql file.

ENG-14261-gram-wiki-tweak: 2 minor grammar-gen improvements

---

src/hsqldb19b3/org/hsqldb_voltpatches/Expression.java
src/hsqldb19b3/org/hsqldb_voltpatches/ExpressionLogical.java
src/hsqldb19b3/org/hsqldb_voltpatches/ParserDQL.java
src/hsqldb19b3/org/hsqldb_voltpatches/QuerySpecification.java
src/hsqldb19b3/org/hsqldb_voltpatches/SubQuery.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

The root cause of this NPE is when parser is cursing back-and-forth on a sql query, one subquery might create multiple logical subqueries in `compile context` while only one of them can be correctly resolved. In this fix I added an iterator that will dedup before adding subquery into list.

ENG-16927 Fixed NPE caused by sub-query

---

src/frontend/org/voltcore/messaging/ForeignHost.java
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/Subconnection.java
src/frontend/org/voltcore/network/PicoNetwork.java
src/frontend/org/voltcore/network/TLSPicoNetwork.java
tests/frontend/org/voltcore/network/TestPicoNetwork.java

Fix an issue that cause uneven site-to-network-threads binding, some pico network threads carry more traffic than others. 
Refactor a few things including 1) single ForeignHost to each remote host ID, 2) each ForeignHost may have more than one connection, 3) no difference between connections, dead host detection is performed on foreign host level.

ENG-16899 make hsid bindings more even for partition group

---

src/frontend/org/voltcore/messaging/ForeignHost.java
src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/Subconnection.java
src/frontend/org/voltcore/network/PicoNetwork.java
src/frontend/org/voltcore/network/TLSPicoNetwork.java
tests/frontend/org/voltcore/network/TestPicoNetwork.java

[backport 2a5640645fb6dc9fa2b8a290f1edb2a932220140]
Fix an issue that cause uneven site-to-network-threads binding, some pico network threads carry more traffic than others.
Refactored a few things including:
1) single ForeignHost to each remote host ID,
2) each ForeignHost may have more than one connection,
3) no difference between connections, dead host detection is performed on foreign host level.
Change-Id: I96c618708f8c247ab409182b57d91fa92c80b6ac

Eng 16899 even distribution 2 for v8.4

---

src/ee/executors/insertexecutor.cpp
src/ee/executors/insertexecutor.h
src/ee/expressions/functionexpression.cpp

Root cause is because now that I cleared the static std::string in InsertExecutor's p_execute_init_internal() method, multiple sites would collide with each other accessing and clearing the std::string, which is not atomic. This lead to memory corruption.
Added a lock to protect write operations on this static std::string.
Note:
1. I still think that using static member variable to communicate between sites is a quick and dirty solution, the biggest problem being that we need to clean the state between txns. But an alternative solution would take some more elaborated design.
2. This fix is only to block system test failures that result in core dumps that point to the line std::string gets clear()-ed. However, we have extensive use of other static variables as means of communication for …

Eng 17469 core dump on basic string create

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/compiler/PlannerTool.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/plannerv2/SqlBatchImpl.java
src/frontend/org/voltdb/plannerv2/VoltFrameworkConfig.java
src/frontend/org/voltdb/plannerv2/VoltSchemaPlus.java
src/frontend/org/voltdb/plannerv2/guards/AcceptDDLsAsWeCan.java
src/frontend/org/voltdb/sysprocs/AdHocNTBase.java

When using AdHoc to create a table and then run a SELECT query on that table, Calcite doesn't work for 2 reasons:
1. I accidentally commented out the code path for letting Calcite run `CREATE TABLE` statement that generates a new SchemaPlus.
2. @wenxuanqiu's work on SchemaPlus work to sync Catalog updates to SchemaPlus did not consider Calcite's `CREATE TABLE` work, from VoltCompiler. 
The (temporal) solution is to let PlannerTool generate a new version of SchemaPlus from PlannerTool everytime an Ad Hoc DQL is planned.
Additionally, I added a warning to `start VoltDB` process when it runs in Calcite mode.

Fix broken tests in calcite build

---

tests/frontend/org/voltdb/parser/TestSQLParser.java

The root cause of this memcheck issue is: to use `LocalCluster` the JUnit test must extend `RegressionSuite` or `JUnit4LocalClusterTest` . The fix simply change test base into `JUnit4LocalClusterTest`.

ENG-16985 Fixed TestSQLParser Failure after Calcite Merge

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

Delete empty segment in the middle of pbd segment chain would fail the integrity
check in next recovery.
Change-Id: I542e874bae6590a92f3c0e37a8c47fcd635ff7d7

ENG-16609, stop deleting empty pbd segments in the initialization of recovery

---

src/catgen/in/javasrc/CatalogType.java

During UAC,  the first site which acquires a lock builds the updated catalog, and other sites reference it.  Some of objects in catalog, such as CatalogMap, CatalogReference etc, are not  thread safe.  Objects updated on one site may not be visible on other sites.  System tests have caught this issue with @ NibbleDeleteSP.  Right after UAC, the sys procedure tried to build TTL procedures but couldn't find the partition column in a partition table.  The PR makes the value and path variables volatile.

ENG-16922 make cached variables in CatalogReference volatile

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
tests/frontend/org/voltdb/regressionsuites/TestSubQueriesSuite.java

This is only a workaround to get rid of NPE stacktrace. A real fix should include correct parsing of subquery. In the case of `SELECT ID FROM P1 WHERE EXISTS (SELECT COUNT * FROM P1);`, [previous guarding conditional block](https://github.com/VoltDB/voltdb/commit/d042c2eb141200972062b21b826323ea041667dd) cannot guard the incorrect use of partitioned table in subquery because parser fail to fetch the subquery info.

ENG 16932 - Fixed NPE when Subquery Accesses Partitioned Table

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/plannerv2/utils/DropTableUtils.java

on unsupported DDL statements.
The reason is that when supporting "DROP TABLE" statements in Calcite,
it could throw SqlParseException, which gets printed.
The fix by-pass the Calcite parser for DDL in normal build (that should not use
Calcite), which was intended as a special path for processing "DROP TABLE".

Fix error message emmited from Calcite

---

tests/sqlcmd/baselines/simple/testcte.errbaseline

when table does not exist.
Previous error message was issued from Calcite;
since master branch should not ever use Calcite parser/planner,
this message should revert back to original one.

Fixed error message change on DROP TABLE

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
tests/frontend/org/voltdb/export/TestExportFeatureOption.java

- New deployment file option to specify export feature option of BASIC vs. ADVANCED export mode.
- ExportManagerInterface picks up the appropriate ExportManager implementation based on the export mode.
- New method in ExportManagerInterface, getExportMode, which can be used to find out if it is running
BASIC or ADVANCED mode.

ENG-17723:

---

LICENSE.voltdbclient
build.xml
tools/kit_tools/upload.gradle

* ENG-17722. Change voltdbclient license to MIT.
* ENG-17722. Add a LICENSE.voltdbclient with MIT client into the kit.
(Same as  pull #6516 for release-9.1.x branch)

ENG-17722. Change voltdbclient license to MIT.

---

src/ee/common/SerializableEEException.cpp
src/ee/common/serializeio.h

This bug is only hit on Voltmini, and many other MacOSX enviroments.
Investigation shows that ReferenceSerializeInput and ReferenceSerializeOutput buffer size was initialized to 4096 bytes, but the error message complains overflowing 10MB network/output buffer.
The cause is in the debug build, I added stack trace to SerializableEEException message, that exceeds 4096 bytes, and causes a problem on this particular platform. The fix is to truncate stack trace to 2048 bytes. The error message looks normal (no recursion, etc.): see description of the [ticket](https://issues.voltdb.com/browse/ENG-17700).
Also updated obsolete error message complaining that buffer exceeds 10MB limit, to the actual size and capacity, since the old assumption no longer holds.

Eng 17700 ee check fails on voltmini

---

src/frontend/org/voltcore/zk/ZooKeeperLock.java
third_party/java/src/org/apache/zookeeper_voltpatches/ClientCnxn.java

ZK client thread waits for Packet's finished status to be updated on SendThread.  Make Packet.finished volatile.  Also removed ZK sync in ZooKeeperLock since ZK is leaderless, no sync is needed.

ENG-17816 prevent ZK from being blocked

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/compiler/VoltCompiler.java
src/frontend/org/voltdb/compiler/statements/CreateTask.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskManager.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

Push the validation of tasks in the catalog to after the catalog compiles. It
needs to be done this way because the tasks cannot be validated until after all
procedures have been added to the catalog and can be retrieved during
validation. This also guarantees that validation occurs on all catalog update
paths.

ENG-17826: Validate task configuration after catalog compile

---

tests/frontend/org/voltdb/task/TestTaskManager.java

With a change to the validation logic the validation nolonger calls
ClientInterface.getProcedureFromName() so do not increment the expected call
count of that method.

ENG-17911: Do not increment expected call count

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/executorcontext.hpp

This reverts commit 0ae47f0cbdd983656582c9d243ce17222702d836, which was
causeing TestImportSuite to wedge the JVM during shutdown.

Revert "ENG-17626 Use C++11 TLS types to replace pthread (#6495)"

---

src/ee/common/ThreadLocalPool.cpp
src/ee/common/ThreadLocalPool.h

In some unmanaged cases, multiple threads could call `ThreadLocalPool::freeExactSizedObject()` or `ThreadLocalPool::freeRelocatable()` at the same time, creating a race condition in accessing `poolMap.find(key)` when the other thread had already freed the memory from pool, therefore the crash in system test when cluster shutdown (ServerExport-kafka-migrate).
This was just my theory; but upon adding a mutex lock in those methods, the failure now changed to the one found in ENG-17818 (crash on std::set::erase on compaction path).

Fixed ENG-17930

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/ddl.sql

Change target names in DDL to be more descriptive; remove "default" targets.

ENG-17861: cleanup tnxid2 export targets.

---

src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/task/TestTaskManager.java

If the procedure is a work procedure reject its use except when the scope is PARTITIONS.

ENG-17972: Only allow work procedures on partitions

---

src/frontend/org/voltdb/task/Initializable.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/task/TestTaskManager.java

Instead of optionaly implementing a setter to get the scopeId put the taskName,
scope and scopeId into TaskHelper so that it can be accessed that way.

Initializable: Remove setScopeId

---

tests/test_apps/tpcc/src/com/procedures/LoadWarehouse.java

following changes due to ENG-16464 & ENG-16564: Add caller ID to load
table

ENG-18017: Update calls to DeprecatedProcedureAPIAccess.voltLoadTable

---

src/ee/common/SynchronizedThreadLock.cpp

The static pthread_cond_t member vars must be initialized inside
SynchronizedThreadLock::create() to avoid hanging of eecheck and
memcheck-lite of tabletuple_test suite on U14 OS platform.

Fixed ENG-18002

---

src/frontend/org/voltdb/task/TaskManager.java

This is because we try to set a CorePoolSize that is larger than the maximum pool size.
In Java 8 this is allowed but in Java >= 9, this will throw a java.lang.IllegalArgumentException. See the discussion [here](https://bugs.openjdk.java.net/browse/JDK-7153400). The system test is running in Java 11 and hit the exception(I am surprised). 
Fix all places including `TaskManager`  that uses `setCorePoolSize`.

ENG-18020: System test error: [TaskManager] TASK: java.lang.IllegalArgumentException

---

src/ee/common/StringRef.cpp
src/ee/storage/persistenttable.cpp

When fixing ENG-15734 at commit
ae2dc9e9f1511130f54b3be1ef0c63a298eddd67,
I accidentally introduced this stupid error, by adding unnecessary
partial-index check condition into a branch of persistent table update
tuple step;
And then fixed in the wrong way at
0ef6fc6a7bebd8e8cd5ef8eb24b8286ab60b3057 by introducing empty string as
a special instance of StringRef object, that partially masked the
original reproducer when running on a single host.
The reason that adding this additional check fails the reproducer is that it skips the first UPDATE statement when the tuple gets updated, so the old index tuple that should get updated together now points to recycled data (Yes, recycled in C++!), and de-referencing StringRef from garbage simply gives garbage back.

ENG-17091 The right fix

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/messaging/EnableTasksOnPartitionsMessage.java
src/frontend/org/voltdb/messaging/VoltDbMessageFactory.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

The current implemenation would mark the host leader for the partition once the
site was ready regardless of whether or not the host was leader for that
partition. Instead send a message from ElasticJoinOperator to all
joining hosts once all joining hosts have completed the streaming
snapshot.

ENG-18013: Only start tasks when all hosts are ready

---

src/frontend/org/voltdb/exportclient/loopback/LoopbackExportClient.java

The timeout is due to a deadlock in the `LoopbackExportClient.onBlockCompletion`.
`LoopbackExportClient` has a loop back mechanism that calls an insert procedure to insert the processed row back to the Volt stream. It also maintains a Semaphore that is released in the insertion procedures' callbacks.  The `onBlockCompletion` will block until all Semaphore is released and then check for the ClientResponse status. 
The problem is UAC is an MP transaction that will block all the loopback insertions that are queued after the UAC. Therefore we have:
```text
UAC  ----> wait for LoopbackExportClient.onBlockCompletion to shutdown the GuestProcessor.
LoopbackExportClient.onBlockCompletion ---> wait for the insertion callbacks that are blocked by UAC
```

ENG-18058: disabling exporter target causes UAC timeout

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h

`git diff 0ae47f0~..HEAD src/ee/common/SynchonizedThreadLock.* src/ee/common/executor/executorcontext.cpp` leaves only coding style changes.

ENG-18034 Changed back std::mutex -> pthread_mutex_t for pef issues

---

src/frontend/org/voltdb/task/TaskStatsSource.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

In order to be more consistent with other statistics rename the NAME column
TASK_NAME and move PARTITION_ID to be before TASK_NAME.
Also, do not trim the prefix from the subselelected columns when performing a
sub selection.

ENG-18200: Update statistic columns

---

build.xml
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/task/ActionGenerator.java
src/frontend/org/voltdb/task/ActionGeneratorBase.java
src/frontend/org/voltdb/task/ActionScheduler.java
src/frontend/org/voltdb/task/CompositeActionScheduler.java
src/frontend/org/voltdb/task/SingleProcGenerator.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java

Add the concept of read only mode to TaskManager, which causes all read/write
tasks to enter paused mode. When the task manager exits read only mode than all
paused tasks will be started. TaskManager is in read only mode whenever the
database is paused or the database is a replica.
All interfaces which return an Action have a isReadOnly() method which by
default returns false. A custom implementor can override this method to return
an appropriate value. The builtin one returns the read only flag on the
procedure.

ENG-18197: Add read only mode to TaskManager

---

src/ee/executors/abstractjoinexecutor.h
src/ee/executors/aggregateexecutor.cpp
src/ee/executors/executorutil.cpp
src/ee/executors/executorutil.h
src/ee/executors/indexscanexecutor.cpp
src/ee/executors/indexscanexecutor.h
src/ee/executors/largeorderbyexecutor.cpp
src/ee/executors/limitexecutor.cpp
src/ee/executors/mergejoinexecutor.cpp
src/ee/executors/mergereceiveexecutor.cpp
src/ee/executors/mergereceiveexecutor.h
src/ee/executors/nestloopexecutor.cpp
src/ee/executors/nestloopindexexecutor.cpp
src/ee/executors/orderbyexecutor.cpp
src/ee/executors/seqscanexecutor.cpp
src/ee/executors/seqscanexecutor.h
src/ee/plannodes/limitnode.cpp
src/ee/plannodes/limitnode.h
src/ee/storage/tabletuplefilter.cpp
src/ee/storage/tabletuplefilter.h

This PR is part of effort when reviewing Mike's work, specifically on merge join executor (https://github.com/VoltDB/voltdb/pull/6596).
Two key changes in this refactory:
1. Changed signature for `LimitPlanNode::getLimitAndOffsetByReference()`, by moving two function parameters to return value, to make intention more clean.
2. Simplifying `TableTupleFilter` template design.

refactories on tabletuplefilter

---

tools/jenkins/jenkinsbot.py
tools/jenkins/junit-stats.py

Added FREQUENT failure type (>= 80% failure);
made NEW require 2 failures (out of last 10);
tickets initially filed with fix-version 'Autofiled', not 'Backlog';
do not file new tickets for class 'TestFixedSQLSuite', which opens way
too many;
and a few other minor tweaks.

ENG-17694: Auto-filer improvements

---

tools/kit_tools/build_kits.py

- Add the version to the licensee field in the trial downloads kit. 
- Change the licensee for the internal-use license to say "Internal Use"
See changes in the pro repo for more details.

Eng 17910. Add version information to licensee field in trial license.

---

src/frontend/org/voltdb/iv2/ElasticJoinProducer.java
src/frontend/org/voltdb/iv2/RejoinProducer.java

Join tests were failing intermittently because join was calling setDrVersion with 0
if DR was not established before the join. setDrVersion has the side effect of starting
to write dr binay logs as well, which was causing "unexpected protocol version of 0" on the
consumer side.
Changed rejoin as well to check the version before calling setDrVersion, even though the tests
were not related to rejoin.

ENG-16636:

---

src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/task/TestTaskManager.java

It is possible for a procedure to return an error when the system is going in
to paused mode. When this happens it is OK to ignore the failure as long as the
manager is supposed to be in read only mode and the scheduler is not read only.
The task should be paused shortly when evaluateReadOnlyMode completes
execution.
Stop task when any exception is caught in the executor

ENG-18247: Ignore failures during read only transition

---

src/ee/execution/VoltDBEngine.cpp
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/UserDefinedAggregateFunctionRunner.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java

ENG-16292:
Even though the java layer invokes shutdown in the order highest to lowest it
does not wait for one to complete before invoking the next shutdown. This means
that even though the lowest site shutdown is initiated last it could execute
before the the others. Simplify the deallocation of m_engine in VoltDBIPC so
there is only one path and it always deallocates all other sites prior to the
lowest site.
ENG-17299: Implement IPC for user defined aggregate functions
Valgrind identified read of uninitialized memory which was that during sending
of user defined aggregate function method invocations the size of the message
was including the size value which should be excluded.

ENG-16292 & ENG-17299: Fix memcheck test failures

---

tests/frontend/org/voltdb/export/TestExportSuite.java

Other threads sometimes print to stdout prior to the snapshot verifiier which
was messing up the startsWith check. Instead of using startsWith use contains.

ENG-16097: Check that the output contains the string

---

tests/frontend/org/voltdb/regressionsuites/TestGroupByComplexMaterializedViewSuite.java

Use order by clause to guarantee order of result rows

ENG-17794: Use order by in query

---

tests/frontend/org/voltdb/export/TestExportSuite.java

With E3 stats are reported with 0 tuples during initialized eventhough there
are some tuples in the stream. Wait for some tuples to show up before waiting
for the backlog to be 0.

ENG-18289: Wait for tuples to be in stats

---

src/frontend/org/voltdb/iv2/MpScheduler.java

… on the repair path if the duplicate counters contain only the partition masters from failed hosts. The transaction is then declared completed. Ignore responses from failed partition masters after the transaction has been  completed.

ENG-18358 The duplicate counters for run-everywhere MP system procedures could be cleaned

---

src/frontend/org/voltdb/compiler/MaterializedViewProcessor.java
src/frontend/org/voltdb/expressions/ExpressionUtil.java
src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/CommonTableLeafNode.java
src/frontend/org/voltdb/planner/ParsedSelectStmt.java
src/frontend/org/voltdb/planner/PlanAssembler.java
src/frontend/org/voltdb/planner/SelectSubPlanAssembler.java
src/frontend/org/voltdb/planner/StatementPartitioning.java
src/frontend/org/voltdb/planner/SubPlanAssembler.java
src/frontend/org/voltdb/planner/WriterSubPlanAssembler.java
src/frontend/org/voltdb/planner/parseinfo/BranchNode.java
src/frontend/org/voltdb/planner/parseinfo/JoinNode.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
src/frontend/org/voltdb/planner/parseinfo/SubqueryLeafNode.java
src/frontend/org/voltdb/planner/parseinfo/TableLeafNode.java
src/frontend/org/voltdb/plannodes/AbstractJoinPlanNode.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/planner/TestParsedStatements.java

Fortify support for planning multi-table join query.
In a SELECT query that has table joins, our (legacy) planner would enumerate different join orders and filters, and find a best join order as plan. 
However, when mutating join order (and filter), it is likely that the join condition could refer to some other table not seen yet; or the same thing could happen to filter. We did not consider such case, and it results in table not found when resolving TVE expression.
The fix is to add eager validation check in those two phases, and abort current join order (and continue with next candidate), since apparently it is not a valid permutation.
As usual, there are lots of code refactories/clean ups on related code path that were necessary (not really; but it always helps) to understand what goes …

Eng 17134 left join gives error

---

src/frontend/org/voltdb/utils/VoltFile.java
tests/frontend/org/voltdb/TestExportConstraintsSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuite.java
tests/frontend/org/voltdb/TestExportLiveDDLSuiteLegacy.java
tests/frontend/org/voltdb/TestExportRejoinWithView.java
tests/frontend/org/voltdb/TestExportSuiteReplicatedSocketExport.java
tests/frontend/org/voltdb/TestExportView.java
tests/frontend/org/voltdb/TestImportStatistics.java
tests/frontend/org/voltdb/TestImportSuite.java
tests/frontend/org/voltdb/TestSnapshotWithViews.java
tests/frontend/org/voltdb/export/TestExportStatsSuite.java
tests/frontend/org/voltdb/export/TestExportSuite.java
tests/frontend/org/voltdb/export/TestExportV2SuitePro.java
tests/frontend/org/voltdb/regressionsuites/MultiConfigSuiteBuilder.java
tests/frontend/org/voltdb/regressionsuites/StatisticsTestSuiteBase.java
tests/frontend/org/voltdb/regressionsuites/TestAdminMode.java
tests/frontend/org/voltdb/regressionsuites/TestCatalogUpdateSuite.java
tests/frontend/org/voltdb/regressionsuites/TestExportRowLengthLimit.java
tests/frontend/org/voltdb/regressionsuites/TestMaterializedViewSuite.java
tests/frontend/org/voltdb/regressionsuites/TestRestoreEmptyDatabaseSuite.java
tests/frontend/org/voltdb/regressionsuites/TestRestoreSysprocSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java
tests/frontend/org/voltdb/regressionsuites/TestSecuritySuite.java
tests/frontend/org/voltdb/regressionsuites/TestSnapshotStatus.java
tests/frontend/org/voltdb/regressionsuites/TestStopNode.java
tests/frontend/org/voltdb/regressionsuites/TestUpdateDeployment.java
tests/frontend/org/voltdb/regressionsuites/TestViewsInPartialSnapshotRestore.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

ENG-17844: Files.deleteIfExists() throws an exception with the reason why the delete failed which can be good for information reasons. Also, if delete fails because directory is not empty retry the delete and if it continues to fail throw an exception with the contents of the directory.
ENG-16349: When the server is restarted between tests of TestMaterializedViewSuite the memcheck runs take over 30 minutes to run and cause a timeout. Force the server to never restart between runs.

ENG-17844 & ENG-16349: More junit fixes/improvements

---

src/frontend/org/voltdb/iv2/SpScheduler.java

When a partition leader is migrated away and the target host fails,  the original partition leader site can be elected as leader again. A duplicate counter for a particular transaction is created on the original partition leader. Prior to the partition leader promotion,  repair process will be triggered. A new duplicate counter will be created during the repair. If  the original duplicate count is not cleaned before the repair kicks in, the new duplicate counter will collide with the existing duplicate counter.

ENG-18410 duplicate counter collision fix 

---

tools/VoltDBCompilation.cmake

Add -Wno-error=deprecated-copy when compiling with gcc 9.
Simplify gcc argument determination by trying to use the major version of gcc mostly and appending the arguments as you increment through the versions. Also, remove references to OS which are not officially supported.

Support gcc 9 and simplify gcc argument determination

---

src/frontend/org/voltcore/utils/PortGenerator.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/utils/CommandLine.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/PortGeneratorForTest.java

Allow the kipling port to be able to be set in both the deployment and
commandline. Update LocalCluster to handle when kipling is enabled and run each
host on a different kipling port

Allow kipling port to be set in deployment

---

src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PbdQuarantinedSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

- Close or closeCursor at PBD level now gets rid of segment level readers completely. Removed purge method not that purge is the same as close.
- Added new closeAndSaveReaderState method to save closed cursors as a reader moves from a segment on the next and closes the cursor.

ENG-18453:

---

src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/export/ExportDataSource.java

As read-write MP system procedure, @ValidatePartitioning needs to be restartable
to avoid corrupting task scoreboard, so does @ExportControl.
Change-Id: I0f911399517eba90568a2fc6d5d2706f3e0bf47b

ENG-13113, make @ValidatePartitioning and @ExportControl restartable..

---

src/frontend/org/voltdb/exportclient/ExportToFileClient.java

I believe this lock-up was a a latent bug predating the latest changes

Ensure the file decoder unlocks the read/write lock on exception

---

tests/test_apps/genqa/src/genqa/ExportRabbitMQVerifier.java

might help debugging som test failures
ran a series of rabbitmq server export tests.  None failed due to channel shutdown.  Clean shutdowns produced something like 
```
2019-11-12 22:26:36 INFO tear down and close channel
2019-11-12 22:26:36 INFO shutdownCompleted, cause: com.rabbitmq.client.ShutdownSignalException: clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id\
=0, method-id=0)
```

ENG-18500: add a shutdown listener to print shutdown reason

---

src/frontend/org/voltdb/planner/AbstractParsedStmt.java
src/frontend/org/voltdb/planner/StatementPartitioning.java
src/frontend/org/voltdb/planner/microoptimizations/InlineOrderByIntoMergeReceive.java
src/frontend/org/voltdb/planner/parseinfo/BranchNode.java
src/frontend/org/voltdb/planner/parseinfo/StmtSubqueryScan.java
src/frontend/org/voltdb/plannodes/AbstractPlanNode.java
src/frontend/org/voltdb/plannodes/MergeReceivePlanNode.java
tests/frontend/org/voltdb/TestAdHocQueries.java
tests/frontend/org/voltdb/planner/TestPlansGroupBy.java

When we did order-by micro-optimization, we used to combine order-by
with send/receive into a merge-receive node. When this happens inside a
sub-query, it would complain that the query is cross-partition, even if
the upper-level query can be plannable.
The fix is to perform this optimization only when the current plan node is on replicated table only.

Eng 18533 partitioned subquery join

---

tests/test_apps/kafkaimporter/pounder10.groovy

replace kafka BLOCK_ON_BUFFER_FULL_CONFIG with MAX_BLOCK_MS_CONFIG.
c096962f05 brought along a new kafka client library which no longer supports the former property

ENG-18536: remove old kafka property

---

tests/sqlcoverage/SQLCoverageReport.py
tests/sqlcoverage/template/include/advanced-select.sql

Also, a tiny tweak to make it easier to find mismatched results (in
failed tests), with an asterisk ('*').

ENG-18533: Added sqlcov tests of sub-query with (& without) LIMIT

---

tests/test_apps/kafkaimporter/kafkaloader10-SSL.props

The new client (commit  c096962f05) library tightened up certificate validation

ENG-18568: disable SSL host name verification for kafka client

---

src/frontend/org/voltdb/export/ExportCoordinator.java

Intermittent bug hard to reproduce: a node becomes leader but because there are no new buffers pushed after this point, it does not resume polling.

ENG-18639: resume polling on leadership change

---

src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java

The fragment PF_updateCatalogPrecheckAndSync now waits for all closing sources until a fixed timeout of 30s.

ENG-18612: catalog prechecks wait on closing sources up to fixed timeout

---

tools/kit_tools/build_kits.py

(cherry picked from commit c369b0ed2cfac18e217e63f1dc75b95e9896a9c7). This has been tested on V9.2.2 and no supplies the corrected .jar file to maven.

ENG-18663. Move the maven prep step.

---

src/frontend/org/voltdb/compiler/VoltProjectBuilder.java
src/frontend/org/voltdb/export/ExportManagerInterface.java

If the system is enterprise use E3 as the default export implementation.
If the export implemenation is in the deployment file honor it.

ENG-18653: Use E3 as default export implementation for enterprise

---

tests/test_apps/genqa/src/genqa/ExportRabbitMQVerifier.java
tests/test_apps/genqa/src/genqa/RabbitMQExchangeDelete.java

verifier was exiting too soon because it wasn't accounting for duplicate rows exported
testing: ServerExport1-groups-E3--$i running in a loop of 10.

ENG-18575: track unique rows exported and don't exit until all received

---

src/frontend/org/voltdb/importclient/kafka10/KafkaConsumerRunner.java

When handling exceptions while retrieving offsets from kafka handle them
similar to the poll and ignore wakeup exceptions. Also if shutting down do not
log exceptions at warning log them at info instead.

ENG-18668: Do not log error for wakeup exception during shutdown

---

src/frontend/org/voltdb/utils/SQLCommand.java

SQLCommand.java was failing in licensecheck because of a line containing trailing spaces.
(Looks like result of previous manual edit?)

strip trailing spaces

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/ProcedureRunnerNT.java
src/frontend/org/voltdb/VoltZK.java

NT procedure runner gets a list of live hosts and send requests to their client interfaces for callAllNodeNTProcedure.  If a request is sent to the rejoining host, the caller won't get any response from the rejoining host. The scenario occurred in rejoining and UAC since  they are mutually exclusive.  UAC sends @VerifyCatalogAndWriteJar to all the live hosts which includes the rejoining host.  UAC will eventually timed out. Rejoining may also fail because it is unable to get action blocker.

ENG-18785  Prevent NT callAllNodeNTProcedure from being blocked by rejoining host

---

CMakeLists.txt

Because of a race between installing openssl libraries and installing
openssl doc, the openssl build sometimes failes. Since we do not need to
install the openssl doc only install the libraries.
Also, remove unnecessary declaration of make and install for external
projects.

ENG-18710: Do not install openssl man pages

---

src/frontend/org/voltdb/exportclient/SocketExporter.java
tests/frontend/org/voltdb/export/SocketExportTestServer.java

- Removed callables in SocketExporter that were there just to connect to socket. We were waiting on the future in processRow thread and also erroring out if we cannot connect to any of the sockets. Changed the connect to happen in the same thread and get the same behaviour.
- New configuration property on SocketExporter, which will determine if a sync/ack is required from the receiver (ServerSocket) on a block completion. If this property is set, new sync block message will be sent to the receiver on block completion. The receiver must send a single byte ack in response to this message. This will prevent SocketExporter from acking a block before the receiver receives it.

ENG-18823:

---

src/frontend/org/voltdb/task/Action.java
src/frontend/org/voltdb/task/CompositeActionScheduler.java
src/frontend/org/voltdb/task/ScheduledAction.java
src/frontend/org/voltdb/task/SingleProcGenerator.java
src/frontend/org/voltdb/task/TaskManager.java
tests/frontend/org/voltdb/task/TestTaskManager.java
tests/frontend/org/voltdb/task/TestTasksEnd2End.java
tests/frontend/org/voltdb/tasktest/CustomTestActionGenerator.java
tests/frontend/org/voltdb/tasktest/CustomTestActionScheduler.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/OrphanedTuples.java

Improve some error messages which were not quite right or descriptive enough.
Modify factory methods to have shorter and more obvious names.
Try to stabilize TestTaskManager by not having to infer what the manager did on an update

ENG-18746 & ENG-18534: Improve error messages, method names and tests

---

src/frontend/org/voltdb/exportclient/ExportRow.java

When decoding a row validate that the column count read from the row
matches the expected column count of the scheman. If it doesn't throw a
detailed exception.

ENG-18440: Validate columnCount in row matches schema

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java

Previously, rejoining node pick up remote (latest) deployment based on the fact that zk nodes for catalogBytes already exist. (i.e. hitting NodeExistsException when it tries to sync local deployment)
Since now that zk can keep up more than one version of catalogbytes. If previous version no longer exist, the rejoining node can accidentally always pick up local (and stale) deployment.

Eng 18856:  Resolve deployment file from zk in rejoing/join case

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

New ee test added that simulates interleaved txn execution with snapshot process.
Found a bug from this test of an edge condition, fixed. Also contains some minor simplifications of the module.

Eng 18513 add eecheck test simulating mp execution

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

- Picked up latest dev-branch improvements/bug fixes related to the module
- (Finally) Fixed the special edge case of single non-full chunk when snapshot started, AND when tuple deletes occur in the snapshot process, to ensure that snapshot view is intact. (Involves quite some logic/arbitrage, and some meta-programming crap to get the wheels running!)
- No work on the new API for batch removal operation done. Will continue on this branch; but plan to merge current changes to master.

Table tuple allocator batch removal api

---

src/frontend/org/voltdb/exportclient/kafka/KafkaExportClient.java

- At the end of a block, flush to make sure that Kafka executes all the queued sends and waits for acks. We can get rid of ack timeout with this.
- On sourceNoLongerAdvertised, don't call producer.close without timeout because that will block the catalog update txn thread. Call close with timeout of 0, which will return immediately and mark any pending sends as failed.

ENG-18652:

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java

With ssm initialization being async the members passed into the
initialize method could become stale by the time m_knownMembers is set.
This can happen when a member update comes in after the initialization
is started and the updated is scheduled between two of the async steps
of the state machine initialization.

SSM: Only initialize members if not set

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
src/frontend/org/voltdb/VoltDB.java

Use listenable callbacks to guarantee that exceptions are always handled and
not ignored. Also simplify exception handling so that redundant exception
blocks are merged into one and all fatal exceptions are handled as high up the
stack as possible.

SSM: Simplify and guarantee exceptions handled

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
tests/frontend/org/voltcore/zk/TestStateMachine.java

Once a state change has been proposed all hosts must complete that state
change even if the host which proposed that state change goes down. There
was a hole previously that if a host died immediately after proposing a
state change another host could grab the distributed lock because it had
not processed the participant change. If there is an outstanding
participant change defer lock acquisition until that change has been
handled.

ENG-18740: Resolve current proposal

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java

As the code was looping through export stats, it would extend the time to wait if last_pending != pending.  The trouble is it was setting last pending on each row when it should have been
tracking each stream.
Since the client inserts data and otherwise doesn't validate the data, removed the code entirely.  Other clients validate the data

ENG-18941: remove AsyncExportClient export drain monitoring code

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
src/frontend/org/voltdb/utils/Mutex.java
tests/frontend/org/voltdb/utils/TestMutex.java

Simplify the locking in StateMachineInstance so that the method which
locks also unlocks. If a method being called needs to perform work
outside of the lock it returns a callback which will be invoked after
the lock is released. This implemenation guarantees that a method will
never return with the lock still locked. It does make the unlock work a
little harder to manage but it should be easier over all.

ENG-18833: Use try with resource to guarantee unlock

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java
src/frontend/org/voltdb/export/ExportCoordinator.java
tests/frontend/org/voltcore/zk/StateMachineSnipits.java
tests/frontend/org/voltcore/zk/TestStateMachine.java

While the zoo keeper watchers do check if the state machine is shutdown
before scheduling any work to be done the work does not check if the
state machine has been shutdown since then. This is problematic if there
is a lot of work executing on the SSM thread since that means there
could be significant lag between when a watcher is triggered and when
the actual work is performed. Make sure each runnable or callable checks
the state of the state machine before performing any work.
Also change the state from a boolena to an enum so that reset can detect
when the state machine has been shutdown and not perform a reset.

ENG-18944: Check if state machine is shutdown

---

src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PBDSegmentReader.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

We were not updating read offset we marked a segment as fully read and discarded. This was OK when the segment is not the last one. When the segment is the last one, we may write and read additional buffers, which means the readOffset has to be set correctly as well.

ENG-19025: Update the readOffset as well when we mark all as read.

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Bug on pointer arithmetic when there are whole chunk removed in batch removal, and the following chunk (after whole-chunk-removal) happens to be not full.

Fixed bad batch-removal on multiple sites

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Made `HookedIteratorType` nested template class aware of allocator state when `freeze()` is called. This guarantees that the iterator (types) will never return `NULL` value, and skip any newly allocated values after `freeze()`.
Other types of snapshot iterator (templates) remain unaware of the status: `iterator_type`, `iterator_cb_type` and `time_traveling_iterator_type`. But that is fine, since `iterator_type` should only serve for txn view, and the other two are simply building blocks for the `hooked_iterator_type`.
And some other simplifications.
Now changed `freeze()` method to be template method that creates a shared pointer of snapshot rw iterator.

Snapshot iterator aware hook

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Added `chunkSize()` method to CompactingChunks, that returns how many bytes of memory each chunk contains available for allocation.
Removed caching mechanism.

Allocator add chunk size

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
src/frontend/org/voltdb/iv2/SpInitiator.java

Using a listener for partition leadership changes. The amount of code that is identical between E2 and E3 Export Manager implementations calls for a base class. But that is beyond the scope of this bug fix and a follow-up ticket will be opened.

ENG-19044: refactor handling partition leadership changes in export

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp

So that the call back function sees the world as having all compaction done
(but head is not adjusted)

Moved memcpy before batch-remove callback execution

---

tests/test_apps/txnid-selfcheck2/run.sh

new java jar files, besides checking the current directory (which it already does), also check certain other directories, based on the VOLTDB_BASE environment variable; and if found, then copy them from there.

Modified (txnid2's) run.sh's function bigjars to, before generating

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Light weight removing from head (for schema update), or from tail (for insertion undo).
Testing finished for head removal; not yet started for tail removal. Use at your own risk.
Read the document for caveat on head removal.

APIs for insertion undo/schema update (a.k.a. light weight removals)

---

src/ee/CMakeLists.txt
src/ee/common/serializeio.h
src/ee/kipling/GroupStore.cpp
src/ee/kipling/GroupStore.h
tests/ee/CMakeLists.txt
tests/ee/kipling/GroupStoreTest.cpp

Add a group coordinator into the EE layer which is the interface to
managing the data in the kipling system tables. This supports four
opperations: storeGroup, deleteGroup, fetchGroups, commitOffsets and fetchOffsets.

ENG-18989, ENG-18991 & ENG-18995: Add group and offset operations

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Finished no-compaction-removal from both ends.
**Do not merge! The eecheck is failing on U14.04 and OSX10.6 (but succeeds on U18.4, U16.4 and C7)**

ENG-18967-insert-undo-API

---

src/ee/common/serializeio.h
src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/kipling/GroupStore.cpp
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/KiplingSystemTableConnection.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/SystemProcedureExecutionContext.java
src/frontend/org/voltdb/exceptions/InvalidMessageException.java
src/frontend/org/voltdb/exceptions/SerializableException.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/utils/VoltTableUtil.java

Add the kipling GroupStore to the execution engine and a getter so
it can be accessed by the different interfaces.
Add a connector to the site which can be used to interact with the
kipling system tests.

ENG-18993 & ENG-18994: Add kipling group store to engine and system procedures

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/CMakeLists.txt
tests/ee/storage/TableTupleAllocatorTest.cpp

1. Lifted implementation of light-weight delete operations from `HookedCompactingChunks<...>` to `CompactingChunks`, now that these two operations don't need to take extra care about snapshot status.
2. Minor: moved `HistoryRetainTrait` batch size constant off and combined into enum def
3. Bug fix: ptr aliasing check done wrong.
4. Added additional test on single-tuple -> remove -> re-insert -> using iterator with `until` API.

ENG-19088 Fix eecheck on all os

---

src/frontend/org/voltdb/utils/generate_logkeys.py

Dave P. pointed out that when I updated the license copyright dates (see
ENG-18751-copyright-script & -update), I also added a final newline to
<voltdb>/src/frontend/org/voltdb/utils/LogKeys.java (and a bunch of
other files, it turns out); this is because my copyright script uses
sed, and I ran it on a Mac (same script on Linux does not add newlines).
The trouble for this particular file is that it gets regenerated each
time you do a build (pro, at least), without a final newline, so git
(e.g. 'git status') thinks that you've altered it and need to check it
in. However, rather than revert LogKeys.java to its previous
no-final-newline state, I decided to modify
<voltdb>/src/frontend/org/voltdb/utils/generate_logkeys.py, which
generates it, to include a final newline, since every Java (or …

ENG-18751-resolve-newline:

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/snmp/SnmpTrapSender.java

The implementation of the snmp methods already catches exceptions, so having the caller do it is redundant.

ENG-19061 -- remove redundant try/catch from snmp calls

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp

Getting ready to drop-in replace other `map` implementations, and other `chunkId()` types.

Prepare to use other types/impls of maps

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

On an empty table at iterator creation time. The lazy behavior defers setting internal state until next `refresh()` call

Fixed construction of elastic_iterator

---

src/frontend/org/voltcore/logging/VoltLogger.java

Copy from 9..3; need for snmp.

add 'log(level, message, throwable)' to 7.7

---

src/frontend/org/voltcore/logging/VoltLogger.java

Copy from 9.3 a general logging method needed for SNMP trap logging.

Eng 19061 19115 backport snmp changes to v8.4

---

src/ee/common/NValue.cpp
src/ee/storage/TableCatalogDelegate.cpp
tests/ee/storage/tabletuple_export_test.cpp
third_party/cpp/crc/crc32c.cc
third_party/cpp/murmur3/MurmurHash3.cpp

Changes to make it possible to compile with gcc 7.x.
Mostly switch-statement fall-through comments.
One snprintf buffer size increase.
All copied from 9.3.

source changes for gcc 7 compatibility

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/CMakeLists.txt
tests/ee/storage/TableTupleAllocatorTest.cpp

Fixed `eecheck` failure in VoltMini, in the progress of fixing `eecheck` memcheck failures; and enabled memcheck on the table tuple allocator. (And a few more changes to help future adoption to different set/map implementations).

Memcheck allocator

---

tools/kit_tools/build_kits.py

Some tweaks to the kit builds.
1. Stop making the "Pro" kit. This saves space more than time.
2. Speed up cloning: On OSX only clone repo.  Do shallow clone of exact branch, if possible
3. On OSX only build ee, not full community distro

Eng 18234 - Speed up the final kit builds

---

src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/StreamBlock.java
src/frontend/org/voltdb/export/StreamBlockQueue.java
src/frontend/org/voltdb/exportclient/ExportRow.java
src/frontend/org/voltdb/exportclient/ExportRowSchema.java
src/frontend/org/voltdb/exportclient/PersistedMetadata.java
src/frontend/org/voltdb/exportclient/PersistedMetadataSerializer.java
tests/frontend/org/voltdb/export/TestStreamBlockQueue.java

Add PersistedMetadata as the extra header which is stored for export. This allows cleanly adding more metadata to the header but not making it part of ExportRowSchema.
Cleanup:
ExportRow: Make all public fields final
ExportRowSchema:
* Remove unnecessary implementation of DeferredSerializer.
* Fix serialization of strings so that length of bytes and not length of chars is used.

ENG-18982: Add PersistedMetadata

---

src/frontend/org/voltdb/SystemProcedureCatalog.java

Readonly tranasacations do not modify any data and durability is only
for transactions which modify data. It is impossible to have a
readonly transaction which requires durability so make them mutually
exclusive.

SystemProcedureCatalog: Readonly transactions cannot be durable

---

src/ee/common/SynchronizedThreadLock.cpp
src/ee/common/SynchronizedThreadLock.h
src/ee/common/UndoQuantumReleaseInterest.h
src/ee/storage/streamedtable.h

Replicated deletes require coordination across sites. Use CountdownLatch in the new finalizeDelete() path.

ENG-18744:

---

tests/test_apps/aggbench/run.sh
tests/test_apps/csvbenchmark/run.sh
tests/test_apps/kvbenchmark/run.sh
tests/test_apps/matviewbenchmark/run.sh
tests/test_apps/measure-overhead/run.sh
tests/test_apps/oneshotkv/run.sh
tests/test_apps/overhead/run.sh
tests/test_apps/scans/run.sh
tests/test_apps/schemachange/run.sh
tests/test_apps/txnid-selfcheck/run.sh
tests/test_apps/voter-selfcheck/ddl.sql
tests/test_apps/voter-selfcheck/deployment-secure.xml
tests/test_apps/voter-selfcheck/run.sh
tests/test_apps/ycsb-zipfian/run.sh

Remove legacycompile from test_apps run.sh:
Mostly a "rebase" of ENG-17214-app-legacycompile3 onto a recent (2/19)
version of master. On the 'voltdb' (community) side, modified run.sh
files, replacing the srccompile & catalog functions (and any calls to them) with jars &
jars-if-needed, and updating server & help functions accordingly (&
other minor changes, as needed), for the following 'test_apps', which
previously used the long-deprecated 'voltdb legacycompile' (in the
catalog function): aggbench, csvbenchmark, kvbenchmark,
matviewbenchmark, measure-overhead, oneshotkv, overhead, scans,
schemachange, voter-selfcheck (also needed a tweak in
deployment-secure.xml), and ycsb-zipfian.
Also added, to voter-selfcheck/ddl.sql, a 'LOAD CLASSES
voter.jar;' line, in order to avoid 'dbscript …

Eng 17214 app legacycompile4

---

src/frontend/org/voltdb/elastic/BalancePartitionsListener.java
src/frontend/org/voltdb/elastic/ElasticService.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java

Create a new interface to be able to listen to the balance partition operations. Once a listener is registered it will be notified of all balance partition transactions and tuples which are moved.

ENG-19132: Create BalancePartitionsListener interface

---

src/frontend/org/voltdb/plannerv2/rel/physical/VoltPhysicalSerialAggregate.java
src/frontend/org/voltdb/plannerv2/rules/PlannerRules.java
src/frontend/org/voltdb/plannerv2/rules/physical/VoltPAggregateRule.java
src/frontend/org/voltdb/plannerv2/rules/physical/VoltPHashToSerialAggregateRule.java
tests/frontend/org/voltdb/plannerv2/TestPhysicalAggregate.java

Convert a Hash Aggregate to a Serial one if there is an index which collation matches a set of GROUP BY columns if it covers all GROUP BY columns starting from collations index 0 without gaps.
Given a table T with indexes (A, B),  (A, B, C), (A, C, B) and (C, A, B) and a query
select max(B), a, b from T group by b ,a;
The first index (A,B) would provide a right ordering for the SerialAggregate -
GROUP BY columns (B,A) match the all index columns
The second index (A, B, C) also works because ORDER BY columns again match the first two index columns
The (A, C, B) index won't because the GROUP BY columns B and A  match the first and the third index columns
The (C, A, B) index is also in-eligible because the first index column is not part of the CROUP BY columns.

Calcite. Hash Aggregate to Serial Aggregate optimization

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

- Added `clear()` to the allocator which, depending on the frozen state, will get to the fastest route to clear out all contents from txn view
- Updates to batch removal API: removed function that returns a vector of pointers; and added a cb arg to `remove_force()`, which gets called *after* all memory movements
- Found and fixed a couple of NPE bugs

Add clear api to allocator

---

build.xml
tests/sqlcoverage/SQLCoverageReport.py
tests/sqlcoverage/normalizer/normalizer.py
tests/sqlcoverage/normalizer/not-a-normalizer.py
tests/sqlcoverage/normalizer/nulls-lowest-normalizer.py
tests/sqlcoverage/sql_coverage_test.py

Added new SqlCoverage argument '--maxdetailfiles' (default value 10),
and pass it down to print_section & generate_detail (in
SQLCoverageReport.py), where it is used to limit the number of detail
files (& corresponding reproducer files) created, for each category of
failure (e.g. mismatches vs crashes vs various exception types), for
each test suite. Also, updated generate_html_reports (also in
SQLCoverageReport.py), to better handle 'Connection broken' errors,
which are now considered crashes (not mismatches), and 'timeout:
procedure call took longer than 5 seconds' errors, which should no
longer cause all subsequent results to get out of sync. And removed the
ignore_known_mismatches function (in sql_coverage_test.py), since that
is no longer needed (the maximum number of detail and …

ENG-19165-scv-num-files:

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Micro-optimization on the map type from chunk id to chunk list's iterator on compacting chunk only, by replacing `std::map` to `std::deque`, so that its search operation decreases from O(log(n)) to O(1).
Added a switch to enable this micro-optimization (disabled by default).

Micro optimization of chunklist search by chunk id

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

to help debugging system tests.
Added a new method that returns the information related to a particular memory address and the allocator; and a bunch of `VOLT_TRACE` statements that prints all write-op to the terminal.
Tune which information you need, by changing the log level (`VOLT_DEBUG`), and/or project build option (`-DVOLT_LOG_LEVEL`).
*(And, accidentally, found & fixed a bug)*

Add debug info for allocator writes

---

build.xml
src/frontend/org/voltdb/task/DurationIntervalGenerator.java
src/frontend/org/voltdb/task/SingleProcGenerator.java
src/frontend/org/voltdb/task/TaskHelper.java
src/frontend/org/voltdb/task/TaskHelperImpl.java
src/frontend/org/voltdb/task/TaskManager.java
src/frontend/org/voltdb/utils/CompoundErrors.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/OrphanedTuples.java

TaskValidationErrors is part of the public API for tasks and needs to be
renamed before tasks comes out of beta.

CompoundErrors: Backport rename of error collector

---

lib/python/voltcli/voltdb.d/init.py
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/ServerThread.java
src/frontend/org/voltdb/common/Constants.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/utils/MiscUtils.java
tests/frontend/org/voltdb/TestInitStartAction.java

1. add a --license argument to the voltdb init command. The specified license file is copied into the database root directory.
2. Deprecate the use of --license on the voltdb start command.(For v10.0 release?)
3. Add the database root directory as the first location searched for the license at startup (but continue to look in the existing list of directories: working directory, home directory, and voltdb software root).
Unit tests in https://github.com/VoltDB/pro/pull/3043

ENG 19130 use init --license or -l to stage license file before database starts

---

src/frontend/org/voltdb/iv2/RepairLog.java
src/frontend/org/voltdb/messaging/CompleteTransactionMessage.java

'I' = InitiateTaskMessage,
'F' = FragmentTaskMessage,
'C' = CompleteTransactionMessage,
'C(I)' = The regular CompleteTransactionMessage, no restart or rollback,
'C(R)' = The rollback CompleteTransactionMessage, send during MP repair,
'D' = DummyTransactionMessage
'U' = Unknown
Change-Id: I0023fb9ee9d8cfe4e238e522625ee5cc6efd3719

Add message type in repair log dump.

---

src/frontend/org/voltdb/DiskResourceChecker.java

Don't print the log message for crossing the limit, when it's only crossing the snmp alert level.

ENG-18544 - log message correction for disk usage alert snmp threshold

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Fixed allocator finalizer behavior, and verified that it is both complete and called only once per allocation, at the right moment, in any combination of use cases (frozen or not, different change sequence, etc).

Allocator finalizer

---

tests/sqlcoverage/SQLCoverageReport.py
tests/sqlcoverage/SQLGenerator.py
tests/sqlcoverage/sql_coverage_test.py
tests/sqlcoverage/start_postgresql.sh
tests/sqlcoverage/template/include/advanced-select.sql
tests/sqlcoverage/template/include/grammar.sql
tests/sqlcoverage/template/int/advanced-ints.sql

Several improvements:
1. A more complete fix for ENG-15712 ('timeout: procedure call took longer than 5 seconds'): slow PostgreSQL queries will no longer cause a failure;
2. A fix for ENG-19187, part 8 ('TypeError: cannot concatenate 'str' and 'NoneType' objects') [both in SQLCoverageReport.py];
3. Added test queries with GROUP BY, somewhat like ENG-18549, but without the '?' parameter, which SqlCoverage cannot handle [in advanced-select.sql, advanced-ints.sql];
4. Improved start_postgresql.sh to give better messages, especially when errors occur;
5. In SQLCoverageReport.py, just add 2 asterisks ('**') for mismatched data, so they are easier to find in long query results;
6. Trivial changes to grammar.sql;
7. Added test queries with (& without) LIMIT in sub-queries (named SUBQ), per …

Eng 15712 scov misc

---

src/frontend/org/voltdb/iv2/MpInitiatorMailbox.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/MpRepairTask.java
src/frontend/org/voltdb/iv2/MpScheduler.java

Mixed SP leader changes that caused by host down and leader migration request can have a side effect, that is when the last SP leader change was caused by leader migration request, because an optimization we put on leader migration the MPI won't send repair message. If there was a pending
repair needs to restart, all sites will miss the repair message which can cause other severe issues like cluster hang or deadlock. This commit addresses that issue.

ENG-19147, skip sending repair message *only* if leader change is caused by leader migration request, and no pending repair was cancelled previously

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

- Added a multi-threaded EE test with well coordinated producer-consumer model to simulate possible race condition;
- Fixed a multi-thread bug on chunk boundary under some (very) corner case
- Added a write barrier (equivalent) to snapshot iterator, to read only when the whole allocator is done with **any** writing. Not sure if this would cure the failing system test; but since I don't have a perfect reproducer, this is the best I could come up with now.

Eng 19264 add allocator eecheck to simulate snapshot duplicate

---

src/frontend/org/voltdb/Inits.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/export/TestExportBaseSocketExport.java
tests/frontend/org/voltdb/export/TestExportGeneration.java
tests/frontend/org/voltdb/utils/TestCSVLoader.java

RealVoltDB: Remove unnecessary null checks
Export: Use a map to represent partition to site ID mapping
CatalogUtil: Return a map of streams rather than a set
TestExportBaseSocketExport: synchronize while iterating over clients
TestCSVLoader: Move test from sub class

ENG-18628: Export and test cleanup

---

lib/python/voltcli/voltadmin.d/resize.py
src/frontend/org/voltdb/DiskResourceChecker.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/settings/NodeSettings.java
src/frontend/org/voltdb/sysprocs/SystemInformation.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java

To easily separate the topic data from the export data topics are going to be put into a separate directory. This means that the check that export overflow is empty during restore can still behave the same and the topics will be left alone.
Related https://github.com/VoltDB/pro/pull/3073

ENG-18628: Add a seperate path entry for topic data

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Fixed the bug on snapshot iterator chunk boundary calculation, when current chunk is on the left frozen boundary, causing snapshot to read extra false values.

Eng 19180 snapshot reads duplicate values

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java
tests/frontend/org/voltdb/LocalClustersTestBase.java
tests/frontend/org/voltdb/TestExportOverflow.java

Topic data is kept after a restore so it needs to be treated the same way an export stream is treated during recovery.
ExecutionEngine.exportAction was always called with true as the first argument. That means that it was only used to set the export stream positions. Remove the boolean argument and rename the method to setExportStreamPositions. Also, remove any extra code for old use including a return value.
Related https://github.com/VoltDB/pro/pull/3075

Eng 18630 topic restore

---

lib/python/voltcli/voltadmin.d/opshutdown.py
lib/python/voltcli/voltadmin.d/opstop.py
src/frontend/org/voltdb/CommandLog.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/sysprocs/OpShutdown.java
src/frontend/org/voltdb/sysprocs/OpShutdownWait.java
src/frontend/org/voltdb/sysprocs/OpStopNode.java

GracefulShutdown, GracefulShutdownWait, GracefulStopNode now have names starting with 'Op' rather that 'Graceful'.
This is in response to a suggestion from @ajgent to adopt common prefixing.  Not everything we need to add for k8s operator support will necessarily be graceful.

Rename GracefulXyz sysprocs to OpXyz

---

src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/utils/SnapshotComparer.java

Use --ignoreOrder for ignore all row order checking
Use -ignoreChunkOrder for only ignore row order with incorresponding chunk, but still assume rows within same chunk are same.
e.g.
| => ~/workspace/voltdb/tools/snapshotcomparer.sh --self --nonce MANUAL1581622336043 --dirs ./host0,./host1
Finished comparing table AREA_CODE_STATE.
Finished comparing table VOTES.
Finished comparing table V_VOTES_BY_PHONE_NUMBER.
Diffs between file ./host0/MANUAL1581622336043-CONTESTANTS.vpt and file ./host1/MANUAL1581622336043-CONTESTANTS.vpt
1,Edwina Burnam
2,Tabatha Gehling
3,Kelly Clauss
-4,Jessie Alloway
+4,Jessie Eichman
5,Alana Bregman
-6,Jessie Eichman
+6,Jessie Alloway
WARN: Replicated Table CONTESTANTS is inconsistent between host0 with host1 on partition 16383
Finished comparing table …

ENG-19314: Additional ignoreOrder option for snapshot consitent checking

---

src/frontend/org/voltdb/iv2/MpInitiatorMailbox.java
src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
src/frontend/org/voltdb/iv2/RepairAlgo.java
src/frontend/org/voltdb/iv2/SpPromoteAlgo.java

The previous attempt to fix it isn't complete, partly because the m_algo is always not null. @MigratePartitionLeader sends repair even if it didn't cancel the previous repair.

ENG-19147, send repair only in necessary

---

src/frontend/org/voltdb/iv2/MpPromoteAlgo.java
tests/frontend/org/voltdb/iv2/TestMpPromoteAlgo.java

we used to assume repairing with only the latest CompleteTransactionMessage is enough to clear transaction queue and scoreboard of SP, but this assumption no longer holds when we introduce partition leader migration. The replica of the away leader may fall behind to other partitions, before it catches up a rollback completion message of newer transaction can eat up prior CompleteTransactionMessage if a MP repair happened during this window. This issue could lead to orphaned entry of scoreboard, which freezes the database.
Change-Id: I41fb00c57c22cf835980a5d2f7fbfd04e58d96fe

ENG-19206, repair all SPs with every CompleteTransactionMessage the MPI collects

---

tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/TruncateTableLoader.java
tests/test_apps/txnid-selfcheck2/src/txnIdSelfCheck/TxnId2Utils.java

Consider the error message that mastership changed and the transaction may or may not been appliead as ndeterminate.
TruncateTableLoader: Update some logic to be simpler or more correct

ENG-19335: Add mastership change message as indeterminate

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Removed empty value from `position_type` class, which was used to represent out-of-boundary state. This change entailed changing quite a few member variable types to use optional, and using them are now (forced to be) more explicit. Noticed from ee-test slight slow down due to these changes; but also noticed/fixed a bug hidden otherwise.
I intend to leave this PR from branch `ENG-18744` momentarily, so that @zeemanhe could test the branch with two earlier changes (but without this one), and verify that those 2 changes are innocent. After that, feel free to merge this change into ENG-18744.

Remove empty value from position_type class

---

src/frontend/org/voltdb/DefaultSnapshotDataTarget.java

Each table (and materialized view) has a snapshot data target. For all data targets combined together they can write up to 256M data between sync. Sync thread flushes dirty page to disk if any data target has more than 4MB data in page cache.
What will happen if snapshotting a large number of tables in the same time? 
One possibility is that every data target could have less than 4MB data in page cache, but in total all data targets write more than 256M data to file. Some targets will sleep because they fail to acquire the write permit, they will never wake up!

ENG-19277, force sync_file_range() if available snapshot write permits running low.

---

src/ee/storage/persistenttable.cpp
src/ee/storage/streamedtable.h
tests/ee/storage/persistenttable_test.cpp

When recreating a table because of a truncate if the table has a shadow stream the ExportTupleStream in the StreamedTable needs to be moved from the original StreamedTable to the new one. If the transaction is undone the stream needs to be moved back.

ENG-19355: Move ExportTupleStream to new StreamedTable

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/persistenttable.cpp
tests/ee/storage/persistenttable_test.cpp

When a table with a shadow stream (migrate or Change-Data-Capture) is truncated, the shadow stream of the new (empty) table is not updated correctly. Tosting did not find this previously because small tables are not replaced with new tables whereas now a truncate always creates a new empty table.

ENG-19308:

---

src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
src/ee/storage/persistenttable.cpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Use explicit class def for optional pair of call backs.
Also optimized member storage for this optional pair in the hook class.
See also #7019 for the version based on implicit typedef of _truely_ optional pair of call backs.

Add deepcopier callback 2

---

src/frontend/org/voltcore/utils/Bits.java
src/frontend/org/voltdb/DefaultSnapshotDataTarget.java

Sync for at least single page size (4K, thus more frequently) if bytes allowed to
write is running low. 
Also fixed a miscalculation of stable page write boundary in Bits.java. When a dirty page is written to disk, write() to the same dirty page is blocked until flushing to disk is done. This is called "Stable Page Write". In sync_file_range() calls we avoid syncing the appending page, but the miscalculation of write boundary causes sync thread could only sync to the offset which is 2 pages away from the current write position.
The correct behavior should be:    
```
When current write position is in 
(the initial syncStart is 0)
* 0-4095 -> not allowed to flush, avoid stable page write.
* 4096-8191 -> flush [syncStart, 4095], set next syncStart to 4096
* 8192-12288 -> flush [syncStart, …
```

ENG-19383, adjust the minimum sync threshold for snapshot buffers.

---

src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/tablefactory.cpp
tests/ee/storage/persistenttable_test.cpp

A CppUnit test was verifying the transfer of a export stream wrapper to a newly created table after a truncate. However, the check was performed after the commit (when the table being checked) was deleted.

ENG-19377:

---

src/ee/common/ExecuteWithMpMemory.cpp
src/ee/common/ExecuteWithMpMemory.h
src/ee/common/SynchronizedThreadLock.h
src/ee/common/UndoLog.cpp
src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/persistenttable.h

Since the snapshot iterator may deallocate tuples or chunks, the COW needs to be in the correct Memory Context.

ENG-19393:

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
src/ee/storage/persistenttable.cpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Previous behavior:
----
- When in snapshot, all of the addresses requested to be removed are copied into the hook memory, at `remove_add` time, disregarding whether each address was to be removed, or compacted.
- When in `thaw()`, the finalizer is then called on all hook memory, thereby in effect finalizing all frozen-only regions. Note that finalize is always called at `thaw` time.
- Then again, at `thaw()` time, all chunks in frozen-only region are finalized, in `CompactingStorageTrait::thaw()`.
- Of course, optimization considering snapshot iterator position is taken into account, skipping copying certain memory into hook.
- This creates a problem: for moved addresses, the finalizer is called at `thaw()` time for the address that gets moved-over, but they could still be active in the …

Fixed finalizer behavior

---

src/frontend/org/voltdb/ActivityHelper.java
src/frontend/org/voltdb/PauseActivityStats.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/ShutdownActivityStats.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/StopActivityStats.java
src/frontend/org/voltdb/export/ExportManagerInterface.java

Adds a stats class for use by kubernetes operator code. Effectively duplicates the check being made in 'voltadmin stop node' but isolates operator from details.
Most of this is cookie-cutter code similar to previous such stats additions.
Merge target is KO-integration branch!

Add stop-node stats check.

---

src/frontend/org/voltdb/utils/BinaryDequeGapWriter.java
src/frontend/org/voltdb/utils/PBDRegularSegment.java
src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

The BinaryDeque.offer API states that the container will be discarded if
an exception is thrown. This was not true if exceptions were thrown
prior to the attempt to write the entry. Update the implementation so
that this is now guaranteed.
Move the common code in PBDRegularSegment.offer into a common offer
which takes a BBContainer.

PBD: Always discard containers and use common offer

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h

Stop updates from finalizing the txn memory tuple. This also requires a small rework of the delete path.

ENG-19410:

---

src/ee/execution/VoltDBEngine.cpp

If a persistent table has a shadow stream processing of the table would
stop after the shadow stream was processed if there was no schema
change. When the table is a persistent table indexes and views still
need to be processed.

ENG-19411: Continue processing persistent tables

---

tests/sqlgrammar/run.sh
tests/test-tools.sh

Multiple improvements & minor tweaks to grammar-gen scripts run.sh & test-tools.sh:
1. Added code to not run certain functions if previous ones failed (e.g. if 'build[-pro]' fails, 'server[-pro]' is skipped; if 'server[-pro]' fails (or is skipped), 'tests-only' is skipped) - which is ENG-19338;
2. Print a warning if the number of minutes (for the tests to run) was unspecified and used the default value of '1' (Lukai's request);
3. Added the tt-set-tt-build-args function (& tweaked 'tt-build[-pro]'), to interpret the '--debug', '--pool', and '--release' abbreviations (this used to happen in the Jenkins script, but someone "simplified" it, and anyway it belongs here);
4. Changed the 'prepare[-pro]' functions (and therefore the 'all[-pro]' functions, which call them) to not call …

Eng 19338 gram hang misc

---

tests/test_apps/measure-overhead/ddl.sql

Added, to tests/test_apps/FOO/ddl.sql, a 'LOAD CLASSES FOO.jar;' line,
where this time FOO is 'measure-overhead' (having previously done this
for overhead, oneshotkv, and scans, for this ticket; and for
voter[-selfcheck] earlier).

ENG-19174-ap-legcy-broke-perf2:

---

src/frontend/org/voltdb/iv2/Scoreboard.java
src/frontend/org/voltdb/iv2/TransactionTaskQueue.java

[ backport 52b615def6d5589da432e922e8de047a912c1ef3 ]
The method TransactionTaskQueue.coordinatedTaskQueueOffer is suppose to
complete the task for the passed in task and any other fully completed tasks
behind it. However that wouldn't happen.
RelativeSiteOffset.releaseStashedCompleteTxns would return true if the next
task in all the Scoreboards was the same. That result would then be assigned to
the done variable and cause nothing else to be processed.
Instead of returning a boolean keep releasing completed transactions until they
are all gone or one is encountered which is not completed on all sites.

ENG-16168: Release all completely completed tasks

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java

Catalog update is an MP procedure which occurs concurrently on all hosts. The order of operations is all sites call quiesce and then RealVoltDB.updateCatalog(). The first site on each host to call updateCatalog() performs the actual work. This can be an issue because the other sites on the host might still be performing the quiesce. When this happens the schema can be updated in export and DR before the buffers with the data from the previous schema are processed.
This results in the new schema being attached to the old rows.

ENG-19430: Guarantee that catalog update happens after quiesce

---

src/frontend/org/voltdb/HTTPClientInterface.java

Only @Shutdown and @OpPseudoShutdown can bring the database into SHUTTINGDOWN state, this is also irreversible, it's reasonable to disallow http request in such condition.

Ko 135 reject http request while database is shutting down

---

src/frontend/org/voltcore/messaging/Subconnection.java
src/frontend/org/voltdb/InvocationDispatcher.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/iv2/Cartographer.java
tests/frontend/org/voltdb/MockVoltDB.java

Called by orchestration platform, @OpPseudoStopNode does the same checks but
doesn't kill node.
Pro side: https://github.com/VoltDB/pro/pull/3109

KO-32, @OpPseudoStopNode, simplified version of @StopNode.

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java

chance of retention threads getting "is closed" error.

ENG-19306: Closing PBD should stop retention enforcement to minimize the

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

When closing a reader cursor also close any segment readers for that cursor.
When skipping past a segment if it doesn't have any oustanding entries close the reader for that segment.

ENG-19401: Close read cursors

---

src/frontend/org/voltdb/operator/StatusListener.java

Prevent occasional error from fast exit/restart (the usual TCP TIME_WAIT thing). I've seen this once or twice in manual testing.
(Not used for 'find free port' case since it is obviously not consistent with that)
Obviously, requires the admin to have correctly specified port numbers in the first case.

For a specified status listener port, set reuseaddr.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/BinaryLogSinkWrapper.h
src/ee/storage/CompatibleBinaryLogSink.cpp
src/ee/storage/CompatibleBinaryLogSink.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
tests/ee/execution/add_drop_table.cpp
tests/ee/execution/engine_test.cpp
tests/ee/indexes/index_test.cpp
tests/ee/storage/CompactionTest.cpp
tests/ee/storage/CopyOnWriteTest.cpp
tests/ee/storage/PersistentTableMemStatsTest.cpp
tests/ee/storage/constraint_test.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/frontend/org/voltdb/TestTheHashinator.java
tests/frontend/org/voltdb/TestTwoSitePlans.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

Provide a Java Property: DR_IGNORE_CONFLICTS to ignore all conflicts generated by XDCR Binary logs and preserve the existing row state. Note that for transactions that update multiple rows, the consequence is that parts of the transaction will be executed while changes with conflicts will be skipped.

ENG-19469:

---

src/frontend/org/voltdb/SnapshotDaemon.java
src/frontend/org/voltdb/SnapshotStatus.java
src/frontend/org/voltdb/SnapshotStatusSummary.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/sysprocs/SnapshotRegistry.java

Comparing to stats API SNAPSHOTSTATUS, this API is friendly to outside observers who monitor the completion of snapshot. Because SnapshotStatus returns per-host-per-table information. Monitoring snapshot completion, the outside watcher needs to know 
1) the expected number of node,
2) the number of table.
to aggregate all rows with the same nonce.
SNAPSHOTSTATUSSUMMARY returns one row per snapshot, the result is aggregated from all nodes.
Example output:
```
exec @Statistics SNAPSHOTSTATUSSUMMARY 0;
NONCE                TXNID             START_TIME     END_TIME       DURATION  RESULT   TYPE
-------------------- ----------------- -------------- -------------- --------- -------- -----
MANUAL1588593223049   3619631923314687  1588593223113  1588593223383         0 SUCCESS  AUTO …
```

KO-137, user-friendly statistics API to monitor snapshot completion.

---

src/frontend/org/voltdb/compiler/DDLCompiler.java
src/frontend/org/voltdb/exportclient/PersistedMetadata.java
src/frontend/org/voltdb/utils/CatalogUtil.java

Use a common utility for splitting a CSV which trims each entry.
Throw an error if a blank value is supplied for a column or role.

ENG-19339: Use common utility for parsing csv DDL

---

src/frontend/org/voltcore/utils/CoreUtils.java
src/frontend/org/voltdb/sysprocs/Shutdown.java

1. Fix up silly stars printing. It's always annoyed me that the stars had a different width to the text!
2. Define constant for shutdown timeout (easy to change). I'm currently messing around in shutdown so this is convenient. 
3. Distinguish timeout shutdown from intended shutdown path.
4. Sites not executing RealVoltDB.shutdown() should wait forever, not just hope 10 secs is enough.

ongoing work.

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteSnapshotConnection.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java

Add a new boolean to getSnapshotSchema which forces the ee to retrieve the schame from the current catalog instead of from the snapshot schemas.
This is needed by elastic which needs to copy data from tables which are added ore modified during balance partitions.

ENG-19479: Add a way to force retrieving schema from catalog

---

src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/utils/CatalogUtil.java

CatalogUtil.shallowClusterAndPathsClone is supposed to copy almost all of the fields for the original deployment instance but most of the new fields were not added. Add the missing fields and organize the copy order to match the declaration in DeploymentFileSchema.xsd for easier reading

ENG-19397: Copy all deployment fields

---

src/ee/common/types.h
src/ee/execution/VoltDBEngine.cpp
src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/CopyOnWriteContext.h
src/ee/storage/TableStreamer.cpp
src/ee/storage/TableStreamerContext.h
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/TableStreamer.java

When serialization error occurs, snapshot site processor will take  the current table out for more rounds of streaming even though there may be more tuples to be streamed. The snapshot  for the table is not done in engine but is marked as done  in snapshot site processor, which allows next snapshot to be started on snapshot site processor but not in the engine. Snapshot can not be performed again.

ENG-19442 allow snapshot stream to the end when serialization errors show up

---

src/ee/common/types.h
src/ee/execution/VoltDBEngine.cpp
src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/CopyOnWriteContext.h
src/ee/storage/TableStreamer.cpp
src/ee/storage/TableStreamerContext.h
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/TableStreamer.java

When serialization error occurs, snapshot site processor will take the current table out for more rounds of streaming even though there may be more tuples to be streamed. The snapshot for the table is not done in engine but is marked as done in snapshot site processor, which allows next snapshot to be started on snapshot site processor but not in the engine. Snapshot can not be performed again.

ENG-19505 allow snapshot stream to the end when serialization errors

---

tests/test_apps/genqa/src/genqa/AsyncExportClient.java

Proc call error, adjusted so error message is put into the log but not fatal level so the test can continue.

ENG-19495: Change fatal log message on proc call error to info so test can complete.

---

src/frontend/org/voltdb/AuthSystem.java
src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/client/ConnectionUtil.java

[ backport 9a553c86456451d4c2fe0be24e10b0c538f5afb8 ]
When a connection is encrypted the only way to send messages through that
connection is by using the MessageChannel. Kerberos authentication methods were
all using the raw SocketChannel and were sending unencrypted messages on an
encrypted connection. Always use the MessagingChannel to send messages over a
connection.

ENG-19515: Backport: Use MessagingChannel for kerberos auth

---

src/frontend/org/voltdb/operator/StatusListener.java

If an interface is not specified in --status then the intent was to listen on any interfaces.
It turns out you need interface=null for that, not interface=empty string.  Problem showed up in k8s testing.
The getListenInterface function is used for log messages and still wants to return an empty string.

need null, not empty string, for listen on any interface

---

src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/SysProcDuplicateCounter.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/iv2/TransactionTask.java
src/frontend/org/voltdb/utils/VoltTableUtil.java

When transactions hits failure on executing fragments, a dummy response is added to its dependency.  A partition leader could receive  various responses. A successful response has   dependency tables with one schema  while  a failed  response has  dependency tables with another schema.  When a transaction tries to combine the responses, schema mismatch will be encountered, which will crash cluster.

ENG-19474 prevent cluster from crash caused heterogeneous responses  from replicas

---

src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java

UAC fragment processing assumes that staging catalog  is pending status.   If UAC is restarted after catalog staging is completed, the staged catalog in pending status won't found for command logging.  NPE will be thrown. For UAC restart, the status of the catalog staging should be reset to pending.

ENG-19489 reset catalog staging status if published upon UAC restart

---

src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java

UAC fragment processing assumes that staging catalog is pending status. If UAC is restarted after catalog staging is completed, the staged catalog in pending status won't found for command logging. NPE will be thrown. For UAC restart, the status of the catalog staging should be reset to pending.

ENG-19524 reset catalog staging status if published upon UAC restart

---

src/frontend/org/voltdb/utils/CatalogUtil.java

[ backport dc1535488b56f352cf14cb75a895f2462e1a6ffd ]
If the DR role of a cluster was ever updated to xdcr the error message which
was printed reported errors because export was misconfigured for DR. This error
message is confusing especially because export is reporting invalid dr changes.
Create a check in the dr validation method that checks if the role is xdcr the
cluster was correctly initialized for xdcr. Remove DR specific checks from
export configuration validation.

ENG-19511: Backport: Provide a clear error message when role is changed to xdcr

---

src/frontend/org/voltdb/join/BalancePartitionsStatistics.java

[ backport 7b66e37b109101b15e0a1197a69b5ac12a00666e ]
Throughput is used to calculate sleep between rebalance calls. When it
is not reset it can accumulate between runs forcing future elastic
operaitons to slow down.

ENG-19502: Backport: Reset throughput on initialization

---

src/frontend/org/voltdb/iv2/FragmentTask.java
src/frontend/org/voltdb/iv2/SysProcDuplicateCounter.java
src/frontend/org/voltdb/iv2/SysprocFragmentTask.java
src/frontend/org/voltdb/iv2/TransactionTask.java
src/frontend/org/voltdb/utils/VoltTableUtil.java

When transactions hits failure on executing fragments, a dummy response is added to its dependency. A partition leader could receive various responses. A successful response has dependency tables with one schema while a failed response has dependency tables with another schema. When a transaction tries to combine the responses, schema mismatch will be encountered, which will crash cluster.

ENG-19523 prevent cluster from crash caused heterogeneous responses from replicas

---

CMakeLists.txt
src/ee/common/NValue.hpp
src/ee/executors/OptimizedProjector.cpp
src/ee/storage/CopyOnWriteContext.cpp
src/ee/storage/ElasticIndex.h
src/ee/storage/ElasticIndexReadContext.cpp
src/ee/storage/TableCatalogDelegate.cpp
src/ee/structures/CompactingHashTable.h
src/ee/structures/CompactingMap.h
tools/VoltDBCompilation.cmake

Instead of using OS releases as the boundries for compiler options use the
major version of gcc to determine which options are appropriate for that
compiler.
A few classes defined either a copy constructor or assignment opperator but not
both. With newer versions of gcc that causes a warning. In all of those
locations the custom implementation was not necessary so it was removed to
allow the default implementations to be used.

Backport: Add support for gcc 8 and 9 and simplify version handling

---

src/frontend/org/voltdb/ClientInterface.java
src/frontend/org/voltdb/iv2/Cartographer.java

[ backport b540c8d ]
A scheduled executor catches all throwables and sets the throwable as a failure
on the associated future. If the future is discarded that means that any
throwable generated by a runnable or a callable will never be seen. Instead of
letting the executor handle the exception catch and log all exceptions caused
by migrate leader.

ENG-19504: Backport Handle null return from getHostsByPartionMasterCount

---

src/ee/execution/VoltDBEngine.cpp
src/ee/execution/VoltDBEngine.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/voltdbipc.cpp
src/ee/voltdbjni.cpp
src/frontend/org/voltdb/SiteProcedureConnection.java
src/frontend/org/voltdb/iv2/MpRoSite.java
src/frontend/org/voltdb/iv2/Site.java
src/frontend/org/voltdb/jni/ExecutionEngine.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
src/frontend/org/voltdb/jni/MockExecutionEngine.java
src/frontend/org/voltdb/rejoin/StreamSnapshotSink.java
tests/frontend/org/voltdb/jni/TestExecutionEngine.java
tests/frontend/org/voltdb/jni/TestFragmentProgressUpdate.java

[ backport 24fde9f ]
When elastic remove is running it is easy to go over a tables tuple limit. It
is possible to try and maintain under the limit by running the delete clause if
it exists but it is questionable when it should be run and if it will do the
right thing, especially since it will not be running under the documented
conditions. Also, dr already ignores the limit. The limit will be checked an
enforced on the next insert into the table.
Related https://github.com/VoltDB/pro/pull/3150

ENG-19503: Backport: Ignore tuple limit during elastic ops

---

src/frontend/org/voltdb/iv2/RejoinProducer.java
src/frontend/org/voltdb/rejoin/Iv2RejoinCoordinator.java

[ backport 7a772a3035f25a150518ae0fdb089f5deca7766e ]
On rejoin without any persistent tables the snapshot completion event was
not being processed. When the system does not have persistent tables
only skip waiting for streams from other hosts but not processing the
snapshot completion.
Update rejoin with only stream tests to confirm that the sequence id
continues to increase.

ENG-19509: Backport: On rejoin always monitor snapshot

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/exportclient/ExportRow.java

[ backport cd496ad ]
Catalog update is an MP procedure which occurs concurrently on all
hosts. The order of operations is all sites call quiesce and then
RealVoltDB.updateCatalog(). The first site on each host to call
updateCatalog() performs the actual work. This can be an issue because
the other sites on the host might still be performing the quiesce. When
this happens the schema can be updated in export and DR before the
buffers with the data from the previous schema are processed.
This results in the new schema being attached to the old rows.

ENG-19497: Backport: Guarantee that catalog update happens after quiesce

---

src/frontend/org/voltcore/messaging/HostMessenger.java
src/frontend/org/voltcore/messaging/JoinAcceptor.java
src/frontend/org/voltdb/probe/MeshProber.java
tests/frontend/org/voltcore/messaging/TestHostMessenger.java

[ backport 3bebd5cdfbf811e8432674d38cc0eb4d05bc88a1 ]
There is a time when a the zk rejoin node exists for a rejoining host but the
host is not in zookeeper. If the host failed in this window the rejoin node
would be left in zookeeper not allowing any other hosts to rejoin.
Update MeshProber.detract(int) to also take in a zookepeer instance and call
CoreZK.removeRejoinNodeIndicatorForHost to remove the rejoin node from
zookeeper.

ENG-15414: Backport: Remove rejoin node from zk on failure

---

src/frontend/org/voltdb/iv2/MpScheduler.java

MP initiator could get responses after a transaction is marked as complete when a partition master is migrated to a host which is then immediately shutdown: response from original partition master arrives after duplicate counter is cleaned for the transaction upon the node failure.

ENG-19490 response comes after transaction is marked as complete

---

src/frontend/org/voltcore/network/NetworkDBBPool.java
src/frontend/org/voltcore/utils/Pair.java
src/frontend/org/voltdb/rejoin/StreamSnapshotAckReceiver.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java

[ backport 4ac1b68 ]
If a balance partitions starts but an error occurs and no EOS is
received the ack receiver keeps running. If balance partitions is
retried the previously running ack receiver could still be running which
means that it could intercept the messages and the retry will just
timeout. This will keep happening indefinently.
Add a mechanism to force stop the ack receiver. This stop is called by
StreamSnapshotDataTarget when it encounters a message or a timeout.
Also, add a way for the ack receiver to notify the data target if an
error is received so that everything can be shutdown faster instead of
waiting for the timeout.

ENG-19500: Backport: Add a way to stop an ack receiver

---

src/frontend/org/voltdb/VoltDB.java
src/frontend/org/voltdb/compiler/DeploymentFileSchema.xsd
src/frontend/org/voltdb/utils/CatalogUtil.java

[ backport 49d9517ba4033ad0797043a774dd324feccf509d ]
CatalogUtil.shallowClusterAndPathsClone is supposed to copy almost all
of the fields for the original deployment instance but most of the new
fields were not added. Add the missing fields and organize the copy
order to match the declaration in DeploymentFileSchema.xsd for easier
reading

ENG-19499: Backport: Copy all deployment fields

---

src/frontend/org/voltdb/types/GeographyPointValue.java
tests/frontend/org/voltdb/types/TestGeographyPointValue.java
tests/sqlcmd/baselines/geospatial/points.errbaseline

In the GeographyPointValue use a conditional check which will fail for
NaN values and throw an IllegalArgumentException.
Use one check in the constructor instead of one in the factory method
and also in the constructor.

ENG-13836: Detect nan in geography point

---

src/frontend/org/voltdb/iv2/MpScheduler.java

MP initiator could get responses after a transaction is marked as complete when a partition master is migrated to a host which is then immediately shutdown: response from original partition master arrives after duplicate counter is cleaned for the transaction upon the node failure.

ENG-19566 response comes after transaction is marked as complete

---

tests/test_apps/voltkvqa/build.xml

Building  voltkvqa used to fail if connection-pool library wasn't in /home/opt (as it is on lab machines). Now you can override by setting CONNECTIONPOOLLIB in your environment.

ENG-13425. build now picks up env.CONNECTIONPOOLLIB for client classpath

---

src/frontend/org/voltdb/types/GeographyPointValue.java
tests/frontend/org/voltdb/types/TestGeographyPointValue.java
tests/sqlcmd/baselines/geospatial/points.errbaseline

[ backport 48fe07c6986f78cddb4672a7be1efb9819af2571 ]
In the GeographyPointValue use a conditional check which will fail for
NaN values and throw an IllegalArgumentException.
Use one check in the constructor instead of one in the factory method
and also in the constructor.

ENG-13836: Backport: Detect nan in geography point

---

src/frontend/org/voltdb/SnapshotStatus.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/sysprocs/SnapshotRegistry.java

SnapshotSummary returns one row per snapshot about the progress and result of 10 most recent CommandLog, AUTO or MANUAL snapshots.
But it starts to show SUCCESS result as early as snapshot initiation finishes, it rewrites the result if the snapshot failed later. I would rather to keep result column empty until the snapshot is actually finished. 
Now looks better?
```
exec @Statistics SNAPSHOTSUMMARY 0;
NONCE                TXNID             TYPE        START_TIME     END_TIME       DURATION  PROGRESS_PCT  RESULT
-------------------- ----------------- ----------- -------------- -------------- --------- ------------- ------------
1589861877645         3619631923445759 COMMANDLOG   1589861877731  1589861880452         2         100.0 SUCCESS
MANUAL1589861949114   3619631923462143 AUTO …
```

KO-241, when database is snapshotting, print "in_progress" instead of "success" in SNAPSHOTSUMMARY.

---

src/frontend/org/voltdb/expressions/ExpressionUtil.java

The startswith operation was not being handled in many of the switch
statements in ExpressionUtil. Add startswith as well as other missing
operations to the map of operations and at the same time make the map
immutable.

ENG-19594: Add startswith handling

---

src/frontend/org/voltdb/expressions/AbstractSubqueryExpression.java
src/frontend/org/voltdb/expressions/RowSubqueryExpression.java
src/frontend/org/voltdb/expressions/SelectSubqueryExpression.java

The m_subqueryNodeId value was only really being used for validate().
The getter actually returned m_subqueryNode.getPlanNodeId(). Since the
id can always be retrieved from m_subqueryNode just use that as the
authoritative location.

ENG-19627: Remove m_subqueryNodeId

---

src/frontend/org/voltdb/UserDefinedFunctionManager.java

On every Catalog Update the set of UDFs and UDAFs is removed and reinstalled on every partition. However, a shared list of names is also updated without being protected from race conditions that could cause the underlying shared data structures to become corrupted. Adding some synchronization to the path protects against this scenario.

ENG-19626:

---

lib/python/voltcli/voltadmin.d/license.py
lib/python/voltcli/voltdb.d/init.py
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/ServerThread.java
src/frontend/org/voltdb/SystemProcedureCatalog.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/common/Constants.java
src/frontend/org/voltdb/sysprocs/SysProcFragmentId.java
src/frontend/org/voltdb/sysprocs/UpdateLicense.java
src/frontend/org/voltdb/utils/MiscUtils.java
src/frontend/org/voltdb/utils/SQLCommand.java
tests/frontend/org/voltdb/MockVoltDB.java
tests/frontend/org/voltdb/TestInitStartAction.java

This pull request includes 3 parts:
1) a new `voltadmin license` command to update the database license dynamically. There're some restrictions for changes allowed, see MiscUtil.isLicenseChangeAllowed().
2) move `--license` option to `voltdb init` step. `voltdb start` will continue supporting `--license` option to avoid disruption for existing customers and our unit/system tests.
3) a new system procedure `UpdateLicense` to distribute the license file across cluster, to validate the format of license, do proper checks and update the license api on each node. 
Cluster license consistency check when cluster startup, node rejoin or join will be added in a separate PR.
Pro PR: https://github.com/VoltDB/pro/pull/3174

Eng 19204 dynamic license update

---

src/frontend/org/voltcore/zk/SynchronizedStatesManager.java

For ENG-19050 we refactor SSM shutdown to speed up completion of coordinator shutdown sequence: we no longer want to wait for the actual SSM shutdown given that re-creating the coordinator for the same topic/partition will use a different SSM nonce.

Create asynchronous version of shutdown

---

tools/git-remove-branches-script.py

Updated the tools/git-remove-branches-script.py script, to include a new
--max-num-branches= option (e.g. =10), to limit the number of branches
listed (and removed, potentially) in one run; and a new --release=
option (e.g. =origin/release-8.4.x), from Ruth's old
notest-better-branch-removal branch, which allows you to specify a
specific branch to which other branches were merged.

ENG-19246-branch-cleanup-notest:

---

src/frontend/org/voltdb/DRConsumerDrIdTracker.java
src/frontend/org/voltdb/dr2/DRIDTrackerHelper.java
src/frontend/org/voltdb/sysprocs/SnapshotRestore.java

DRConsumerDrIdTracker only are used during recover so do not try to deserialize DRConsumerDrIdTracker for restore.

ENG-19599: Only deserialize DR trackers for recover

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltZK.java
src/frontend/org/voltdb/sysprocs/UpdateLicense.java
src/frontend/org/voltdb/utils/MiscUtils.java

Fix an issue that in some cases license file is staged on top of itself. For example, `voltdb init` staged license.xml, `voltdb start` found the license in voltdbroot, it doesn't need to stage it again.
Fix a race condition as @zeemanhe mentioned when live license update coexists with node rejoin, now two operations are mutually exclusive.
Test case update: https://github.com/VoltDB/pro/pull/3181

Eng 19204 post merge fix 2

---

src/frontend/org/voltdb/SnapshotStatus.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/saverestore/CSVSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/IndexSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/NativeSnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java

Covers more types of snapshot, index snapshot (used by elastic) is intentionally ignored because it can't be used in restore.
Stream snapshot tracking is incorrect in master because each snapshot data target covers multiple tables, unlike the native snapshot which is one to one mapping. So onClose handler is always triggered from the last registered table.

Snapshotsummary more fixes

---

src/frontend/org/voltdb/ClientResponseImpl.java
src/frontend/org/voltdb/VoltTable.java
src/frontend/org/voltdb/client/ClientUtils.java
src/frontend/org/voltdb/utils/SnapshotComparer.java
tests/frontend/org/voltdb/TestVoltTable.java
tests/frontend/org/voltdb/test/utils/RandomTestRule.java

Make sure all chunks are visited so that in order mode 0 or 1 the
difference is always noticed or in 2 and greater all chunks are included
in the hash.
Use a single checksum algorithm which calculates a crc for each row and
the header and adds them together. This is a more robust checksum
mechanism than just adding the bytes together. Also, if performing an
exact comparison between tables just compare the buffers of the two
tables.

ENG-19646: Always visit all chunks

---

src/frontend/org/voltdb/sysprocs/Shutdown.java
tests/frontend/org/voltdb/TestMidRejoinDeath.java

As part of the Junit Singleton Isolation branch, an assert was added to verify that Shutdown (which has it's own singletons) was never called from ServerLocalThread. However, some Junit tests do call it which means that for those tests, the Shutdown Singletons need to be reinitialized before Shutdown completes.

ENG-19226:

---

src/frontend/org/voltcore/agreement/AgreementSite.java
src/frontend/org/voltcore/messaging/BinaryPayloadMessage.java

Backport: break >50MB (compressed size) ZK snapshot into small chunks to complete the rejoin.

Eng 19654 backport 8.4.x

---

src/ee/storage/persistenttable.h
tests/ee/storage/CopyOnWriteTest.cpp

When deleting the last tuple of a block pending snapshot, and removing the block from the PersistentTable, notify the table streamer that the block was "compacted away".

Eng 19517 empty blocks pending snapshot

---

src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java

When a host fails before rejoining is completed, the host of stream snapshot sources will log the message every 5 seconds, non-stop:  "While sending rejoin data to site X:X, 0 bytes have been sent in the past 5 seconds."   if not data are sent in 1 minute and destination host is down, stop logging the message.

ENG-18081 stop stream snapshot watcher if destination is not available

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/CatalogChangeResult.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
src/frontend/org/voltdb/sysprocs/Promote.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/sysprocs/UpdateClasses.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java

In C/L replay path the next catalog version may not be the expected version plus 1, because C/L reinitiator may queue multiple UACs before any of those get executed, failed UAC also consumes a version number. Catalog update runs in non-replay time is unchanged.
Pro change: https://github.com/VoltDB/pro/pull/3210

Eng 19332 cat ver in replay

---

tools/git-remove-branches-script.py

Added a new '--keep-branches=' option to the
tools/git-remove-branches-script.py script, including: a new
skip_branch_names arg added to the make_delete_branches_script and
make_archive_branches_script functions (with related code, and standard
values 'keep', 'feature', and 'integ', which are always kept); also
added a new get_tagname function to pick an archive tag name, which for
branch FOO will normally return 'archive/FOO' as before, but if that
already exists will try 'archive/FOO-2', 'archive/FOO-3', etc., thus
making sure we don't delete a branch before archiving a *current*
version of it; and some miscellaneous improvements, including a new
get_final_comment function (which just refactors similar comments that
need to be printed in 4 different places) and other minor tweaks.

ENG-19246-branch-cleanup2-notest:

---

src/frontend/org/voltdb/CatalogContext.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/VoltDBInterface.java
src/frontend/org/voltdb/compiler/CatalogChangeResult.java
src/frontend/org/voltdb/sysprocs/AdHoc.java
src/frontend/org/voltdb/sysprocs/Promote.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationBase.java
src/frontend/org/voltdb/sysprocs/UpdateApplicationCatalog.java
src/frontend/org/voltdb/sysprocs/UpdateClasses.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java
src/frontend/org/voltdb/utils/CatalogUtil.java
tests/frontend/org/voltdb/MockVoltDB.java

In C/L replay path the next catalog version may not be the expected version plus 1, because C/L reinitiator may queue multiple UACs before any of those get executed, failed UAC also consumes a version number. Catalog update runs in non-replay time is unchanged.
Got rid of unnecessary input parameter from updateApplication.
Get rid of the redundant toArray() calls.

Add next catalog version into UpdateCore's parameter list.

---

src/ee/common/TupleSchema.cpp
src/ee/common/TupleSchema.h
src/ee/common/tabletuple.h

Only use memcpy to copy hidden columns if the schemas are the same
instance. If they are not the same instance copy or initialize the
hidden columns in the destination tuple by hidden column type.
This is needed because the planner and the java layer are mostly unaware
of hidden columns so a plan can be constructed which uses copy but the
hidden columns are not the same for the source and destination.

ENG-19371: Do not use memcpy to copy hidden columns

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.core.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.service.js

If result of TestConnection is false do not call AddConnection in the
callback.
Also remove the unauthorizedTimeout from TestConnection. Since there is
already a timer for the response this second timer is not necessary.

ENG-17073: Only call AddConnection if TestConnection is a success

---

src/frontend/org/voltdb/dbmonitor/js/voltdb.core.js
src/frontend/org/voltdb/dbmonitor/js/voltdb.service.js

[ backport cc48f70de237d1d82bcca15d100a716a4a52018d ]
If result of TestConnection is false do not call AddConnection in the
callback.
Also remove the unauthorizedTimeout from TestConnection. Since there is
already a timer for the response this second timer is not necessary.

ENG-17073: Backport: Only call AddConnection if TestConnection is a success

---

src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/frontend/org/voltcore/utils/DBBPool.java.template
src/frontend/org/voltcore/utils/DirectBufferCleaner.java
src/frontend/org/voltcore/utils/ReflectiveDirectBufferCleaner.java
src/frontend/org/voltcore/utils/UnsafeDirectBufferCleaner.java
src/frontend/org/voltcore/utils/VoltUnsafe.java
src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportGeneration.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/ExportManagerInterface.java
src/frontend/org/voltdb/export/Generation.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java
src/frontend/org/voltdb/jni/ExecutionEngineJNI.java
tests/frontend/org/voltdb/export/TestExportDataSource.java
tests/frontend/org/voltdb/export/TestExportGeneration.java

* Wrap EE's direct buffers into BBContainer in JNI topends
* Remove unneeded MEMCHECK_FULL code

ENG-19679: fix handling EE direct buffers (#7219)

---

build.xml

"VOLTPRO../pro  ant  clean"  fails to clean up compilation artifacts in the pro tree. This simple addition wipes out obj/*...
There is of course a counterpart PR in the pro repo.  https://github.com/VoltDB/pro/pull/3236
The lack of this caused actual problems with stale code for the prometheus plugin.

clean up stuff that gets compiled into the pro tree

---

src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportManager.java

When the buffer is owned by the current method discard it before
returning or throwing.

ENG-19710: Discard buffers before return

---

src/frontend/org/voltdb/planner/ParsedColInfo.java
tests/frontend/org/voltdb/regressionsuites/TestSQLFeaturesSuite.java

If order by contains a constant value or a reference to a value which is
not part of the current select return an error message with hopefully a
reasonable error message.

ENG-19623: Prevent values and references in order by

---

src/frontend/org/voltdb/PartitionDRGateway.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportManager.java

[ backport 3bd42142d3237fcedd5a09d0457fe91ca6d4be9b ]
When the buffer is owned by the current method discard it before
returning or throwing.

ENG-19710: Backport: Discard buffers before return

---

src/frontend/org/voltdb/iv2/SpTerm.java

The following events could cause a missed replica update and block transactions:  a partition leader is migrated away,  a node fails, rejoin and fails again.

ENG-19728 missed replica update

---

src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/operator/ActivityHelper.java
src/frontend/org/voltdb/operator/PauseActivityStats.java
src/frontend/org/voltdb/operator/ShutdownActivityStats.java
src/frontend/org/voltdb/operator/XDCRReadinessStats.java

XDCR readiness criteria:
1) DRRole.State in "ACTIVE" state,
2) DRProducer.State in "ACTIVE" state,
3) DRProducer.Is_synced is true,
4) DRProducer.Connection_status is "UP",
5) DRConsumer.State in "RECEIVE" state,
6) DRConsumer.Is_covered is true,
7) DRConsumer.Is_paused is false.
XCDR must meet all the criteria to be "ready".

KO-329, aggregate DR-related stats to determine XDCR readiness.

---

src/ee/common/Topend.cpp
src/ee/common/Topend.h
src/ee/common/TxnEgo.h
src/ee/common/executorcontext.cpp
src/ee/execution/JNITopend.cpp
src/ee/execution/JNITopend.h
src/ee/storage/AbstractDRTupleStream.cpp
src/ee/storage/AbstractDRTupleStream.h
src/ee/storage/DRTupleStream.cpp
src/ee/storage/ExportTupleStream.cpp
src/ee/storage/ExportTupleStream.h
src/ee/storage/TupleStreamBase.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/tablefactory.cpp
src/ee/storage/viewableandreplicabletable.h
src/ee/voltdbipc.cpp
src/frontend/org/voltdb/export/AckingContainer.java
src/frontend/org/voltdb/export/ExportDataSource.java
src/frontend/org/voltdb/export/ExportManager.java
src/frontend/org/voltdb/export/processors/GuestProcessor.java
src/frontend/org/voltdb/jni/ExecutionEngineIPC.java

In export and migration use the TxnId for replicated tables and the
SpHandle for partitioned tables. This allows the transaction ID column
of replication to always be in the same number space and increase in
value. This also keeps it so that the same transaction ID is used to
identify migrating rows in replicated tables.
Create a new abstract table class to hold some of the common methods and
functions between streamed and persistent tables. This includes the
method to determine which transaction ID to be used for the table.

ENG-19677: Use TxnId for replicated tables

---

tests/frontend/org/voltdb/regressionsuites/TestSystemCatalogSuite.java

Don't know why the order of expected strings is slightly different but it shouldn't ring the bell.

Fix junit test TestSystemCatalogSuite.testTablesSelector().

---

src/frontend/org/voltdb/exportclient/JDBCExportClient.java

Shutdown executive service  with 60 s timeout. If timed out, shutdown immediately to prevent catalog update from being blocked.

ENG-19723 jdbc export client shutdown

---

src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

When a cluster is promoted the ConsumerDRGateway is shutdown and set to null in RealVoltDB, however an instace of the gateway is still registered with the GlobalServiceElector. When the gateway is shutdown deregister it from the GlobalServiceElector.

ENG-19743: Unregister dr consumer from global service leader

---

src/frontend/org/voltdb/RealVoltDB.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java

[ backport 79475e81fb52bb207d0d43bf1ac1e969dc5650ab ]
When a cluster is promoted the ConsumerDRGateway is shutdown and set to
null in RealVoltDB, however an instace of the gateway is still
registered with the GlobalServiceElector. When the gateway is shutdown
deregister it from the GlobalServiceElector.

ENG-19743: Backport: Unregister dr consumer from global service leader

---

src/frontend/org/voltdb/VoltTable.java

Many stats tables look ugly under the 30 max column width, because of the lengthy names or long paths.
```
exec @Statistics SNAPSHOTSummary 0;
NONCE                           TXNID             TYPE        START_TIME     END_TIME       DURATION  PROGRESS_PCT  RESULT
------------------------------- ----------------- ----------- -------------- -------------- --------- ------------- --------
1592486383194                    3619631923232767 COMMANDLOG   1592486383259  1592486383530         0         100.0 SUCCESS
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  3619631923314687 MANUAL       1592486393488  1592486393734         0         100.0 SUCCESS
```
It looks better with this patch, doesn't it?
```
exec @Statistics SNAPSHOTSummary 0;
NONCE                               TXNID …
```

Change the max column name width of VoltTable to 90.

---

src/frontend/org/voltdb/DefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DeprecatedDefaultSnapshotDataTarget.java
src/frontend/org/voltdb/DevNullSnapshotTarget.java
src/frontend/org/voltdb/SimpleFileSnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotDataTarget.java
src/frontend/org/voltdb/SnapshotSiteProcessor.java
src/frontend/org/voltdb/SnapshotStatus.java
src/frontend/org/voltdb/SnapshotSummary.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/SnapshotRegistry.java
src/frontend/org/voltdb/sysprocs/saverestore/SnapshotWritePlan.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSerializationFailures.java
tests/frontend/org/voltdb/regressionsuites/TestSaveRestoreSysprocSuite.java

Snapshot serialization exception can happen in streamMore(), defer the reporting of error will give every data target a chance to close itself and maintain the record in snapshot registry, so that the result of snapshot (success or failure) can be determined at finish time.

Eng 19697 close snapshot targets before report serialization error.

---

lib/python/voltcli/voltdb.d/collect.py
src/frontend/org/voltdb/utils/Collector.java

'--stdout' option redirects the binary content of compressed system and voltdb logs to
standard output, so that user can easily pipe the zip file out of remote machine
or container. Note that using '--stdout' will NOT generate a local copy of the zip file.
Change-Id: I9706cf03d906fe054afeb09a7f3bb09a092f5bc0

KO-136, add '--stdout' option to 'voltdb collect'.

---

src/frontend/org/voltdb/exportclient/JDBCExportClient.java

If property  ignoregenerations,  one of the export JDBC client configurations, is true, the client's PreparedStatement won't be updated upon schema changes.  Property  ignoregenerations can be confusing since it is overridden by property createtable. ignoregenerations will be set to true if createtable is set to false. Here proposed to ignore property ignoreGenerations  for schema change validation, update the PreparedStatement if schema has been updated.

ENG-19758 reset PreparedStatement upon schema changes

---

src/ee/storage/TableCatalogDelegate.cpp
src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
tests/ee/storage/TableTupleAllocatorTest.cpp

Changed compaction order detail of the bottom of the design, so that compaction is truly/always rolling right-ward, rather than compacting from tail of head chunk. 
The finalization behavior is left unchanged. There are a few lingering **TODO**s related to finalization behavior and more thorough test; but they are left here since we do not know for sure if current handling works.
To get most understanding out of the changes, it's advisable to review all the source code (not just changes), and EE test code.
Pending CI tests status check, before any system tests can be run.
NOTE: `CopyOnWriteTest` is currently failing.

True deterministic row order

---

src/ee/execution/VoltDBEngine.cpp
src/ee/executors/abstractexecutor.h
src/ee/executors/commontableexecutor.cpp
src/ee/executors/deleteexecutor.cpp
src/ee/stats/StatsAgent.cpp
src/ee/storage/AbstractTempTable.hpp
src/ee/storage/BinaryLogSink.cpp
src/ee/storage/BinaryLogSink.h
src/ee/storage/LargeTempTable.cpp
src/ee/storage/LargeTempTable.h
src/ee/storage/PersistentTableUndoTruncateTableAction.h
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
src/ee/storage/streamedtable.cpp
src/ee/storage/streamedtable.h
src/ee/storage/table.h
src/ee/storage/temptable.cpp
src/ee/storage/temptable.h
tests/ee/executors/MergeReceiveExecutorTest.cpp
tests/ee/storage/CopyOnWriteTest.cpp
tests/ee/storage/LargeTempTableTest.cpp
tests/ee/storage/persistent_table_log_test.cpp
tests/ee/storage/persistenttable_test.cpp
tests/ee/storage/table_test.cpp

VoltDBEngine::initMaterializedViewsAndLimitDeletePlans calls
disableReplicatedFlag() on all purge executors. The delete executor uses
the m_replicatedTableOperation for both synchronizing and passing into
PersistentTable::truncateTable. Because m_replicatedTableOperation was
always false forge purge truncates VoltDBEngine::rebuildTableCollections
was never rebuilding anything for replicated tables which resulted in
freed stats sources in the stats agent.
PersistentTable already knows if it is a replicated table or not so the
replicatedTable argument was unnecessary. By removing the argument the
executor cannot pass an incorrect value into the table.

ENG-17813: PersistentTable knows if it is replicated

---

tests/test_apps/genqa/build.xml
tests/test_apps/genqa/run.sh

Remove Rabbit MQ references from run.sh and build.xml. The Rabbit verifier is still in the src directory.. It's a good model for fast data verification that might be worth keeping around.

ENG-19785: Remove Rabbit MQ references from genqa test

---

src/frontend/org/voltdb/iv2/MpTransactionTaskQueue.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java

When @UpdateCore is aborted upon node down, do not delete catalog from ZooKeeper. If the staged catalog is deleted from ZooKeeper, no more catalog can be found when @UpdateCore transaction is restarted.

ENG-19784 do not remove staged catalog when @UpdateCore transaction is aborted

---

src/frontend/org/voltdb/rejoin/StreamSnapshotAckReceiver.java
src/frontend/org/voltdb/rejoin/StreamSnapshotDataTarget.java
src/frontend/org/voltdb/sysprocs/UpdateSettings.java
src/frontend/org/voltdb/sysprocs/saverestore/StreamSnapshotWritePlan.java
tests/frontend/org/voltdb/rejoin/TestStreamSnapshotDataTarget.java

In close(), stream data target sends the last EOS and expects for an ACK. However,
when rejoin is timeout the AckReceiver is stopped, therefore no ACK would be received.
Add a liveness check on AckReceiver receiver inside close() to break the loop, let data target
to handle other resource release work.

Eng 19791 fix test mid rejoin death

---

src/frontend/org/voltdb/utils/PersistentBinaryDeque.java
tests/frontend/org/voltdb/regressionsuites/LocalCluster.java
tests/frontend/org/voltdb/regressionsuites/PipeToFile.java
tests/frontend/org/voltdb/utils/TestPersistentBinaryDeque.java

Port @wweiss-voltdb fix for properly waiting until a rejoin is completed from ENG-18744
Do not delete segments when a transient read cursor is closed
Related https://github.com/VoltDB/pro/pull/3282

ENG-19635: Wait for rejoin and do not delete segments on transient close

---

src/frontend/org/voltcore/messaging/SocketJoiner.java

SocketJoiner has a list of non-fatal errors.  Socket timeout isn't on that list; it should be.
Without this, we sometimes crash when we should not.

add socket timeout to list of non-fatal errors

---

tools/kit_tools/build_kits.py

Can use -l or --includelicense to make the kit with a trial license.

ENG-19802.  Default to no trial license in enterprise kit

---

src/frontend/org/voltdb/RealVoltDB.java

Java provides system properties related to user identity.  We uses these properties in various places (to make filenames, etc).  I thought it would be handy to log them.  In particular, I discovered that if you don't have an account entry these strings may get set to '?'.

report java user properties in host log

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
src/ee/storage/persistenttable.cpp
src/ee/storage/persistenttable.h
tests/ee/storage/TableTupleAllocatorTest.cpp

on the new/different memory model:
1. Previously, both src/dst of moved tuples in batch removal are
captured in hook memory. Using the new memory model, we can safely only
capture the dst tuple (that gets overwritten) in hook. Also separated hook's 
`add()` method into `addForUpdate()` and `addForDelete()` to account for
this difference.
2. Previously, when adding hook memory entry for deletes or updates, we
always use deep copier when applicable. Now, we only invoke deep copier
on update: we use shallow memcpy for deleted tuples, and let batch
removal call back discriminate the frozen case, when it does not
finalize (i.e. call `decreaseStringMemCount()' and
`freeObjectColumns()') if frozen.
3. Previously, since we always did deep copy of deleted or compacted tuples
into hook memory, it …

Optimize away some deep copier/finalize operations, etc.

---

src/frontend/org/voltdb/sysprocs/UpdateCore.java

@UpdateCore may be far ahead in the transaction processing on some sites. If the transaction fails on these sites and the stage catalog is deleted, other sites which fall behind in transaction may not be able to get the catalog when needed.
[back port from master](https://github.com/VoltDB/voltdb/pull/7315)

ENG-19821 Do not delete staged catalog upon exception. 

---

src/ee/storage/TableTupleAllocator.cpp
src/ee/storage/TableTupleAllocator.hpp
src/ee/storage/persistenttable.cpp
tests/ee/storage/TableTupleAllocatorTest.cpp

1. Compaction (i.e. tuple movement in deletion) now deep copies when
copying src addr to dst addr.
2. Bug fix: since both deleted/updated contents are kept in hook memory,
but only updated hook memory uses deep copier, the finalization at
thaw time that release hook memory need to keep track of which is from
updates, and only finalize the update changes.
3. Due to change #1, at thaw() time, the frozen region need to be finalized
up to min(frozen right, txn begin).

Changes on finalization behavior:

---

src/frontend/org/voltdb/DRProducerClusterStats.java
src/frontend/org/voltdb/DRProducerStatsBase.java
src/frontend/org/voltdb/RealVoltDB.java
src/frontend/org/voltdb/StatsAgent.java
src/frontend/org/voltdb/StatsSelector.java
src/frontend/org/voltdb/dr2/DRProducerClusterStats.java
tests/frontend/org/voltdb/TestStatsAgent.java
tests/frontend/org/voltdb/regressionsuites/statistics/TestStatisticsSuiteDRStats.java

Failures are encoded byte defined in https://github.com/VoltDB/pro/blob/KO-integration/src/frontend/org/voltdb/dr2/DRCtrlRespFailure.java.
The main purpose is to expose programmatically information for XDCR cluster to decide when to do _dr reset_.

KO-434, report last failure in Statistics.DRPRODUCER.cluster (the 3rd table)

---

src/frontend/org/voltdb/RealVoltDB.java

SSL key/trust store info comes from the deployment file.  It seems however that Java system properties can override the deployment. This caught my attention while debugging some SSL work and concerned me enough that I wanted to log any conflict. Actual operation unchanged.
Fixes KO-501 NPE as well. Affects unit test only.

1. log contradictory ssl args, 2. fix restore NPE

---

src/frontend/org/voltdb/RealVoltDB.java

Excludes some TLS cipher suites from being used by VoltDB.
If you follow the VoltDB documentation for preparing self-signed certificates, then the OpenSSL library will tell you that several are too weak, though you can use them anyway.
This is (a) noisy in the log, and (b) potentially a risk, so this change adds the weak suites to the exclusion list we already have. I determined the list to exclude by harvesting the OpenSSL log messages complaining about them.
I filed this bug as ENG-19839 since we need to fix it in master (as well), but I thought I'd try it out here first.
Note, I sorted the list alphabetically, so the existing suites are now differently ordered as well.

exclude weak TLS cipher suites

---

src/frontend/org/voltdb/iv2/Site.java

Running state is altered while a site is de-commissioned.  Check running state for rejoining.

ENG-19843 checking running state while decommissioned

---

lib/python/voltdbclient.py

voltadmin, and anything else using the voltdb python client, required SSL config to be supplied in jks format. This in turn required the hard-to-set-up and probably-obsolete pyjks package.
It turns out that most of the pyjks gyrations were in order to get a pem format certificate for the ssl code.  It's a lot easier to just give  it a pem certificate; there are tools to generate them (I used the openssl command to post-process jks files made per voltdb documention).
So: the change: if the config file (--ssl=FILE on voltadmin command) has a .pem extenstion, it's a pem file (!).  We feed it to the ssl mode as the ca_certs argument. i.e., it's used to validate the cert we get from the server.  There is no mutual identification of us to the server.
Addiitonally, if the config file is the …

More SSL choices for voltadmin etc.

---

lib/python/voltdbclient.py

Allow use of PEM-format CA certificate [chain] without
requiring pyjks module which we do not need anyway.
Prior to this change, voltdbclient had provision for
the following:
keystore - for *client* identification in jks format
truststore - for *server* identification in jks format
cacerts - for *server* identification in pem format
(Of the two server id formats, only one was used)
The trouble was that even if you only wanted the pem
format cacerts, you had to load the pyjks parsing
module, which would then not be used.
This rearranges the code flow slightly so that we
only check for pyjks if we're about to use it.
The jks file parsing is now in a separate method
for clarity.
Also, the ssl_version field was mishandled by
being treated as a certificate path!  I conclude
no-one ever …

Allow use of PEM-format CA certificate

---

lib/python/voltdbclient.py

Increase required python version to 2.7.13
This allows us to use PROTOCOL_TLS to select the highest protocol available to both parties.
No attempt has been made to screen out 'weak' protocols since that is done at the VoltDB end.

remove tricky TLS protocol version code

---

tests/frontend/org/voltdb/regressionsuites/TestSystemCatalogSuite.java

[backport 7a05ad27521b38563071578e8947e44e6060f623]
ENG-19440 changed expected order of JSON keys, but it shouldn't ring the bell.

Unit test fix: TestSystemCatalogSuite.testTablesSelector(). (#7253)

---

src/frontend/org/voltdb/sysprocs/SnapshotSave.java
src/frontend/org/voltdb/sysprocs/UpdateCore.java

A host may not have any partition leaders, such as a newly rejoined host.  When hash mismatch occurs, a host without partition leader will be shutdown.  Under certain race conditions, the host may still receive transaction processing requests before it is shutdown.  Procedures, such as catalog update or snapshot save, which require synchronization among all sites, may be broken since the host does not have any active sites.

ENG-19849 abort catalog update and snapshot if there are no active sites 
